test/parser/ast/call/basic.myte
{
  node: Program,
  loc: 1:0-11:1,
  toplevels: [
    {
      node: Function,
      loc: 1:0-11:1,
      name: {
        node: Identifier,
        loc: 1:4-1:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 1:11-11:1,
        statements: [
          {
            node: ExpressionStatement,
            loc: 2:2-2:8,
            expression: {
              node: Call,
              loc: 2:2-2:7,
              func: {
                node: Identifier,
                loc: 2:2-2:5,
                name: "foo",
              },
              args: [],
            },
          },
          {
            node: ExpressionStatement,
            loc: 3:2-3:9,
            expression: {
              node: Call,
              loc: 3:2-3:8,
              func: {
                node: Identifier,
                loc: 3:2-3:5,
                name: "foo",
              },
              args: [
                {
                  node: IntLiteral,
                  loc: 3:6-3:7,
                  value: 1,
                  raw: "1",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 4:2-4:15,
            expression: {
              node: Call,
              loc: 4:2-4:14,
              func: {
                node: Identifier,
                loc: 4:2-4:5,
                name: "foo",
              },
              args: [
                {
                  node: IntLiteral,
                  loc: 4:6-4:7,
                  value: 1,
                  raw: "1",
                },
                {
                  node: IntLiteral,
                  loc: 4:9-4:10,
                  value: 2,
                  raw: "2",
                },
                {
                  node: IntLiteral,
                  loc: 4:12-4:13,
                  value: 3,
                  raw: "3",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 5:2-5:16,
            expression: {
              node: Call,
              loc: 5:2-5:15,
              func: {
                node: Identifier,
                loc: 5:2-5:5,
                name: "foo",
              },
              args: [
                {
                  node: IntLiteral,
                  loc: 5:6-5:7,
                  value: 1,
                  raw: "1",
                },
                {
                  node: IntLiteral,
                  loc: 5:9-5:10,
                  value: 2,
                  raw: "2",
                },
                {
                  node: IntLiteral,
                  loc: 5:12-5:13,
                  value: 3,
                  raw: "3",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 7:2-7:10,
            expression: {
              node: Call,
              loc: 7:2-7:9,
              func: {
                node: Identifier,
                loc: 7:3-7:6,
                name: "foo",
              },
              args: [],
            },
          },
          {
            node: ExpressionStatement,
            loc: 8:2-8:19,
            expression: {
              node: Call,
              loc: 8:2-8:18,
              func: {
                node: LogicalOr,
                loc: 8:3-8:15,
                left: {
                  node: Identifier,
                  loc: 8:3-8:6,
                  name: "foo",
                },
                right: {
                  node: Identifier,
                  loc: 8:11-8:14,
                  name: "bar",
                },
              },
              args: [],
            },
          },
          {
            node: ExpressionStatement,
            loc: 10:2-10:12,
            expression: {
              node: Call,
              loc: 10:2-10:11,
              func: {
                node: Call,
                loc: 10:2-10:9,
                func: {
                  node: Call,
                  loc: 10:2-10:7,
                  func: {
                    node: Identifier,
                    loc: 10:2-10:5,
                    name: "foo",
                  },
                  args: [],
                },
                args: [],
              },
              args: [],
            },
          },
        ],
      },
      return: None,
    },
  ],
}