test/parser/if/basic.myte
{
  node: Module,
  loc: 1:0-14:1,
  name: {
    node: ModuleName,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-14:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-14:1,
        statements: [
          {
            node: IfStatement,
            loc: 4:2-4:14,
            test: {
              node: Identifier,
              loc: 4:6-4:10,
              name: "test",
            },
            conseq: {
              node: Block,
              loc: 4:12-4:14,
              statements: [],
            },
            altern: None,
          },
          {
            node: IfStatement,
            loc: 6:2-8:3,
            test: {
              node: Identifier,
              loc: 6:6-6:10,
              name: "test",
            },
            conseq: {
              node: Block,
              loc: 6:12-7:3,
              statements: [],
            },
            altern: {
              node: Block,
              loc: 7:9-8:3,
              statements: [],
            },
          },
          {
            node: IfStatement,
            loc: 10:2-13:3,
            test: {
              node: Identifier,
              loc: 10:6-10:10,
              name: "test",
            },
            conseq: {
              node: Block,
              loc: 10:12-11:3,
              statements: [],
            },
            altern: {
              node: IfStatement,
              loc: 11:9-13:3,
              test: {
                node: Identifier,
                loc: 11:13-11:18,
                name: "test2",
              },
              conseq: {
                node: Block,
                loc: 11:20-12:3,
                statements: [],
              },
              altern: {
                node: Block,
                loc: 12:9-13:3,
                statements: [],
              },
            },
          },
        ],
      },
      return: None,
      type_params: [],
      is_public: false,
      is_builtin: false,
      is_static: false,
      is_override: false,
    },
  ],
}