test/parser/access/named_access.myte
{
  node: Module,
  loc: 1:0-6:1,
  name: {
    node: ModuleName,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-6:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-6:1,
        statements: [
          {
            node: ExpressionStatement,
            loc: 4:2-4:6,
            expression: {
              node: NamedAccess,
              loc: 4:2-4:5,
              target: {
                node: Identifier,
                loc: 4:2-4:3,
                name: "a",
              },
              name: {
                node: Identifier,
                loc: 4:4-4:5,
                name: "b",
              },
            },
          },
          {
            node: ExpressionStatement,
            loc: 5:2-5:8,
            expression: {
              node: NamedAccess,
              loc: 5:2-5:7,
              target: {
                node: NamedAccess,
                loc: 5:2-5:5,
                target: {
                  node: Identifier,
                  loc: 5:2-5:3,
                  name: "a",
                },
                name: {
                  node: Identifier,
                  loc: 5:4-5:5,
                  name: "b",
                },
              },
              name: {
                node: Identifier,
                loc: 5:6-5:7,
                name: "c",
              },
            },
          },
        ],
      },
      return: None,
      type_params: [],
      is_public: false,
      is_static: false,
      is_override: false,
    },
  ],
}