test/parser/assignment/basic.myte
{
  node: Module,
  loc: 1:0-43:1,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-43:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-43:1,
        statements: [
          {
            node: Assignment,
            loc: 5:2-5:8,
            lvalue: {
              node: ScopedIdentifier,
              loc: 5:2-5:3,
              scopes: [],
              name: {
                node: Identifier,
                loc: 5:2-5:3,
                name: "x",
              },
            },
            expr: {
              node: IntLiteral,
              loc: 5:6-5:7,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 8:2-8:13,
            lvalue: {
              node: TuplePattern,
              loc: 8:2-8:8,
              name: None,
              elements: [
                {
                  node: ScopedIdentifier,
                  loc: 8:3-8:4,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 8:3-8:4,
                    name: "x",
                  },
                },
                {
                  node: ScopedIdentifier,
                  loc: 8:6-8:7,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 8:6-8:7,
                    name: "y",
                  },
                },
              ],
            },
            expr: {
              node: IntLiteral,
              loc: 8:11-8:12,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 9:2-9:17,
            lvalue: {
              node: TuplePattern,
              loc: 9:2-9:12,
              name: None,
              elements: [
                {
                  node: ScopedIdentifier,
                  loc: 9:3-9:4,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 9:3-9:4,
                    name: "x",
                  },
                },
                {
                  node: ScopedIdentifier,
                  loc: 9:6-9:7,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 9:6-9:7,
                    name: "y",
                  },
                },
                {
                  node: ScopedIdentifier,
                  loc: 9:9-9:10,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 9:9-9:10,
                    name: "z",
                  },
                },
              ],
            },
            expr: {
              node: IntLiteral,
              loc: 9:15-9:16,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 12:2-12:14,
            lvalue: {
              node: TuplePattern,
              loc: 12:2-12:9,
              name: {
                node: ScopedIdentifier,
                loc: 12:2-12:5,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 12:2-12:5,
                  name: "Tup",
                },
              },
              elements: [
                {
                  node: ScopedIdentifier,
                  loc: 12:7-12:8,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 12:7-12:8,
                    name: "x",
                  },
                },
              ],
            },
            expr: {
              node: IntLiteral,
              loc: 12:12-12:13,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 13:2-13:20,
            lvalue: {
              node: TuplePattern,
              loc: 13:2-13:15,
              name: {
                node: ScopedIdentifier,
                loc: 13:2-13:5,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 13:2-13:5,
                  name: "Tup",
                },
              },
              elements: [
                {
                  node: ScopedIdentifier,
                  loc: 13:7-13:8,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 13:7-13:8,
                    name: "x",
                  },
                },
                {
                  node: ScopedIdentifier,
                  loc: 13:10-13:11,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 13:10-13:11,
                    name: "y",
                  },
                },
                {
                  node: ScopedIdentifier,
                  loc: 13:13-13:14,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 13:13-13:14,
                    name: "z",
                  },
                },
              ],
            },
            expr: {
              node: IntLiteral,
              loc: 13:18-13:19,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 14:2-14:21,
            lvalue: {
              node: TuplePattern,
              loc: 14:2-14:16,
              name: {
                node: ScopedIdentifier,
                loc: 14:2-14:5,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 14:2-14:5,
                  name: "Tup",
                },
              },
              elements: [
                {
                  node: ScopedIdentifier,
                  loc: 14:7-14:8,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 14:7-14:8,
                    name: "x",
                  },
                },
                {
                  node: ScopedIdentifier,
                  loc: 14:10-14:11,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 14:10-14:11,
                    name: "y",
                  },
                },
                {
                  node: ScopedIdentifier,
                  loc: 14:13-14:14,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 14:13-14:14,
                    name: "z",
                  },
                },
              ],
            },
            expr: {
              node: IntLiteral,
              loc: 14:19-14:20,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 17:2-17:32,
            lvalue: {
              node: RecordPattern,
              loc: 17:2-17:27,
              name: {
                node: ScopedIdentifier,
                loc: 17:2-17:5,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 17:2-17:5,
                  name: "Rec",
                },
              },
              fields: [
                {
                  node: RecordPatternField,
                  loc: 17:8-17:17,
                  name: {
                    node: Identifier,
                    loc: 17:8-17:14,
                    name: "field1",
                  },
                  value: {
                    node: ScopedIdentifier,
                    loc: 17:16-17:17,
                    scopes: [],
                    name: {
                      node: Identifier,
                      loc: 17:16-17:17,
                      name: "x",
                    },
                  },
                },
                {
                  node: RecordPatternField,
                  loc: 17:19-17:25,
                  name: None,
                  value: {
                    node: ScopedIdentifier,
                    loc: 17:19-17:25,
                    scopes: [],
                    name: {
                      node: Identifier,
                      loc: 17:19-17:25,
                      name: "field2",
                    },
                  },
                },
              ],
              rest: false,
            },
            expr: {
              node: IntLiteral,
              loc: 17:30-17:31,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 18:2-18:33,
            lvalue: {
              node: RecordPattern,
              loc: 18:2-18:28,
              name: {
                node: ScopedIdentifier,
                loc: 18:2-18:5,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 18:2-18:5,
                  name: "Rec",
                },
              },
              fields: [
                {
                  node: RecordPatternField,
                  loc: 18:8-18:14,
                  name: None,
                  value: {
                    node: ScopedIdentifier,
                    loc: 18:8-18:14,
                    scopes: [],
                    name: {
                      node: Identifier,
                      loc: 18:8-18:14,
                      name: "field1",
                    },
                  },
                },
                {
                  node: RecordPatternField,
                  loc: 18:16-18:25,
                  name: {
                    node: Identifier,
                    loc: 18:16-18:22,
                    name: "field2",
                  },
                  value: {
                    node: ScopedIdentifier,
                    loc: 18:24-18:25,
                    scopes: [],
                    name: {
                      node: Identifier,
                      loc: 18:24-18:25,
                      name: "x",
                    },
                  },
                },
              ],
              rest: false,
            },
            expr: {
              node: IntLiteral,
              loc: 18:31-18:32,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 19:2-19:26,
            lvalue: {
              node: RecordPattern,
              loc: 19:2-19:21,
              name: {
                node: ScopedIdentifier,
                loc: 19:2-19:5,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 19:2-19:5,
                  name: "Rec",
                },
              },
              fields: [
                {
                  node: RecordPatternField,
                  loc: 19:8-19:14,
                  name: None,
                  value: {
                    node: ScopedIdentifier,
                    loc: 19:8-19:14,
                    scopes: [],
                    name: {
                      node: Identifier,
                      loc: 19:8-19:14,
                      name: "field1",
                    },
                  },
                },
              ],
              rest: true,
            },
            expr: {
              node: IntLiteral,
              loc: 19:24-19:25,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 20:2-20:27,
            lvalue: {
              node: RecordPattern,
              loc: 20:2-20:22,
              name: {
                node: ScopedIdentifier,
                loc: 20:2-20:5,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 20:2-20:5,
                  name: "Rec",
                },
              },
              fields: [
                {
                  node: RecordPatternField,
                  loc: 20:8-20:14,
                  name: None,
                  value: {
                    node: ScopedIdentifier,
                    loc: 20:8-20:14,
                    scopes: [],
                    name: {
                      node: Identifier,
                      loc: 20:8-20:14,
                      name: "field1",
                    },
                  },
                },
              ],
              rest: true,
            },
            expr: {
              node: IntLiteral,
              loc: 20:25-20:26,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 23:2-23:28,
            lvalue: {
              node: TuplePattern,
              loc: 23:2-23:23,
              name: None,
              elements: [
                {
                  node: TuplePattern,
                  loc: 23:3-23:9,
                  name: {
                    node: ScopedIdentifier,
                    loc: 23:3-23:6,
                    scopes: [],
                    name: {
                      node: Identifier,
                      loc: 23:3-23:6,
                      name: "Tup",
                    },
                  },
                  elements: [
                    {
                      node: ScopedIdentifier,
                      loc: 23:7-23:8,
                      scopes: [],
                      name: {
                        node: Identifier,
                        loc: 23:7-23:8,
                        name: "x",
                      },
                    },
                  ],
                },
                {
                  node: RecordPattern,
                  loc: 23:11-23:22,
                  name: {
                    node: ScopedIdentifier,
                    loc: 23:11-23:14,
                    scopes: [],
                    name: {
                      node: Identifier,
                      loc: 23:11-23:14,
                      name: "Rec",
                    },
                  },
                  fields: [
                    {
                      node: RecordPatternField,
                      loc: 23:16-23:21,
                      name: None,
                      value: {
                        node: ScopedIdentifier,
                        loc: 23:16-23:21,
                        scopes: [],
                        name: {
                          node: Identifier,
                          loc: 23:16-23:21,
                          name: "field",
                        },
                      },
                    },
                  ],
                  rest: false,
                },
              ],
            },
            expr: {
              node: IntLiteral,
              loc: 23:26-23:27,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 24:2-24:36,
            lvalue: {
              node: RecordPattern,
              loc: 24:2-24:31,
              name: {
                node: ScopedIdentifier,
                loc: 24:2-24:5,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 24:2-24:5,
                  name: "Rec",
                },
              },
              fields: [
                {
                  node: RecordPatternField,
                  loc: 24:8-24:29,
                  name: {
                    node: Identifier,
                    loc: 24:8-24:13,
                    name: "field",
                  },
                  value: {
                    node: TuplePattern,
                    loc: 24:15-24:29,
                    name: {
                      node: ScopedIdentifier,
                      loc: 24:15-24:18,
                      scopes: [],
                      name: {
                        node: Identifier,
                        loc: 24:15-24:18,
                        name: "Tup",
                      },
                    },
                    elements: [
                      {
                        node: TuplePattern,
                        loc: 24:19-24:25,
                        name: None,
                        elements: [
                          {
                            node: ScopedIdentifier,
                            loc: 24:20-24:21,
                            scopes: [],
                            name: {
                              node: Identifier,
                              loc: 24:20-24:21,
                              name: "x",
                            },
                          },
                          {
                            node: ScopedIdentifier,
                            loc: 24:23-24:24,
                            scopes: [],
                            name: {
                              node: Identifier,
                              loc: 24:23-24:24,
                              name: "y",
                            },
                          },
                        ],
                      },
                      {
                        node: ScopedIdentifier,
                        loc: 24:27-24:28,
                        scopes: [],
                        name: {
                          node: Identifier,
                          loc: 24:27-24:28,
                          name: "z",
                        },
                      },
                    ],
                  },
                },
              ],
              rest: false,
            },
            expr: {
              node: IntLiteral,
              loc: 24:34-24:35,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 27:2-27:20,
            lvalue: {
              node: TuplePattern,
              loc: 27:2-27:15,
              name: {
                node: ScopedIdentifier,
                loc: 27:2-27:11,
                scopes: [
                  {
                    node: Identifier,
                    loc: 27:2-27:3,
                    name: "A",
                  },
                  {
                    node: Identifier,
                    loc: 27:4-27:5,
                    name: "B",
                  },
                  {
                    node: Identifier,
                    loc: 27:6-27:7,
                    name: "C",
                  },
                ],
                name: {
                  node: Identifier,
                  loc: 27:8-27:11,
                  name: "Tup",
                },
              },
              elements: [
                {
                  node: ScopedIdentifier,
                  loc: 27:13-27:14,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 27:13-27:14,
                    name: "x",
                  },
                },
              ],
            },
            expr: {
              node: IntLiteral,
              loc: 27:18-27:19,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 28:2-28:26,
            lvalue: {
              node: RecordPattern,
              loc: 28:2-28:21,
              name: {
                node: ScopedIdentifier,
                loc: 28:2-28:11,
                scopes: [
                  {
                    node: Identifier,
                    loc: 28:2-28:3,
                    name: "A",
                  },
                  {
                    node: Identifier,
                    loc: 28:4-28:5,
                    name: "B",
                  },
                  {
                    node: Identifier,
                    loc: 28:6-28:7,
                    name: "C",
                  },
                ],
                name: {
                  node: Identifier,
                  loc: 28:8-28:11,
                  name: "Rec",
                },
              },
              fields: [
                {
                  node: RecordPatternField,
                  loc: 28:14-28:19,
                  name: None,
                  value: {
                    node: ScopedIdentifier,
                    loc: 28:14-28:19,
                    scopes: [],
                    name: {
                      node: Identifier,
                      loc: 28:14-28:19,
                      name: "field",
                    },
                  },
                },
              ],
              rest: false,
            },
            expr: {
              node: IntLiteral,
              loc: 28:24-28:25,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 31:2-31:10,
            lvalue: {
              node: NamedAccess,
              loc: 31:2-31:5,
              target: {
                node: Identifier,
                loc: 31:2-31:3,
                name: "A",
              },
              name: {
                node: Identifier,
                loc: 31:4-31:5,
                name: "B",
              },
            },
            expr: {
              node: IntLiteral,
              loc: 31:8-31:9,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 32:2-32:14,
            lvalue: {
              node: NamedAccess,
              loc: 32:2-32:9,
              target: {
                node: NamedAccess,
                loc: 32:2-32:7,
                target: {
                  node: NamedAccess,
                  loc: 32:2-32:5,
                  target: {
                    node: Identifier,
                    loc: 32:2-32:3,
                    name: "A",
                  },
                  name: {
                    node: Identifier,
                    loc: 32:4-32:5,
                    name: "B",
                  },
                },
                name: {
                  node: Identifier,
                  loc: 32:6-32:7,
                  name: "C",
                },
              },
              name: {
                node: Identifier,
                loc: 32:8-32:9,
                name: "D",
              },
            },
            expr: {
              node: IntLiteral,
              loc: 32:12-32:13,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 33:2-33:11,
            lvalue: {
              node: IndexedAccess,
              loc: 33:2-33:6,
              target: {
                node: Identifier,
                loc: 33:2-33:3,
                name: "A",
              },
              index: {
                node: Identifier,
                loc: 33:4-33:5,
                name: "B",
              },
            },
            expr: {
              node: IntLiteral,
              loc: 33:9-33:10,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 34:2-34:17,
            lvalue: {
              node: IndexedAccess,
              loc: 34:2-34:12,
              target: {
                node: IndexedAccess,
                loc: 34:2-34:9,
                target: {
                  node: IndexedAccess,
                  loc: 34:2-34:6,
                  target: {
                    node: Identifier,
                    loc: 34:2-34:3,
                    name: "A",
                  },
                  index: {
                    node: Identifier,
                    loc: 34:4-34:5,
                    name: "B",
                  },
                },
                index: {
                  node: Identifier,
                  loc: 34:7-34:8,
                  name: "C",
                },
              },
              index: {
                node: Identifier,
                loc: 34:10-34:11,
                name: "D",
              },
            },
            expr: {
              node: IntLiteral,
              loc: 34:15-34:16,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 35:2-35:13,
            lvalue: {
              node: IndexedAccess,
              loc: 35:2-35:8,
              target: {
                node: NamedAccess,
                loc: 35:2-35:5,
                target: {
                  node: Identifier,
                  loc: 35:2-35:3,
                  name: "A",
                },
                name: {
                  node: Identifier,
                  loc: 35:4-35:5,
                  name: "B",
                },
              },
              index: {
                node: Identifier,
                loc: 35:6-35:7,
                name: "C",
              },
            },
            expr: {
              node: IntLiteral,
              loc: 35:11-35:12,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 36:2-36:13,
            lvalue: {
              node: NamedAccess,
              loc: 36:2-36:8,
              target: {
                node: IndexedAccess,
                loc: 36:2-36:6,
                target: {
                  node: Identifier,
                  loc: 36:2-36:3,
                  name: "A",
                },
                index: {
                  node: Identifier,
                  loc: 36:4-36:5,
                  name: "B",
                },
              },
              name: {
                node: Identifier,
                loc: 36:7-36:8,
                name: "C",
              },
            },
            expr: {
              node: IntLiteral,
              loc: 36:11-36:12,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 37:2-37:25,
            lvalue: {
              node: NamedAccess,
              loc: 37:2-37:20,
              target: {
                node: IndexedAccess,
                loc: 37:2-37:18,
                target: {
                  node: NamedAccess,
                  loc: 37:2-37:15,
                  target: {
                    node: NamedAccess,
                    loc: 37:2-37:13,
                    target: {
                      node: IndexedAccess,
                      loc: 37:2-37:11,
                      target: {
                        node: IndexedAccess,
                        loc: 37:2-37:8,
                        target: {
                          node: NamedAccess,
                          loc: 37:2-37:5,
                          target: {
                            node: Identifier,
                            loc: 37:2-37:3,
                            name: "A",
                          },
                          name: {
                            node: Identifier,
                            loc: 37:4-37:5,
                            name: "B",
                          },
                        },
                        index: {
                          node: Identifier,
                          loc: 37:6-37:7,
                          name: "C",
                        },
                      },
                      index: {
                        node: Identifier,
                        loc: 37:9-37:10,
                        name: "D",
                      },
                    },
                    name: {
                      node: Identifier,
                      loc: 37:12-37:13,
                      name: "E",
                    },
                  },
                  name: {
                    node: Identifier,
                    loc: 37:14-37:15,
                    name: "F",
                  },
                },
                index: {
                  node: Identifier,
                  loc: 37:16-37:17,
                  name: "G",
                },
              },
              name: {
                node: Identifier,
                loc: 37:19-37:20,
                name: "H",
              },
            },
            expr: {
              node: IntLiteral,
              loc: 37:23-37:24,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 40:2-40:18,
            lvalue: {
              node: Or,
              loc: 40:3-40:12,
              left: {
                node: Or,
                loc: 40:3-40:8,
                left: {
                  node: ScopedIdentifier,
                  loc: 40:3-40:4,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 40:3-40:4,
                    name: "A",
                  },
                },
                right: {
                  node: ScopedIdentifier,
                  loc: 40:7-40:8,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 40:7-40:8,
                    name: "B",
                  },
                },
              },
              right: {
                node: ScopedIdentifier,
                loc: 40:11-40:12,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 40:11-40:12,
                  name: "C",
                },
              },
            },
            expr: {
              node: IntLiteral,
              loc: 40:16-40:17,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 41:2-41:20,
            lvalue: {
              node: Or,
              loc: 41:3-41:14,
              left: {
                node: Or,
                loc: 41:4-41:9,
                left: {
                  node: ScopedIdentifier,
                  loc: 41:4-41:5,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 41:4-41:5,
                    name: "A",
                  },
                },
                right: {
                  node: ScopedIdentifier,
                  loc: 41:8-41:9,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 41:8-41:9,
                    name: "B",
                  },
                },
              },
              right: {
                node: ScopedIdentifier,
                loc: 41:13-41:14,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 41:13-41:14,
                  name: "C",
                },
              },
            },
            expr: {
              node: IntLiteral,
              loc: 41:18-41:19,
              raw: "1",
            },
          },
          {
            node: Assignment,
            loc: 42:2-42:20,
            lvalue: {
              node: Or,
              loc: 42:3-42:14,
              left: {
                node: ScopedIdentifier,
                loc: 42:3-42:4,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 42:3-42:4,
                  name: "A",
                },
              },
              right: {
                node: Or,
                loc: 42:8-42:13,
                left: {
                  node: ScopedIdentifier,
                  loc: 42:8-42:9,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 42:8-42:9,
                    name: "B",
                  },
                },
                right: {
                  node: ScopedIdentifier,
                  loc: 42:12-42:13,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 42:12-42:13,
                    name: "C",
                  },
                },
              },
            },
            expr: {
              node: IntLiteral,
              loc: 42:18-42:19,
              raw: "1",
            },
          },
        ],
      },
      return: None,
      type_params: [],
      builtin: false,
      static: false,
      override: false,
    },
  ],
}