global int @test.x = 0

func unit @test.testReassignGlobals() {
  Store int @test.x, 1
  %0 := Add int 2, 3
  Store int @test.x, %0
  %1 := Load int @test.x
  %2 := Load int @test.x
  %3 := Mul int %1, %2
  Store int @test.x, %3
  Ret
}

func unit @test.testReassignLocals() {
  %4 := Neg int 0
  %5 := Neg int 1
  %6 := Add int 2, 3
  %7 := Neg int %6
  %8 := Mul int %6, %6
  Ret
}

func unit @test.use<fn>(fn %9) {
  Ret
}

func int @test.main() {
  %10 := Call unit @test.use<fn>(@test.testReassignGlobals)
  %11 := Call unit @test.use<fn>(@test.testReassignLocals)
  Ret 0
}