global int @test.x = 0

func void @test.testReassignGlobals() {
  Store int @test.x, 1
  %0 := Add int 2, 3
  Store int @test.x, %0
  %1 := Load int @test.x
  %2 := Load int @test.x
  %3 := Mul int %1, %2
  Store int @test.x, %3
  Ret
}

func void @test.testReassignLocals() {
  %0 := Neg int 0
  %1 := Neg int 1
  %2 := Add int 2, 3
  %3 := Neg int %2
  %4 := Mul int %2, %2
  Ret
}

func void @test.use<Function>(fn %0) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.testReassignGlobals)
  Call void @test.use<Function>(@test.testReassignLocals)
  Ret 0
}