global int @test.global = 0

func int @test.getInt() {
  Ret 1
}

func int @test.getInt2() {
  Ret 2
}

func void @test.testGlobal() {
  %0 := Load int @test.global
  %1 := Add int %0, 1
  Store int @test.global, %1
  %2 := Load int @test.global
  %3 := Call int @test.getInt()
  %4 := Sub int %2, %3
  Store int @test.global, %4
  Ret
}

func void @test.testOperators() {
  %0 := Call int @test.getInt()
  %1 := Add int %0, 1
  %2 := Sub int %1, 2
  %3 := Mul int %2, 3
  %4 := Div int %3, 4
  %5 := Rem int %4, 5
  %6 := BitAnd int, %5 6
  %7 := BitOr int, %6 7
  %8 := BitXor int, %7 8
  %9 := Shl int, %8 9
  %10 := Shr int, %9 10
  %11 := Shrl int, %10 11
  Ret
}

func void @test.testOrder() {
  %0 := Call int @test.getInt()
  %1 := Call int @test.getInt2()
  %2 := Add int %0, %1
  Ret
}

func void @test.use<Function>(fn %0) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.testGlobal)
  Call void @test.use<Function>(@test.testOperators)
  Call void @test.use<Function>(@test.testOrder)
  Ret 0
}