type $tuple<Int,test.Rec5> {int, test.Rec5*}

type test.Rec1 {test.Rec1*}

func void @test.useSelfRecursive(test.Rec1* %0) {
  Ret
}

type test.Rec2 {test.Rec3*}

type test.Rec3 {test.Rec4*}

type test.Rec4 {test.Rec2*}

func void @test.useMutuallyRecursive(test.Rec3* %0) {
  Ret
}

type test.Rec5 {$tuple<Int,test.Rec5>*}

type test.Rec6 {test.Generic<test.Rec6>*}

type test.Generic<test.Rec6> {int, byte[4], test.Rec6*}

func void @test.useNested(test.Rec5* %0, test.Rec6* %1) {
  Ret
}

func int @test.main() {
  Ret 0
}