func unit @_init() {
  %0 := CallBuiltin std.string.String* myte_alloc(1)
  %1 := GetPointer byte*, std.string.String* %0.0
  Store byte* %1, @.S0
  %2 := GetPointer int, std.string.String* %0.1
  Store int %2, 4
  %3 := GetPointer int, std.string.String* %0.2
  Store int %3, 4
  Store std.string.String* @test.z, %0
  Ret
}

func unit @test.use<int>(int %4) {
  Ret
}

func unit @test.use<long>(long %5) {
  Ret
}

global unit @test.x = ()

global int @test.y1 = 500

global byte @test.y2 = 1

global long @test.y3 = 2147483648

global std.string.String* @test.z = uninitialized

global byte[4] @.S0 = "test"

global bool @test.a1 = true

func int @test.main() {
  %6 := Call unit @test.use<int>(0)
  %7 := Call unit @test.use<int>(2147483647)
  %8 := Call unit @test.use<long>(2147483648)
  %9 := Add int 2, 4
  %10 := Add int %9, 6
  %11 := Call unit @test.use<int>(%10)
  %12 := Add long 2, 2147483648
  %13 := Add long %12, 6
  %14 := Call unit @test.use<long>(%13)
  Ret 0
}