func void @test.test() {
  %0 := Call std.string.String* myte.builtin.alloc(1)
  %1 := Cast byte[3]* @.S0 to byte*
  %2 := GetPointer byte*, std.string.String* %0.2
  Store byte* %2, %1
  %3 := GetPointer int, std.string.String* %0.0
  Store int %3, 3
  %4 := GetPointer int, std.string.String* %0.1
  Store int %4, 3
  %5 := Call std.string.String* myte.builtin.alloc(1)
  %6 := Cast byte[6]* @.S1 to byte*
  %7 := GetPointer byte*, std.string.String* %5.2
  Store byte* %7, %6
  %8 := GetPointer int, std.string.String* %5.0
  Store int %8, 6
  %9 := GetPointer int, std.string.String* %5.1
  Store int %9, 6
  Ret
}

global byte[3] @.S0 = "foo"

global byte[6] @.S1 = "barbaz"

func int @test.main() {
  Call void @test.test()
  Ret 0
}