func void @test.test() {
  %0 := Call std.string.String* myte.builtin.alloc(1)
  %1 := GetPointer byte*, std.string.String* %0.2
  Store byte* %1, @.S0
  %2 := GetPointer int, std.string.String* %0.0
  Store int %2, 3
  %3 := GetPointer int, std.string.String* %0.1
  Store int %3, 3
  %4 := Call std.string.String* myte.builtin.alloc(1)
  %5 := GetPointer byte*, std.string.String* %4.2
  Store byte* %5, @.S1
  %6 := GetPointer int, std.string.String* %4.0
  Store int %6, 6
  %7 := GetPointer int, std.string.String* %4.1
  Store int %7, 6
  Ret
}

global byte[3] @.S0 = "foo"

global byte[6] @.S1 = "barbaz"

func int @test.main() {
  Call void @test.test()
  Ret 0
}