type $tuple<Bool,Bool> {bool, bool}

type $tuple<Bool,Byte,Bool> {bool, byte, bool}

type $tuple<Bool,Byte,Int> {bool, byte, int}

type $tuple<Bool,Byte> {bool, byte}

type $tuple<Bool,Int> {bool, int}

type $tuple<Bool,Long,Bool> {bool, long, bool}

type $tuple<Bool,Long,Int> {bool, long, int}

type $tuple<Bool,Long> {bool, long}

type $tuple<Int,Bool> {int, bool}

type $tuple<Int,Byte,Bool> {int, byte, bool}

type $tuple<Int,Byte,Int> {int, byte, int}

type $tuple<Int,Byte> {int, byte}

type $tuple<Int,Int> {int, int}

type $tuple<Int,Long,Bool> {int, long, bool}

type $tuple<Int,Long,Int> {int, long, int}

type $tuple<Int,Long> {int, long}

type _closure {fn, byte*}

func void @test.testNongenericInToplevel() {
  %0 := Call _closure* myte.builtin.alloc(1)
  %1 := Cast _closure* %0 to fn*
  Store fn %1, @test.testNongenericInToplevel:0
  %2 := GetPointer byte*, _closure* %0.1
  Store byte* %2, null
  %3 := Cast _closure* %0 to fn*
  %4 := Load fn %3
  %5 := GetPointer byte*, _closure* %0.1
  %6 := Load byte* %5
  %7 := Call int %4(1, %6)
  %8 := Call _closure* myte.builtin.alloc(1)
  %9 := Cast _closure* %8 to fn*
  Store fn %9, @test.testNongenericInToplevel:1
  %10 := GetPointer byte*, _closure* %8.1
  Store byte* %10, null
  %11 := Cast _closure* %8 to fn*
  %12 := Load fn %11
  %13 := GetPointer byte*, _closure* %8.1
  %14 := Load byte* %13
  %15 := Call bool %12(true, %14)
  %16 := Call _closure* myte.builtin.alloc(1)
  %17 := Cast _closure* %16 to fn*
  Store fn %17, @test.testNongenericInToplevel:2
  %18 := GetPointer byte*, _closure* %16.1
  Store byte* %18, null
  %19 := Cast _closure* %16 to fn*
  %20 := Load fn %19
  %21 := GetPointer byte*, _closure* %16.1
  %22 := Load byte* %21
  %23 := Call int %20(3, %22)
  Ret
}

func int @test.testNongenericInToplevel:0(int %0, byte* %1) {
  Ret %0
}

func bool @test.testNongenericInToplevel:1(bool %0, byte* %1) {
  Ret %0
}

func int @test.testNongenericInToplevel:2(int %0, byte* %1) {
  %2 := Add int %0, 1
  %3 := Mul int 2, %2
  Ret %3
}

func void @test.genericInToplevel<Bool>(bool %0) {
  %1 := Call _closure* myte.builtin.alloc(1)
  %2 := Cast _closure* %1 to fn*
  Store fn %2, @test.genericInToplevel<Bool>:0
  %3 := Call test.genericInToplevel<Bool>:0:env* myte.builtin.alloc(1)
  %4 := GetPointer bool, test.genericInToplevel<Bool>:0:env* %3.0
  Store bool %4, %0
  %5 := Cast test.genericInToplevel<Bool>:0:env* %3 to byte*
  %6 := GetPointer byte*, _closure* %1.1
  Store byte* %6, %5
  %7 := Cast _closure* %1 to fn*
  %8 := Load fn %7
  %9 := GetPointer byte*, _closure* %1.1
  %10 := Load byte* %9
  %11 := Call $tuple<Int,Bool>* %8(1, %10)
  %12 := Call _closure* myte.builtin.alloc(1)
  %13 := Cast _closure* %12 to fn*
  Store fn %13, @test.genericInToplevel<Bool>:1
  %14 := Call test.genericInToplevel<Bool>:1:env* myte.builtin.alloc(1)
  %15 := GetPointer bool, test.genericInToplevel<Bool>:1:env* %14.0
  Store bool %15, %0
  %16 := Cast test.genericInToplevel<Bool>:1:env* %14 to byte*
  %17 := GetPointer byte*, _closure* %12.1
  Store byte* %17, %16
  %18 := Cast _closure* %12 to fn*
  %19 := Load fn %18
  %20 := GetPointer byte*, _closure* %12.1
  %21 := Load byte* %20
  %22 := Call $tuple<Bool,Bool>* %19(true, %21)
  Ret
}

func void @test.genericInToplevel<Int>(int %0) {
  %1 := Call _closure* myte.builtin.alloc(1)
  %2 := Cast _closure* %1 to fn*
  Store fn %2, @test.genericInToplevel<Int>:0
  %3 := Call test.genericInToplevel<Int>:0:env* myte.builtin.alloc(1)
  %4 := GetPointer int, test.genericInToplevel<Int>:0:env* %3.0
  Store int %4, %0
  %5 := Cast test.genericInToplevel<Int>:0:env* %3 to byte*
  %6 := GetPointer byte*, _closure* %1.1
  Store byte* %6, %5
  %7 := Cast _closure* %1 to fn*
  %8 := Load fn %7
  %9 := GetPointer byte*, _closure* %1.1
  %10 := Load byte* %9
  %11 := Call $tuple<Int,Int>* %8(1, %10)
  %12 := Call _closure* myte.builtin.alloc(1)
  %13 := Cast _closure* %12 to fn*
  Store fn %13, @test.genericInToplevel<Int>:1
  %14 := Call test.genericInToplevel<Int>:1:env* myte.builtin.alloc(1)
  %15 := GetPointer int, test.genericInToplevel<Int>:1:env* %14.0
  Store int %15, %0
  %16 := Cast test.genericInToplevel<Int>:1:env* %14 to byte*
  %17 := GetPointer byte*, _closure* %12.1
  Store byte* %17, %16
  %18 := Cast _closure* %12 to fn*
  %19 := Load fn %18
  %20 := GetPointer byte*, _closure* %12.1
  %21 := Load byte* %20
  %22 := Call $tuple<Bool,Int>* %19(true, %21)
  Ret
}

type test.genericInToplevel<Bool>:0:env {bool}

type test.genericInToplevel<Int>:0:env {int}

func $tuple<Int,Bool>* @test.genericInToplevel<Bool>:0(int %0, test.genericInToplevel<Bool>:0:env* %1) {
  %2 := Call $tuple<Int,Bool>* myte.builtin.alloc(1)
  %3 := GetPointer int, $tuple<Int,Bool>* %2.0
  Store int %3, %0
  %4 := GetPointer bool, test.genericInToplevel<Bool>:0:env* %1.0
  %5 := Load bool %4
  %6 := GetPointer bool, $tuple<Int,Bool>* %2.1
  Store bool %6, %5
  Ret %2
}

func $tuple<Int,Int>* @test.genericInToplevel<Int>:0(int %0, test.genericInToplevel<Int>:0:env* %1) {
  %2 := Call $tuple<Int,Int>* myte.builtin.alloc(1)
  %3 := GetPointer int, $tuple<Int,Int>* %2.0
  Store int %3, %0
  %4 := GetPointer int, test.genericInToplevel<Int>:0:env* %1.0
  %5 := Load int %4
  %6 := GetPointer int, $tuple<Int,Int>* %2.1
  Store int %6, %5
  Ret %2
}

type test.genericInToplevel<Bool>:1:env {bool}

type test.genericInToplevel<Int>:1:env {int}

func $tuple<Bool,Bool>* @test.genericInToplevel<Bool>:1(bool %0, test.genericInToplevel<Bool>:1:env* %1) {
  %2 := Call $tuple<Bool,Bool>* myte.builtin.alloc(1)
  %3 := GetPointer bool, $tuple<Bool,Bool>* %2.0
  Store bool %3, %0
  %4 := GetPointer bool, test.genericInToplevel<Bool>:1:env* %1.0
  %5 := Load bool %4
  %6 := GetPointer bool, $tuple<Bool,Bool>* %2.1
  Store bool %6, %5
  Ret %2
}

func $tuple<Bool,Int>* @test.genericInToplevel<Int>:1(bool %0, test.genericInToplevel<Int>:1:env* %1) {
  %2 := Call $tuple<Bool,Int>* myte.builtin.alloc(1)
  %3 := GetPointer bool, $tuple<Bool,Int>* %2.0
  Store bool %3, %0
  %4 := GetPointer int, test.genericInToplevel<Int>:1:env* %1.0
  %5 := Load int %4
  %6 := GetPointer int, $tuple<Bool,Int>* %2.1
  Store int %6, %5
  Ret %2
}

func void @test.testGenericInToplevel() {
  Call void @test.genericInToplevel<Int>(1)
  Call void @test.genericInToplevel<Bool>(false)
  Ret
}

type test.Type1 {int}

func void @test.Type1.nongeneric(test.Type1* %0) {
  %1 := Call _closure* myte.builtin.alloc(1)
  %2 := Cast _closure* %1 to fn*
  Store fn %2, @test.Type1.nongeneric:0
  %3 := GetPointer byte*, _closure* %1.1
  Store byte* %3, null
  %4 := Cast _closure* %1 to fn*
  %5 := Load fn %4
  %6 := GetPointer byte*, _closure* %1.1
  %7 := Load byte* %6
  %8 := Call int %5(1, %7)
  %9 := Call _closure* myte.builtin.alloc(1)
  %10 := Cast _closure* %9 to fn*
  Store fn %10, @test.Type1.nongeneric:1
  %11 := GetPointer byte*, _closure* %9.1
  Store byte* %11, null
  %12 := Cast _closure* %9 to fn*
  %13 := Load fn %12
  %14 := GetPointer byte*, _closure* %9.1
  %15 := Load byte* %14
  %16 := Call bool %13(true, %15)
  Ret
}

func int @test.Type1.nongeneric:0(int %0, byte* %1) {
  Ret %0
}

func bool @test.Type1.nongeneric:1(bool %0, byte* %1) {
  Ret %0
}

func void @test.testNongenericInMethod(test.Type1* %0) {
  Call void @test.Type1.nongeneric(%0)
  Ret
}

type test.Type2<Byte> {byte}

type test.Type2<Long> {long}

func void @test.Type2.nongeneric<Byte>(test.Type2<Byte>* %0, byte %1) {
  %2 := Call _closure* myte.builtin.alloc(1)
  %3 := Cast _closure* %2 to fn*
  Store fn %3, @test.Type2.nongeneric<Byte>:0
  %4 := Call test.Type2.nongeneric<Byte>:0:env* myte.builtin.alloc(1)
  %5 := GetPointer byte, test.Type2.nongeneric<Byte>:0:env* %4.0
  Store byte %5, %1
  %6 := Cast test.Type2.nongeneric<Byte>:0:env* %4 to byte*
  %7 := GetPointer byte*, _closure* %2.1
  Store byte* %7, %6
  %8 := Cast _closure* %2 to fn*
  %9 := Load fn %8
  %10 := GetPointer byte*, _closure* %2.1
  %11 := Load byte* %10
  %12 := Call $tuple<Int,Byte>* %9(1, %11)
  %13 := Call _closure* myte.builtin.alloc(1)
  %14 := Cast _closure* %13 to fn*
  Store fn %14, @test.Type2.nongeneric<Byte>:1
  %15 := Call test.Type2.nongeneric<Byte>:1:env* myte.builtin.alloc(1)
  %16 := GetPointer byte, test.Type2.nongeneric<Byte>:1:env* %15.0
  Store byte %16, %1
  %17 := Cast test.Type2.nongeneric<Byte>:1:env* %15 to byte*
  %18 := GetPointer byte*, _closure* %13.1
  Store byte* %18, %17
  %19 := Cast _closure* %13 to fn*
  %20 := Load fn %19
  %21 := GetPointer byte*, _closure* %13.1
  %22 := Load byte* %21
  %23 := Call $tuple<Bool,Byte>* %20(true, %22)
  Ret
}

func void @test.Type2.nongeneric<Long>(test.Type2<Long>* %0, long %1) {
  %2 := Call _closure* myte.builtin.alloc(1)
  %3 := Cast _closure* %2 to fn*
  Store fn %3, @test.Type2.nongeneric<Long>:0
  %4 := Call test.Type2.nongeneric<Long>:0:env* myte.builtin.alloc(1)
  %5 := GetPointer long, test.Type2.nongeneric<Long>:0:env* %4.0
  Store long %5, %1
  %6 := Cast test.Type2.nongeneric<Long>:0:env* %4 to byte*
  %7 := GetPointer byte*, _closure* %2.1
  Store byte* %7, %6
  %8 := Cast _closure* %2 to fn*
  %9 := Load fn %8
  %10 := GetPointer byte*, _closure* %2.1
  %11 := Load byte* %10
  %12 := Call $tuple<Int,Long>* %9(1, %11)
  %13 := Call _closure* myte.builtin.alloc(1)
  %14 := Cast _closure* %13 to fn*
  Store fn %14, @test.Type2.nongeneric<Long>:1
  %15 := Call test.Type2.nongeneric<Long>:1:env* myte.builtin.alloc(1)
  %16 := GetPointer long, test.Type2.nongeneric<Long>:1:env* %15.0
  Store long %16, %1
  %17 := Cast test.Type2.nongeneric<Long>:1:env* %15 to byte*
  %18 := GetPointer byte*, _closure* %13.1
  Store byte* %18, %17
  %19 := Cast _closure* %13 to fn*
  %20 := Load fn %19
  %21 := GetPointer byte*, _closure* %13.1
  %22 := Load byte* %21
  %23 := Call $tuple<Bool,Long>* %20(true, %22)
  Ret
}

type test.Type2.nongeneric<Byte>:0:env {byte}

type test.Type2.nongeneric<Long>:0:env {long}

func $tuple<Int,Byte>* @test.Type2.nongeneric<Byte>:0(int %0, test.Type2.nongeneric<Byte>:0:env* %1) {
  %2 := Call $tuple<Int,Byte>* myte.builtin.alloc(1)
  %3 := GetPointer int, $tuple<Int,Byte>* %2.0
  Store int %3, %0
  %4 := GetPointer byte, test.Type2.nongeneric<Byte>:0:env* %1.0
  %5 := Load byte %4
  %6 := GetPointer byte, $tuple<Int,Byte>* %2.1
  Store byte %6, %5
  Ret %2
}

func $tuple<Int,Long>* @test.Type2.nongeneric<Long>:0(int %0, test.Type2.nongeneric<Long>:0:env* %1) {
  %2 := Call $tuple<Int,Long>* myte.builtin.alloc(1)
  %3 := GetPointer int, $tuple<Int,Long>* %2.0
  Store int %3, %0
  %4 := GetPointer long, test.Type2.nongeneric<Long>:0:env* %1.0
  %5 := Load long %4
  %6 := GetPointer long, $tuple<Int,Long>* %2.1
  Store long %6, %5
  Ret %2
}

type test.Type2.nongeneric<Byte>:1:env {byte}

type test.Type2.nongeneric<Long>:1:env {long}

func $tuple<Bool,Byte>* @test.Type2.nongeneric<Byte>:1(bool %0, test.Type2.nongeneric<Byte>:1:env* %1) {
  %2 := Call $tuple<Bool,Byte>* myte.builtin.alloc(1)
  %3 := GetPointer bool, $tuple<Bool,Byte>* %2.0
  Store bool %3, %0
  %4 := GetPointer byte, test.Type2.nongeneric<Byte>:1:env* %1.0
  %5 := Load byte %4
  %6 := GetPointer byte, $tuple<Bool,Byte>* %2.1
  Store byte %6, %5
  Ret %2
}

func $tuple<Bool,Long>* @test.Type2.nongeneric<Long>:1(bool %0, test.Type2.nongeneric<Long>:1:env* %1) {
  %2 := Call $tuple<Bool,Long>* myte.builtin.alloc(1)
  %3 := GetPointer bool, $tuple<Bool,Long>* %2.0
  Store bool %3, %0
  %4 := GetPointer long, test.Type2.nongeneric<Long>:1:env* %1.0
  %5 := Load long %4
  %6 := GetPointer long, $tuple<Bool,Long>* %2.1
  Store long %6, %5
  Ret %2
}

func void @test.Type2.generic<Byte,Bool>(test.Type2<Byte>* %0, byte %1, bool %2) {
  %3 := Call _closure* myte.builtin.alloc(1)
  %4 := Cast _closure* %3 to fn*
  Store fn %4, @test.Type2.generic<Byte,Bool>:0
  %5 := Call test.Type2.generic<Byte,Bool>:0:env* myte.builtin.alloc(1)
  %6 := GetPointer bool, test.Type2.generic<Byte,Bool>:0:env* %5.0
  Store bool %6, %2
  %7 := GetPointer byte, test.Type2.generic<Byte,Bool>:0:env* %5.1
  Store byte %7, %1
  %8 := Cast test.Type2.generic<Byte,Bool>:0:env* %5 to byte*
  %9 := GetPointer byte*, _closure* %3.1
  Store byte* %9, %8
  %10 := Cast _closure* %3 to fn*
  %11 := Load fn %10
  %12 := GetPointer byte*, _closure* %3.1
  %13 := Load byte* %12
  %14 := Call $tuple<Int,Byte,Bool>* %11(1, %13)
  %15 := Call _closure* myte.builtin.alloc(1)
  %16 := Cast _closure* %15 to fn*
  Store fn %16, @test.Type2.generic<Byte,Bool>:1
  %17 := Call test.Type2.generic<Byte,Bool>:1:env* myte.builtin.alloc(1)
  %18 := GetPointer bool, test.Type2.generic<Byte,Bool>:1:env* %17.0
  Store bool %18, %2
  %19 := GetPointer byte, test.Type2.generic<Byte,Bool>:1:env* %17.1
  Store byte %19, %1
  %20 := Cast test.Type2.generic<Byte,Bool>:1:env* %17 to byte*
  %21 := GetPointer byte*, _closure* %15.1
  Store byte* %21, %20
  %22 := Cast _closure* %15 to fn*
  %23 := Load fn %22
  %24 := GetPointer byte*, _closure* %15.1
  %25 := Load byte* %24
  %26 := Call $tuple<Bool,Byte,Bool>* %23(true, %25)
  Ret
}

func void @test.Type2.generic<Byte,Int>(test.Type2<Byte>* %0, byte %1, int %2) {
  %3 := Call _closure* myte.builtin.alloc(1)
  %4 := Cast _closure* %3 to fn*
  Store fn %4, @test.Type2.generic<Byte,Int>:0
  %5 := Call test.Type2.generic<Byte,Int>:0:env* myte.builtin.alloc(1)
  %6 := GetPointer byte, test.Type2.generic<Byte,Int>:0:env* %5.0
  Store byte %6, %1
  %7 := GetPointer int, test.Type2.generic<Byte,Int>:0:env* %5.2
  Store int %7, %2
  %8 := Cast test.Type2.generic<Byte,Int>:0:env* %5 to byte*
  %9 := GetPointer byte*, _closure* %3.1
  Store byte* %9, %8
  %10 := Cast _closure* %3 to fn*
  %11 := Load fn %10
  %12 := GetPointer byte*, _closure* %3.1
  %13 := Load byte* %12
  %14 := Call $tuple<Int,Byte,Int>* %11(1, %13)
  %15 := Call _closure* myte.builtin.alloc(1)
  %16 := Cast _closure* %15 to fn*
  Store fn %16, @test.Type2.generic<Byte,Int>:1
  %17 := Call test.Type2.generic<Byte,Int>:1:env* myte.builtin.alloc(1)
  %18 := GetPointer byte, test.Type2.generic<Byte,Int>:1:env* %17.0
  Store byte %18, %1
  %19 := GetPointer int, test.Type2.generic<Byte,Int>:1:env* %17.2
  Store int %19, %2
  %20 := Cast test.Type2.generic<Byte,Int>:1:env* %17 to byte*
  %21 := GetPointer byte*, _closure* %15.1
  Store byte* %21, %20
  %22 := Cast _closure* %15 to fn*
  %23 := Load fn %22
  %24 := GetPointer byte*, _closure* %15.1
  %25 := Load byte* %24
  %26 := Call $tuple<Bool,Byte,Int>* %23(true, %25)
  Ret
}

func void @test.Type2.generic<Long,Bool>(test.Type2<Long>* %0, long %1, bool %2) {
  %3 := Call _closure* myte.builtin.alloc(1)
  %4 := Cast _closure* %3 to fn*
  Store fn %4, @test.Type2.generic<Long,Bool>:0
  %5 := Call test.Type2.generic<Long,Bool>:0:env* myte.builtin.alloc(1)
  %6 := GetPointer bool, test.Type2.generic<Long,Bool>:0:env* %5.0
  Store bool %6, %2
  %7 := GetPointer long, test.Type2.generic<Long,Bool>:0:env* %5.2
  Store long %7, %1
  %8 := Cast test.Type2.generic<Long,Bool>:0:env* %5 to byte*
  %9 := GetPointer byte*, _closure* %3.1
  Store byte* %9, %8
  %10 := Cast _closure* %3 to fn*
  %11 := Load fn %10
  %12 := GetPointer byte*, _closure* %3.1
  %13 := Load byte* %12
  %14 := Call $tuple<Int,Long,Bool>* %11(1, %13)
  %15 := Call _closure* myte.builtin.alloc(1)
  %16 := Cast _closure* %15 to fn*
  Store fn %16, @test.Type2.generic<Long,Bool>:1
  %17 := Call test.Type2.generic<Long,Bool>:1:env* myte.builtin.alloc(1)
  %18 := GetPointer bool, test.Type2.generic<Long,Bool>:1:env* %17.0
  Store bool %18, %2
  %19 := GetPointer long, test.Type2.generic<Long,Bool>:1:env* %17.2
  Store long %19, %1
  %20 := Cast test.Type2.generic<Long,Bool>:1:env* %17 to byte*
  %21 := GetPointer byte*, _closure* %15.1
  Store byte* %21, %20
  %22 := Cast _closure* %15 to fn*
  %23 := Load fn %22
  %24 := GetPointer byte*, _closure* %15.1
  %25 := Load byte* %24
  %26 := Call $tuple<Bool,Long,Bool>* %23(true, %25)
  Ret
}

func void @test.Type2.generic<Long,Int>(test.Type2<Long>* %0, long %1, int %2) {
  %3 := Call _closure* myte.builtin.alloc(1)
  %4 := Cast _closure* %3 to fn*
  Store fn %4, @test.Type2.generic<Long,Int>:0
  %5 := Call test.Type2.generic<Long,Int>:0:env* myte.builtin.alloc(1)
  %6 := GetPointer int, test.Type2.generic<Long,Int>:0:env* %5.0
  Store int %6, %2
  %7 := GetPointer long, test.Type2.generic<Long,Int>:0:env* %5.2
  Store long %7, %1
  %8 := Cast test.Type2.generic<Long,Int>:0:env* %5 to byte*
  %9 := GetPointer byte*, _closure* %3.1
  Store byte* %9, %8
  %10 := Cast _closure* %3 to fn*
  %11 := Load fn %10
  %12 := GetPointer byte*, _closure* %3.1
  %13 := Load byte* %12
  %14 := Call $tuple<Int,Long,Int>* %11(1, %13)
  %15 := Call _closure* myte.builtin.alloc(1)
  %16 := Cast _closure* %15 to fn*
  Store fn %16, @test.Type2.generic<Long,Int>:1
  %17 := Call test.Type2.generic<Long,Int>:1:env* myte.builtin.alloc(1)
  %18 := GetPointer int, test.Type2.generic<Long,Int>:1:env* %17.0
  Store int %18, %2
  %19 := GetPointer long, test.Type2.generic<Long,Int>:1:env* %17.2
  Store long %19, %1
  %20 := Cast test.Type2.generic<Long,Int>:1:env* %17 to byte*
  %21 := GetPointer byte*, _closure* %15.1
  Store byte* %21, %20
  %22 := Cast _closure* %15 to fn*
  %23 := Load fn %22
  %24 := GetPointer byte*, _closure* %15.1
  %25 := Load byte* %24
  %26 := Call $tuple<Bool,Long,Int>* %23(true, %25)
  Ret
}

type test.Type2.generic<Byte,Bool>:0:env {bool, byte}

type test.Type2.generic<Byte,Int>:0:env {byte, byte[3], int}

type test.Type2.generic<Long,Bool>:0:env {bool, byte[7], long}

type test.Type2.generic<Long,Int>:0:env {int, byte[4], long}

func $tuple<Int,Byte,Bool>* @test.Type2.generic<Byte,Bool>:0(int %0, test.Type2.generic<Byte,Bool>:0:env* %1) {
  %2 := Call $tuple<Int,Byte,Bool>* myte.builtin.alloc(1)
  %3 := GetPointer int, $tuple<Int,Byte,Bool>* %2.0
  Store int %3, %0
  %4 := GetPointer byte, test.Type2.generic<Byte,Bool>:0:env* %1.1
  %5 := Load byte %4
  %6 := GetPointer byte, $tuple<Int,Byte,Bool>* %2.1
  Store byte %6, %5
  %7 := GetPointer bool, test.Type2.generic<Byte,Bool>:0:env* %1.0
  %8 := Load bool %7
  %9 := GetPointer bool, $tuple<Int,Byte,Bool>* %2.2
  Store bool %9, %8
  Ret %2
}

func $tuple<Int,Byte,Int>* @test.Type2.generic<Byte,Int>:0(int %0, test.Type2.generic<Byte,Int>:0:env* %1) {
  %2 := Call $tuple<Int,Byte,Int>* myte.builtin.alloc(1)
  %3 := GetPointer int, $tuple<Int,Byte,Int>* %2.0
  Store int %3, %0
  %4 := GetPointer byte, test.Type2.generic<Byte,Int>:0:env* %1.0
  %5 := Load byte %4
  %6 := GetPointer byte, $tuple<Int,Byte,Int>* %2.1
  Store byte %6, %5
  %7 := GetPointer int, test.Type2.generic<Byte,Int>:0:env* %1.2
  %8 := Load int %7
  %9 := GetPointer int, $tuple<Int,Byte,Int>* %2.2
  Store int %9, %8
  Ret %2
}

func $tuple<Int,Long,Bool>* @test.Type2.generic<Long,Bool>:0(int %0, test.Type2.generic<Long,Bool>:0:env* %1) {
  %2 := Call $tuple<Int,Long,Bool>* myte.builtin.alloc(1)
  %3 := GetPointer int, $tuple<Int,Long,Bool>* %2.0
  Store int %3, %0
  %4 := GetPointer long, test.Type2.generic<Long,Bool>:0:env* %1.2
  %5 := Load long %4
  %6 := GetPointer long, $tuple<Int,Long,Bool>* %2.1
  Store long %6, %5
  %7 := GetPointer bool, test.Type2.generic<Long,Bool>:0:env* %1.0
  %8 := Load bool %7
  %9 := GetPointer bool, $tuple<Int,Long,Bool>* %2.2
  Store bool %9, %8
  Ret %2
}

func $tuple<Int,Long,Int>* @test.Type2.generic<Long,Int>:0(int %0, test.Type2.generic<Long,Int>:0:env* %1) {
  %2 := Call $tuple<Int,Long,Int>* myte.builtin.alloc(1)
  %3 := GetPointer int, $tuple<Int,Long,Int>* %2.0
  Store int %3, %0
  %4 := GetPointer long, test.Type2.generic<Long,Int>:0:env* %1.2
  %5 := Load long %4
  %6 := GetPointer long, $tuple<Int,Long,Int>* %2.1
  Store long %6, %5
  %7 := GetPointer int, test.Type2.generic<Long,Int>:0:env* %1.0
  %8 := Load int %7
  %9 := GetPointer int, $tuple<Int,Long,Int>* %2.2
  Store int %9, %8
  Ret %2
}

type test.Type2.generic<Byte,Bool>:1:env {bool, byte}

type test.Type2.generic<Byte,Int>:1:env {byte, byte[3], int}

type test.Type2.generic<Long,Bool>:1:env {bool, byte[7], long}

type test.Type2.generic<Long,Int>:1:env {int, byte[4], long}

func $tuple<Bool,Byte,Bool>* @test.Type2.generic<Byte,Bool>:1(bool %0, test.Type2.generic<Byte,Bool>:1:env* %1) {
  %2 := Call $tuple<Bool,Byte,Bool>* myte.builtin.alloc(1)
  %3 := GetPointer bool, $tuple<Bool,Byte,Bool>* %2.0
  Store bool %3, %0
  %4 := GetPointer byte, test.Type2.generic<Byte,Bool>:1:env* %1.1
  %5 := Load byte %4
  %6 := GetPointer byte, $tuple<Bool,Byte,Bool>* %2.1
  Store byte %6, %5
  %7 := GetPointer bool, test.Type2.generic<Byte,Bool>:1:env* %1.0
  %8 := Load bool %7
  %9 := GetPointer bool, $tuple<Bool,Byte,Bool>* %2.2
  Store bool %9, %8
  Ret %2
}

func $tuple<Bool,Byte,Int>* @test.Type2.generic<Byte,Int>:1(bool %0, test.Type2.generic<Byte,Int>:1:env* %1) {
  %2 := Call $tuple<Bool,Byte,Int>* myte.builtin.alloc(1)
  %3 := GetPointer bool, $tuple<Bool,Byte,Int>* %2.0
  Store bool %3, %0
  %4 := GetPointer byte, test.Type2.generic<Byte,Int>:1:env* %1.0
  %5 := Load byte %4
  %6 := GetPointer byte, $tuple<Bool,Byte,Int>* %2.1
  Store byte %6, %5
  %7 := GetPointer int, test.Type2.generic<Byte,Int>:1:env* %1.2
  %8 := Load int %7
  %9 := GetPointer int, $tuple<Bool,Byte,Int>* %2.2
  Store int %9, %8
  Ret %2
}

func $tuple<Bool,Long,Bool>* @test.Type2.generic<Long,Bool>:1(bool %0, test.Type2.generic<Long,Bool>:1:env* %1) {
  %2 := Call $tuple<Bool,Long,Bool>* myte.builtin.alloc(1)
  %3 := GetPointer bool, $tuple<Bool,Long,Bool>* %2.0
  Store bool %3, %0
  %4 := GetPointer long, test.Type2.generic<Long,Bool>:1:env* %1.2
  %5 := Load long %4
  %6 := GetPointer long, $tuple<Bool,Long,Bool>* %2.1
  Store long %6, %5
  %7 := GetPointer bool, test.Type2.generic<Long,Bool>:1:env* %1.0
  %8 := Load bool %7
  %9 := GetPointer bool, $tuple<Bool,Long,Bool>* %2.2
  Store bool %9, %8
  Ret %2
}

func $tuple<Bool,Long,Int>* @test.Type2.generic<Long,Int>:1(bool %0, test.Type2.generic<Long,Int>:1:env* %1) {
  %2 := Call $tuple<Bool,Long,Int>* myte.builtin.alloc(1)
  %3 := GetPointer bool, $tuple<Bool,Long,Int>* %2.0
  Store bool %3, %0
  %4 := GetPointer long, test.Type2.generic<Long,Int>:1:env* %1.2
  %5 := Load long %4
  %6 := GetPointer long, $tuple<Bool,Long,Int>* %2.1
  Store long %6, %5
  %7 := GetPointer int, test.Type2.generic<Long,Int>:1:env* %1.0
  %8 := Load int %7
  %9 := GetPointer int, $tuple<Bool,Long,Int>* %2.2
  Store int %9, %8
  Ret %2
}

func void @test.testGenericInMethod(test.Type2<Long>* %0, test.Type2<Byte>* %1) {
  Call void @test.Type2.nongeneric<Long>(%0, 1)
  Call void @test.Type2.nongeneric<Byte>(%1, 1)
  Call void @test.Type2.generic<Long,Int>(%0, 1, 1)
  Call void @test.Type2.generic<Long,Bool>(%0, 1, true)
  Call void @test.Type2.generic<Byte,Int>(%1, 1, 1)
  Call void @test.Type2.generic<Byte,Bool>(%1, 1, true)
  Ret
}

func void @test.Trait3.generic<test.Type3<Long>,Long,Bool>(test.Type3<Long>* %0, long %1, bool %2) {
  %3 := Call _closure* myte.builtin.alloc(1)
  %4 := Cast _closure* %3 to fn*
  Store fn %4, @test.Trait3.generic<test.Type3<Long>,Long,Bool>:0
  %5 := Call test.Trait3.generic<test.Type3<Long>,Long,Bool>:0:env* myte.builtin.alloc(1)
  %6 := GetPointer bool, test.Trait3.generic<test.Type3<Long>,Long,Bool>:0:env* %5.0
  Store bool %6, %2
  %7 := GetPointer long, test.Trait3.generic<test.Type3<Long>,Long,Bool>:0:env* %5.2
  Store long %7, %1
  %8 := Cast test.Trait3.generic<test.Type3<Long>,Long,Bool>:0:env* %5 to byte*
  %9 := GetPointer byte*, _closure* %3.1
  Store byte* %9, %8
  %10 := Cast _closure* %3 to fn*
  %11 := Load fn %10
  %12 := GetPointer byte*, _closure* %3.1
  %13 := Load byte* %12
  %14 := Call $tuple<Int,Long,Bool>* %11(1, %13)
  %15 := Call _closure* myte.builtin.alloc(1)
  %16 := Cast _closure* %15 to fn*
  Store fn %16, @test.Trait3.generic<test.Type3<Long>,Long,Bool>:1
  %17 := Call test.Trait3.generic<test.Type3<Long>,Long,Bool>:1:env* myte.builtin.alloc(1)
  %18 := GetPointer bool, test.Trait3.generic<test.Type3<Long>,Long,Bool>:1:env* %17.0
  Store bool %18, %2
  %19 := GetPointer long, test.Trait3.generic<test.Type3<Long>,Long,Bool>:1:env* %17.2
  Store long %19, %1
  %20 := Cast test.Trait3.generic<test.Type3<Long>,Long,Bool>:1:env* %17 to byte*
  %21 := GetPointer byte*, _closure* %15.1
  Store byte* %21, %20
  %22 := Cast _closure* %15 to fn*
  %23 := Load fn %22
  %24 := GetPointer byte*, _closure* %15.1
  %25 := Load byte* %24
  %26 := Call $tuple<Bool,Long,Bool>* %23(true, %25)
  Ret
}

func void @test.Trait3.generic<test.Type3<Long>,Long,Int>(test.Type3<Long>* %0, long %1, int %2) {
  %3 := Call _closure* myte.builtin.alloc(1)
  %4 := Cast _closure* %3 to fn*
  Store fn %4, @test.Trait3.generic<test.Type3<Long>,Long,Int>:0
  %5 := Call test.Trait3.generic<test.Type3<Long>,Long,Int>:0:env* myte.builtin.alloc(1)
  %6 := GetPointer int, test.Trait3.generic<test.Type3<Long>,Long,Int>:0:env* %5.0
  Store int %6, %2
  %7 := GetPointer long, test.Trait3.generic<test.Type3<Long>,Long,Int>:0:env* %5.2
  Store long %7, %1
  %8 := Cast test.Trait3.generic<test.Type3<Long>,Long,Int>:0:env* %5 to byte*
  %9 := GetPointer byte*, _closure* %3.1
  Store byte* %9, %8
  %10 := Cast _closure* %3 to fn*
  %11 := Load fn %10
  %12 := GetPointer byte*, _closure* %3.1
  %13 := Load byte* %12
  %14 := Call $tuple<Int,Long,Int>* %11(1, %13)
  %15 := Call _closure* myte.builtin.alloc(1)
  %16 := Cast _closure* %15 to fn*
  Store fn %16, @test.Trait3.generic<test.Type3<Long>,Long,Int>:1
  %17 := Call test.Trait3.generic<test.Type3<Long>,Long,Int>:1:env* myte.builtin.alloc(1)
  %18 := GetPointer int, test.Trait3.generic<test.Type3<Long>,Long,Int>:1:env* %17.0
  Store int %18, %2
  %19 := GetPointer long, test.Trait3.generic<test.Type3<Long>,Long,Int>:1:env* %17.2
  Store long %19, %1
  %20 := Cast test.Trait3.generic<test.Type3<Long>,Long,Int>:1:env* %17 to byte*
  %21 := GetPointer byte*, _closure* %15.1
  Store byte* %21, %20
  %22 := Cast _closure* %15 to fn*
  %23 := Load fn %22
  %24 := GetPointer byte*, _closure* %15.1
  %25 := Load byte* %24
  %26 := Call $tuple<Bool,Long,Int>* %23(true, %25)
  Ret
}

type test.Trait3.generic<test.Type3<Long>,Long,Bool>:0:env {bool, byte[7], long}

type test.Trait3.generic<test.Type3<Long>,Long,Int>:0:env {int, byte[4], long}

func $tuple<Int,Long,Bool>* @test.Trait3.generic<test.Type3<Long>,Long,Bool>:0(int %0, test.Trait3.generic<test.Type3<Long>,Long,Bool>:0:env* %1) {
  %2 := Call $tuple<Int,Long,Bool>* myte.builtin.alloc(1)
  %3 := GetPointer int, $tuple<Int,Long,Bool>* %2.0
  Store int %3, %0
  %4 := GetPointer long, test.Trait3.generic<test.Type3<Long>,Long,Bool>:0:env* %1.2
  %5 := Load long %4
  %6 := GetPointer long, $tuple<Int,Long,Bool>* %2.1
  Store long %6, %5
  %7 := GetPointer bool, test.Trait3.generic<test.Type3<Long>,Long,Bool>:0:env* %1.0
  %8 := Load bool %7
  %9 := GetPointer bool, $tuple<Int,Long,Bool>* %2.2
  Store bool %9, %8
  Ret %2
}

func $tuple<Int,Long,Int>* @test.Trait3.generic<test.Type3<Long>,Long,Int>:0(int %0, test.Trait3.generic<test.Type3<Long>,Long,Int>:0:env* %1) {
  %2 := Call $tuple<Int,Long,Int>* myte.builtin.alloc(1)
  %3 := GetPointer int, $tuple<Int,Long,Int>* %2.0
  Store int %3, %0
  %4 := GetPointer long, test.Trait3.generic<test.Type3<Long>,Long,Int>:0:env* %1.2
  %5 := Load long %4
  %6 := GetPointer long, $tuple<Int,Long,Int>* %2.1
  Store long %6, %5
  %7 := GetPointer int, test.Trait3.generic<test.Type3<Long>,Long,Int>:0:env* %1.0
  %8 := Load int %7
  %9 := GetPointer int, $tuple<Int,Long,Int>* %2.2
  Store int %9, %8
  Ret %2
}

type test.Trait3.generic<test.Type3<Long>,Long,Bool>:1:env {bool, byte[7], long}

type test.Trait3.generic<test.Type3<Long>,Long,Int>:1:env {int, byte[4], long}

func $tuple<Bool,Long,Bool>* @test.Trait3.generic<test.Type3<Long>,Long,Bool>:1(bool %0, test.Trait3.generic<test.Type3<Long>,Long,Bool>:1:env* %1) {
  %2 := Call $tuple<Bool,Long,Bool>* myte.builtin.alloc(1)
  %3 := GetPointer bool, $tuple<Bool,Long,Bool>* %2.0
  Store bool %3, %0
  %4 := GetPointer long, test.Trait3.generic<test.Type3<Long>,Long,Bool>:1:env* %1.2
  %5 := Load long %4
  %6 := GetPointer long, $tuple<Bool,Long,Bool>* %2.1
  Store long %6, %5
  %7 := GetPointer bool, test.Trait3.generic<test.Type3<Long>,Long,Bool>:1:env* %1.0
  %8 := Load bool %7
  %9 := GetPointer bool, $tuple<Bool,Long,Bool>* %2.2
  Store bool %9, %8
  Ret %2
}

func $tuple<Bool,Long,Int>* @test.Trait3.generic<test.Type3<Long>,Long,Int>:1(bool %0, test.Trait3.generic<test.Type3<Long>,Long,Int>:1:env* %1) {
  %2 := Call $tuple<Bool,Long,Int>* myte.builtin.alloc(1)
  %3 := GetPointer bool, $tuple<Bool,Long,Int>* %2.0
  Store bool %3, %0
  %4 := GetPointer long, test.Trait3.generic<test.Type3<Long>,Long,Int>:1:env* %1.2
  %5 := Load long %4
  %6 := GetPointer long, $tuple<Bool,Long,Int>* %2.1
  Store long %6, %5
  %7 := GetPointer int, test.Trait3.generic<test.Type3<Long>,Long,Int>:1:env* %1.0
  %8 := Load int %7
  %9 := GetPointer int, $tuple<Bool,Long,Int>* %2.2
  Store int %9, %8
  Ret %2
}

type test.Type3<Long> {long}

func void @test.testGenericInInheritedMethod(test.Type3<Long>* %0) {
  Call void @test.Trait3.generic<test.Type3<Long>,Long,Int>(%0, 1, 1)
  Call void @test.Trait3.generic<test.Type3<Long>,Long,Bool>(%0, 1, true)
  Ret
}

func int @test.main() {
  Ret 0
}