type $tuple<Bool,Bool> {bool, bool}

type $tuple<Bool,Byte,Bool> {bool, byte, bool}

type $tuple<Bool,Byte,Int> {bool, byte, int}

type $tuple<Bool,Byte> {bool, byte}

type $tuple<Bool,Int> {bool, int}

type $tuple<Bool,Long,Bool> {bool, long, bool}

type $tuple<Bool,Long,Int> {bool, long, int}

type $tuple<Bool,Long> {bool, long}

type $tuple<Int,Bool> {int, bool}

type $tuple<Int,Byte,Bool> {int, byte, bool}

type $tuple<Int,Byte,Int> {int, byte, int}

type $tuple<Int,Byte> {int, byte}

type $tuple<Int,Int> {int, int}

type $tuple<Int,Long,Bool> {int, long, bool}

type $tuple<Int,Long,Int> {int, long, int}

type $tuple<Int,Long> {int, long}

type _closure {fn, byte*}

func void @test.testNongenericInToplevel() {
  %0 := Call _closure* myte.builtin.alloc(1)
  %1 := Cast _closure* %0 to fn*
  Store fn %1, @test.testNongenericInToplevel:0
  %2 := GetPointer byte*, _closure* %0.1
  Store byte* %2, null
  %3 := Cast _closure* %0 to fn*
  %4 := Load fn %3
  %5 := GetPointer byte*, _closure* %0.1
  %6 := Load byte* %5
  %7 := Call int %4(1, %6)
  %8 := Call _closure* myte.builtin.alloc(1)
  %9 := Cast _closure* %8 to fn*
  Store fn %9, @test.testNongenericInToplevel:1
  %10 := GetPointer byte*, _closure* %8.1
  Store byte* %10, null
  %11 := Cast _closure* %8 to fn*
  %12 := Load fn %11
  %13 := GetPointer byte*, _closure* %8.1
  %14 := Load byte* %13
  %15 := Call bool %12(true, %14)
  %16 := Call _closure* myte.builtin.alloc(1)
  %17 := Cast _closure* %16 to fn*
  Store fn %17, @test.testNongenericInToplevel:2
  %18 := GetPointer byte*, _closure* %16.1
  Store byte* %18, null
  %19 := Cast _closure* %16 to fn*
  %20 := Load fn %19
  %21 := GetPointer byte*, _closure* %16.1
  %22 := Load byte* %21
  %23 := Call int %20(3, %22)
  Ret
}

func int @test.testNongenericInToplevel:0(int %0, byte* %1) {
  Ret %0
}

func bool @test.testNongenericInToplevel:1(bool %0, byte* %1) {
  Ret %0
}

func int @test.testNongenericInToplevel:2(int %0, byte* %1) {
  %2 := Add int %0, 1
  %3 := Mul int 2, %2
  Ret %3
}

func void @test.genericInToplevel<Bool>(bool %0) {
  %1 := Call _closure* myte.builtin.alloc(1)
  %2 := Cast _closure* %1 to fn*
  Store fn %2, @test.genericInToplevel<Bool>:0
  %3 := GetPointer byte*, _closure* %1.1
  Store byte* %3, null
  %4 := Cast _closure* %1 to fn*
  %5 := Load fn %4
  %6 := GetPointer byte*, _closure* %1.1
  %7 := Load byte* %6
  %8 := Call $tuple<Int,Bool>* %5(1, %7)
  %9 := Call _closure* myte.builtin.alloc(1)
  %10 := Cast _closure* %9 to fn*
  Store fn %10, @test.genericInToplevel<Bool>:1
  %11 := GetPointer byte*, _closure* %9.1
  Store byte* %11, null
  %12 := Cast _closure* %9 to fn*
  %13 := Load fn %12
  %14 := GetPointer byte*, _closure* %9.1
  %15 := Load byte* %14
  %16 := Call $tuple<Bool,Bool>* %13(true, %15)
  Ret
}

func void @test.genericInToplevel<Int>(int %0) {
  %1 := Call _closure* myte.builtin.alloc(1)
  %2 := Cast _closure* %1 to fn*
  Store fn %2, @test.genericInToplevel<Int>:0
  %3 := GetPointer byte*, _closure* %1.1
  Store byte* %3, null
  %4 := Cast _closure* %1 to fn*
  %5 := Load fn %4
  %6 := GetPointer byte*, _closure* %1.1
  %7 := Load byte* %6
  %8 := Call $tuple<Int,Int>* %5(1, %7)
  %9 := Call _closure* myte.builtin.alloc(1)
  %10 := Cast _closure* %9 to fn*
  Store fn %10, @test.genericInToplevel<Int>:1
  %11 := GetPointer byte*, _closure* %9.1
  Store byte* %11, null
  %12 := Cast _closure* %9 to fn*
  %13 := Load fn %12
  %14 := GetPointer byte*, _closure* %9.1
  %15 := Load byte* %14
  %16 := Call $tuple<Bool,Int>* %13(true, %15)
  Ret
}

func $tuple<Int,Bool>* @test.genericInToplevel<Bool>:0(int %0, byte* %1) {
  %2 := Call $tuple<Int,Bool>* myte.builtin.alloc(1)
  %3 := GetPointer int, $tuple<Int,Bool>* %2.0
  Store int %3, %0
  %4 := GetPointer bool, $tuple<Int,Bool>* %2.1
  Store bool %4, %0
  Ret %2
}

func $tuple<Int,Int>* @test.genericInToplevel<Int>:0(int %0, byte* %1) {
  %2 := Call $tuple<Int,Int>* myte.builtin.alloc(1)
  %3 := GetPointer int, $tuple<Int,Int>* %2.0
  Store int %3, %0
  %4 := GetPointer int, $tuple<Int,Int>* %2.1
  Store int %4, %0
  Ret %2
}

func $tuple<Bool,Bool>* @test.genericInToplevel<Bool>:1(bool %0, byte* %1) {
  %2 := Call $tuple<Bool,Bool>* myte.builtin.alloc(1)
  %3 := GetPointer bool, $tuple<Bool,Bool>* %2.0
  Store bool %3, %0
  %4 := GetPointer bool, $tuple<Bool,Bool>* %2.1
  Store bool %4, %0
  Ret %2
}

func $tuple<Bool,Int>* @test.genericInToplevel<Int>:1(bool %0, byte* %1) {
  %2 := Call $tuple<Bool,Int>* myte.builtin.alloc(1)
  %3 := GetPointer bool, $tuple<Bool,Int>* %2.0
  Store bool %3, %0
  %4 := GetPointer int, $tuple<Bool,Int>* %2.1
  Store int %4, %0
  Ret %2
}

func void @test.testGenericInToplevel() {
  Call void @test.genericInToplevel<Int>(1)
  Call void @test.genericInToplevel<Bool>(false)
  Ret
}

type test.Type1 {int}

func void @test.Type1.nongeneric(test.Type1* %0) {
  %1 := Call _closure* myte.builtin.alloc(1)
  %2 := Cast _closure* %1 to fn*
  Store fn %2, @test.Type1.nongeneric:0
  %3 := GetPointer byte*, _closure* %1.1
  Store byte* %3, null
  %4 := Cast _closure* %1 to fn*
  %5 := Load fn %4
  %6 := GetPointer byte*, _closure* %1.1
  %7 := Load byte* %6
  %8 := Call int %5(1, %7)
  %9 := Call _closure* myte.builtin.alloc(1)
  %10 := Cast _closure* %9 to fn*
  Store fn %10, @test.Type1.nongeneric:1
  %11 := GetPointer byte*, _closure* %9.1
  Store byte* %11, null
  %12 := Cast _closure* %9 to fn*
  %13 := Load fn %12
  %14 := GetPointer byte*, _closure* %9.1
  %15 := Load byte* %14
  %16 := Call bool %13(true, %15)
  Ret
}

func int @test.Type1.nongeneric:0(int %0, byte* %1) {
  Ret %0
}

func bool @test.Type1.nongeneric:1(bool %0, byte* %1) {
  Ret %0
}

func void @test.testNongenericInMethod(test.Type1* %0) {
  Call void @test.Type1.nongeneric(%0)
  Ret
}

type test.Type2<Byte> {byte}

type test.Type2<Long> {long}

func void @test.Type2.nongeneric<Byte>(test.Type2<Byte>* %0, byte %1) {
  %2 := Call _closure* myte.builtin.alloc(1)
  %3 := Cast _closure* %2 to fn*
  Store fn %3, @test.Type2.nongeneric<Byte>:0
  %4 := GetPointer byte*, _closure* %2.1
  Store byte* %4, null
  %5 := Cast _closure* %2 to fn*
  %6 := Load fn %5
  %7 := GetPointer byte*, _closure* %2.1
  %8 := Load byte* %7
  %9 := Call $tuple<Int,Byte>* %6(1, %8)
  %10 := Call _closure* myte.builtin.alloc(1)
  %11 := Cast _closure* %10 to fn*
  Store fn %11, @test.Type2.nongeneric<Byte>:1
  %12 := GetPointer byte*, _closure* %10.1
  Store byte* %12, null
  %13 := Cast _closure* %10 to fn*
  %14 := Load fn %13
  %15 := GetPointer byte*, _closure* %10.1
  %16 := Load byte* %15
  %17 := Call $tuple<Bool,Byte>* %14(true, %16)
  Ret
}

func void @test.Type2.nongeneric<Long>(test.Type2<Long>* %0, long %1) {
  %2 := Call _closure* myte.builtin.alloc(1)
  %3 := Cast _closure* %2 to fn*
  Store fn %3, @test.Type2.nongeneric<Long>:0
  %4 := GetPointer byte*, _closure* %2.1
  Store byte* %4, null
  %5 := Cast _closure* %2 to fn*
  %6 := Load fn %5
  %7 := GetPointer byte*, _closure* %2.1
  %8 := Load byte* %7
  %9 := Call $tuple<Int,Long>* %6(1, %8)
  %10 := Call _closure* myte.builtin.alloc(1)
  %11 := Cast _closure* %10 to fn*
  Store fn %11, @test.Type2.nongeneric<Long>:1
  %12 := GetPointer byte*, _closure* %10.1
  Store byte* %12, null
  %13 := Cast _closure* %10 to fn*
  %14 := Load fn %13
  %15 := GetPointer byte*, _closure* %10.1
  %16 := Load byte* %15
  %17 := Call $tuple<Bool,Long>* %14(true, %16)
  Ret
}

func $tuple<Int,Byte>* @test.Type2.nongeneric<Byte>:0(int %0, byte* %1) {
  %2 := Call $tuple<Int,Byte>* myte.builtin.alloc(1)
  %3 := GetPointer int, $tuple<Int,Byte>* %2.0
  Store int %3, %0
  %4 := GetPointer byte, $tuple<Int,Byte>* %2.1
  Store byte %4, %1
  Ret %2
}

func $tuple<Int,Long>* @test.Type2.nongeneric<Long>:0(int %0, byte* %1) {
  %2 := Call $tuple<Int,Long>* myte.builtin.alloc(1)
  %3 := GetPointer int, $tuple<Int,Long>* %2.0
  Store int %3, %0
  %4 := GetPointer long, $tuple<Int,Long>* %2.1
  Store long %4, %1
  Ret %2
}

func $tuple<Bool,Byte>* @test.Type2.nongeneric<Byte>:1(bool %0, byte* %1) {
  %2 := Call $tuple<Bool,Byte>* myte.builtin.alloc(1)
  %3 := GetPointer bool, $tuple<Bool,Byte>* %2.0
  Store bool %3, %0
  %4 := GetPointer byte, $tuple<Bool,Byte>* %2.1
  Store byte %4, %1
  Ret %2
}

func $tuple<Bool,Long>* @test.Type2.nongeneric<Long>:1(bool %0, byte* %1) {
  %2 := Call $tuple<Bool,Long>* myte.builtin.alloc(1)
  %3 := GetPointer bool, $tuple<Bool,Long>* %2.0
  Store bool %3, %0
  %4 := GetPointer long, $tuple<Bool,Long>* %2.1
  Store long %4, %1
  Ret %2
}

func void @test.Type2.generic<Byte,Bool>(test.Type2<Byte>* %0, byte %1, bool %2) {
  %3 := Call _closure* myte.builtin.alloc(1)
  %4 := Cast _closure* %3 to fn*
  Store fn %4, @test.Type2.generic<Byte,Bool>:0
  %5 := GetPointer byte*, _closure* %3.1
  Store byte* %5, null
  %6 := Cast _closure* %3 to fn*
  %7 := Load fn %6
  %8 := GetPointer byte*, _closure* %3.1
  %9 := Load byte* %8
  %10 := Call $tuple<Int,Byte,Bool>* %7(1, %9)
  %11 := Call _closure* myte.builtin.alloc(1)
  %12 := Cast _closure* %11 to fn*
  Store fn %12, @test.Type2.generic<Byte,Bool>:1
  %13 := GetPointer byte*, _closure* %11.1
  Store byte* %13, null
  %14 := Cast _closure* %11 to fn*
  %15 := Load fn %14
  %16 := GetPointer byte*, _closure* %11.1
  %17 := Load byte* %16
  %18 := Call $tuple<Bool,Byte,Bool>* %15(true, %17)
  Ret
}

func void @test.Type2.generic<Byte,Int>(test.Type2<Byte>* %0, byte %1, int %2) {
  %3 := Call _closure* myte.builtin.alloc(1)
  %4 := Cast _closure* %3 to fn*
  Store fn %4, @test.Type2.generic<Byte,Int>:0
  %5 := GetPointer byte*, _closure* %3.1
  Store byte* %5, null
  %6 := Cast _closure* %3 to fn*
  %7 := Load fn %6
  %8 := GetPointer byte*, _closure* %3.1
  %9 := Load byte* %8
  %10 := Call $tuple<Int,Byte,Int>* %7(1, %9)
  %11 := Call _closure* myte.builtin.alloc(1)
  %12 := Cast _closure* %11 to fn*
  Store fn %12, @test.Type2.generic<Byte,Int>:1
  %13 := GetPointer byte*, _closure* %11.1
  Store byte* %13, null
  %14 := Cast _closure* %11 to fn*
  %15 := Load fn %14
  %16 := GetPointer byte*, _closure* %11.1
  %17 := Load byte* %16
  %18 := Call $tuple<Bool,Byte,Int>* %15(true, %17)
  Ret
}

func void @test.Type2.generic<Long,Bool>(test.Type2<Long>* %0, long %1, bool %2) {
  %3 := Call _closure* myte.builtin.alloc(1)
  %4 := Cast _closure* %3 to fn*
  Store fn %4, @test.Type2.generic<Long,Bool>:0
  %5 := GetPointer byte*, _closure* %3.1
  Store byte* %5, null
  %6 := Cast _closure* %3 to fn*
  %7 := Load fn %6
  %8 := GetPointer byte*, _closure* %3.1
  %9 := Load byte* %8
  %10 := Call $tuple<Int,Long,Bool>* %7(1, %9)
  %11 := Call _closure* myte.builtin.alloc(1)
  %12 := Cast _closure* %11 to fn*
  Store fn %12, @test.Type2.generic<Long,Bool>:1
  %13 := GetPointer byte*, _closure* %11.1
  Store byte* %13, null
  %14 := Cast _closure* %11 to fn*
  %15 := Load fn %14
  %16 := GetPointer byte*, _closure* %11.1
  %17 := Load byte* %16
  %18 := Call $tuple<Bool,Long,Bool>* %15(true, %17)
  Ret
}

func void @test.Type2.generic<Long,Int>(test.Type2<Long>* %0, long %1, int %2) {
  %3 := Call _closure* myte.builtin.alloc(1)
  %4 := Cast _closure* %3 to fn*
  Store fn %4, @test.Type2.generic<Long,Int>:0
  %5 := GetPointer byte*, _closure* %3.1
  Store byte* %5, null
  %6 := Cast _closure* %3 to fn*
  %7 := Load fn %6
  %8 := GetPointer byte*, _closure* %3.1
  %9 := Load byte* %8
  %10 := Call $tuple<Int,Long,Int>* %7(1, %9)
  %11 := Call _closure* myte.builtin.alloc(1)
  %12 := Cast _closure* %11 to fn*
  Store fn %12, @test.Type2.generic<Long,Int>:1
  %13 := GetPointer byte*, _closure* %11.1
  Store byte* %13, null
  %14 := Cast _closure* %11 to fn*
  %15 := Load fn %14
  %16 := GetPointer byte*, _closure* %11.1
  %17 := Load byte* %16
  %18 := Call $tuple<Bool,Long,Int>* %15(true, %17)
  Ret
}

func $tuple<Int,Byte,Bool>* @test.Type2.generic<Byte,Bool>:0(int %0, byte* %1) {
  %2 := Call $tuple<Int,Byte,Bool>* myte.builtin.alloc(1)
  %3 := GetPointer int, $tuple<Int,Byte,Bool>* %2.0
  Store int %3, %0
  %4 := GetPointer byte, $tuple<Int,Byte,Bool>* %2.1
  Store byte %4, %1
  %5 := GetPointer bool, $tuple<Int,Byte,Bool>* %2.2
  Store bool %5, %2
  Ret %2
}

func $tuple<Int,Byte,Int>* @test.Type2.generic<Byte,Int>:0(int %0, byte* %1) {
  %2 := Call $tuple<Int,Byte,Int>* myte.builtin.alloc(1)
  %3 := GetPointer int, $tuple<Int,Byte,Int>* %2.0
  Store int %3, %0
  %4 := GetPointer byte, $tuple<Int,Byte,Int>* %2.1
  Store byte %4, %1
  %5 := GetPointer int, $tuple<Int,Byte,Int>* %2.2
  Store int %5, %2
  Ret %2
}

func $tuple<Int,Long,Bool>* @test.Type2.generic<Long,Bool>:0(int %0, byte* %1) {
  %2 := Call $tuple<Int,Long,Bool>* myte.builtin.alloc(1)
  %3 := GetPointer int, $tuple<Int,Long,Bool>* %2.0
  Store int %3, %0
  %4 := GetPointer long, $tuple<Int,Long,Bool>* %2.1
  Store long %4, %1
  %5 := GetPointer bool, $tuple<Int,Long,Bool>* %2.2
  Store bool %5, %2
  Ret %2
}

func $tuple<Int,Long,Int>* @test.Type2.generic<Long,Int>:0(int %0, byte* %1) {
  %2 := Call $tuple<Int,Long,Int>* myte.builtin.alloc(1)
  %3 := GetPointer int, $tuple<Int,Long,Int>* %2.0
  Store int %3, %0
  %4 := GetPointer long, $tuple<Int,Long,Int>* %2.1
  Store long %4, %1
  %5 := GetPointer int, $tuple<Int,Long,Int>* %2.2
  Store int %5, %2
  Ret %2
}

func $tuple<Bool,Byte,Bool>* @test.Type2.generic<Byte,Bool>:1(bool %0, byte* %1) {
  %2 := Call $tuple<Bool,Byte,Bool>* myte.builtin.alloc(1)
  %3 := GetPointer bool, $tuple<Bool,Byte,Bool>* %2.0
  Store bool %3, %0
  %4 := GetPointer byte, $tuple<Bool,Byte,Bool>* %2.1
  Store byte %4, %1
  %5 := GetPointer bool, $tuple<Bool,Byte,Bool>* %2.2
  Store bool %5, %2
  Ret %2
}

func $tuple<Bool,Byte,Int>* @test.Type2.generic<Byte,Int>:1(bool %0, byte* %1) {
  %2 := Call $tuple<Bool,Byte,Int>* myte.builtin.alloc(1)
  %3 := GetPointer bool, $tuple<Bool,Byte,Int>* %2.0
  Store bool %3, %0
  %4 := GetPointer byte, $tuple<Bool,Byte,Int>* %2.1
  Store byte %4, %1
  %5 := GetPointer int, $tuple<Bool,Byte,Int>* %2.2
  Store int %5, %2
  Ret %2
}

func $tuple<Bool,Long,Bool>* @test.Type2.generic<Long,Bool>:1(bool %0, byte* %1) {
  %2 := Call $tuple<Bool,Long,Bool>* myte.builtin.alloc(1)
  %3 := GetPointer bool, $tuple<Bool,Long,Bool>* %2.0
  Store bool %3, %0
  %4 := GetPointer long, $tuple<Bool,Long,Bool>* %2.1
  Store long %4, %1
  %5 := GetPointer bool, $tuple<Bool,Long,Bool>* %2.2
  Store bool %5, %2
  Ret %2
}

func $tuple<Bool,Long,Int>* @test.Type2.generic<Long,Int>:1(bool %0, byte* %1) {
  %2 := Call $tuple<Bool,Long,Int>* myte.builtin.alloc(1)
  %3 := GetPointer bool, $tuple<Bool,Long,Int>* %2.0
  Store bool %3, %0
  %4 := GetPointer long, $tuple<Bool,Long,Int>* %2.1
  Store long %4, %1
  %5 := GetPointer int, $tuple<Bool,Long,Int>* %2.2
  Store int %5, %2
  Ret %2
}

func void @test.testGenericInMethod(test.Type2<Long>* %0, test.Type2<Byte>* %1) {
  Call void @test.Type2.nongeneric<Long>(%0, 1)
  Call void @test.Type2.nongeneric<Byte>(%1, 1)
  Call void @test.Type2.generic<Long,Int>(%0, 1, 1)
  Call void @test.Type2.generic<Long,Bool>(%0, 1, true)
  Call void @test.Type2.generic<Byte,Int>(%1, 1, 1)
  Call void @test.Type2.generic<Byte,Bool>(%1, 1, true)
  Ret
}

func void @test.Trait3.generic<test.Type3<Long>,Long,Bool>(test.Type3<Long>* %0, long %1, bool %2) {
  %3 := Call _closure* myte.builtin.alloc(1)
  %4 := Cast _closure* %3 to fn*
  Store fn %4, @test.Trait3.generic<test.Type3<Long>,Long,Bool>:0
  %5 := GetPointer byte*, _closure* %3.1
  Store byte* %5, null
  %6 := Cast _closure* %3 to fn*
  %7 := Load fn %6
  %8 := GetPointer byte*, _closure* %3.1
  %9 := Load byte* %8
  %10 := Call $tuple<Int,Long,Bool>* %7(1, %9)
  %11 := Call _closure* myte.builtin.alloc(1)
  %12 := Cast _closure* %11 to fn*
  Store fn %12, @test.Trait3.generic<test.Type3<Long>,Long,Bool>:1
  %13 := GetPointer byte*, _closure* %11.1
  Store byte* %13, null
  %14 := Cast _closure* %11 to fn*
  %15 := Load fn %14
  %16 := GetPointer byte*, _closure* %11.1
  %17 := Load byte* %16
  %18 := Call $tuple<Bool,Long,Bool>* %15(true, %17)
  Ret
}

func void @test.Trait3.generic<test.Type3<Long>,Long,Int>(test.Type3<Long>* %0, long %1, int %2) {
  %3 := Call _closure* myte.builtin.alloc(1)
  %4 := Cast _closure* %3 to fn*
  Store fn %4, @test.Trait3.generic<test.Type3<Long>,Long,Int>:0
  %5 := GetPointer byte*, _closure* %3.1
  Store byte* %5, null
  %6 := Cast _closure* %3 to fn*
  %7 := Load fn %6
  %8 := GetPointer byte*, _closure* %3.1
  %9 := Load byte* %8
  %10 := Call $tuple<Int,Long,Int>* %7(1, %9)
  %11 := Call _closure* myte.builtin.alloc(1)
  %12 := Cast _closure* %11 to fn*
  Store fn %12, @test.Trait3.generic<test.Type3<Long>,Long,Int>:1
  %13 := GetPointer byte*, _closure* %11.1
  Store byte* %13, null
  %14 := Cast _closure* %11 to fn*
  %15 := Load fn %14
  %16 := GetPointer byte*, _closure* %11.1
  %17 := Load byte* %16
  %18 := Call $tuple<Bool,Long,Int>* %15(true, %17)
  Ret
}

func $tuple<Int,Long,Bool>* @test.Trait3.generic<test.Type3<Long>,Long,Bool>:0(int %0, byte* %1) {
  %2 := Call $tuple<Int,Long,Bool>* myte.builtin.alloc(1)
  %3 := GetPointer int, $tuple<Int,Long,Bool>* %2.0
  Store int %3, %0
  %4 := GetPointer long, $tuple<Int,Long,Bool>* %2.1
  Store long %4, %1
  %5 := GetPointer bool, $tuple<Int,Long,Bool>* %2.2
  Store bool %5, %2
  Ret %2
}

func $tuple<Int,Long,Int>* @test.Trait3.generic<test.Type3<Long>,Long,Int>:0(int %0, byte* %1) {
  %2 := Call $tuple<Int,Long,Int>* myte.builtin.alloc(1)
  %3 := GetPointer int, $tuple<Int,Long,Int>* %2.0
  Store int %3, %0
  %4 := GetPointer long, $tuple<Int,Long,Int>* %2.1
  Store long %4, %1
  %5 := GetPointer int, $tuple<Int,Long,Int>* %2.2
  Store int %5, %2
  Ret %2
}

func $tuple<Bool,Long,Bool>* @test.Trait3.generic<test.Type3<Long>,Long,Bool>:1(bool %0, byte* %1) {
  %2 := Call $tuple<Bool,Long,Bool>* myte.builtin.alloc(1)
  %3 := GetPointer bool, $tuple<Bool,Long,Bool>* %2.0
  Store bool %3, %0
  %4 := GetPointer long, $tuple<Bool,Long,Bool>* %2.1
  Store long %4, %1
  %5 := GetPointer bool, $tuple<Bool,Long,Bool>* %2.2
  Store bool %5, %2
  Ret %2
}

func $tuple<Bool,Long,Int>* @test.Trait3.generic<test.Type3<Long>,Long,Int>:1(bool %0, byte* %1) {
  %2 := Call $tuple<Bool,Long,Int>* myte.builtin.alloc(1)
  %3 := GetPointer bool, $tuple<Bool,Long,Int>* %2.0
  Store bool %3, %0
  %4 := GetPointer long, $tuple<Bool,Long,Int>* %2.1
  Store long %4, %1
  %5 := GetPointer int, $tuple<Bool,Long,Int>* %2.2
  Store int %5, %2
  Ret %2
}

type test.Type3<Long> {long}

func void @test.testGenericInInheritedMethod(test.Type3<Long>* %0) {
  Call void @test.Trait3.generic<test.Type3<Long>,Long,Int>(%0, 1, 1)
  Call void @test.Trait3.generic<test.Type3<Long>,Long,Bool>(%0, 1, true)
  Ret
}

func int @test.main() {
  Ret 0
}