  .global _main

  .data
.S0:
  .ascii "Failed 1\n"
.S1:
  .ascii "Passed 1\n"
.S2:
  .ascii "Passed 2\n"
.S3:
  .ascii "Failed 2\n"

  .text
test.Trait1.foo:
  cmp w0, #7
  cset w0, eq
  ret
_main:
  str x30, [sp, #-16]!
  movz w0, #5
  bl test.Trait1.foo
  cbz w0, .L0
  movz w0, #16
  bl mytec_alloc
  adrp x1, .S0
  add x1, x1, :lo12:.S0
  str x1, [x0, #8]
  movz w1, #9
  str w1, [x0]
  movz w1, #9
  str w1, [x0, #4]
  bl std.io.print
  b .L1
.L0:
  movz w0, #16
  bl mytec_alloc
  adrp x1, .S1
  add x1, x1, :lo12:.S1
  str x1, [x0, #8]
  movz w1, #9
  str w1, [x0]
  movz w1, #9
  str w1, [x0, #4]
  bl std.io.print
.L1:
  movz w0, #7
  bl test.Trait1.foo
  cbz w0, .L2
  movz w0, #16
  bl mytec_alloc
  adrp x1, .S2
  add x1, x1, :lo12:.S2
  str x1, [x0, #8]
  movz w1, #9
  str w1, [x0]
  movz w1, #9
  str w1, [x0, #4]
  bl std.io.print
  b .L3
.L2:
  movz w0, #16
  bl mytec_alloc
  adrp x1, .S3
  add x1, x1, :lo12:.S3
  str x1, [x0, #8]
  movz w1, #9
  str w1, [x0]
  movz w1, #9
  str w1, [x0, #4]
  bl std.io.print
.L3:
  mov w0, wzr
  ldr x30, [sp], #16
  ret
Passed 1
Passed 2