func int @test.test1(bool %0) {
  branch %0, @0, @1
label @0:
  %1 := Mov int 2
  continue @2
label @1:
  %2 := Mov int 3
  continue @2
label @2:
  %3 := Phi int @0:%1, @1:%2
  Ret %3
}

func int @test.test2(bool %4, int %5) {
  branch %4, @3, @4
label @3:
  %6 := Mov int 3
  continue @5
label @4:
  %7 := Mov int %5
  continue @5
label @5:
  %8 := Phi int @3:%6, @4:%7
  %9 := Add int %8, 2
  Ret %9
}

func unit @test.test3() {
  %10 := Mov int 1
  continue @6
label @6:
  %12 := Phi int @test.test3:%10, @7:%11
  %13 := Eq int %12, 2
  branch %13, @7, @8
label @7:
  %14 := Add int %12, 1
  %11 := Mov int %14
  continue @6
label @8:
  %15 := Neg int %12
  Ret
}

func unit @test.main() {
  Ret
}