global int @t.int1 {
  Store @t.int1, 3
}

global bool @t.bool1 {
  Store @t.bool1, false
}

global int @t.int2 {
  Store @t.int2, -286
}

global bool @t.bool2 {
  Store @t.bool2, true
}

global bool @t.mixed {
  Store @t.mixed, true
}

func unit @t.useBool(bool %0) {
  Ret
}

func unit @t.useInt(int %1) {
  Ret
}

func bool @t.rand() {
  Ret true
}

func unit @t.main() {
  %2 := Call unit @t.useInt(6)
  %3 := Call unit @t.useBool(false)
  %4 := Call bool @t.rand()
  %5 := Call unit @t.useBool(true)
  Ret
}