  .global _main

  .text
_main:
  str x30, [sp, #-16]!
  movz w0, #1
  bl test.testMyteAllocLiteralCount
  movz w0, #1
  bl test.testMyteAllocVariableCount
  mov w0, wzr
  ldr x30, [sp], #16
  ret
test.testMyteAllocLiteralCount:
  str x30, [sp, #-16]!
  movz w0, #16
  bl mytec_alloc
  movz w0, #800
  bl mytec_alloc
  ldr x30, [sp], #16
  ret
test.testMyteAllocVariableCount:
  stp x19, x30, [sp, #-16]!
  mov w19, w0
  mov w0, w19
  bl mytec_alloc
  lsl w0, w19, #2
  bl mytec_alloc
  lsl w0, w19, #3
  bl mytec_alloc
  ldp x19, x30, [sp], #16
  ret