  .global _main

  .text
test.boolFalse:
  mov w0, wzr
  ret
test.boolTrue:
  movz w0, #1
  ret
test.byteMax:
  movz w0, #127
  ret
test.byteOne:
  movz w0, #1
  ret
test.byteZero:
  mov w0, wzr
  ret
test.intMax:
  movz w0, #65535
  movk w0, #32767, lsl #16
  ret
test.intMaxOneChunk:
  movz w0, #65535
  ret
test.intMinTwoChunks:
  movz w0, #0
  movk w0, #1, lsl #16
  ret
test.intOne:
  movz w0, #1
  ret
test.intTwoChunks:
  movz w0, #9999
  movk w0, #1, lsl #16
  ret
test.intZero:
  mov w0, wzr
  ret
test.longFourChunks:
  movz x0, #16384
  movk x0, #15954, lsl #16
  movk x0, #30233, lsl #32
  movk x0, #35, lsl #48
  ret
test.longMax:
  movz x0, #65535
  movk x0, #65535, lsl #16
  movk x0, #65535, lsl #32
  movk x0, #32767, lsl #48
  ret
test.longMaxOneChunk:
  movz x0, #65535
  ret
test.longMaxThreeChunks:
  movz x0, #65535
  movk x0, #65535, lsl #16
  movk x0, #65535, lsl #32
  ret
test.longMaxTwoChunks:
  movz x0, #65535
  movk x0, #65535, lsl #16
  ret
test.longMinFourChunks:
  movz x0, #0
  movk x0, #0, lsl #16
  movk x0, #0, lsl #32
  movk x0, #1, lsl #48
  ret
test.longMinThreeChunks:
  movz x0, #0
  movk x0, #0, lsl #16
  movk x0, #1, lsl #32
  ret
test.longMinTwoChunks:
  movz x0, #0
  movk x0, #1, lsl #16
  ret
test.longOne:
  movz x0, #1
  ret
test.longThreeChunks:
  movz x0, #42495
  movk x0, #16794, lsl #16
  movk x0, #21, lsl #32
  ret
test.longTwoChunks:
  movz x0, #9999
  movk x0, #1, lsl #16
  ret
test.longZero:
  mov x0, xzr
  ret
_main:
  mov w0, wzr
  ret
test.negByteMin:
  movn w0, #127
  ret
test.negByteNegOne:
  movn w0, #0
  ret
test.negIntMaxOneChunk:
  movn w0, #65535
  ret
test.negIntMin:
  movn w0, #65535
  movk w0, #32768, lsl #16
  ret
test.negIntMinTwoChunks:
  movn w0, #0
  movk w0, #65534, lsl #16
  ret
test.negIntNegOne:
  movn w0, #0
  ret
test.negLongFourChunks:
  movn x0, #37850
  movk x0, #2519, lsl #16
  movk x0, #52058, lsl #32
  movk x0, #65532, lsl #48
  ret
test.negLongMaxOneChunk:
  movn x0, #65535
  ret
test.negLongMaxThreeChunks:
  movn x0, #65535
  movk x0, #0, lsl #16
  movk x0, #0, lsl #32
  ret
test.negLongMaxTwoChunks:
  movn x0, #65535
  movk x0, #0, lsl #16
  ret
test.negLongMin:
  movn x0, #65535
  movk x0, #0, lsl #16
  movk x0, #0, lsl #32
  movk x0, #32768, lsl #48
  ret
test.negLongMinFourChunks:
  movn x0, #0
  movk x0, #65535, lsl #16
  movk x0, #65535, lsl #32
  movk x0, #65534, lsl #48
  ret
test.negLongMinThreeChunks:
  movn x0, #0
  movk x0, #65535, lsl #16
  movk x0, #65534, lsl #32
  ret
test.negLongMinTwoChunks:
  movn x0, #0
  movk x0, #65534, lsl #16
  ret
test.negLongNegOne:
  movn x0, #0
  ret
test.negLongThreeChunks:
  movn x0, #2745
  movk x0, #424, lsl #16
  movk x0, #65508, lsl #32
  ret
test.negLongTwoChunks:
  movn x0, #12685
  movk x0, #51767, lsl #16
  ret