test/parser/trait_declaration/traits.myte
{
  node: Module,
  loc: 1:0-26:0,
  name: {
    node: ModuleName,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: TraitDeclaration,
      loc: 3:0-3:12,
      kind: Trait,
      name: {
        node: Identifier,
        loc: 3:6-3:9,
        name: "Foo",
      },
      type_params: [],
      implemented: [],
      methods: [],
      is_public: false,
    },
    {
      node: TraitDeclaration,
      loc: 5:0-5:16,
      kind: Trait,
      name: {
        node: Identifier,
        loc: 5:10-5:13,
        name: "Foo",
      },
      type_params: [],
      implemented: [],
      methods: [],
      is_public: true,
    },
    {
      node: TraitDeclaration,
      loc: 7:0-10:1,
      kind: Trait,
      name: {
        node: Identifier,
        loc: 7:6-7:9,
        name: "Foo",
      },
      type_params: [],
      implemented: [
        {
          node: IdentifierType,
          loc: 8:2-8:16,
          name: {
            node: ScopedIdentifier,
            loc: 8:10-8:13,
            scopes: [],
            name: {
              node: Identifier,
              loc: 8:10-8:13,
              name: "Bar",
            },
          },
          type_args: [
            {
              node: IdentifierType,
              loc: 8:14-8:15,
              name: {
                node: ScopedIdentifier,
                loc: 8:14-8:15,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 8:14-8:15,
                  name: "T",
                },
              },
              type_args: [],
            },
          ],
        },
        {
          node: IdentifierType,
          loc: 9:2-9:24,
          name: {
            node: ScopedIdentifier,
            loc: 9:10-9:13,
            scopes: [],
            name: {
              node: Identifier,
              loc: 9:10-9:13,
              name: "Baz",
            },
          },
          type_args: [
            {
              node: IdentifierType,
              loc: 9:14-9:15,
              name: {
                node: ScopedIdentifier,
                loc: 9:14-9:15,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 9:14-9:15,
                  name: "T",
                },
              },
              type_args: [],
            },
            {
              node: TupleType,
              loc: 9:17-9:23,
              elements: [
                {
                  node: IdentifierType,
                  loc: 9:18-9:19,
                  name: {
                    node: ScopedIdentifier,
                    loc: 9:18-9:19,
                    scopes: [],
                    name: {
                      node: Identifier,
                      loc: 9:18-9:19,
                      name: "U",
                    },
                  },
                  type_args: [],
                },
                {
                  node: IdentifierType,
                  loc: 9:21-9:22,
                  name: {
                    node: ScopedIdentifier,
                    loc: 9:21-9:22,
                    scopes: [],
                    name: {
                      node: Identifier,
                      loc: 9:21-9:22,
                      name: "V",
                    },
                  },
                  type_args: [],
                },
              ],
            },
          ],
        },
      ],
      methods: [],
      is_public: false,
    },
    {
      node: TraitDeclaration,
      loc: 12:0-16:1,
      kind: Trait,
      name: {
        node: Identifier,
        loc: 12:6-12:9,
        name: "Foo",
      },
      type_params: [],
      implemented: [],
      methods: [
        {
          node: Function,
          loc: 13:2-13:17,
          name: {
            node: Identifier,
            loc: 13:6-13:9,
            name: "bar",
          },
          params: [
            {
              node: Param,
              loc: 13:10-13:16,
              name: {
                node: Identifier,
                loc: 13:10-13:11,
                name: "x",
              },
              annot: {
                node: IdentifierType,
                loc: 13:13-13:16,
                name: {
                  node: ScopedIdentifier,
                  loc: 13:13-13:16,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 13:13-13:16,
                    name: "Int",
                  },
                },
                type_args: [],
              },
            },
          ],
          body: None,
          return: None,
          type_params: [],
          is_public: false,
          is_static: false,
          is_override: false,
        },
        {
          node: Function,
          loc: 14:2-14:25,
          name: {
            node: Identifier,
            loc: 14:6-14:9,
            name: "foo",
          },
          params: [
            {
              node: Param,
              loc: 14:10-14:16,
              name: {
                node: Identifier,
                loc: 14:10-14:11,
                name: "x",
              },
              annot: {
                node: IdentifierType,
                loc: 14:13-14:16,
                name: {
                  node: ScopedIdentifier,
                  loc: 14:13-14:16,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 14:13-14:16,
                    name: "Int",
                  },
                },
                type_args: [],
              },
            },
          ],
          body: None,
          return: {
            node: IdentifierType,
            loc: 14:19-14:25,
            name: {
              node: ScopedIdentifier,
              loc: 14:19-14:25,
              scopes: [],
              name: {
                node: Identifier,
                loc: 14:19-14:25,
                name: "String",
              },
            },
            type_args: [],
          },
          type_params: [],
          is_public: false,
          is_static: false,
          is_override: false,
        },
        {
          node: Function,
          loc: 15:2-15:17,
          name: {
            node: Identifier,
            loc: 15:6-15:9,
            name: "baz",
          },
          params: [
            {
              node: Param,
              loc: 15:10-15:16,
              name: {
                node: Identifier,
                loc: 15:10-15:11,
                name: "x",
              },
              annot: {
                node: IdentifierType,
                loc: 15:13-15:16,
                name: {
                  node: ScopedIdentifier,
                  loc: 15:13-15:16,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 15:13-15:16,
                    name: "Int",
                  },
                },
                type_args: [],
              },
            },
          ],
          body: None,
          return: None,
          type_params: [],
          is_public: false,
          is_static: false,
          is_override: false,
        },
      ],
      is_public: false,
    },
    {
      node: TraitDeclaration,
      loc: 18:0-25:1,
      kind: Trait,
      name: {
        node: Identifier,
        loc: 18:6-18:9,
        name: "Foo",
      },
      type_params: [
        {
          node: TypeParameter,
          loc: 18:10-18:11,
          name: {
            node: Identifier,
            loc: 18:10-18:11,
            name: "T",
          },
          bounds: [],
        },
      ],
      implemented: [],
      methods: [
        {
          node: Function,
          loc: 19:2-21:3,
          name: {
            node: Identifier,
            loc: 19:6-19:9,
            name: "foo",
          },
          params: [
            {
              node: Param,
              loc: 19:13-19:17,
              name: {
                node: Identifier,
                loc: 19:13-19:14,
                name: "x",
              },
              annot: {
                node: IdentifierType,
                loc: 19:16-19:17,
                name: {
                  node: ScopedIdentifier,
                  loc: 19:16-19:17,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 19:16-19:17,
                    name: "T",
                  },
                },
                type_args: [],
              },
            },
          ],
          body: {
            node: Block,
            loc: 19:22-21:3,
            statements: [
              {
                node: Return,
                loc: 20:4-20:13,
                arg: {
                  node: IntLiteral,
                  loc: 20:11-20:12,
                  raw: "1",
                },
              },
            ],
          },
          return: {
            node: IdentifierType,
            loc: 19:20-19:21,
            name: {
              node: ScopedIdentifier,
              loc: 19:20-19:21,
              scopes: [],
              name: {
                node: Identifier,
                loc: 19:20-19:21,
                name: "U",
              },
            },
            type_args: [],
          },
          type_params: [
            {
              node: TypeParameter,
              loc: 19:10-19:11,
              name: {
                node: Identifier,
                loc: 19:10-19:11,
                name: "U",
              },
              bounds: [],
            },
          ],
          is_public: false,
          is_static: false,
          is_override: false,
        },
        {
          node: Function,
          loc: 23:2-23:28,
          name: {
            node: Identifier,
            loc: 23:15-23:26,
            name: "overrideFun",
          },
          params: [],
          body: None,
          return: None,
          type_params: [],
          is_public: false,
          is_static: false,
          is_override: true,
        },
        {
          node: Function,
          loc: 24:2-24:24,
          name: {
            node: Identifier,
            loc: 24:13-24:22,
            name: "staticFun",
          },
          params: [],
          body: None,
          return: None,
          type_params: [],
          is_public: false,
          is_static: true,
          is_override: false,
        },
      ],
      is_public: false,
    },
  ],
}