func unit @main() {
  continue @0
label @0:
  branch true, @0, @1
label @1:
  %0 := Mov bool true
  continue @2
label @2:
  branch %0, @3, @4
label @3:
  %1 := Add int 1, 1
  continue @2
label @4:
  %2 := LogNot false
  branch %2, @5, @9
label @5:
  %3 := Add int 2, 2
  continue @6
label @6:
  %4 := LogNot true
  branch %4, @7, @8
label @7:
  %5 := Add int 3, 3
  continue @6
label @8:
  %6 := Add int 4, 4
  continue @4
label @9:
  Ret
}