func unit @test.main() {
  branch true, @test.main, @0
label @0:
  %0 := Mov bool true
  continue @1
label @1:
  branch %0, @2, @3
label @2:
  %1 := Add int 1, 1
  continue @1
label @3:
  %2 := LogNot false
  branch %2, @4, @8
label @4:
  %3 := Add int 2, 2
  continue @5
label @5:
  %4 := LogNot true
  branch %4, @6, @7
label @6:
  %5 := Add int 3, 3
  continue @5
label @7:
  %6 := Add int 4, 4
  continue @3
label @8:
  Ret
}