func unit @main() {
  continue @0
label @0:
  branch true, @1, @2
label @1:
  continue @0
label @2:
  %0 := Mov bool true
  continue @3
label @3:
  branch %0, @4, @5
label @4:
  %1 := Add int 1, 1
  continue @3
label @5:
  continue @6
label @6:
  %2 := LogNot false
  branch %2, @7, @11
label @7:
  %3 := Add int 2, 2
  continue @8
label @8:
  %4 := LogNot true
  branch %4, @9, @10
label @9:
  %5 := Add int 3, 3
  continue @8
label @10:
  %6 := Add int 4, 4
  continue @6
label @11:
}