test/parser/ast/type_cast/basic.myte
{
  node: Module,
  loc: 1:0-8:13,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-6:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "test",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-6:1,
        statements: [
          {
            node: ExpressionStatement,
            loc: 4:2-4:12,
            expression: {
              node: TypeCast,
              loc: 4:2-4:11,
              expr: {
                node: IntLiteral,
                loc: 4:3-4:4,
                value: 1,
                raw: "1",
              },
              type: {
                node: PrimitiveType,
                loc: 4:6-4:10,
                kind: Unit,
              },
            },
          },
          {
            node: ExpressionStatement,
            loc: 5:2-5:14,
            expression: {
              node: TypeCast,
              loc: 5:3-5:12,
              expr: {
                node: IntLiteral,
                loc: 5:4-5:5,
                value: 1,
                raw: "1",
              },
              type: {
                node: PrimitiveType,
                loc: 5:7-5:11,
                kind: Unit,
              },
            },
          },
        ],
      },
      return: None,
      type_params: [],
    },
    {
      node: Function,
      loc: 8:0-8:13,
      name: {
        node: Identifier,
        loc: 8:4-8:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 8:11-8:13,
        statements: [],
      },
      return: None,
      type_params: [],
    },
  ],
}