test/parser/type/basic.myte
{
  node: Module,
  loc: 1:0-25:19,
  name: {
    node: ModuleName,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: VariableDeclaration,
      loc: 3:0-3:16,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 3:4-3:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 3:4-3:5,
          name: "x",
        },
      },
      init: {
        node: Unit,
        loc: 3:14-3:16,
      },
      annot: {
        node: IdentifierType,
        loc: 3:7-3:11,
        name: {
          node: ScopedIdentifier,
          loc: 3:7-3:11,
          scopes: [],
          name: {
            node: Identifier,
            loc: 3:7-3:11,
            name: "Unit",
          },
        },
        type_args: [],
      },
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 4:0-4:14,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 4:4-4:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 4:4-4:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 4:13-4:14,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 4:7-4:10,
        name: {
          node: ScopedIdentifier,
          loc: 4:7-4:10,
          scopes: [],
          name: {
            node: Identifier,
            loc: 4:7-4:10,
            name: "Int",
          },
        },
        type_args: [],
      },
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 5:0-5:15,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 5:4-5:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 5:4-5:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 5:14-5:15,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 5:7-5:11,
        name: {
          node: ScopedIdentifier,
          loc: 5:7-5:11,
          scopes: [],
          name: {
            node: Identifier,
            loc: 5:7-5:11,
            name: "Byte",
          },
        },
        type_args: [],
      },
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 6:0-6:15,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 6:4-6:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 6:4-6:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 6:14-6:15,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 6:7-6:11,
        name: {
          node: ScopedIdentifier,
          loc: 6:7-6:11,
          scopes: [],
          name: {
            node: Identifier,
            loc: 6:7-6:11,
            name: "Long",
          },
        },
        type_args: [],
      },
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 7:0-7:22,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 7:4-7:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 7:4-7:5,
          name: "x",
        },
      },
      init: {
        node: StringLiteral,
        loc: 7:16-7:22,
        value: "test",
      },
      annot: {
        node: IdentifierType,
        loc: 7:7-7:13,
        name: {
          node: ScopedIdentifier,
          loc: 7:7-7:13,
          scopes: [],
          name: {
            node: Identifier,
            loc: 7:7-7:13,
            name: "String",
          },
        },
        type_args: [],
      },
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 8:0-8:18,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 8:4-8:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 8:4-8:5,
          name: "x",
        },
      },
      init: {
        node: BoolLiteral,
        loc: 8:14-8:18,
        value: true,
      },
      annot: {
        node: IdentifierType,
        loc: 8:7-8:11,
        name: {
          node: ScopedIdentifier,
          loc: 8:7-8:11,
          scopes: [],
          name: {
            node: Identifier,
            loc: 8:7-8:11,
            name: "Bool",
          },
        },
        type_args: [],
      },
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 10:0-10:26,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 10:4-10:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 10:4-10:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 10:25-10:26,
        raw: "1",
      },
      annot: {
        node: FunctionType,
        loc: 10:7-10:22,
        params: [
          {
            node: IdentifierType,
            loc: 10:8-10:11,
            name: {
              node: ScopedIdentifier,
              loc: 10:8-10:11,
              scopes: [],
              name: {
                node: Identifier,
                loc: 10:8-10:11,
                name: "Int",
              },
            },
            type_args: [],
          },
        ],
        return: {
          node: IdentifierType,
          loc: 10:16-10:22,
          name: {
            node: ScopedIdentifier,
            loc: 10:16-10:22,
            scopes: [],
            name: {
              node: Identifier,
              loc: 10:16-10:22,
              name: "String",
            },
          },
          type_args: [],
        },
      },
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 11:0-11:36,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 11:4-11:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 11:4-11:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 11:35-11:36,
        raw: "1",
      },
      annot: {
        node: FunctionType,
        loc: 11:7-11:32,
        params: [
          {
            node: IdentifierType,
            loc: 11:8-11:11,
            name: {
              node: ScopedIdentifier,
              loc: 11:8-11:11,
              scopes: [],
              name: {
                node: Identifier,
                loc: 11:8-11:11,
                name: "Int",
              },
            },
            type_args: [],
          },
        ],
        return: {
          node: FunctionType,
          loc: 11:16-11:32,
          params: [
            {
              node: IdentifierType,
              loc: 11:17-11:23,
              name: {
                node: ScopedIdentifier,
                loc: 11:17-11:23,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 11:17-11:23,
                  name: "String",
                },
              },
              type_args: [],
            },
          ],
          return: {
            node: IdentifierType,
            loc: 11:28-11:32,
            name: {
              node: ScopedIdentifier,
              loc: 11:28-11:32,
              scopes: [],
              name: {
                node: Identifier,
                loc: 11:28-11:32,
                name: "Bool",
              },
            },
            type_args: [],
          },
        },
      },
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 12:0-12:48,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 12:4-12:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 12:4-12:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 12:47-12:48,
        raw: "1",
      },
      annot: {
        node: FunctionType,
        loc: 12:7-12:44,
        params: [
          {
            node: IdentifierType,
            loc: 12:8-12:11,
            name: {
              node: ScopedIdentifier,
              loc: 12:8-12:11,
              scopes: [],
              name: {
                node: Identifier,
                loc: 12:8-12:11,
                name: "Int",
              },
            },
            type_args: [],
          },
        ],
        return: {
          node: FunctionType,
          loc: 12:16-12:44,
          params: [
            {
              node: IdentifierType,
              loc: 12:17-12:23,
              name: {
                node: ScopedIdentifier,
                loc: 12:17-12:23,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 12:17-12:23,
                  name: "String",
                },
              },
              type_args: [],
            },
          ],
          return: {
            node: FunctionType,
            loc: 12:28-12:44,
            params: [
              {
                node: IdentifierType,
                loc: 12:29-12:33,
                name: {
                  node: ScopedIdentifier,
                  loc: 12:29-12:33,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 12:29-12:33,
                    name: "Bool",
                  },
                },
                type_args: [],
              },
            ],
            return: {
              node: IdentifierType,
              loc: 12:38-12:44,
              name: {
                node: ScopedIdentifier,
                loc: 12:38-12:44,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 12:38-12:44,
                  name: "String",
                },
              },
              type_args: [],
            },
          },
        },
      },
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 14:0-14:18,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 14:4-14:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 14:4-14:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 14:17-14:18,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 14:7-14:14,
        name: {
          node: ScopedIdentifier,
          loc: 14:7-14:14,
          scopes: [],
          name: {
            node: Identifier,
            loc: 14:7-14:14,
            name: "Custom1",
          },
        },
        type_args: [],
      },
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 15:0-15:34,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 15:4-15:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 15:4-15:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 15:33-15:34,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 15:7-15:30,
        name: {
          node: ScopedIdentifier,
          loc: 15:7-15:30,
          scopes: [
            {
              node: Identifier,
              loc: 15:7-15:14,
              name: "Custom1",
            },
            {
              node: Identifier,
              loc: 15:15-15:22,
              name: "Custom2",
            },
          ],
          name: {
            node: Identifier,
            loc: 15:23-15:30,
            name: "Custom3",
          },
        },
        type_args: [],
      },
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 16:0-16:68,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 16:4-16:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 16:4-16:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 16:67-16:68,
        raw: "1",
      },
      annot: {
        node: FunctionType,
        loc: 16:7-16:64,
        params: [
          {
            node: IdentifierType,
            loc: 16:8-16:23,
            name: {
              node: ScopedIdentifier,
              loc: 16:8-16:23,
              scopes: [
                {
                  node: Identifier,
                  loc: 16:8-16:15,
                  name: "Custom1",
                },
              ],
              name: {
                node: Identifier,
                loc: 16:16-16:23,
                name: "Custom2",
              },
            },
            type_args: [],
          },
        ],
        return: {
          node: FunctionType,
          loc: 16:28-16:64,
          params: [
            {
              node: IdentifierType,
              loc: 16:29-16:44,
              name: {
                node: ScopedIdentifier,
                loc: 16:29-16:44,
                scopes: [
                  {
                    node: Identifier,
                    loc: 16:29-16:36,
                    name: "Custom3",
                  },
                ],
                name: {
                  node: Identifier,
                  loc: 16:37-16:44,
                  name: "Custom4",
                },
              },
              type_args: [],
            },
          ],
          return: {
            node: IdentifierType,
            loc: 16:49-16:64,
            name: {
              node: ScopedIdentifier,
              loc: 16:49-16:64,
              scopes: [
                {
                  node: Identifier,
                  loc: 16:49-16:56,
                  name: "Custom5",
                },
              ],
              name: {
                node: Identifier,
                loc: 16:57-16:64,
                name: "Custom6",
              },
            },
            type_args: [],
          },
        },
      },
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 19:0-19:16,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 19:4-19:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 19:4-19:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 19:15-19:16,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 19:7-19:12,
        name: {
          node: ScopedIdentifier,
          loc: 19:7-19:9,
          scopes: [],
          name: {
            node: Identifier,
            loc: 19:7-19:9,
            name: "Id",
          },
        },
        type_args: [
          {
            node: IdentifierType,
            loc: 19:10-19:11,
            name: {
              node: ScopedIdentifier,
              loc: 19:10-19:11,
              scopes: [],
              name: {
                node: Identifier,
                loc: 19:10-19:11,
                name: "A",
              },
            },
            type_args: [],
          },
        ],
      },
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 20:0-20:22,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 20:4-20:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 20:4-20:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 20:21-20:22,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 20:7-20:18,
        name: {
          node: ScopedIdentifier,
          loc: 20:7-20:9,
          scopes: [],
          name: {
            node: Identifier,
            loc: 20:7-20:9,
            name: "ID",
          },
        },
        type_args: [
          {
            node: IdentifierType,
            loc: 20:10-20:11,
            name: {
              node: ScopedIdentifier,
              loc: 20:10-20:11,
              scopes: [],
              name: {
                node: Identifier,
                loc: 20:10-20:11,
                name: "A",
              },
            },
            type_args: [],
          },
          {
            node: IdentifierType,
            loc: 20:13-20:14,
            name: {
              node: ScopedIdentifier,
              loc: 20:13-20:14,
              scopes: [],
              name: {
                node: Identifier,
                loc: 20:13-20:14,
                name: "B",
              },
            },
            type_args: [],
          },
          {
            node: IdentifierType,
            loc: 20:16-20:17,
            name: {
              node: ScopedIdentifier,
              loc: 20:16-20:17,
              scopes: [],
              name: {
                node: Identifier,
                loc: 20:16-20:17,
                name: "C",
              },
            },
            type_args: [],
          },
        ],
      },
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 21:0-21:23,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 21:4-21:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 21:4-21:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 21:22-21:23,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 21:7-21:19,
        name: {
          node: ScopedIdentifier,
          loc: 21:7-21:9,
          scopes: [],
          name: {
            node: Identifier,
            loc: 21:7-21:9,
            name: "ID",
          },
        },
        type_args: [
          {
            node: IdentifierType,
            loc: 21:10-21:11,
            name: {
              node: ScopedIdentifier,
              loc: 21:10-21:11,
              scopes: [],
              name: {
                node: Identifier,
                loc: 21:10-21:11,
                name: "A",
              },
            },
            type_args: [],
          },
          {
            node: IdentifierType,
            loc: 21:13-21:14,
            name: {
              node: ScopedIdentifier,
              loc: 21:13-21:14,
              scopes: [],
              name: {
                node: Identifier,
                loc: 21:13-21:14,
                name: "B",
              },
            },
            type_args: [],
          },
          {
            node: IdentifierType,
            loc: 21:16-21:17,
            name: {
              node: ScopedIdentifier,
              loc: 21:16-21:17,
              scopes: [],
              name: {
                node: Identifier,
                loc: 21:16-21:17,
                name: "C",
              },
            },
            type_args: [],
          },
        ],
      },
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 22:0-22:24,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 22:4-22:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 22:4-22:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 22:23-22:24,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 22:7-22:20,
        name: {
          node: ScopedIdentifier,
          loc: 22:7-22:9,
          scopes: [],
          name: {
            node: Identifier,
            loc: 22:7-22:9,
            name: "ID",
          },
        },
        type_args: [
          {
            node: IdentifierType,
            loc: 22:10-22:19,
            name: {
              node: ScopedIdentifier,
              loc: 22:10-22:12,
              scopes: [],
              name: {
                node: Identifier,
                loc: 22:10-22:12,
                name: "ID",
              },
            },
            type_args: [
              {
                node: IdentifierType,
                loc: 22:13-22:18,
                name: {
                  node: ScopedIdentifier,
                  loc: 22:13-22:15,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 22:13-22:15,
                    name: "ID",
                  },
                },
                type_args: [
                  {
                    node: IdentifierType,
                    loc: 22:16-22:17,
                    name: {
                      node: ScopedIdentifier,
                      loc: 22:16-22:17,
                      scopes: [],
                      name: {
                        node: Identifier,
                        loc: 22:16-22:17,
                        name: "A",
                      },
                    },
                    type_args: [],
                  },
                ],
              },
            ],
          },
        ],
      },
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 23:0-23:23,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 23:4-23:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 23:4-23:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 23:22-23:23,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 23:7-23:19,
        name: {
          node: ScopedIdentifier,
          loc: 23:7-23:9,
          scopes: [],
          name: {
            node: Identifier,
            loc: 23:7-23:9,
            name: "ID",
          },
        },
        type_args: [
          {
            node: TupleType,
            loc: 23:10-23:18,
            elements: [
              {
                node: IdentifierType,
                loc: 23:11-23:12,
                name: {
                  node: ScopedIdentifier,
                  loc: 23:11-23:12,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 23:11-23:12,
                    name: "A",
                  },
                },
                type_args: [],
              },
              {
                node: IdentifierType,
                loc: 23:14-23:17,
                name: {
                  node: ScopedIdentifier,
                  loc: 23:14-23:17,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 23:14-23:17,
                    name: "Int",
                  },
                },
                type_args: [],
              },
            ],
          },
        ],
      },
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 25:0-25:19,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 25:4-25:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 25:4-25:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 25:18-25:19,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 25:7-25:15,
        name: {
          node: ScopedIdentifier,
          loc: 25:7-25:12,
          scopes: [],
          name: {
            node: Identifier,
            loc: 25:7-25:12,
            name: "Array",
          },
        },
        type_args: [
          {
            node: IdentifierType,
            loc: 25:13-25:14,
            name: {
              node: ScopedIdentifier,
              loc: 25:13-25:14,
              scopes: [],
              name: {
                node: Identifier,
                loc: 25:13-25:14,
                name: "A",
              },
            },
            type_args: [],
          },
        ],
      },
      is_public: false,
    },
  ],
}