test/parser/type/function.myte
{
  node: Module,
  loc: 1:0-13:13,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: TypeDeclaration,
      loc: 3:0-3:28,
      name: {
        node: Identifier,
        loc: 3:11-3:13,
        name: "t2",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 3:16-3:28,
        params: [],
        return: {
          node: IdentifierType,
          loc: 3:22-3:28,
          name: {
            node: ScopedIdentifier,
            loc: 3:22-3:28,
            scopes: [],
            name: {
              node: Identifier,
              loc: 3:22-3:28,
              name: "String",
            },
          },
          type_args: [],
        },
      },
    },
    {
      node: TypeDeclaration,
      loc: 4:0-4:31,
      name: {
        node: Identifier,
        loc: 4:11-4:13,
        name: "t3",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 4:16-4:31,
        params: [
          {
            node: IdentifierType,
            loc: 4:17-4:20,
            name: {
              node: ScopedIdentifier,
              loc: 4:17-4:20,
              scopes: [],
              name: {
                node: Identifier,
                loc: 4:17-4:20,
                name: "Int",
              },
            },
            type_args: [],
          },
        ],
        return: {
          node: IdentifierType,
          loc: 4:25-4:31,
          name: {
            node: ScopedIdentifier,
            loc: 4:25-4:31,
            scopes: [],
            name: {
              node: Identifier,
              loc: 4:25-4:31,
              name: "String",
            },
          },
          type_args: [],
        },
      },
    },
    {
      node: TypeDeclaration,
      loc: 5:0-5:35,
      name: {
        node: Identifier,
        loc: 5:11-5:13,
        name: "t4",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 5:16-5:35,
        params: [
          {
            node: IdentifierType,
            loc: 5:19-5:22,
            name: {
              node: ScopedIdentifier,
              loc: 5:19-5:22,
              scopes: [],
              name: {
                node: Identifier,
                loc: 5:19-5:22,
                name: "Int",
              },
            },
            type_args: [],
          },
        ],
        return: {
          node: IdentifierType,
          loc: 5:29-5:35,
          name: {
            node: ScopedIdentifier,
            loc: 5:29-5:35,
            scopes: [],
            name: {
              node: Identifier,
              loc: 5:29-5:35,
              name: "String",
            },
          },
          type_args: [],
        },
      },
    },
    {
      node: TypeDeclaration,
      loc: 6:0-6:37,
      name: {
        node: Identifier,
        loc: 6:11-6:13,
        name: "t5",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 6:16-6:37,
        params: [
          {
            node: IdentifierType,
            loc: 6:17-6:20,
            name: {
              node: ScopedIdentifier,
              loc: 6:17-6:20,
              scopes: [],
              name: {
                node: Identifier,
                loc: 6:17-6:20,
                name: "Int",
              },
            },
            type_args: [],
          },
          {
            node: IdentifierType,
            loc: 6:22-6:28,
            name: {
              node: ScopedIdentifier,
              loc: 6:22-6:28,
              scopes: [],
              name: {
                node: Identifier,
                loc: 6:22-6:28,
                name: "String",
              },
            },
            type_args: [],
          },
        ],
        return: {
          node: IdentifierType,
          loc: 6:33-6:37,
          name: {
            node: ScopedIdentifier,
            loc: 6:33-6:37,
            scopes: [],
            name: {
              node: Identifier,
              loc: 6:33-6:37,
              name: "Unit",
            },
          },
          type_args: [],
        },
      },
    },
    {
      node: TypeDeclaration,
      loc: 7:0-7:43,
      name: {
        node: Identifier,
        loc: 7:11-7:13,
        name: "t6",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 7:16-7:43,
        params: [
          {
            node: IdentifierType,
            loc: 7:17-7:20,
            name: {
              node: ScopedIdentifier,
              loc: 7:17-7:20,
              scopes: [],
              name: {
                node: Identifier,
                loc: 7:17-7:20,
                name: "Int",
              },
            },
            type_args: [],
          },
          {
            node: IdentifierType,
            loc: 7:22-7:28,
            name: {
              node: ScopedIdentifier,
              loc: 7:22-7:28,
              scopes: [],
              name: {
                node: Identifier,
                loc: 7:22-7:28,
                name: "String",
              },
            },
            type_args: [],
          },
          {
            node: IdentifierType,
            loc: 7:30-7:34,
            name: {
              node: ScopedIdentifier,
              loc: 7:30-7:34,
              scopes: [],
              name: {
                node: Identifier,
                loc: 7:30-7:34,
                name: "Bool",
              },
            },
            type_args: [],
          },
        ],
        return: {
          node: IdentifierType,
          loc: 7:39-7:43,
          name: {
            node: ScopedIdentifier,
            loc: 7:39-7:43,
            scopes: [],
            name: {
              node: Identifier,
              loc: 7:39-7:43,
              name: "Unit",
            },
          },
          type_args: [],
        },
      },
    },
    {
      node: TypeDeclaration,
      loc: 8:0-8:55,
      name: {
        node: Identifier,
        loc: 8:11-8:13,
        name: "t7",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 8:16-8:55,
        params: [
          {
            node: IdentifierType,
            loc: 8:17-8:20,
            name: {
              node: ScopedIdentifier,
              loc: 8:17-8:20,
              scopes: [],
              name: {
                node: Identifier,
                loc: 8:17-8:20,
                name: "Int",
              },
            },
            type_args: [],
          },
          {
            node: IdentifierType,
            loc: 8:22-8:28,
            name: {
              node: ScopedIdentifier,
              loc: 8:22-8:28,
              scopes: [],
              name: {
                node: Identifier,
                loc: 8:22-8:28,
                name: "String",
              },
            },
            type_args: [],
          },
        ],
        return: {
          node: FunctionType,
          loc: 8:33-8:55,
          params: [
            {
              node: IdentifierType,
              loc: 8:34-8:38,
              name: {
                node: ScopedIdentifier,
                loc: 8:34-8:38,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 8:34-8:38,
                  name: "Bool",
                },
              },
              type_args: [],
            },
            {
              node: IdentifierType,
              loc: 8:40-8:44,
              name: {
                node: ScopedIdentifier,
                loc: 8:40-8:44,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 8:40-8:44,
                  name: "Unit",
                },
              },
              type_args: [],
            },
          ],
          return: {
            node: IdentifierType,
            loc: 8:49-8:55,
            name: {
              node: ScopedIdentifier,
              loc: 8:49-8:55,
              scopes: [],
              name: {
                node: Identifier,
                loc: 8:49-8:55,
                name: "String",
              },
            },
            type_args: [],
          },
        },
      },
    },
    {
      node: TypeDeclaration,
      loc: 9:0-9:38,
      name: {
        node: Identifier,
        loc: 9:11-9:13,
        name: "t8",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 9:16-9:38,
        params: [
          {
            node: IdentifierType,
            loc: 9:17-9:20,
            name: {
              node: ScopedIdentifier,
              loc: 9:17-9:20,
              scopes: [],
              name: {
                node: Identifier,
                loc: 9:17-9:20,
                name: "Int",
              },
            },
            type_args: [],
          },
          {
            node: IdentifierType,
            loc: 9:22-9:28,
            name: {
              node: ScopedIdentifier,
              loc: 9:22-9:28,
              scopes: [],
              name: {
                node: Identifier,
                loc: 9:22-9:28,
                name: "String",
              },
            },
            type_args: [],
          },
        ],
        return: {
          node: IdentifierType,
          loc: 9:34-9:38,
          name: {
            node: ScopedIdentifier,
            loc: 9:34-9:38,
            scopes: [],
            name: {
              node: Identifier,
              loc: 9:34-9:38,
              name: "Unit",
            },
          },
          type_args: [],
        },
      },
    },
    {
      node: TypeDeclaration,
      loc: 10:0-10:30,
      name: {
        node: Identifier,
        loc: 10:11-10:13,
        name: "t9",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 10:16-10:30,
        params: [
          {
            node: IdentifierType,
            loc: 10:17-10:20,
            name: {
              node: ScopedIdentifier,
              loc: 10:17-10:20,
              scopes: [],
              name: {
                node: Identifier,
                loc: 10:17-10:20,
                name: "Int",
              },
            },
            type_args: [],
          },
        ],
        return: {
          node: IdentifierType,
          loc: 10:26-10:30,
          name: {
            node: ScopedIdentifier,
            loc: 10:26-10:30,
            scopes: [],
            name: {
              node: Identifier,
              loc: 10:26-10:30,
              name: "Unit",
            },
          },
          type_args: [],
        },
      },
    },
    {
      node: TypeDeclaration,
      loc: 11:0-11:41,
      name: {
        node: Identifier,
        loc: 11:11-11:14,
        name: "t10",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 11:17-11:41,
        params: [
          {
            node: TupleType,
            loc: 11:18-11:31,
            elements: [
              {
                node: IdentifierType,
                loc: 11:19-11:22,
                name: {
                  node: ScopedIdentifier,
                  loc: 11:19-11:22,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 11:19-11:22,
                    name: "Int",
                  },
                },
                type_args: [],
              },
              {
                node: IdentifierType,
                loc: 11:24-11:30,
                name: {
                  node: ScopedIdentifier,
                  loc: 11:24-11:30,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 11:24-11:30,
                    name: "String",
                  },
                },
                type_args: [],
              },
            ],
          },
        ],
        return: {
          node: IdentifierType,
          loc: 11:37-11:41,
          name: {
            node: ScopedIdentifier,
            loc: 11:37-11:41,
            scopes: [],
            name: {
              node: Identifier,
              loc: 11:37-11:41,
              name: "Unit",
            },
          },
          type_args: [],
        },
      },
    },
    {
      node: Function,
      loc: 13:0-13:13,
      name: {
        node: Identifier,
        loc: 13:4-13:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 13:11-13:13,
        statements: [],
      },
      return: None,
      type_params: [],
      builtin: false,
      static: false,
      override: false,
    },
  ],
}