test/parser/type/parens.myte
{
  node: Module,
  loc: 1:0-5:28,
  name: {
    node: ModuleName,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: VariableDeclaration,
      loc: 3:0-3:16,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 3:4-3:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 3:4-3:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 3:15-3:16,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 3:8-3:11,
        name: {
          node: ScopedIdentifier,
          loc: 3:8-3:11,
          scopes: [],
          name: {
            node: Identifier,
            loc: 3:8-3:11,
            name: "Int",
          },
        },
        type_args: [],
      },
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 4:0-4:20,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 4:4-4:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 4:4-4:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 4:19-4:20,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 4:10-4:13,
        name: {
          node: ScopedIdentifier,
          loc: 4:10-4:13,
          scopes: [],
          name: {
            node: Identifier,
            loc: 4:10-4:13,
            name: "Int",
          },
        },
        type_args: [],
      },
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 5:0-5:28,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 5:4-5:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 5:4-5:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 5:27-5:28,
        raw: "1",
      },
      annot: {
        node: FunctionType,
        loc: 5:8-5:23,
        params: [
          {
            node: IdentifierType,
            loc: 5:9-5:12,
            name: {
              node: ScopedIdentifier,
              loc: 5:9-5:12,
              scopes: [],
              name: {
                node: Identifier,
                loc: 5:9-5:12,
                name: "Int",
              },
            },
            type_args: [],
          },
        ],
        return: {
          node: IdentifierType,
          loc: 5:17-5:23,
          name: {
            node: ScopedIdentifier,
            loc: 5:17-5:23,
            scopes: [],
            name: {
              node: Identifier,
              loc: 5:17-5:23,
              name: "String",
            },
          },
          type_args: [],
        },
      },
      is_public: false,
    },
  ],
}