test/parser/type/precedence.myte
{
  node: Module,
  loc: 1:0-8:0,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: TypeDeclaration,
      loc: 4:0-4:41,
      name: {
        node: Identifier,
        loc: 4:11-4:13,
        name: "t1",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 4:16-4:41,
        params: [
          {
            node: FunctionType,
            loc: 4:17-4:32,
            params: [
              {
                node: IdentifierType,
                loc: 4:18-4:21,
                name: {
                  node: ScopedIdentifier,
                  loc: 4:18-4:21,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 4:18-4:21,
                    name: "Int",
                  },
                },
                type_args: [],
              },
            ],
            return: {
              node: IdentifierType,
              loc: 4:26-4:32,
              name: {
                node: ScopedIdentifier,
                loc: 4:26-4:32,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 4:26-4:32,
                  name: "String",
                },
              },
              type_args: [],
            },
          },
        ],
        return: {
          node: IdentifierType,
          loc: 4:37-4:41,
          name: {
            node: ScopedIdentifier,
            loc: 4:37-4:41,
            scopes: [],
            name: {
              node: Identifier,
              loc: 4:37-4:41,
              name: "Bool",
            },
          },
          type_args: [],
        },
      },
    },
    {
      node: TypeDeclaration,
      loc: 5:0-5:43,
      name: {
        node: Identifier,
        loc: 5:11-5:13,
        name: "t2",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 5:16-5:43,
        params: [
          {
            node: IdentifierType,
            loc: 5:17-5:20,
            name: {
              node: ScopedIdentifier,
              loc: 5:17-5:20,
              scopes: [],
              name: {
                node: Identifier,
                loc: 5:17-5:20,
                name: "Int",
              },
            },
            type_args: [],
          },
        ],
        return: {
          node: FunctionType,
          loc: 5:26-5:42,
          params: [
            {
              node: IdentifierType,
              loc: 5:27-5:33,
              name: {
                node: ScopedIdentifier,
                loc: 5:27-5:33,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 5:27-5:33,
                  name: "String",
                },
              },
              type_args: [],
            },
          ],
          return: {
            node: IdentifierType,
            loc: 5:38-5:42,
            name: {
              node: ScopedIdentifier,
              loc: 5:38-5:42,
              scopes: [],
              name: {
                node: Identifier,
                loc: 5:38-5:42,
                name: "Bool",
              },
            },
            type_args: [],
          },
        },
      },
    },
    {
      node: TypeDeclaration,
      loc: 6:0-6:41,
      name: {
        node: Identifier,
        loc: 6:11-6:13,
        name: "t3",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 6:16-6:41,
        params: [
          {
            node: IdentifierType,
            loc: 6:17-6:20,
            name: {
              node: ScopedIdentifier,
              loc: 6:17-6:20,
              scopes: [],
              name: {
                node: Identifier,
                loc: 6:17-6:20,
                name: "Int",
              },
            },
            type_args: [],
          },
        ],
        return: {
          node: FunctionType,
          loc: 6:25-6:41,
          params: [
            {
              node: IdentifierType,
              loc: 6:26-6:32,
              name: {
                node: ScopedIdentifier,
                loc: 6:26-6:32,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 6:26-6:32,
                  name: "String",
                },
              },
              type_args: [],
            },
          ],
          return: {
            node: IdentifierType,
            loc: 6:37-6:41,
            name: {
              node: ScopedIdentifier,
              loc: 6:37-6:41,
              scopes: [],
              name: {
                node: Identifier,
                loc: 6:37-6:41,
                name: "Bool",
              },
            },
            type_args: [],
          },
        },
      },
    },
  ],
}