test/parser/type/type_names_used_as_identifier.myte
{
  node: Module,
  loc: 1:0-5:1,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-5:1,
      name: {
        node: Identifier,
        loc: 3:4-3:7,
        name: "Int",
      },
      params: [
        {
          node: Param,
          loc: 3:9-3:17,
          name: {
            node: Identifier,
            loc: 3:9-3:12,
            name: "Int",
          },
          annot: {
            node: IdentifierType,
            loc: 3:14-3:17,
            name: {
              node: ScopedIdentifier,
              loc: 3:14-3:17,
              scopes: [],
              name: {
                node: Identifier,
                loc: 3:14-3:17,
                name: "Int",
              },
            },
            type_args: [],
          },
        },
      ],
      body: {
        node: Block,
        loc: 3:19-5:1,
        statements: [
          {
            node: ExpressionStatement,
            loc: 4:2-4:8,
            expression: {
              node: NamedAccess,
              loc: 4:2-4:7,
              target: {
                node: Identifier,
                loc: 4:2-4:3,
                name: "x",
              },
              name: {
                node: Identifier,
                loc: 4:4-4:7,
                name: "Int",
              },
            },
          },
        ],
      },
      return: None,
      type_params: [],
      builtin: false,
      static: false,
      override: false,
    },
  ],
}