func unit @test.testLatest() {
  branch true, @0, @1
label @0:
  %0 := Call unit @test.use<int>(1)
  continue @1
label @1:
  %1 := Phi int @test.testLatest:1, @0:3
  branch true, @2, @3
label @2:
  %2 := Call unit @test.use<int>(2)
  continue @3
label @3:
  %3 := Phi int @1:2, @2:4
  branch false, @4, @5
label @4:
  %4 := Call unit @test.use<int>(%3)
  continue @7
label @5:
  %5 := Call unit @test.use<int>(%3)
  branch false, @6, @7
label @6:
  %6 := Neg int %1
  continue @7
label @7:
  %7 := Phi int @4:5, @5:6, @6:6
  %8 := Neg int %7
  Ret
}

func unit @test.use<fn>(fn %9) {
  Ret
}

func unit @test.use<int>(int %10) {
  Ret
}

func int @test.main() {
  %11 := Call unit @test.use<fn>(@test.testLatest)
  Ret 0
}