func void @test.testLatest() {
  branch true, @0, @1
label @0:
  Call void @test.use<Int>(1)
  continue @1
label @1:
  %0 := Phi int @test.testLatest:1, @0:3
  branch true, @2, @3
label @2:
  Call void @test.use<Int>(2)
  continue @3
label @3:
  %1 := Phi int @1:2, @2:4
  branch false, @4, @5
label @4:
  Call void @test.use<Int>(%1)
  continue @7
label @5:
  Call void @test.use<Int>(%1)
  branch false, @6, @7
label @6:
  %2 := Neg int %0
  continue @7
label @7:
  %3 := Phi int @4:5, @5:6, @6:6
  %4 := Neg int %3
  Ret
}

func void @test.use<Function>(fn %5) {
  Ret
}

func void @test.use<Int>(int %6) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.testLatest)
  Ret 0
}