func unit @test.test1() {
  branch true, @0, @3
label @0:
  branch false, @1, @2
label @1:
  continue @2
label @2:
  %0 := Phi int @0:1, @1:3
  %1 := Phi int @0:2, @1:4
  continue @6
label @3:
  branch false, @4, @5
label @4:
  continue @5
label @5:
  %2 := Phi int @3:2, @4:5
  continue @6
label @6:
  %3 := Phi int @2:%0, @5:1
  %4 := Phi int @2:%1, @5:%2
  %5 := Neg int %3
  %6 := Neg int %4
  Ret
}

func unit @test.test2() {
  branch true, @7, @10
label @7:
  branch false, @8, @9
label @8:
  continue @9
label @9:
  %7 := Phi int @7:1, @8:3
  %8 := Phi int @7:2, @8:4
  %9 := Neg int %8
  continue @13
label @10:
  branch false, @11, @12
label @11:
  continue @12
label @12:
  %10 := Phi int @10:2, @11:5
  continue @13
label @13:
  %11 := Phi int @9:%7, @12:1
  %12 := Phi int @9:%8, @12:%10
  %13 := Neg int %11
  %14 := Neg int %12
  Ret
}

func unit @test.test3() {
  branch true, @14, @17
label @14:
  branch false, @15, @16
label @15:
  continue @16
label @16:
  %15 := Phi int @14:1, @15:3
  %16 := Phi int @14:2, @15:4
  continue @20
label @17:
  branch false, @18, @19
label @18:
  continue @19
label @19:
  %17 := Phi int @17:2, @18:5
  %18 := Neg int %17
  continue @20
label @20:
  %19 := Phi int @16:%15, @19:1
  %20 := Phi int @16:%16, @19:%17
  %21 := Neg int %19
  %22 := Neg int %20
  Ret
}

func unit @test.test4() {
  branch true, @21, @24
label @21:
  branch false, @22, @23
label @22:
  continue @23
label @23:
  %23 := Phi int @21:1, @22:3
  %24 := Phi int @21:2, @22:4
  %25 := Neg int %24
  continue @27
label @24:
  branch false, @25, @26
label @25:
  continue @26
label @26:
  %26 := Phi int @24:2, @25:5
  %27 := Neg int %26
  continue @27
label @27:
  %28 := Phi int @23:%23, @26:1
  %29 := Phi int @23:%24, @26:%26
  %30 := Neg int %28
  %31 := Neg int %29
  Ret
}

func int @test.main() {
  Ret 0
}