func void @test.test1() {
  branch true, @0, @3
label @0:
  branch false, @1, @2
label @1:
  continue @2
label @2:
  %0 := Phi int @0:1, @1:3
  %1 := Phi int @0:2, @1:4
  continue @6
label @3:
  branch false, @4, @5
label @4:
  continue @5
label @5:
  %2 := Phi int @3:2, @4:5
  continue @6
label @6:
  %3 := Phi int @2:%0, @5:1
  %4 := Phi int @2:%1, @5:%2
  %5 := Neg int %3
  %6 := Neg int %4
  Ret
}

func void @test.test2() {
  branch true, @0, @3
label @0:
  branch false, @1, @2
label @1:
  continue @2
label @2:
  %0 := Phi int @0:1, @1:3
  %1 := Phi int @0:2, @1:4
  %2 := Neg int %1
  continue @6
label @3:
  branch false, @4, @5
label @4:
  continue @5
label @5:
  %3 := Phi int @3:2, @4:5
  continue @6
label @6:
  %4 := Phi int @2:%0, @5:1
  %5 := Phi int @2:%1, @5:%3
  %6 := Neg int %4
  %7 := Neg int %5
  Ret
}

func void @test.test3() {
  branch true, @0, @3
label @0:
  branch false, @1, @2
label @1:
  continue @2
label @2:
  %0 := Phi int @0:1, @1:3
  %1 := Phi int @0:2, @1:4
  continue @6
label @3:
  branch false, @4, @5
label @4:
  continue @5
label @5:
  %2 := Phi int @3:2, @4:5
  %3 := Neg int %2
  continue @6
label @6:
  %4 := Phi int @2:%0, @5:1
  %5 := Phi int @2:%1, @5:%2
  %6 := Neg int %4
  %7 := Neg int %5
  Ret
}

func void @test.test4() {
  branch true, @0, @3
label @0:
  branch false, @1, @2
label @1:
  continue @2
label @2:
  %0 := Phi int @0:1, @1:3
  %1 := Phi int @0:2, @1:4
  %2 := Neg int %1
  continue @6
label @3:
  branch false, @4, @5
label @4:
  continue @5
label @5:
  %3 := Phi int @3:2, @4:5
  %4 := Neg int %3
  continue @6
label @6:
  %5 := Phi int @2:%0, @5:1
  %6 := Phi int @2:%1, @5:%3
  %7 := Neg int %5
  %8 := Neg int %6
  Ret
}

func int @test.main() {
  Ret 0
}