func unit @test.use(int %0) {
  Ret
}

func unit @test.testNotUpdated() {
  branch true, @0, @1
label @0:
  %1 := Call unit @test.use(1)
  continue @1
label @1:
  %2 := Neg int 1
  Ret
}

func unit @test.testUpdated() {
  branch true, @2, @3
label @2:
  continue @3
label @3:
  %3 := Phi int @test.testUpdated:1, @2:2
  %4 := Neg int %3
  Ret
}

func unit @test.testMultiple(int %5) {
  branch true, @4, @5
label @4:
  continue @5
label @5:
  %6 := Phi int @test.testMultiple:1, @4:4
  %7 := Phi int @test.testMultiple:2, @4:5
  %8 := Neg int %6
  %9 := Neg int %7
  %10 := Neg int %5
  branch true, @6, @7
label @6:
  continue @7
label @7:
  %11 := Phi int @5:%6, @6:6
  %12 := Neg int %11
  Ret
}

global int @test.glob = 1

func unit @test.testGlobal() {
  branch true, @8, @9
label @8:
  Store int @test.glob, 2
  continue @9
label @9:
  %13 := Load int @test.glob
  %14 := Neg int %13
  Ret
}

func int @test.main() {
  Ret 0
}