func void @test.writeInBody() {
  continue @0
label @0:
  %1 := Phi int @test.writeInBody:1, @1:%0
  %2 := Eq long 1, 3
  branch %2, @1, @2
label @1:
  %0 := Add int %1, 1
  continue @0
label @2:
  %3 := Neg int %1
  continue @3
label @3:
  %5 := Phi int @2:%1, @4:%4
  %6 := Eq int %5, 2
  branch %6, @4, @5
label @4:
  %4 := Add int %5, 1
  continue @3
label @5:
  %7 := Neg int %5
  Ret
}

func int @test.main() {
  Call void @test.writeInBody()
  Ret 0
}