func unit @test.writeInBody() {
  continue @0
label @0:
  %1 := Phi int @test.writeInBody:1, @1:%0
  branch false, @1, @2
label @1:
  %0 := Add int %1, 1
  continue @0
label @2:
  %2 := Neg int %1
  continue @3
label @3:
  %4 := Phi int @2:%1, @4:%3
  %5 := Eq int %4, 2
  branch %5, @4, @5
label @4:
  %3 := Add int %4, 1
  continue @3
label @5:
  %6 := Neg int %4
  Ret
}

func int @test.main() {
  Ret 0
}