  .global _start

  .text
_main:
  movl $0, %eax
  ret
test.nestedAccess:
  movq 8(%rdi), %rax
  movq 8(%rdi), %rax
  movq 8(%rax), %rax
  movq 8(%rdi), %rax
  movq 8(%rax), %rax
  movb 1(%rax), %al
  ret
test.simpleAccess:
  movl (%rdi), %eax
  movq 8(%rdi), %rax
  movb 16(%rdi), %al
  movl (%rsi), %eax
  movq 8(%rsi), %rax
  movb 16(%rsi), %al
  movb (%rdx), %al
  movb 1(%rdx), %al
  movb 2(%rdx), %al
  ret
_start:
  call __myte_init
  call _main
  ret