  .global _main

  .text
_main:
  call test.testTuple
  call test.testRecord
  call test.testNested
  movl $0, %eax
  ret
test.testNested:
  push %rbx
  push %r12
  movl $8, %edi
  call __myte_alloc
  movq %rax, %r12
  movl $1, (%r12)
  movb $2, 4(%r12)
  movl $16, %edi
  call __myte_alloc
  movq %rax, %rbx
  movq $3, (%rbx)
  movb $4, 8(%rbx)
  movl $16, %edi
  call __myte_alloc
  movq %r12, (%rax)
  movq %rbx, 8(%rax)
  pop %r12
  pop %rbx
  ret
test.testRecord:
  movl $16, %edi
  call __myte_alloc
  movl $1, (%rax)
  movb $2, 4(%rax)
  movq $3, 8(%rax)
  ret
test.testTuple:
  movl $12, %edi
  call __myte_alloc
  movl $1, (%rax)
  movl $2, 4(%rax)
  movl $3, 8(%rax)
  movl $8, %edi
  call __myte_alloc
  movl $1, (%rax)
  movb $2, 4(%rax)
  movl $8, %edi
  call __myte_alloc
  movb $1, (%rax)
  movl $2, 4(%rax)
  ret