  .global _main

  .text
_main:
  leaq test.sextByteToInt(%rip), %rdi
  call test.use$Function$
  leaq test.sextByteToLong(%rip), %rdi
  call test.use$Function$
  leaq test.sextIntToLong(%rip), %rdi
  call test.use$Function$
  movl $0, %eax
  ret
test.sextByteToInt:
  movsx %dil, %eax
  ret
test.sextByteToLong:
  movsx %dil, %rax
  ret
test.sextIntToLong:
  movsx %edi, %rax
  ret
test.use$Function$:
  ret