  .global _main

  .text
_main:
  leaq test.truncIntToByte(%rip), %rdi
  call test.use$Function$
  leaq test.truncLongToByte(%rip), %rdi
  call test.use$Function$
  leaq test.truncLongToInt(%rip), %rdi
  call test.use$Function$
  movl $0, %eax
  ret
test.truncIntToByte:
  movb %sil, (%rdi)
  movl %esi, %eax
  ret
test.truncLongToByte:
  movb %sil, (%rdi)
  movl %esi, %eax
  ret
test.truncLongToInt:
  movl %esi, 4(%rdi)
  movl %esi, %eax
  ret
test.use$Function$:
  ret