test/parser/ast/string_literal/escapes.myte
{
  node: Module,
  loc: 1:0-14:1,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-14:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-14:1,
        statements: [
          {
            node: ExpressionStatement,
            loc: 5:2-5:13,
            expression: {
              node: StringLiteral,
              loc: 5:2-5:12,
              value: "foo"bar",
            },
          },
          {
            node: ExpressionStatement,
            loc: 6:2-6:13,
            expression: {
              node: StringLiteral,
              loc: 6:2-6:12,
              value: "foo\bar",
            },
          },
          {
            node: ExpressionStatement,
            loc: 7:2-7:13,
            expression: {
              node: StringLiteral,
              loc: 7:2-7:12,
              value: "foo
bar",
            },
          },
          {
            node: ExpressionStatement,
            loc: 8:2-8:13,
            expression: {
              node: StringLiteral,
              loc: 8:2-8:12,
              value: "foo	bar",
            },
          },
          {
            node: ExpressionStatement,
            loc: 9:2-9:13,
            expression: {
              node: StringLiteral,
              loc: 9:2-9:12,
              value: "foobar",
            },
          },
          {
            node: ExpressionStatement,
            loc: 12:2-12:23,
            expression: {
              node: StringLiteral,
              loc: 12:2-12:22,
              value: "foohexbar",
            },
          },
          {
            node: ExpressionStatement,
            loc: 13:2-13:13,
            expression: {
              node: StringLiteral,
              loc: 13:2-13:12,
              value: "jj",
            },
          },
        ],
      },
      return: None,
      type_params: [],
      builtin: false,
      static: false,
    },
  ],
}