func unit @testLatest() {
  %0 := Mov int 1
  %1 := Mov int 2
  branch true, @0, @1
label @0:
  %2 := Mov int 3
  continue @1
label @1:
  %3 := Phi %0, %2
  branch true, @2, @3
label @2:
  %4 := Mov int 4
  continue @3
label @3:
  branch false, @4, @5
label @4:
  %5 := Mov int 5
  continue @7
label @5:
  %6 := Mov int 6
  branch false, @6, @7
label @6:
  %7 := Neg int %3
  continue @7
label @7:
  %8 := Phi %5, %6
  %9 := Neg int %8
  Ret
}

func unit @main() {
  Ret
}