func unit @test.test1() {
  %0 := Mov int 1
  %1 := Mov int 2
  branch true, @0, @2
label @0:
  branch false, @1, @4
label @1:
  %2 := Mov int 3
  %3 := Mov int 4
  continue @4
label @2:
  branch false, @3, @4
label @3:
  %4 := Mov int 5
  continue @4
label @4:
  %5 := Phi %0, %2
  %6 := Phi %1, %3, %4
  %7 := Neg int %5
  %8 := Neg int %6
  Ret
}

func unit @test.test2() {
  %9 := Mov int 1
  %10 := Mov int 2
  branch true, @5, @8
label @5:
  branch false, @6, @7
label @6:
  %11 := Mov int 3
  %12 := Mov int 4
  continue @7
label @7:
  %13 := Phi %10, %12
  %14 := Neg int %13
  continue @10
label @8:
  branch false, @9, @10
label @9:
  %15 := Mov int 5
  continue @10
label @10:
  %16 := Phi %9, %11
  %17 := Phi %10, %13, %15
  %18 := Neg int %16
  %19 := Neg int %17
  Ret
}

func unit @test.test3() {
  %20 := Mov int 1
  %21 := Mov int 2
  branch true, @11, @13
label @11:
  branch false, @12, @16
label @12:
  %22 := Mov int 3
  %23 := Mov int 4
  continue @16
label @13:
  branch false, @14, @15
label @14:
  %24 := Mov int 5
  continue @15
label @15:
  %25 := Phi %21, %24
  %26 := Neg int %25
  continue @16
label @16:
  %27 := Phi %20, %22
  %28 := Phi %21, %23, %25
  %29 := Neg int %27
  %30 := Neg int %28
  Ret
}

func unit @test.test4() {
  %31 := Mov int 1
  %32 := Mov int 2
  branch true, @17, @20
label @17:
  branch false, @18, @19
label @18:
  %33 := Mov int 3
  %34 := Mov int 4
  continue @19
label @19:
  %35 := Phi %32, %34
  %36 := Neg int %35
  continue @23
label @20:
  branch false, @21, @22
label @21:
  %37 := Mov int 5
  continue @22
label @22:
  %38 := Phi %32, %37
  %39 := Neg int %38
  continue @23
label @23:
  %40 := Phi %31, %33
  %41 := Phi %35, %38
  %42 := Neg int %40
  %43 := Neg int %41
  Ret
}

func unit @test.main() {
  Ret
}