func unit @test.test1() {
  %0 := Mov int 1
  %1 := Mov int 2
  branch true, @0, @3
label @0:
  branch false, @1, @2
label @1:
  %2 := Mov int 3
  %3 := Mov int 4
  continue @2
label @2:
  %4 := Phi @0:%0, @1:%2
  %5 := Phi @0:%1, @1:%3
  continue @6
label @3:
  branch false, @4, @5
label @4:
  %6 := Mov int 5
  continue @5
label @5:
  %7 := Phi @3:%1, @4:%6
  continue @6
label @6:
  %8 := Phi @2:%4, @5:%0
  %9 := Phi @2:%5, @5:%7
  %10 := Neg int %8
  %11 := Neg int %9
  Ret
}

func unit @test.test2() {
  %12 := Mov int 1
  %13 := Mov int 2
  branch true, @7, @10
label @7:
  branch false, @8, @9
label @8:
  %14 := Mov int 3
  %15 := Mov int 4
  continue @9
label @9:
  %16 := Phi @7:%12, @8:%14
  %17 := Phi @7:%13, @8:%15
  %18 := Neg int %17
  continue @13
label @10:
  branch false, @11, @12
label @11:
  %19 := Mov int 5
  continue @12
label @12:
  %20 := Phi @10:%13, @11:%19
  continue @13
label @13:
  %21 := Phi @9:%16, @12:%12
  %22 := Phi @9:%17, @12:%20
  %23 := Neg int %21
  %24 := Neg int %22
  Ret
}

func unit @test.test3() {
  %25 := Mov int 1
  %26 := Mov int 2
  branch true, @14, @17
label @14:
  branch false, @15, @16
label @15:
  %27 := Mov int 3
  %28 := Mov int 4
  continue @16
label @16:
  %29 := Phi @14:%25, @15:%27
  %30 := Phi @14:%26, @15:%28
  continue @20
label @17:
  branch false, @18, @19
label @18:
  %31 := Mov int 5
  continue @19
label @19:
  %32 := Phi @17:%26, @18:%31
  %33 := Neg int %32
  continue @20
label @20:
  %34 := Phi @16:%29, @19:%25
  %35 := Phi @16:%30, @19:%32
  %36 := Neg int %34
  %37 := Neg int %35
  Ret
}

func unit @test.test4() {
  %38 := Mov int 1
  %39 := Mov int 2
  branch true, @21, @24
label @21:
  branch false, @22, @23
label @22:
  %40 := Mov int 3
  %41 := Mov int 4
  continue @23
label @23:
  %42 := Phi @21:%38, @22:%40
  %43 := Phi @21:%39, @22:%41
  %44 := Neg int %43
  continue @27
label @24:
  branch false, @25, @26
label @25:
  %45 := Mov int 5
  continue @26
label @26:
  %46 := Phi @24:%39, @25:%45
  %47 := Neg int %46
  continue @27
label @27:
  %48 := Phi @23:%42, @26:%38
  %49 := Phi @23:%43, @26:%46
  %50 := Neg int %48
  %51 := Neg int %49
  Ret
}

func unit @test.main() {
  Ret
}