func unit @test1() {
  %0 := Mov int 1
  %1 := Mov int 2
  branch true, @0, @3
label @0:
  branch false, @1, @2
label @1:
  %2 := Mov int 3
  %3 := Mov int 4
  continue @2
label @2:
  continue @6
label @3:
  branch false, @4, @5
label @4:
  %4 := Mov int 5
  continue @5
label @5:
  continue @6
label @6:
  %5 := Phi %0, %2
  %6 := Phi %1, %3, %4
  %7 := Neg int %5
  %8 := Neg int %6
}

func unit @test2() {
  %9 := Mov int 1
  %10 := Mov int 2
  branch true, @7, @10
label @7:
  branch false, @8, @9
label @8:
  %11 := Mov int 3
  %12 := Mov int 4
  continue @9
label @9:
  %13 := Phi %10, %12
  %14 := Neg int %13
  continue @13
label @10:
  branch false, @11, @12
label @11:
  %15 := Mov int 5
  continue @12
label @12:
  continue @13
label @13:
  %16 := Phi %9, %11
  %17 := Phi %10, %13, %15
  %18 := Neg int %16
  %19 := Neg int %17
}

func unit @test3() {
  %20 := Mov int 1
  %21 := Mov int 2
  branch true, @14, @17
label @14:
  branch false, @15, @16
label @15:
  %22 := Mov int 3
  %23 := Mov int 4
  continue @16
label @16:
  continue @20
label @17:
  branch false, @18, @19
label @18:
  %24 := Mov int 5
  continue @19
label @19:
  %25 := Phi %21, %24
  %26 := Neg int %25
  continue @20
label @20:
  %27 := Phi %20, %22
  %28 := Phi %21, %23, %25
  %29 := Neg int %27
  %30 := Neg int %28
}

func unit @test4() {
  %31 := Mov int 1
  %32 := Mov int 2
  branch true, @21, @24
label @21:
  branch false, @22, @23
label @22:
  %33 := Mov int 3
  %34 := Mov int 4
  continue @23
label @23:
  %35 := Phi %32, %34
  %36 := Neg int %35
  continue @27
label @24:
  branch false, @25, @26
label @25:
  %37 := Mov int 5
  continue @26
label @26:
  %38 := Phi %32, %37
  %39 := Neg int %38
  continue @27
label @27:
  %40 := Phi %31, %33
  %41 := Phi %35, %38
  %42 := Neg int %40
  %43 := Neg int %41
}

func unit @main() {

}