func unit @test.testNeitherUpdated() {
  %0 := Mov int 1
  branch true, @0, @1
label @0:
  %1 := Mov int 0
  continue @2
label @1:
  %2 := Mov int 1
  continue @2
label @2:
  %3 := Neg int %0
  Ret
}

func unit @test.testOnlyFirstUpdated() {
  %4 := Mov int 1
  branch true, @3, @4
label @3:
  %5 := Mov int 2
  continue @5
label @4:
  %6 := Mov int 0
  continue @5
label @5:
  %7 := Phi int @3:%5, @4:%4
  %8 := Neg int %7
  Ret
}

func unit @test.testOnlySecondUpdated() {
  %9 := Mov int 1
  branch true, @6, @7
label @6:
  %10 := Mov int 0
  continue @8
label @7:
  %11 := Mov int 2
  continue @8
label @8:
  %12 := Phi int @6:%9, @7:%11
  %13 := Neg int %12
  Ret
}

func unit @test.testBothUpdated() {
  %14 := Mov int 1
  branch true, @9, @10
label @9:
  %15 := Mov int 2
  continue @11
label @10:
  %16 := Mov int 3
  continue @11
label @11:
  %17 := Phi int @9:%15, @10:%16
  %18 := Neg int %17
  Ret
}

func unit @test.testMultiple() {
  %19 := Mov int 0
  %20 := Mov int 1
  %21 := Mov int 2
  branch true, @12, @13
label @12:
  %22 := Mov int 3
  continue @14
label @13:
  %23 := Mov int 4
  continue @14
label @14:
  %24 := Phi int @12:%22, @13:%19
  %25 := Phi int @12:%20, @13:%23
  %26 := Neg int %24
  %27 := Neg int %25
  %28 := Neg int %21
  Ret
}

global int %test.glob {
  StoreGlobal %test.glob, 1
}

func unit @test.testGlobal() {
  branch true, @15, @16
label @15:
  StoreGlobal %test.glob, 2
  continue @17
label @16:
  %29 := Mov int 0
  continue @17
label @17:
  %30 := LoadGlobal %test.glob
  %31 := Neg int %30
  branch true, @18, @19
label @18:
  %32 := Mov int 0
  continue @20
label @19:
  StoreGlobal %test.glob, 3
  continue @20
label @20:
  %33 := LoadGlobal %test.glob
  %34 := Neg int %33
  branch true, @21, @22
label @21:
  StoreGlobal %test.glob, 4
  continue @23
label @22:
  StoreGlobal %test.glob, 5
  continue @23
label @23:
  %35 := LoadGlobal %test.glob
  %36 := Neg int %35
  Ret
}

func unit @test.main() {
  Ret
}