func unit @inexhaustiveContinue() {
  %0 := Mov int 1
  continue @0
label @0:
  %3 := Phi %0, %1, %2
  branch false, @1, @4
label @1:
  %4 := Gt int %3, 2
  branch %4, @2, @3
label @2:
  %1 := Mov int 3
  continue @0
label @3:
  %2 := Mov int 4
  continue @0
label @4:
  %5 := Neg int %3
}

func unit @inexhaustiveBreak() {
  %6 := Mov int 1
  continue @5
label @5:
  %8 := Phi %6, %7
  branch false, @6, @9
label @6:
  %9 := Gt int %8, 2
  branch %9, @7, @8
label @7:
  %10 := Mov int 3
  continue @9
label @8:
  %7 := Mov int 4
  continue @5
label @9:
  %11 := Phi %8, %10
  %12 := Neg int %11
}

func unit @exhaustiveContinues() {
  %13 := Mov int 1
  continue @10
label @10:
  %16 := Phi %13, %14, %15
  branch false, @11, @14
label @11:
  %17 := Gt int %16, 1
  branch %17, @12, @13
label @12:
  %14 := Mov int 2
  continue @10
label @13:
  %15 := Mov int 3
  continue @10
label @14:
  %18 := Neg int %16
}

func unit @exhaustiveBreaks() {
  %19 := Mov int 1
  continue @15
label @15:
  branch false, @16, @19
label @16:
  %20 := Gt int %19, 1
  branch %20, @17, @18
label @17:
  %21 := Mov int 2
  continue @19
label @18:
  %22 := Mov int 3
  continue @19
label @19:
  %23 := Phi %19, %21, %22
  %24 := Neg int %23
}

func unit @inexhaustiveBreakAndContinue() {
  %25 := Mov int 1
  continue @20
label @20:
  %28 := Phi %25, %26, %27
  branch false, @21, @26
label @21:
  %29 := Gt int %28, 1
  branch %29, @22, @23
label @22:
  %30 := Mov int 2
  continue @26
label @23:
  branch true, @24, @25
label @24:
  %26 := Mov int 3
  continue @20
label @25:
  %27 := Mov int 4
  continue @20
label @26:
  %31 := Phi %28, %30
  %32 := Neg int %31
}

func unit @exhaustiveBreakAndContinue() {
  %33 := Mov int 1
  continue @27
label @27:
  %35 := Phi %33, %34
  branch false, @28, @31
label @28:
  %36 := Gt int %35, 1
  branch %36, @29, @30
label @29:
  %37 := Mov int 2
  continue @31
label @30:
  %34 := Mov int 3
  continue @27
label @31:
  %38 := Phi %35, %37
  %39 := Neg int %38
}

func unit @main() {

}