func unit @test.inexhaustiveContinue() {
  %0 := Mov int 1
  continue @0
label @0:
  %3 := Phi int @test.inexhaustiveContinue:%0, @2:%1, @3:%2
  branch false, @1, @4
label @1:
  %4 := Gt int %3, 2
  branch %4, @2, @3
label @2:
  %1 := Mov int 3
  continue @0
label @3:
  %2 := Mov int 4
  continue @0
label @4:
  %5 := Neg int %3
  Ret
}

func unit @test.inexhaustiveBreak() {
  %6 := Mov int 1
  continue @5
label @5:
  %8 := Phi int @test.inexhaustiveBreak:%6, @7:%7
  branch false, @6, @9
label @6:
  %9 := Gt int %8, 2
  branch %9, @8, @7
label @7:
  %7 := Mov int 4
  continue @5
label @8:
  %10 := Mov int 3
  continue @9
label @9:
  %11 := Phi int @5:%8, @8:%10
  %12 := Neg int %11
  Ret
}

func unit @test.exhaustiveContinues() {
  %13 := Mov int 1
  continue @10
label @10:
  %16 := Phi int @test.exhaustiveContinues:%13, @12:%14, @13:%15
  branch false, @11, @14
label @11:
  %17 := Gt int %16, 1
  branch %17, @12, @13
label @12:
  %14 := Mov int 2
  continue @10
label @13:
  %15 := Mov int 3
  continue @10
label @14:
  %18 := Neg int %16
  Ret
}

func unit @test.exhaustiveBreaks() {
  %19 := Mov int 1
  branch false, @15, @18
label @15:
  %20 := Gt int %19, 1
  branch %20, @16, @17
label @16:
  %21 := Mov int 2
  continue @18
label @17:
  %22 := Mov int 3
  continue @18
label @18:
  %23 := Phi int @test.exhaustiveBreaks:%19, @16:%21, @17:%22
  %24 := Neg int %23
  Ret
}

func unit @test.inexhaustiveBreakAndContinue() {
  %25 := Mov int 1
  continue @19
label @19:
  %28 := Phi int @test.inexhaustiveBreakAndContinue:%25, @23:%26, @22:%27
  branch false, @20, @25
label @20:
  %29 := Gt int %28, 1
  branch %29, @24, @21
label @21:
  branch true, @22, @23
label @22:
  %27 := Mov int 3
  continue @19
label @23:
  %26 := Mov int 4
  continue @19
label @24:
  %30 := Mov int 2
  continue @25
label @25:
  %31 := Phi int @19:%28, @24:%30
  %32 := Neg int %31
  Ret
}

func unit @test.exhaustiveBreakAndContinue() {
  %33 := Mov int 1
  continue @26
label @26:
  %35 := Phi int @test.exhaustiveBreakAndContinue:%33, @28:%34
  branch false, @27, @30
label @27:
  %36 := Gt int %35, 1
  branch %36, @29, @28
label @28:
  %34 := Mov int 3
  continue @26
label @29:
  %37 := Mov int 2
  continue @30
label @30:
  %38 := Phi int @26:%35, @29:%37
  %39 := Neg int %38
  Ret
}

func int @test.main() {
  Ret 0
}