func unit @writeInBody() {
  %0 := Mov int 1
  continue @0
label @0:
  %2 := Phi %0, %1
  branch false, @1, @2
label @1:
  %3 := Add int %2, 1
  %1 := Mov int %3
  continue @0
label @2:
  %4 := Neg int %2
  continue @3
label @3:
  %6 := Phi %2, %5
  %7 := Eq int %6, 2
  branch %7, @4, @5
label @4:
  %8 := Add int %6, 1
  %5 := Mov int %8
  continue @3
label @5:
  %9 := Neg int %6
}

func unit @main() {

}