  .global _main

  .text
test.buildOption$Bool$:
  push %rbx
  movq %rdi, %rbx
  movl $8, %edi
  call __myte_alloc
  movq %rbx, (%rax)
  pop %rbx
  ret
test.buildOption$Int$:
  push %rbx
  movl %edi, %ebx
  movl $4, %edi
  call __myte_alloc
  movl %ebx, (%rax)
  pop %rbx
  ret
test.buildOption$Long$:
  push %rbx
  movq %rdi, %rbx
  movl $8, %edi
  call __myte_alloc
  movq %rbx, (%rax)
  pop %rbx
  ret
test.buildPair$Bool$Bool$:
  push %rbx
  push %r12
  movq %rdi, %r12
  movq %rsi, %rbx
  movl $16, %edi
  call __myte_alloc
  movq %r12, (%rax)
  movq %rbx, 8(%rax)
  pop %r12
  pop %rbx
  ret
test.buildPair$Bool$Int$:
  push %rbx
  push %r12
  movq %rdi, %r12
  movl %esi, %ebx
  movl $16, %edi
  call __myte_alloc
  movq %r12, (%rax)
  movl %ebx, 8(%rax)
  pop %r12
  pop %rbx
  ret
test.buildPair$Int$Int$:
  push %rbx
  push %r12
  movl %edi, %r12d
  movl %esi, %ebx
  movl $8, %edi
  call __myte_alloc
  movl %r12d, (%rax)
  movl %ebx, 4(%rax)
  pop %r12
  pop %rbx
  ret
_main:
  leaq test.testSingleTypeArg(%rip), %rdi
  call test.use$Function$
  leaq test.testTwoTypeArgs(%rip), %rdi
  call test.use$Function$
  movl $0, %eax
  ret
test.testSingleTypeArg:
  movq $3, %rdi
  call test.buildOption$Bool$
  movl $5, %edi
  call test.buildOption$Int$
  movq $6, %rdi
  call test.buildOption$Long$
  ret
test.testTwoTypeArgs:
  movl $1, %edi
  movl $1, %esi
  call test.buildPair$Int$Int$
  movq $3, %rdi
  movl $1, %esi
  call test.buildPair$Bool$Int$
  movq $3, %rdi
  movq $3, %rsi
  call test.buildPair$Bool$Bool$
  ret
test.use$Function$:
  movq %rdi, %rax
  ret