test/parser/vec_literal/basic.myte
{
  node: Module,
  loc: 1:0-9:1,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-9:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "test",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-9:1,
        statements: [
          {
            node: ExpressionStatement,
            loc: 4:2-4:5,
            expression: {
              node: VecLiteral,
              loc: 4:2-4:4,
              elements: [],
            },
          },
          {
            node: ExpressionStatement,
            loc: 5:2-5:6,
            expression: {
              node: VecLiteral,
              loc: 5:2-5:5,
              elements: [
                {
                  node: IntLiteral,
                  loc: 5:3-5:4,
                  raw: "1",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 6:2-6:12,
            expression: {
              node: VecLiteral,
              loc: 6:2-6:11,
              elements: [
                {
                  node: IntLiteral,
                  loc: 6:3-6:4,
                  raw: "1",
                },
                {
                  node: IntLiteral,
                  loc: 6:6-6:7,
                  raw: "2",
                },
                {
                  node: IntLiteral,
                  loc: 6:9-6:10,
                  raw: "3",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 7:2-7:13,
            expression: {
              node: VecLiteral,
              loc: 7:2-7:12,
              elements: [
                {
                  node: IntLiteral,
                  loc: 7:3-7:4,
                  raw: "1",
                },
                {
                  node: IntLiteral,
                  loc: 7:6-7:7,
                  raw: "2",
                },
                {
                  node: IntLiteral,
                  loc: 7:9-7:10,
                  raw: "3",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 8:2-8:9,
            expression: {
              node: VecLiteral,
              loc: 8:2-8:8,
              elements: [
                {
                  node: VecLiteral,
                  loc: 8:3-8:7,
                  elements: [
                    {
                      node: VecLiteral,
                      loc: 8:4-8:6,
                      elements: [],
                    },
                  ],
                },
              ],
            },
          },
        ],
      },
      return: None,
      type_params: [],
      builtin: false,
      static: false,
      override: false,
    },
  ],
}