func void @test.emptySet() {
  %0 := Call std.set.Set<Int>* @std.set.Set.new<Int>()
  %1 := Call std.set.Set<Bool>* @std.set.Set.new<Bool>()
  Ret
}

func void @test.oneEntrySet() {
  %2 := Call std.set.Set<Int>* @std.set.Set.new<Int>()
  Call void @std.set.Set.add<Int>(%2, 1)
  %3 := Call std.set.Set<Byte>* @std.set.Set.new<Byte>()
  Call void @std.set.Set.add<Byte>(%3, 2)
  Ret
}

func void @test.multiEntrySet() {
  %4 := Call std.set.Set<Int>* @std.set.Set.new<Int>()
  Call void @std.set.Set.reserve<Int>(%4, 3)
  Call void @std.set.Set.add<Int>(%4, 5)
  Call void @std.set.Set.add<Int>(%4, 6)
  Call void @std.set.Set.add<Int>(%4, 7)
  %5 := Call std.set.Set<Bool>* @std.set.Set.new<Bool>()
  Call void @std.set.Set.reserve<Bool>(%5, 4)
  Call void @std.set.Set.add<Bool>(%5, false)
  Call void @std.set.Set.add<Bool>(%5, true)
  Call void @std.set.Set.add<Bool>(%5, false)
  Call void @std.set.Set.add<Bool>(%5, true)
  Ret
}

func void @test.use<Function>(fn %6) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.emptySet)
  Call void @test.use<Function>(@test.oneEntrySet)
  Call void @test.use<Function>(@test.multiEntrySet)
  Ret 0
}