test/parser/ast/block/basic.myte
{
  node: Program,
  loc: 1:0-15:1,
  toplevels: [
    {
      node: Function,
      loc: 1:0-15:1,
      name: {
        node: Identifier,
        loc: 1:4-1:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 1:11-15:1,
        statements: [
          {
            node: Block,
            loc: 2:2-2:4,
            statements: [],
          },
          {
            node: Block,
            loc: 4:2-8:3,
            statements: [
              {
                node: Block,
                loc: 5:4-7:5,
                statements: [
                  {
                    node: Block,
                    loc: 6:6-6:8,
                    statements: [],
                  },
                ],
              },
            ],
          },
          {
            node: Block,
            loc: 10:2-14:3,
            statements: [
              {
                node: ExpressionStatement,
                loc: 11:4-11:6,
                expression: {
                  node: IntLiteral,
                  loc: 11:4-11:5,
                  value: 1,
                  raw: "1",
                },
              },
              {
                node: ExpressionStatement,
                loc: 12:4-12:6,
                expression: {
                  node: IntLiteral,
                  loc: 12:4-12:5,
                  value: 2,
                  raw: "2",
                },
              },
              {
                node: ExpressionStatement,
                loc: 13:4-13:6,
                expression: {
                  node: IntLiteral,
                  loc: 13:4-13:5,
                  value: 3,
                  raw: "3",
                },
              },
            ],
          },
        ],
      },
      return: None,
    },
  ],
}