test/parser/ast/block/basic.myte
{
  node: Module,
  loc: 1:0-17:1,
  name: {
    node: ScopedIdentifier,
    loc: 1:7-1:11,
    scopes: [],
    name: {
      node: Identifier,
      loc: 1:7-1:11,
      name: "Test",
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-17:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-17:1,
        statements: [
          {
            node: Block,
            loc: 4:2-4:4,
            statements: [],
          },
          {
            node: Block,
            loc: 6:2-10:3,
            statements: [
              {
                node: Block,
                loc: 7:4-9:5,
                statements: [
                  {
                    node: Block,
                    loc: 8:6-8:8,
                    statements: [],
                  },
                ],
              },
            ],
          },
          {
            node: Block,
            loc: 12:2-16:3,
            statements: [
              {
                node: ExpressionStatement,
                loc: 13:4-13:6,
                expression: {
                  node: IntLiteral,
                  loc: 13:4-13:5,
                  value: 1,
                  raw: "1",
                },
              },
              {
                node: ExpressionStatement,
                loc: 14:4-14:6,
                expression: {
                  node: IntLiteral,
                  loc: 14:4-14:5,
                  value: 2,
                  raw: "2",
                },
              },
              {
                node: ExpressionStatement,
                loc: 15:4-15:6,
                expression: {
                  node: IntLiteral,
                  loc: 15:4-15:5,
                  value: 3,
                  raw: "3",
                },
              },
            ],
          },
        ],
      },
      return: None,
    },
  ],
}