test/parser/ast/block/basic.myte
{
  node: Program,
  loc: 1:0-13:1,
  statements: [
    {
      node: Block,
      loc: 1:0-1:2,
      statements: [],
    },
    {
      node: Block,
      loc: 3:0-7:1,
      statements: [
        {
          node: Block,
          loc: 4:2-6:3,
          statements: [
            {
              node: Block,
              loc: 5:4-5:6,
              statements: [],
            },
          ],
        },
      ],
    },
    {
      node: Block,
      loc: 9:0-13:1,
      statements: [
        {
          node: ExpressionStatement,
          loc: 10:2-10:4,
          expression: {
            node: IntLiteral,
            loc: 10:2-10:3,
            value: 1,
            raw: "1",
          },
        },
        {
          node: ExpressionStatement,
          loc: 11:2-11:4,
          expression: {
            node: IntLiteral,
            loc: 11:2-11:3,
            value: 2,
            raw: "2",
          },
        },
        {
          node: ExpressionStatement,
          loc: 12:2-12:4,
          expression: {
            node: IntLiteral,
            loc: 12:2-12:3,
            value: 3,
            raw: "3",
          },
        },
      ],
    },
  ],
}