  .global _main

  .text
test.getInt:
  movl $1, %eax
  ret
_main:
  leaq test.testAssign(%rip), %rdi
  call test.use$Function$
  leaq test.testAddOperatorAssign(%rip), %rdi
  call test.use$Function$
  leaq test.testSubtractOperatorAssign(%rip), %rdi
  call test.use$Function$
  leaq test.testMultiplyOperatorAssign(%rip), %rdi
  call test.use$Function$
  leaq test.testDivideOperatorAssign(%rip), %rdi
  call test.use$Function$
  leaq test.testRemainderOperatorAssign(%rip), %rdi
  call test.use$Function$
  leaq test.testAndOperatorAssign(%rip), %rdi
  call test.use$Function$
  leaq test.testOrOperatorAssign(%rip), %rdi
  call test.use$Function$
  leaq test.testXorOperatorAssign(%rip), %rdi
  call test.use$Function$
  leaq test.testLeftShiftOperatorAssign(%rip), %rdi
  call test.use$Function$
  leaq test.testArithmeticRightShiftOperatorAssign(%rip), %rdi
  call test.use$Function$
  leaq test.testLogicalRightShiftOperatorAssign(%rip), %rdi
  call test.use$Function$
  movl $0, %eax
  ret
test.testAddOperatorAssign:
  call test.getInt
  addl $7, %eax
  movl %eax, %edi
  call test.useInt
  ret
test.testAndOperatorAssign:
  call test.getInt
  andl $7, %eax
  movl %eax, %edi
  call test.useInt
  ret
test.testArithmeticRightShiftOperatorAssign:
  call test.getInt
  sarl $7, %eax
  movl %eax, %edi
  call test.useInt
  ret
test.testAssign:
  call test.getInt
  movl $6, %edi
  call test.useInt
  ret
test.testDivideOperatorAssign:
  call test.getInt
  movl $7, %ecx
  cdq 
  idivl %ecx
  movl %eax, %edi
  call test.useInt
  ret
test.testLeftShiftOperatorAssign:
  call test.getInt
  shll $7, %eax
  movl %eax, %edi
  call test.useInt
  ret
test.testLogicalRightShiftOperatorAssign:
  call test.getInt
  shrl $7, %eax
  movl %eax, %edi
  call test.useInt
  ret
test.testMultiplyOperatorAssign:
  call test.getInt
  imull $7, %eax, %edi
  call test.useInt
  ret
test.testOrOperatorAssign:
  call test.getInt
  orl $7, %eax
  movl %eax, %edi
  call test.useInt
  ret
test.testRemainderOperatorAssign:
  call test.getInt
  movl $7, %ecx
  cdq 
  idivl %ecx
  movl %edx, %edi
  call test.useInt
  ret
test.testSubtractOperatorAssign:
  call test.getInt
  subl $7, %eax
  movl %eax, %edi
  call test.useInt
  ret
test.testXorOperatorAssign:
  call test.getInt
  xorl $7, %eax
  movl %eax, %edi
  call test.useInt
  ret
test.use$Function$:
  ret
test.useInt:
  ret