test/parser/interpolated_strings/basic.myte
{
  node: Module,
  loc: 1:0-26:1,
  name: {
    node: ModuleName,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-26:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-26:1,
        statements: [
          {
            node: ExpressionStatement,
            loc: 5:2-5:8,
            expression: {
              node: InterpolatedString,
              loc: 5:2-5:7,
              parts: [
                {
                  node: StringLiteral,
                  loc: 5:2-5:7,
                  value: "foo",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 8:2-8:9,
            expression: {
              node: InterpolatedString,
              loc: 8:2-8:8,
              parts: [
                {
                  node: IntLiteral,
                  loc: 8:5-8:6,
                  raw: "1",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 9:2-9:12,
            expression: {
              node: InterpolatedString,
              loc: 9:2-9:11,
              parts: [
                {
                  node: StringLiteral,
                  loc: 9:2-9:8,
                  value: "foo",
                },
                {
                  node: IntLiteral,
                  loc: 9:8-9:9,
                  raw: "1",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 10:2-10:12,
            expression: {
              node: InterpolatedString,
              loc: 10:2-10:11,
              parts: [
                {
                  node: IntLiteral,
                  loc: 10:5-10:6,
                  raw: "1",
                },
                {
                  node: StringLiteral,
                  loc: 10:6-10:11,
                  value: "bar",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 11:2-11:15,
            expression: {
              node: InterpolatedString,
              loc: 11:2-11:14,
              parts: [
                {
                  node: StringLiteral,
                  loc: 11:2-11:8,
                  value: "foo",
                },
                {
                  node: IntLiteral,
                  loc: 11:8-11:9,
                  raw: "1",
                },
                {
                  node: StringLiteral,
                  loc: 11:9-11:14,
                  value: "bar",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 12:2-12:16,
            expression: {
              node: InterpolatedString,
              loc: 12:2-12:15,
              parts: [
                {
                  node: IntLiteral,
                  loc: 12:5-12:6,
                  raw: "1",
                },
                {
                  node: StringLiteral,
                  loc: 12:6-12:12,
                  value: "foo",
                },
                {
                  node: IntLiteral,
                  loc: 12:12-12:13,
                  raw: "2",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 15:2-15:23,
            expression: {
              node: InterpolatedString,
              loc: 15:2-15:22,
              parts: [
                {
                  node: StringLiteral,
                  loc: 15:2-15:8,
                  value: "foo",
                },
                {
                  node: IntLiteral,
                  loc: 15:8-15:9,
                  raw: "1",
                },
                {
                  node: IntLiteral,
                  loc: 15:12-15:13,
                  raw: "2",
                },
                {
                  node: IntLiteral,
                  loc: 15:16-15:17,
                  raw: "3",
                },
                {
                  node: StringLiteral,
                  loc: 15:17-15:22,
                  value: "bar",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 18:2-19:8,
            expression: {
              node: InterpolatedString,
              loc: 18:2-19:7,
              parts: [
                {
                  node: StringLiteral,
                  loc: 18:2-19:7,
                  value: "foo
   bar",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 22:3-22:34,
            expression: {
              node: InterpolatedString,
              loc: 22:3-22:33,
              parts: [
                {
                  node: StringLiteral,
                  loc: 22:3-22:9,
                  value: "foo",
                },
                {
                  node: BinaryOperation,
                  loc: 22:9-22:28,
                  op: Add,
                  left: {
                    node: IntLiteral,
                    loc: 22:9-22:10,
                    raw: "1",
                  },
                  right: {
                    node: BinaryOperation,
                    loc: 22:13-22:28,
                    op: Multiply,
                    left: {
                      node: IntLiteral,
                      loc: 22:13-22:14,
                      raw: "2",
                    },
                    right: {
                      node: Call,
                      loc: 22:17-22:28,
                      func: {
                        node: Identifier,
                        loc: 22:17-22:21,
                        name: "call",
                      },
                      args: [
                        {
                          node: BinaryOperation,
                          loc: 22:22-22:27,
                          op: Add,
                          left: {
                            node: Identifier,
                            loc: 22:22-22:23,
                            name: "x",
                          },
                          right: {
                            node: IntLiteral,
                            loc: 22:26-22:27,
                            raw: "1",
                          },
                        },
                      ],
                    },
                  },
                },
                {
                  node: StringLiteral,
                  loc: 22:28-22:33,
                  value: "bar",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 25:3-25:65,
            expression: {
              node: InterpolatedString,
              loc: 25:3-25:64,
              parts: [
                {
                  node: StringLiteral,
                  loc: 25:3-25:10,
                  value: "foo1",
                },
                {
                  node: InterpolatedString,
                  loc: 25:10-25:37,
                  parts: [
                    {
                      node: StringLiteral,
                      loc: 25:10-25:17,
                      value: "foo2",
                    },
                    {
                      node: InterpolatedString,
                      loc: 25:17-25:31,
                      parts: [
                        {
                          node: StringLiteral,
                          loc: 25:17-25:24,
                          value: "foo3",
                        },
                        {
                          node: IntLiteral,
                          loc: 25:24-25:25,
                          raw: "1",
                        },
                        {
                          node: StringLiteral,
                          loc: 25:25-25:31,
                          value: "bar3",
                        },
                      ],
                    },
                    {
                      node: StringLiteral,
                      loc: 25:31-25:37,
                      value: "bar2",
                    },
                  ],
                },
                {
                  node: StringLiteral,
                  loc: 25:37-25:44,
                  value: "bar1",
                },
                {
                  node: InterpolatedString,
                  loc: 25:44-25:58,
                  parts: [
                    {
                      node: StringLiteral,
                      loc: 25:44-25:51,
                      value: "foo4",
                    },
                    {
                      node: IntLiteral,
                      loc: 25:51-25:52,
                      raw: "1",
                    },
                    {
                      node: StringLiteral,
                      loc: 25:52-25:58,
                      value: "bar4",
                    },
                  ],
                },
                {
                  node: StringLiteral,
                  loc: 25:58-25:64,
                  value: "baz1",
                },
              ],
            },
          },
        ],
      },
      return: None,
      type_params: [],
      is_public: false,
      is_builtin: false,
      is_static: false,
      is_override: false,
    },
  ],
}