test/parser/ast/type/basic.myte
{
  node: Program,
  loc: 1:0-9:0,
  statements: [
    {
      node: VariableDeclaration,
      loc: 1:0-1:17,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 1:4-1:5,
        name: "x",
      },
      init: {
        node: Unit,
        loc: 1:15-1:16,
      },
      annot: {
        node: PrimitiveType,
        loc: 1:7-1:11,
        kind: Unit,
      },
    },
    {
      node: VariableDeclaration,
      loc: 2:0-2:15,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 2:4-2:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 2:13-2:14,
        value: 1,
        raw: "1",
      },
      annot: {
        node: PrimitiveType,
        loc: 2:7-2:10,
        kind: Int,
      },
    },
    {
      node: VariableDeclaration,
      loc: 3:0-3:23,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 3:4-3:5,
        name: "x",
      },
      init: {
        node: StringLiteral,
        loc: 3:16-3:22,
        value: "test",
      },
      annot: {
        node: PrimitiveType,
        loc: 3:7-3:13,
        kind: String,
      },
    },
    {
      node: VariableDeclaration,
      loc: 4:0-4:19,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 4:4-4:5,
        name: "x",
      },
      init: {
        node: BoolLiteral,
        loc: 4:14-4:18,
        value: true,
      },
      annot: {
        node: PrimitiveType,
        loc: 4:7-4:11,
        kind: Bool,
      },
    },
    {
      node: VariableDeclaration,
      loc: 6:0-6:25,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 6:4-6:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 6:23-6:24,
        value: 1,
        raw: "1",
      },
      annot: {
        node: FunctionType,
        loc: 6:7-6:20,
        params: [
          {
            node: PrimitiveType,
            loc: 6:7-6:10,
            kind: Int,
          },
        ],
        return: {
          node: PrimitiveType,
          loc: 6:14-6:20,
          kind: String,
        },
      },
    },
    {
      node: VariableDeclaration,
      loc: 7:0-7:33,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 7:4-7:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 7:31-7:32,
        value: 1,
        raw: "1",
      },
      annot: {
        node: FunctionType,
        loc: 7:7-7:28,
        params: [
          {
            node: PrimitiveType,
            loc: 7:7-7:10,
            kind: Int,
          },
          {
            node: PrimitiveType,
            loc: 7:14-7:20,
            kind: String,
          },
        ],
        return: {
          node: PrimitiveType,
          loc: 7:24-7:28,
          kind: Bool,
        },
      },
    },
    {
      node: VariableDeclaration,
      loc: 8:0-8:43,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 8:4-8:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 8:41-8:42,
        value: 1,
        raw: "1",
      },
      annot: {
        node: FunctionType,
        loc: 8:7-8:38,
        params: [
          {
            node: PrimitiveType,
            loc: 8:7-8:10,
            kind: Int,
          },
          {
            node: PrimitiveType,
            loc: 8:14-8:20,
            kind: String,
          },
          {
            node: PrimitiveType,
            loc: 8:24-8:28,
            kind: Bool,
          },
        ],
        return: {
          node: PrimitiveType,
          loc: 8:32-8:38,
          kind: String,
        },
      },
    },
  ],
}