test/parser/ast/type/basic.myte
{
  node: Module,
  loc: 1:0-25:19,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: VariableDeclaration,
      loc: 3:0-3:16,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 3:4-3:5,
        name: "x",
      },
      init: {
        node: Unit,
        loc: 3:14-3:16,
      },
      annot: {
        node: PrimitiveType,
        loc: 3:7-3:11,
        kind: Unit,
      },
    },
    {
      node: VariableDeclaration,
      loc: 4:0-4:14,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 4:4-4:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 4:13-4:14,
        raw: "1",
      },
      annot: {
        node: PrimitiveType,
        loc: 4:7-4:10,
        kind: Int,
      },
    },
    {
      node: VariableDeclaration,
      loc: 5:0-5:15,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 5:4-5:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 5:14-5:15,
        raw: "1",
      },
      annot: {
        node: PrimitiveType,
        loc: 5:7-5:11,
        kind: Byte,
      },
    },
    {
      node: VariableDeclaration,
      loc: 6:0-6:15,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 6:4-6:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 6:14-6:15,
        raw: "1",
      },
      annot: {
        node: PrimitiveType,
        loc: 6:7-6:11,
        kind: Long,
      },
    },
    {
      node: VariableDeclaration,
      loc: 7:0-7:22,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 7:4-7:5,
        name: "x",
      },
      init: {
        node: StringLiteral,
        loc: 7:16-7:22,
        value: "test",
      },
      annot: {
        node: PrimitiveType,
        loc: 7:7-7:13,
        kind: String,
      },
    },
    {
      node: VariableDeclaration,
      loc: 8:0-8:18,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 8:4-8:5,
        name: "x",
      },
      init: {
        node: BoolLiteral,
        loc: 8:14-8:18,
        value: true,
      },
      annot: {
        node: PrimitiveType,
        loc: 8:7-8:11,
        kind: Bool,
      },
    },
    {
      node: VariableDeclaration,
      loc: 10:0-10:24,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 10:4-10:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 10:23-10:24,
        raw: "1",
      },
      annot: {
        node: FunctionType,
        loc: 10:7-10:20,
        params: [
          {
            node: PrimitiveType,
            loc: 10:7-10:10,
            kind: Int,
          },
        ],
        return: {
          node: PrimitiveType,
          loc: 10:14-10:20,
          kind: String,
        },
      },
    },
    {
      node: VariableDeclaration,
      loc: 11:0-11:32,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 11:4-11:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 11:31-11:32,
        raw: "1",
      },
      annot: {
        node: FunctionType,
        loc: 11:7-11:28,
        params: [
          {
            node: PrimitiveType,
            loc: 11:7-11:10,
            kind: Int,
          },
        ],
        return: {
          node: FunctionType,
          loc: 11:14-11:28,
          params: [
            {
              node: PrimitiveType,
              loc: 11:14-11:20,
              kind: String,
            },
          ],
          return: {
            node: PrimitiveType,
            loc: 11:24-11:28,
            kind: Bool,
          },
        },
      },
    },
    {
      node: VariableDeclaration,
      loc: 12:0-12:42,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 12:4-12:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 12:41-12:42,
        raw: "1",
      },
      annot: {
        node: FunctionType,
        loc: 12:7-12:38,
        params: [
          {
            node: PrimitiveType,
            loc: 12:7-12:10,
            kind: Int,
          },
        ],
        return: {
          node: FunctionType,
          loc: 12:14-12:38,
          params: [
            {
              node: PrimitiveType,
              loc: 12:14-12:20,
              kind: String,
            },
          ],
          return: {
            node: FunctionType,
            loc: 12:24-12:38,
            params: [
              {
                node: PrimitiveType,
                loc: 12:24-12:28,
                kind: Bool,
              },
            ],
            return: {
              node: PrimitiveType,
              loc: 12:32-12:38,
              kind: String,
            },
          },
        },
      },
    },
    {
      node: VariableDeclaration,
      loc: 14:0-14:18,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 14:4-14:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 14:17-14:18,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 14:7-14:14,
        name: {
          node: ScopedIdentifier,
          loc: 14:7-14:14,
          scopes: [],
          name: {
            node: Identifier,
            loc: 14:7-14:14,
            name: "Custom1",
          },
        },
        type_params: [],
      },
    },
    {
      node: VariableDeclaration,
      loc: 15:0-15:34,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 15:4-15:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 15:33-15:34,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 15:7-15:30,
        name: {
          node: ScopedIdentifier,
          loc: 15:7-15:30,
          scopes: [
            {
              node: Identifier,
              loc: 15:7-15:14,
              name: "Custom1",
            },
            {
              node: Identifier,
              loc: 15:15-15:22,
              name: "Custom2",
            },
          ],
          name: {
            node: Identifier,
            loc: 15:23-15:30,
            name: "Custom3",
          },
        },
        type_params: [],
      },
    },
    {
      node: VariableDeclaration,
      loc: 16:0-16:64,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 16:4-16:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 16:63-16:64,
        raw: "1",
      },
      annot: {
        node: FunctionType,
        loc: 16:7-16:60,
        params: [
          {
            node: IdentifierType,
            loc: 16:7-16:22,
            name: {
              node: ScopedIdentifier,
              loc: 16:7-16:22,
              scopes: [
                {
                  node: Identifier,
                  loc: 16:7-16:14,
                  name: "Custom1",
                },
              ],
              name: {
                node: Identifier,
                loc: 16:15-16:22,
                name: "Custom2",
              },
            },
            type_params: [],
          },
        ],
        return: {
          node: FunctionType,
          loc: 16:26-16:60,
          params: [
            {
              node: IdentifierType,
              loc: 16:26-16:41,
              name: {
                node: ScopedIdentifier,
                loc: 16:26-16:41,
                scopes: [
                  {
                    node: Identifier,
                    loc: 16:26-16:33,
                    name: "Custom3",
                  },
                ],
                name: {
                  node: Identifier,
                  loc: 16:34-16:41,
                  name: "Custom4",
                },
              },
              type_params: [],
            },
          ],
          return: {
            node: IdentifierType,
            loc: 16:45-16:60,
            name: {
              node: ScopedIdentifier,
              loc: 16:45-16:60,
              scopes: [
                {
                  node: Identifier,
                  loc: 16:45-16:52,
                  name: "Custom5",
                },
              ],
              name: {
                node: Identifier,
                loc: 16:53-16:60,
                name: "Custom6",
              },
            },
            type_params: [],
          },
        },
      },
    },
    {
      node: VariableDeclaration,
      loc: 19:0-19:16,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 19:4-19:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 19:15-19:16,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 19:7-19:12,
        name: {
          node: ScopedIdentifier,
          loc: 19:7-19:9,
          scopes: [],
          name: {
            node: Identifier,
            loc: 19:7-19:9,
            name: "Id",
          },
        },
        type_params: [
          {
            node: IdentifierType,
            loc: 19:10-19:11,
            name: {
              node: ScopedIdentifier,
              loc: 19:10-19:11,
              scopes: [],
              name: {
                node: Identifier,
                loc: 19:10-19:11,
                name: "A",
              },
            },
            type_params: [],
          },
        ],
      },
    },
    {
      node: VariableDeclaration,
      loc: 20:0-20:22,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 20:4-20:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 20:21-20:22,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 20:7-20:18,
        name: {
          node: ScopedIdentifier,
          loc: 20:7-20:9,
          scopes: [],
          name: {
            node: Identifier,
            loc: 20:7-20:9,
            name: "ID",
          },
        },
        type_params: [
          {
            node: IdentifierType,
            loc: 20:10-20:11,
            name: {
              node: ScopedIdentifier,
              loc: 20:10-20:11,
              scopes: [],
              name: {
                node: Identifier,
                loc: 20:10-20:11,
                name: "A",
              },
            },
            type_params: [],
          },
          {
            node: IdentifierType,
            loc: 20:13-20:14,
            name: {
              node: ScopedIdentifier,
              loc: 20:13-20:14,
              scopes: [],
              name: {
                node: Identifier,
                loc: 20:13-20:14,
                name: "B",
              },
            },
            type_params: [],
          },
          {
            node: IdentifierType,
            loc: 20:16-20:17,
            name: {
              node: ScopedIdentifier,
              loc: 20:16-20:17,
              scopes: [],
              name: {
                node: Identifier,
                loc: 20:16-20:17,
                name: "C",
              },
            },
            type_params: [],
          },
        ],
      },
    },
    {
      node: VariableDeclaration,
      loc: 21:0-21:23,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 21:4-21:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 21:22-21:23,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 21:7-21:19,
        name: {
          node: ScopedIdentifier,
          loc: 21:7-21:9,
          scopes: [],
          name: {
            node: Identifier,
            loc: 21:7-21:9,
            name: "ID",
          },
        },
        type_params: [
          {
            node: IdentifierType,
            loc: 21:10-21:11,
            name: {
              node: ScopedIdentifier,
              loc: 21:10-21:11,
              scopes: [],
              name: {
                node: Identifier,
                loc: 21:10-21:11,
                name: "A",
              },
            },
            type_params: [],
          },
          {
            node: IdentifierType,
            loc: 21:13-21:14,
            name: {
              node: ScopedIdentifier,
              loc: 21:13-21:14,
              scopes: [],
              name: {
                node: Identifier,
                loc: 21:13-21:14,
                name: "B",
              },
            },
            type_params: [],
          },
          {
            node: IdentifierType,
            loc: 21:16-21:17,
            name: {
              node: ScopedIdentifier,
              loc: 21:16-21:17,
              scopes: [],
              name: {
                node: Identifier,
                loc: 21:16-21:17,
                name: "C",
              },
            },
            type_params: [],
          },
        ],
      },
    },
    {
      node: VariableDeclaration,
      loc: 22:0-22:24,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 22:4-22:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 22:23-22:24,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 22:7-22:20,
        name: {
          node: ScopedIdentifier,
          loc: 22:7-22:9,
          scopes: [],
          name: {
            node: Identifier,
            loc: 22:7-22:9,
            name: "ID",
          },
        },
        type_params: [
          {
            node: IdentifierType,
            loc: 22:10-22:19,
            name: {
              node: ScopedIdentifier,
              loc: 22:10-22:12,
              scopes: [],
              name: {
                node: Identifier,
                loc: 22:10-22:12,
                name: "ID",
              },
            },
            type_params: [
              {
                node: IdentifierType,
                loc: 22:13-22:18,
                name: {
                  node: ScopedIdentifier,
                  loc: 22:13-22:15,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 22:13-22:15,
                    name: "ID",
                  },
                },
                type_params: [
                  {
                    node: IdentifierType,
                    loc: 22:16-22:17,
                    name: {
                      node: ScopedIdentifier,
                      loc: 22:16-22:17,
                      scopes: [],
                      name: {
                        node: Identifier,
                        loc: 22:16-22:17,
                        name: "A",
                      },
                    },
                    type_params: [],
                  },
                ],
              },
            ],
          },
        ],
      },
    },
    {
      node: VariableDeclaration,
      loc: 23:0-23:23,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 23:4-23:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 23:22-23:23,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 23:7-23:19,
        name: {
          node: ScopedIdentifier,
          loc: 23:7-23:9,
          scopes: [],
          name: {
            node: Identifier,
            loc: 23:7-23:9,
            name: "ID",
          },
        },
        type_params: [
          {
            node: TupleType,
            loc: 23:10-23:18,
            elements: [
              {
                node: IdentifierType,
                loc: 23:11-23:12,
                name: {
                  node: ScopedIdentifier,
                  loc: 23:11-23:12,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 23:11-23:12,
                    name: "A",
                  },
                },
                type_params: [],
              },
              {
                node: PrimitiveType,
                loc: 23:14-23:17,
                kind: Int,
              },
            ],
          },
        ],
      },
    },
    {
      node: VariableDeclaration,
      loc: 25:0-25:19,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 25:4-25:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 25:18-25:19,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 25:7-25:15,
        name: {
          node: ScopedIdentifier,
          loc: 25:7-25:12,
          scopes: [],
          name: {
            node: Identifier,
            loc: 25:7-25:12,
            name: "Array",
          },
        },
        type_params: [
          {
            node: IdentifierType,
            loc: 25:13-25:14,
            name: {
              node: ScopedIdentifier,
              loc: 25:13-25:14,
              scopes: [],
              name: {
                node: Identifier,
                loc: 25:13-25:14,
                name: "A",
              },
            },
            type_params: [],
          },
        ],
      },
    },
  ],
}