test/parser/ast/type/basic.myte
{
  node: Module,
  loc: 1:0-16:64,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: VariableDeclaration,
      loc: 3:0-3:16,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 3:4-3:5,
        name: "x",
      },
      init: {
        node: Unit,
        loc: 3:14-3:16,
      },
      annot: {
        node: PrimitiveType,
        loc: 3:7-3:11,
        kind: Unit,
      },
    },
    {
      node: VariableDeclaration,
      loc: 4:0-4:14,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 4:4-4:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 4:13-4:14,
        raw: "1",
      },
      annot: {
        node: PrimitiveType,
        loc: 4:7-4:10,
        kind: Int,
      },
    },
    {
      node: VariableDeclaration,
      loc: 5:0-5:15,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 5:4-5:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 5:14-5:15,
        raw: "1",
      },
      annot: {
        node: PrimitiveType,
        loc: 5:7-5:11,
        kind: Byte,
      },
    },
    {
      node: VariableDeclaration,
      loc: 6:0-6:15,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 6:4-6:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 6:14-6:15,
        raw: "1",
      },
      annot: {
        node: PrimitiveType,
        loc: 6:7-6:11,
        kind: Long,
      },
    },
    {
      node: VariableDeclaration,
      loc: 7:0-7:22,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 7:4-7:5,
        name: "x",
      },
      init: {
        node: StringLiteral,
        loc: 7:16-7:22,
        value: "test",
      },
      annot: {
        node: PrimitiveType,
        loc: 7:7-7:13,
        kind: String,
      },
    },
    {
      node: VariableDeclaration,
      loc: 8:0-8:18,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 8:4-8:5,
        name: "x",
      },
      init: {
        node: BoolLiteral,
        loc: 8:14-8:18,
        value: true,
      },
      annot: {
        node: PrimitiveType,
        loc: 8:7-8:11,
        kind: Bool,
      },
    },
    {
      node: VariableDeclaration,
      loc: 10:0-10:24,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 10:4-10:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 10:23-10:24,
        raw: "1",
      },
      annot: {
        node: FunctionType,
        loc: 10:7-10:20,
        params: [
          {
            node: PrimitiveType,
            loc: 10:7-10:10,
            kind: Int,
          },
        ],
        return: {
          node: PrimitiveType,
          loc: 10:14-10:20,
          kind: String,
        },
        type_params: [],
      },
    },
    {
      node: VariableDeclaration,
      loc: 11:0-11:32,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 11:4-11:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 11:31-11:32,
        raw: "1",
      },
      annot: {
        node: FunctionType,
        loc: 11:7-11:28,
        params: [
          {
            node: PrimitiveType,
            loc: 11:7-11:10,
            kind: Int,
          },
        ],
        return: {
          node: FunctionType,
          loc: 11:14-11:28,
          params: [
            {
              node: PrimitiveType,
              loc: 11:14-11:20,
              kind: String,
            },
          ],
          return: {
            node: PrimitiveType,
            loc: 11:24-11:28,
            kind: Bool,
          },
          type_params: [],
        },
        type_params: [],
      },
    },
    {
      node: VariableDeclaration,
      loc: 12:0-12:42,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 12:4-12:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 12:41-12:42,
        raw: "1",
      },
      annot: {
        node: FunctionType,
        loc: 12:7-12:38,
        params: [
          {
            node: PrimitiveType,
            loc: 12:7-12:10,
            kind: Int,
          },
        ],
        return: {
          node: FunctionType,
          loc: 12:14-12:38,
          params: [
            {
              node: PrimitiveType,
              loc: 12:14-12:20,
              kind: String,
            },
          ],
          return: {
            node: FunctionType,
            loc: 12:24-12:38,
            params: [
              {
                node: PrimitiveType,
                loc: 12:24-12:28,
                kind: Bool,
              },
            ],
            return: {
              node: PrimitiveType,
              loc: 12:32-12:38,
              kind: String,
            },
            type_params: [],
          },
          type_params: [],
        },
        type_params: [],
      },
    },
    {
      node: VariableDeclaration,
      loc: 14:0-14:18,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 14:4-14:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 14:17-14:18,
        raw: "1",
      },
      annot: {
        node: CustomType,
        loc: 14:7-14:14,
        name: {
          node: ScopedIdentifier,
          loc: 14:7-14:14,
          scopes: [],
          name: {
            node: Identifier,
            loc: 14:7-14:14,
            name: "Custom1",
          },
        },
      },
    },
    {
      node: VariableDeclaration,
      loc: 15:0-15:34,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 15:4-15:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 15:33-15:34,
        raw: "1",
      },
      annot: {
        node: CustomType,
        loc: 15:7-15:30,
        name: {
          node: ScopedIdentifier,
          loc: 15:7-15:30,
          scopes: [
            {
              node: Identifier,
              loc: 15:7-15:14,
              name: "Custom1",
            },
            {
              node: Identifier,
              loc: 15:15-15:22,
              name: "Custom2",
            },
          ],
          name: {
            node: Identifier,
            loc: 15:23-15:30,
            name: "Custom3",
          },
        },
      },
    },
    {
      node: VariableDeclaration,
      loc: 16:0-16:64,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 16:4-16:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 16:63-16:64,
        raw: "1",
      },
      annot: {
        node: FunctionType,
        loc: 16:7-16:60,
        params: [
          {
            node: CustomType,
            loc: 16:7-16:22,
            name: {
              node: ScopedIdentifier,
              loc: 16:7-16:22,
              scopes: [
                {
                  node: Identifier,
                  loc: 16:7-16:14,
                  name: "Custom1",
                },
              ],
              name: {
                node: Identifier,
                loc: 16:15-16:22,
                name: "Custom2",
              },
            },
          },
        ],
        return: {
          node: FunctionType,
          loc: 16:26-16:60,
          params: [
            {
              node: CustomType,
              loc: 16:26-16:41,
              name: {
                node: ScopedIdentifier,
                loc: 16:26-16:41,
                scopes: [
                  {
                    node: Identifier,
                    loc: 16:26-16:33,
                    name: "Custom3",
                  },
                ],
                name: {
                  node: Identifier,
                  loc: 16:34-16:41,
                  name: "Custom4",
                },
              },
            },
          ],
          return: {
            node: CustomType,
            loc: 16:45-16:60,
            name: {
              node: ScopedIdentifier,
              loc: 16:45-16:60,
              scopes: [
                {
                  node: Identifier,
                  loc: 16:45-16:52,
                  name: "Custom5",
                },
              ],
              name: {
                node: Identifier,
                loc: 16:53-16:60,
                name: "Custom6",
              },
            },
          },
          type_params: [],
        },
        type_params: [],
      },
    },
  ],
}