test/parser/ast/type/function.myte
{
  node: Module,
  loc: 1:0-18:13,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: TypeDeclaration,
      loc: 3:0-3:29,
      name: {
        node: Identifier,
        loc: 3:11-3:13,
        name: "t1",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 3:16-3:29,
        params: [
          {
            node: PrimitiveType,
            loc: 3:16-3:19,
            kind: Int,
          },
        ],
        return: {
          node: PrimitiveType,
          loc: 3:23-3:29,
          kind: String,
        },
        type_params: [],
      },
    },
    {
      node: TypeDeclaration,
      loc: 4:0-4:28,
      name: {
        node: Identifier,
        loc: 4:11-4:13,
        name: "t2",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 4:16-4:28,
        params: [],
        return: {
          node: PrimitiveType,
          loc: 4:22-4:28,
          kind: String,
        },
        type_params: [],
      },
    },
    {
      node: TypeDeclaration,
      loc: 5:0-5:31,
      name: {
        node: Identifier,
        loc: 5:11-5:13,
        name: "t3",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 5:16-5:31,
        params: [
          {
            node: PrimitiveType,
            loc: 5:17-5:20,
            kind: Int,
          },
        ],
        return: {
          node: PrimitiveType,
          loc: 5:25-5:31,
          kind: String,
        },
        type_params: [],
      },
    },
    {
      node: TypeDeclaration,
      loc: 6:0-6:35,
      name: {
        node: Identifier,
        loc: 6:11-6:13,
        name: "t4",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 6:16-6:35,
        params: [
          {
            node: PrimitiveType,
            loc: 6:19-6:22,
            kind: Int,
          },
        ],
        return: {
          node: PrimitiveType,
          loc: 6:29-6:35,
          kind: String,
        },
        type_params: [],
      },
    },
    {
      node: TypeDeclaration,
      loc: 7:0-7:37,
      name: {
        node: Identifier,
        loc: 7:11-7:13,
        name: "t5",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 7:16-7:37,
        params: [
          {
            node: PrimitiveType,
            loc: 7:17-7:20,
            kind: Int,
          },
          {
            node: PrimitiveType,
            loc: 7:22-7:28,
            kind: String,
          },
        ],
        return: {
          node: PrimitiveType,
          loc: 7:33-7:37,
          kind: Unit,
        },
        type_params: [],
      },
    },
    {
      node: TypeDeclaration,
      loc: 8:0-8:43,
      name: {
        node: Identifier,
        loc: 8:11-8:13,
        name: "t6",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 8:16-8:43,
        params: [
          {
            node: PrimitiveType,
            loc: 8:17-8:20,
            kind: Int,
          },
          {
            node: PrimitiveType,
            loc: 8:22-8:28,
            kind: String,
          },
          {
            node: PrimitiveType,
            loc: 8:30-8:34,
            kind: Bool,
          },
        ],
        return: {
          node: PrimitiveType,
          loc: 8:39-8:43,
          kind: Unit,
        },
        type_params: [],
      },
    },
    {
      node: TypeDeclaration,
      loc: 9:0-9:55,
      name: {
        node: Identifier,
        loc: 9:11-9:13,
        name: "t7",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 9:16-9:55,
        params: [
          {
            node: PrimitiveType,
            loc: 9:17-9:20,
            kind: Int,
          },
          {
            node: PrimitiveType,
            loc: 9:22-9:28,
            kind: String,
          },
        ],
        return: {
          node: FunctionType,
          loc: 9:33-9:55,
          params: [
            {
              node: PrimitiveType,
              loc: 9:34-9:38,
              kind: Bool,
            },
            {
              node: PrimitiveType,
              loc: 9:40-9:44,
              kind: Unit,
            },
          ],
          return: {
            node: PrimitiveType,
            loc: 9:49-9:55,
            kind: String,
          },
          type_params: [],
        },
        type_params: [],
      },
    },
    {
      node: TypeDeclaration,
      loc: 10:0-10:38,
      name: {
        node: Identifier,
        loc: 10:11-10:13,
        name: "t8",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 10:16-10:38,
        params: [
          {
            node: PrimitiveType,
            loc: 10:17-10:20,
            kind: Int,
          },
          {
            node: PrimitiveType,
            loc: 10:22-10:28,
            kind: String,
          },
        ],
        return: {
          node: PrimitiveType,
          loc: 10:34-10:38,
          kind: Unit,
        },
        type_params: [],
      },
    },
    {
      node: TypeDeclaration,
      loc: 11:0-11:30,
      name: {
        node: Identifier,
        loc: 11:11-11:13,
        name: "t9",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 11:16-11:30,
        params: [
          {
            node: PrimitiveType,
            loc: 11:17-11:20,
            kind: Int,
          },
        ],
        return: {
          node: PrimitiveType,
          loc: 11:26-11:30,
          kind: Unit,
        },
        type_params: [],
      },
    },
    {
      node: TypeDeclaration,
      loc: 12:0-12:41,
      name: {
        node: Identifier,
        loc: 12:11-12:14,
        name: "t10",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 12:17-12:41,
        params: [
          {
            node: TupleType,
            loc: 12:18-12:31,
            elements: [
              {
                node: PrimitiveType,
                loc: 12:19-12:22,
                kind: Int,
              },
              {
                node: PrimitiveType,
                loc: 12:24-12:30,
                kind: String,
              },
            ],
          },
        ],
        return: {
          node: PrimitiveType,
          loc: 12:37-12:41,
          kind: Unit,
        },
        type_params: [],
      },
    },
    {
      node: TypeDeclaration,
      loc: 13:0-13:28,
      name: {
        node: Identifier,
        loc: 13:11-13:14,
        name: "t11",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 13:17-13:28,
        params: [
          {
            node: CustomType,
            loc: 13:21-13:22,
            name: {
              node: ScopedIdentifier,
              loc: 13:21-13:22,
              scopes: [],
              name: {
                node: Identifier,
                loc: 13:21-13:22,
                name: "A",
              },
            },
          },
        ],
        return: {
          node: CustomType,
          loc: 13:27-13:28,
          name: {
            node: ScopedIdentifier,
            loc: 13:27-13:28,
            scopes: [],
            name: {
              node: Identifier,
              loc: 13:27-13:28,
              name: "A",
            },
          },
        },
        type_params: [
          {
            node: TypeParameter,
            loc: 13:18-13:19,
            name: {
              node: Identifier,
              loc: 13:18-13:19,
              name: "A",
            },
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 14:0-14:29,
      name: {
        node: Identifier,
        loc: 14:11-14:14,
        name: "t12",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 14:17-14:29,
        params: [
          {
            node: CustomType,
            loc: 14:22-14:23,
            name: {
              node: ScopedIdentifier,
              loc: 14:22-14:23,
              scopes: [],
              name: {
                node: Identifier,
                loc: 14:22-14:23,
                name: "A",
              },
            },
          },
        ],
        return: {
          node: CustomType,
          loc: 14:28-14:29,
          name: {
            node: ScopedIdentifier,
            loc: 14:28-14:29,
            scopes: [],
            name: {
              node: Identifier,
              loc: 14:28-14:29,
              name: "A",
            },
          },
        },
        type_params: [
          {
            node: TypeParameter,
            loc: 14:18-14:19,
            name: {
              node: Identifier,
              loc: 14:18-14:19,
              name: "A",
            },
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 15:0-15:47,
      name: {
        node: Identifier,
        loc: 15:11-15:14,
        name: "t13",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 15:17-15:47,
        params: [
          {
            node: PrimitiveType,
            loc: 15:27-15:30,
            kind: Int,
          },
          {
            node: PrimitiveType,
            loc: 15:32-15:38,
            kind: String,
          },
        ],
        return: {
          node: PrimitiveType,
          loc: 15:43-15:47,
          kind: Unit,
        },
        type_params: [
          {
            node: TypeParameter,
            loc: 15:18-15:19,
            name: {
              node: Identifier,
              loc: 15:18-15:19,
              name: "A",
            },
          },
          {
            node: TypeParameter,
            loc: 15:21-15:22,
            name: {
              node: Identifier,
              loc: 15:21-15:22,
              name: "B",
            },
          },
          {
            node: TypeParameter,
            loc: 15:24-15:25,
            name: {
              node: Identifier,
              loc: 15:24-15:25,
              name: "C",
            },
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 16:0-16:48,
      name: {
        node: Identifier,
        loc: 16:11-16:14,
        name: "t14",
      },
      type_params: [],
      alias: {
        node: FunctionType,
        loc: 16:17-16:48,
        params: [
          {
            node: PrimitiveType,
            loc: 16:28-16:31,
            kind: Int,
          },
          {
            node: PrimitiveType,
            loc: 16:33-16:39,
            kind: String,
          },
        ],
        return: {
          node: PrimitiveType,
          loc: 16:44-16:48,
          kind: Unit,
        },
        type_params: [
          {
            node: TypeParameter,
            loc: 16:18-16:19,
            name: {
              node: Identifier,
              loc: 16:18-16:19,
              name: "A",
            },
          },
          {
            node: TypeParameter,
            loc: 16:21-16:22,
            name: {
              node: Identifier,
              loc: 16:21-16:22,
              name: "B",
            },
          },
          {
            node: TypeParameter,
            loc: 16:24-16:25,
            name: {
              node: Identifier,
              loc: 16:24-16:25,
              name: "C",
            },
          },
        ],
      },
    },
    {
      node: Function,
      loc: 18:0-18:13,
      name: {
        node: Identifier,
        loc: 18:4-18:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 18:11-18:13,
        statements: [],
      },
      return: None,
      type_params: [],
    },
  ],
}