test/parser/ast/type/parens.myte
{
  node: Module,
  loc: 1:0-5:26,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: VariableDeclaration,
      loc: 3:0-3:16,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 3:4-3:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 3:15-3:16,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 3:8-3:11,
        name: {
          node: ScopedIdentifier,
          loc: 3:8-3:11,
          scopes: [],
          name: {
            node: Identifier,
            loc: 3:8-3:11,
            name: "Int",
          },
        },
        type_params: [],
      },
    },
    {
      node: VariableDeclaration,
      loc: 4:0-4:20,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 4:4-4:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 4:19-4:20,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 4:10-4:13,
        name: {
          node: ScopedIdentifier,
          loc: 4:10-4:13,
          scopes: [],
          name: {
            node: Identifier,
            loc: 4:10-4:13,
            name: "Int",
          },
        },
        type_params: [],
      },
    },
    {
      node: VariableDeclaration,
      loc: 5:0-5:26,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 5:4-5:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 5:25-5:26,
        raw: "1",
      },
      annot: {
        node: FunctionType,
        loc: 5:8-5:21,
        params: [
          {
            node: IdentifierType,
            loc: 5:8-5:11,
            name: {
              node: ScopedIdentifier,
              loc: 5:8-5:11,
              scopes: [],
              name: {
                node: Identifier,
                loc: 5:8-5:11,
                name: "Int",
              },
            },
            type_params: [],
          },
        ],
        return: {
          node: IdentifierType,
          loc: 5:15-5:21,
          name: {
            node: ScopedIdentifier,
            loc: 5:15-5:21,
            scopes: [],
            name: {
              node: Identifier,
              loc: 5:15-5:21,
              name: "String",
            },
          },
          type_params: [],
        },
      },
    },
  ],
}