test/parser/ast/type/parens.myte
{
  node: Program,
  loc: 1:0-3:27,
  toplevels: [
    {
      node: VariableDeclaration,
      loc: 1:0-1:17,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 1:4-1:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 1:15-1:16,
        value: 1,
        raw: "1",
      },
      annot: {
        node: PrimitiveType,
        loc: 1:8-1:11,
        kind: Int,
      },
    },
    {
      node: VariableDeclaration,
      loc: 2:0-2:21,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 2:4-2:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 2:19-2:20,
        value: 1,
        raw: "1",
      },
      annot: {
        node: PrimitiveType,
        loc: 2:10-2:13,
        kind: Int,
      },
    },
    {
      node: VariableDeclaration,
      loc: 3:0-3:27,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 3:4-3:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 3:25-3:26,
        value: 1,
        raw: "1",
      },
      annot: {
        node: FunctionType,
        loc: 3:8-3:21,
        params: [
          {
            node: PrimitiveType,
            loc: 3:8-3:11,
            kind: Int,
          },
        ],
        return: {
          node: PrimitiveType,
          loc: 3:15-3:21,
          kind: String,
        },
      },
    },
  ],
}