test/parser/ast/type/precedence.myte
{
  node: Module,
  loc: 1:0-8:0,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: TypeDeclaration,
      loc: 4:0-4:33,
      name: {
        node: Identifier,
        loc: 4:5-4:7,
        name: "t1",
      },
      type: {
        node: FunctionType,
        loc: 4:10-4:33,
        params: [
          {
            node: FunctionType,
            loc: 4:11-4:24,
            params: [
              {
                node: PrimitiveType,
                loc: 4:11-4:14,
                kind: Int,
              },
            ],
            return: {
              node: PrimitiveType,
              loc: 4:18-4:24,
              kind: String,
            },
            type_params: [],
          },
        ],
        return: {
          node: PrimitiveType,
          loc: 4:29-4:33,
          kind: Bool,
        },
        type_params: [],
      },
    },
    {
      node: TypeDeclaration,
      loc: 5:0-5:33,
      name: {
        node: Identifier,
        loc: 5:5-5:7,
        name: "t2",
      },
      type: {
        node: FunctionType,
        loc: 5:10-5:33,
        params: [
          {
            node: PrimitiveType,
            loc: 5:10-5:13,
            kind: Int,
          },
        ],
        return: {
          node: FunctionType,
          loc: 5:18-5:32,
          params: [
            {
              node: PrimitiveType,
              loc: 5:18-5:24,
              kind: String,
            },
          ],
          return: {
            node: PrimitiveType,
            loc: 5:28-5:32,
            kind: Bool,
          },
          type_params: [],
        },
        type_params: [],
      },
    },
    {
      node: TypeDeclaration,
      loc: 6:0-6:31,
      name: {
        node: Identifier,
        loc: 6:5-6:7,
        name: "t3",
      },
      type: {
        node: FunctionType,
        loc: 6:10-6:31,
        params: [
          {
            node: PrimitiveType,
            loc: 6:10-6:13,
            kind: Int,
          },
        ],
        return: {
          node: FunctionType,
          loc: 6:17-6:31,
          params: [
            {
              node: PrimitiveType,
              loc: 6:17-6:23,
              kind: String,
            },
          ],
          return: {
            node: PrimitiveType,
            loc: 6:27-6:31,
            kind: Bool,
          },
          type_params: [],
        },
        type_params: [],
      },
    },
  ],
}