test/parser/ast/type/tuple.myte
{
  node: Module,
  loc: 1:0-10:39,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: TypeDeclaration,
      loc: 3:0-3:35,
      name: {
        node: Identifier,
        loc: 3:11-3:13,
        name: "t1",
      },
      type_params: [],
      builtin: false,
      alias: {
        node: TupleType,
        loc: 3:16-3:35,
        elements: [
          {
            node: PrimitiveType,
            loc: 3:17-3:20,
            kind: Int,
          },
          {
            node: IdentifierType,
            loc: 3:22-3:28,
            name: {
              node: ScopedIdentifier,
              loc: 3:22-3:28,
              scopes: [],
              name: {
                node: Identifier,
                loc: 3:22-3:28,
                name: "String",
              },
            },
            type_params: [],
          },
          {
            node: PrimitiveType,
            loc: 3:30-3:34,
            kind: Bool,
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 4:0-4:63,
      name: {
        node: Identifier,
        loc: 4:11-4:13,
        name: "t2",
      },
      type_params: [],
      builtin: false,
      alias: {
        node: TupleType,
        loc: 4:16-4:63,
        elements: [
          {
            node: TupleType,
            loc: 4:17-4:30,
            elements: [
              {
                node: PrimitiveType,
                loc: 4:18-4:21,
                kind: Int,
              },
              {
                node: IdentifierType,
                loc: 4:23-4:29,
                name: {
                  node: ScopedIdentifier,
                  loc: 4:23-4:29,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 4:23-4:29,
                    name: "String",
                  },
                },
                type_params: [],
              },
            ],
          },
          {
            node: TupleType,
            loc: 4:32-4:62,
            elements: [
              {
                node: PrimitiveType,
                loc: 4:33-4:37,
                kind: Bool,
              },
              {
                node: TupleType,
                loc: 4:39-4:61,
                elements: [
                  {
                    node: IdentifierType,
                    loc: 4:40-4:46,
                    name: {
                      node: ScopedIdentifier,
                      loc: 4:40-4:46,
                      scopes: [],
                      name: {
                        node: Identifier,
                        loc: 4:40-4:46,
                        name: "String",
                      },
                    },
                    type_params: [],
                  },
                  {
                    node: IdentifierType,
                    loc: 4:48-4:54,
                    name: {
                      node: ScopedIdentifier,
                      loc: 4:48-4:54,
                      scopes: [],
                      name: {
                        node: Identifier,
                        loc: 4:48-4:54,
                        name: "String",
                      },
                    },
                    type_params: [],
                  },
                  {
                    node: PrimitiveType,
                    loc: 4:56-4:60,
                    kind: Unit,
                  },
                ],
              },
            ],
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 7:0-7:31,
      name: {
        node: Identifier,
        loc: 7:11-7:13,
        name: "t3",
      },
      type_params: [],
      builtin: false,
      alias: {
        node: TupleType,
        loc: 7:16-7:31,
        elements: [
          {
            node: PrimitiveType,
            loc: 7:17-7:20,
            kind: Int,
          },
          {
            node: IdentifierType,
            loc: 7:22-7:28,
            name: {
              node: ScopedIdentifier,
              loc: 7:22-7:28,
              scopes: [],
              name: {
                node: Identifier,
                loc: 7:22-7:28,
                name: "String",
              },
            },
            type_params: [],
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 10:0-10:39,
      name: {
        node: Identifier,
        loc: 10:11-10:13,
        name: "t4",
      },
      type_params: [],
      builtin: false,
      alias: {
        node: FunctionType,
        loc: 10:16-10:39,
        params: [
          {
            node: TupleType,
            loc: 10:17-10:30,
            elements: [
              {
                node: PrimitiveType,
                loc: 10:18-10:21,
                kind: Int,
              },
              {
                node: IdentifierType,
                loc: 10:23-10:29,
                name: {
                  node: ScopedIdentifier,
                  loc: 10:23-10:29,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 10:23-10:29,
                    name: "String",
                  },
                },
                type_params: [],
              },
            ],
          },
        ],
        return: {
          node: PrimitiveType,
          loc: 10:35-10:39,
          kind: Unit,
        },
      },
    },
  ],
}