test/parser/ast/type/type_param_bounds.myte
{
  node: Module,
  loc: 1:0-11:44,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: TypeDeclaration,
      loc: 3:0-3:24,
      name: {
        node: Identifier,
        loc: 3:5-3:9,
        name: "Test",
      },
      type_params: [
        {
          node: TypeParameter,
          loc: 3:10-3:16,
          name: {
            node: Identifier,
            loc: 3:10-3:11,
            name: "T",
          },
          bounds: [
            {
              node: IdentifierType,
              loc: 3:13-3:16,
              name: {
                node: ScopedIdentifier,
                loc: 3:13-3:16,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 3:13-3:16,
                  name: "Foo",
                },
              },
              type_params: [],
            },
          ],
        },
      ],
      builtin: false,
      tuple: {
        node: TupleVariant,
        loc: 3:5-3:24,
        name: {
          node: Identifier,
          loc: 3:5-3:9,
          name: "Test",
        },
        elements: [
          {
            node: IdentifierType,
            loc: 3:19-3:23,
            name: {
              node: ScopedIdentifier,
              loc: 3:19-3:23,
              scopes: [],
              name: {
                node: Identifier,
                loc: 3:19-3:23,
                name: "Unit",
              },
            },
            type_params: [],
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 5:0-5:26,
      name: {
        node: Identifier,
        loc: 5:5-5:9,
        name: "Test",
      },
      type_params: [
        {
          node: TypeParameter,
          loc: 5:10-5:18,
          name: {
            node: Identifier,
            loc: 5:10-5:11,
            name: "T",
          },
          bounds: [
            {
              node: IdentifierType,
              loc: 5:13-5:16,
              name: {
                node: ScopedIdentifier,
                loc: 5:13-5:16,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 5:13-5:16,
                  name: "Foo",
                },
              },
              type_params: [],
            },
          ],
        },
      ],
      builtin: false,
      tuple: {
        node: TupleVariant,
        loc: 5:5-5:26,
        name: {
          node: Identifier,
          loc: 5:5-5:9,
          name: "Test",
        },
        elements: [
          {
            node: IdentifierType,
            loc: 5:21-5:25,
            name: {
              node: ScopedIdentifier,
              loc: 5:21-5:25,
              scopes: [],
              name: {
                node: Identifier,
                loc: 5:21-5:25,
                name: "Unit",
              },
            },
            type_params: [],
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 7:0-7:36,
      name: {
        node: Identifier,
        loc: 7:5-7:9,
        name: "Test",
      },
      type_params: [
        {
          node: TypeParameter,
          loc: 7:10-7:28,
          name: {
            node: Identifier,
            loc: 7:10-7:11,
            name: "T",
          },
          bounds: [
            {
              node: IdentifierType,
              loc: 7:13-7:16,
              name: {
                node: ScopedIdentifier,
                loc: 7:13-7:16,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 7:13-7:16,
                  name: "Foo",
                },
              },
              type_params: [],
            },
            {
              node: IdentifierType,
              loc: 7:19-7:22,
              name: {
                node: ScopedIdentifier,
                loc: 7:19-7:22,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 7:19-7:22,
                  name: "Bar",
                },
              },
              type_params: [],
            },
            {
              node: IdentifierType,
              loc: 7:25-7:28,
              name: {
                node: ScopedIdentifier,
                loc: 7:25-7:28,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 7:25-7:28,
                  name: "Baz",
                },
              },
              type_params: [],
            },
          ],
        },
      ],
      builtin: false,
      tuple: {
        node: TupleVariant,
        loc: 7:5-7:36,
        name: {
          node: Identifier,
          loc: 7:5-7:9,
          name: "Test",
        },
        elements: [
          {
            node: IdentifierType,
            loc: 7:31-7:35,
            name: {
              node: ScopedIdentifier,
              loc: 7:31-7:35,
              scopes: [],
              name: {
                node: Identifier,
                loc: 7:31-7:35,
                name: "Unit",
              },
            },
            type_params: [],
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 9:0-9:39,
      name: {
        node: Identifier,
        loc: 9:5-9:9,
        name: "Test",
      },
      type_params: [
        {
          node: TypeParameter,
          loc: 9:10-9:30,
          name: {
            node: Identifier,
            loc: 9:10-9:11,
            name: "T",
          },
          bounds: [
            {
              node: IdentifierType,
              loc: 9:13-9:16,
              name: {
                node: ScopedIdentifier,
                loc: 9:13-9:16,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 9:13-9:16,
                  name: "Foo",
                },
              },
              type_params: [],
            },
            {
              node: IdentifierType,
              loc: 9:19-9:22,
              name: {
                node: ScopedIdentifier,
                loc: 9:19-9:22,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 9:19-9:22,
                  name: "Bar",
                },
              },
              type_params: [],
            },
            {
              node: IdentifierType,
              loc: 9:25-9:28,
              name: {
                node: ScopedIdentifier,
                loc: 9:25-9:28,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 9:25-9:28,
                  name: "Baz",
                },
              },
              type_params: [],
            },
          ],
        },
      ],
      builtin: false,
      tuple: {
        node: TupleVariant,
        loc: 9:5-9:39,
        name: {
          node: Identifier,
          loc: 9:5-9:9,
          name: "Test",
        },
        elements: [
          {
            node: IdentifierType,
            loc: 9:34-9:38,
            name: {
              node: ScopedIdentifier,
              loc: 9:34-9:38,
              scopes: [],
              name: {
                node: Identifier,
                loc: 9:34-9:38,
                name: "Unit",
              },
            },
            type_params: [],
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 11:0-11:44,
      name: {
        node: Identifier,
        loc: 11:5-11:9,
        name: "Test",
      },
      type_params: [
        {
          node: TypeParameter,
          loc: 11:10-11:19,
          name: {
            node: Identifier,
            loc: 11:10-11:11,
            name: "T",
          },
          bounds: [
            {
              node: IdentifierType,
              loc: 11:13-11:19,
              name: {
                node: ScopedIdentifier,
                loc: 11:13-11:16,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 11:13-11:16,
                  name: "Foo",
                },
              },
              type_params: [
                {
                  node: IdentifierType,
                  loc: 11:17-11:18,
                  name: {
                    node: ScopedIdentifier,
                    loc: 11:17-11:18,
                    scopes: [],
                    name: {
                      node: Identifier,
                      loc: 11:17-11:18,
                      name: "T",
                    },
                  },
                  type_params: [],
                },
              ],
            },
          ],
        },
        {
          node: TypeParameter,
          loc: 11:21-11:33,
          name: {
            node: Identifier,
            loc: 11:21-11:22,
            name: "U",
          },
          bounds: [
            {
              node: IdentifierType,
              loc: 11:24-11:27,
              name: {
                node: ScopedIdentifier,
                loc: 11:24-11:27,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 11:24-11:27,
                  name: "Bar",
                },
              },
              type_params: [],
            },
            {
              node: IdentifierType,
              loc: 11:30-11:33,
              name: {
                node: ScopedIdentifier,
                loc: 11:30-11:33,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 11:30-11:33,
                  name: "Baz",
                },
              },
              type_params: [],
            },
          ],
        },
        {
          node: TypeParameter,
          loc: 11:35-11:36,
          name: {
            node: Identifier,
            loc: 11:35-11:36,
            name: "V",
          },
          bounds: [],
        },
      ],
      builtin: false,
      tuple: {
        node: TupleVariant,
        loc: 11:5-11:44,
        name: {
          node: Identifier,
          loc: 11:5-11:9,
          name: "Test",
        },
        elements: [
          {
            node: IdentifierType,
            loc: 11:39-11:43,
            name: {
              node: ScopedIdentifier,
              loc: 11:39-11:43,
              scopes: [],
              name: {
                node: Identifier,
                loc: 11:39-11:43,
                name: "Unit",
              },
            },
            type_params: [],
          },
        ],
      },
    },
  ],
}