#!/bin/zsh

CURRENT_DIR=$0:A:h
ROOT_DIR=$(dirname $CURRENT_DIR)

# Build myte executable
pushd $ROOT_DIR/src
dune build myte.exe --no-print-directory --debug-backtraces
popd

# Build test suite
pushd $ROOT_DIR/test
dune build run_tests.exe --no-print-directory --debug-backtraces
popd