test/parser/record/expression.myte
{
  node: Module,
  loc: 1:0-21:35,
  name: {
    node: ModuleName,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: VariableDeclaration,
      loc: 3:0-3:23,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 3:4-3:6,
        scopes: [],
        name: {
          node: Identifier,
          loc: 3:4-3:6,
          name: "x1",
        },
      },
      init: {
        node: RecordExpression,
        loc: 3:9-3:23,
        name: {
          node: Identifier,
          loc: 3:9-3:12,
          name: "Foo",
        },
        fields: [
          {
            node: RecordExpressionField,
            loc: 3:15-3:21,
            name: {
              node: Identifier,
              loc: 3:15-3:18,
              name: "bar",
            },
            value: {
              node: IntLiteral,
              loc: 3:20-3:21,
              raw: "1",
            },
          },
        ],
      },
      annot: None,
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 4:0-4:39,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 4:4-4:6,
        scopes: [],
        name: {
          node: Identifier,
          loc: 4:4-4:6,
          name: "x2",
        },
      },
      init: {
        node: RecordExpression,
        loc: 4:9-4:39,
        name: {
          node: Identifier,
          loc: 4:9-4:12,
          name: "Foo",
        },
        fields: [
          {
            node: RecordExpressionField,
            loc: 4:15-4:25,
            name: {
              node: Identifier,
              loc: 4:15-4:18,
              name: "bar",
            },
            value: {
              node: BinaryOperation,
              loc: 4:20-4:25,
              op: Add,
              left: {
                node: IntLiteral,
                loc: 4:20-4:21,
                raw: "2",
              },
              right: {
                node: IntLiteral,
                loc: 4:24-4:25,
                raw: "3",
              },
            },
          },
          {
            node: RecordExpressionField,
            loc: 4:27-4:37,
            name: {
              node: Identifier,
              loc: 4:27-4:30,
              name: "baz",
            },
            value: {
              node: StringLiteral,
              loc: 4:32-4:37,
              value: "str",
            },
          },
        ],
      },
      annot: None,
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 5:0-5:20,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 5:4-5:6,
        scopes: [],
        name: {
          node: Identifier,
          loc: 5:4-5:6,
          name: "x3",
        },
      },
      init: {
        node: RecordExpression,
        loc: 5:9-5:20,
        name: {
          node: Identifier,
          loc: 5:9-5:12,
          name: "Foo",
        },
        fields: [
          {
            node: RecordExpressionField,
            loc: 5:15-5:18,
            name: {
              node: Identifier,
              loc: 5:15-5:18,
              name: "bar",
            },
            value: None,
          },
        ],
      },
      annot: None,
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 6:0-6:25,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 6:4-6:6,
        scopes: [],
        name: {
          node: Identifier,
          loc: 6:4-6:6,
          name: "x4",
        },
      },
      init: {
        node: RecordExpression,
        loc: 6:9-6:25,
        name: {
          node: Identifier,
          loc: 6:9-6:12,
          name: "Foo",
        },
        fields: [
          {
            node: RecordExpressionField,
            loc: 6:15-6:18,
            name: {
              node: Identifier,
              loc: 6:15-6:18,
              name: "bar",
            },
            value: None,
          },
          {
            node: RecordExpressionField,
            loc: 6:20-6:23,
            name: {
              node: Identifier,
              loc: 6:20-6:23,
              name: "baz",
            },
            value: None,
          },
        ],
      },
      annot: None,
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 7:0-7:43,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 7:4-7:6,
        scopes: [],
        name: {
          node: Identifier,
          loc: 7:4-7:6,
          name: "x5",
        },
      },
      init: {
        node: RecordExpression,
        loc: 7:9-7:43,
        name: {
          node: Identifier,
          loc: 7:9-7:12,
          name: "Foo",
        },
        fields: [
          {
            node: RecordExpressionField,
            loc: 7:15-7:21,
            name: {
              node: Identifier,
              loc: 7:15-7:18,
              name: "bar",
            },
            value: {
              node: IntLiteral,
              loc: 7:20-7:21,
              raw: "1",
            },
          },
          {
            node: RecordExpressionField,
            loc: 7:23-7:26,
            name: {
              node: Identifier,
              loc: 7:23-7:26,
              name: "baz",
            },
            value: None,
          },
          {
            node: RecordExpressionField,
            loc: 7:28-7:32,
            name: {
              node: Identifier,
              loc: 7:28-7:32,
              name: "buzz",
            },
            value: None,
          },
          {
            node: RecordExpressionField,
            loc: 7:34-7:41,
            name: {
              node: Identifier,
              loc: 7:34-7:37,
              name: "bzz",
            },
            value: {
              node: Unit,
              loc: 7:39-7:41,
            },
          },
        ],
      },
      annot: None,
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 10:0-10:40,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 10:4-10:6,
        scopes: [],
        name: {
          node: Identifier,
          loc: 10:4-10:6,
          name: "x6",
        },
      },
      init: {
        node: RecordExpression,
        loc: 10:9-10:40,
        name: {
          node: Identifier,
          loc: 10:9-10:12,
          name: "Foo",
        },
        fields: [
          {
            node: RecordExpressionField,
            loc: 10:15-10:32,
            name: {
              node: Identifier,
              loc: 10:15-10:18,
              name: "bar",
            },
            value: {
              node: RecordExpression,
              loc: 10:20-10:32,
              name: {
                node: Identifier,
                loc: 10:20-10:23,
                name: "Bar",
              },
              fields: [
                {
                  node: RecordExpressionField,
                  loc: 10:26-10:29,
                  name: {
                    node: Identifier,
                    loc: 10:26-10:29,
                    name: "baz",
                  },
                  value: None,
                },
              ],
            },
          },
          {
            node: RecordExpressionField,
            loc: 10:34-10:38,
            name: {
              node: Identifier,
              loc: 10:34-10:38,
              name: "buzz",
            },
            value: None,
          },
        ],
      },
      annot: None,
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 13:0-13:43,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 13:4-13:17,
        scopes: [],
        name: {
          node: Identifier,
          loc: 13:4-13:17,
          name: "trailingValue",
        },
      },
      init: {
        node: RecordExpression,
        loc: 13:20-13:43,
        name: {
          node: Identifier,
          loc: 13:20-13:23,
          name: "Foo",
        },
        fields: [
          {
            node: RecordExpressionField,
            loc: 13:26-13:32,
            name: {
              node: Identifier,
              loc: 13:26-13:29,
              name: "bar",
            },
            value: {
              node: IntLiteral,
              loc: 13:31-13:32,
              raw: "1",
            },
          },
          {
            node: RecordExpressionField,
            loc: 13:34-13:40,
            name: {
              node: Identifier,
              loc: 13:34-13:37,
              name: "baz",
            },
            value: {
              node: IntLiteral,
              loc: 13:39-13:40,
              raw: "2",
            },
          },
        ],
      },
      annot: None,
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 14:0-14:36,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 14:4-14:16,
        scopes: [],
        name: {
          node: Identifier,
          loc: 14:4-14:16,
          name: "trailingName",
        },
      },
      init: {
        node: RecordExpression,
        loc: 14:19-14:36,
        name: {
          node: Identifier,
          loc: 14:19-14:22,
          name: "Foo",
        },
        fields: [
          {
            node: RecordExpressionField,
            loc: 14:25-14:28,
            name: {
              node: Identifier,
              loc: 14:25-14:28,
              name: "bar",
            },
            value: None,
          },
          {
            node: RecordExpressionField,
            loc: 14:30-14:33,
            name: {
              node: Identifier,
              loc: 14:30-14:33,
              name: "baz",
            },
            value: None,
          },
        ],
      },
      annot: None,
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 17:0-17:36,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 17:4-17:15,
        scopes: [],
        name: {
          node: Identifier,
          loc: 17:4-17:15,
          name: "scopedName1",
        },
      },
      init: {
        node: RecordExpression,
        loc: 17:18-17:36,
        name: {
          node: NamedAccess,
          loc: 17:18-17:25,
          target: {
            node: Identifier,
            loc: 17:18-17:21,
            name: "Foo",
          },
          name: {
            node: Identifier,
            loc: 17:22-17:25,
            name: "Bar",
          },
        },
        fields: [
          {
            node: RecordExpressionField,
            loc: 17:28-17:34,
            name: {
              node: Identifier,
              loc: 17:28-17:31,
              name: "bar",
            },
            value: {
              node: IntLiteral,
              loc: 17:33-17:34,
              raw: "1",
            },
          },
        ],
      },
      annot: None,
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 18:0-18:45,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 18:4-18:15,
        scopes: [],
        name: {
          node: Identifier,
          loc: 18:4-18:15,
          name: "scopedName2",
        },
      },
      init: {
        node: RecordExpression,
        loc: 18:18-18:45,
        name: {
          node: NamedAccess,
          loc: 18:18-18:34,
          target: {
            node: NamedAccess,
            loc: 18:18-18:29,
            target: {
              node: NamedAccess,
              loc: 18:18-18:25,
              target: {
                node: Identifier,
                loc: 18:18-18:21,
                name: "Foo",
              },
              name: {
                node: Identifier,
                loc: 18:22-18:25,
                name: "Bar",
              },
            },
            name: {
              node: Identifier,
              loc: 18:26-18:29,
              name: "Baz",
            },
          },
          name: {
            node: Identifier,
            loc: 18:30-18:34,
            name: "Bazz",
          },
        },
        fields: [
          {
            node: RecordExpressionField,
            loc: 18:37-18:43,
            name: {
              node: Identifier,
              loc: 18:37-18:40,
              name: "bar",
            },
            value: {
              node: IntLiteral,
              loc: 18:42-18:43,
              raw: "1",
            },
          },
        ],
      },
      annot: None,
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 21:0-21:35,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 21:4-21:18,
        scopes: [],
        name: {
          node: Identifier,
          loc: 21:4-21:18,
          name: "invalidRecord1",
        },
      },
      init: {
        node: RecordExpression,
        loc: 21:21-21:35,
        name: {
          node: IntLiteral,
          loc: 21:21-21:22,
          raw: "1",
        },
        fields: [
          {
            node: RecordExpressionField,
            loc: 21:25-21:33,
            name: {
              node: Identifier,
              loc: 21:25-21:30,
              name: "field",
            },
            value: {
              node: IntLiteral,
              loc: 21:32-21:33,
              raw: "1",
            },
          },
        ],
      },
      annot: None,
      is_public: false,
    },
  ],
}