test/parser/ast/logical_operations/basic.myte
{
  node: Module,
  loc: 1:0-6:1,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-6:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-6:1,
        statements: [
          {
            node: ExpressionStatement,
            loc: 4:2-4:16,
            expression: {
              node: LogicalAnd,
              loc: 4:2-4:15,
              left: {
                node: BoolLiteral,
                loc: 4:2-4:6,
                value: true,
              },
              right: {
                node: BoolLiteral,
                loc: 4:10-4:15,
                value: false,
              },
            },
          },
          {
            node: ExpressionStatement,
            loc: 5:2-5:16,
            expression: {
              node: LogicalOr,
              loc: 5:2-5:15,
              left: {
                node: BoolLiteral,
                loc: 5:2-5:6,
                value: true,
              },
              right: {
                node: BoolLiteral,
                loc: 5:10-5:15,
                value: false,
              },
            },
          },
        ],
      },
      return: None,
      type_params: [],
      builtin: false,
      static: false,
      override: false,
    },
  ],
}