func void @test.emptyVec() {
  %0 := CallBuiltin std.vec.Vec<Int>* myte_alloc(1)
  %1 := GetPointer int*, std.vec.Vec<Int>* %0.0
  Store int* %1, 0
  %2 := GetPointer int, std.vec.Vec<Int>* %0.1
  Store int %2, 0
  %3 := GetPointer int, std.vec.Vec<Int>* %0.2
  Store int %3, 0
  %4 := CallBuiltin std.vec.Vec<Bool>* myte_alloc(1)
  %5 := GetPointer bool*, std.vec.Vec<Bool>* %4.0
  Store bool* %5, 0
  %6 := GetPointer int, std.vec.Vec<Bool>* %4.1
  Store int %6, 0
  %7 := GetPointer int, std.vec.Vec<Bool>* %4.2
  Store int %7, 0
  Ret
}

func void @test.oneElementVec() {
  %8 := CallBuiltin int* myte_alloc(1)
  %9 := GetPointer int, int* %8[int 0]
  Store int %9, 1
  %10 := CallBuiltin std.vec.Vec<Int>* myte_alloc(1)
  %11 := GetPointer int*, std.vec.Vec<Int>* %10.0
  Store int* %11, %8
  %12 := GetPointer int, std.vec.Vec<Int>* %10.1
  Store int %12, 1
  %13 := GetPointer int, std.vec.Vec<Int>* %10.2
  Store int %13, 1
  %14 := CallBuiltin byte* myte_alloc(1)
  %15 := GetPointer byte, byte* %14[int 0]
  Store byte %15, 2
  %16 := CallBuiltin std.vec.Vec<Byte>* myte_alloc(1)
  %17 := GetPointer byte*, std.vec.Vec<Byte>* %16.0
  Store byte* %17, %14
  %18 := GetPointer int, std.vec.Vec<Byte>* %16.1
  Store int %18, 1
  %19 := GetPointer int, std.vec.Vec<Byte>* %16.2
  Store int %19, 1
  Ret
}

func void @test.multiElementVec() {
  %20 := CallBuiltin int* myte_alloc(3)
  %21 := GetPointer int, int* %20[int 0]
  Store int %21, 5
  %22 := GetPointer int, int* %20[int 1]
  Store int %22, 6
  %23 := GetPointer int, int* %20[int 2]
  Store int %23, 7
  %24 := CallBuiltin std.vec.Vec<Int>* myte_alloc(1)
  %25 := GetPointer int*, std.vec.Vec<Int>* %24.0
  Store int* %25, %20
  %26 := GetPointer int, std.vec.Vec<Int>* %24.1
  Store int %26, 3
  %27 := GetPointer int, std.vec.Vec<Int>* %24.2
  Store int %27, 3
  %28 := CallBuiltin bool* myte_alloc(4)
  %29 := GetPointer bool, bool* %28[int 0]
  Store bool %29, false
  %30 := GetPointer bool, bool* %28[int 1]
  Store bool %30, true
  %31 := GetPointer bool, bool* %28[int 2]
  Store bool %31, false
  %32 := GetPointer bool, bool* %28[int 3]
  Store bool %32, true
  %33 := CallBuiltin std.vec.Vec<Bool>* myte_alloc(1)
  %34 := GetPointer bool*, std.vec.Vec<Bool>* %33.0
  Store bool* %34, %28
  %35 := GetPointer int, std.vec.Vec<Bool>* %33.1
  Store int %35, 4
  %36 := GetPointer int, std.vec.Vec<Bool>* %33.2
  Store int %36, 4
  Ret
}

func void @test.use<Function>(fn %37) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.emptyVec)
  Call void @test.use<Function>(@test.oneElementVec)
  Call void @test.use<Function>(@test.multiElementVec)
  Ret 0
}