#!/bin/zsh

CURRENT_DIR=$0:A:h
ROOT_DIR=$(dirname $CURRENT_DIR)

CPP_FILES=$(find $ROOT_DIR/lib -name "*.cpp")

# Build myte executable
mkdir -p $ROOT_DIR/builds
clang++ -o $ROOT_DIR/builds/mytepp \
  -Wall -Wextra -Wpedantic \
  -std=c++17 \
  -Iinclude \
  ${=CPP_FILES}
