  .global _main

  .text
_main:
  push %rbx
  push %r12
  movl $16, %edi
  call __myte_alloc
  movl $0, 4(%rax)
  movq $0, 8(%rax)
  movb $0, (%rax)
  movq %rax, %rdi
  call test.simpleReassign
  movl $16, %edi
  call __myte_alloc
  movq %rax, %rbx
  movq $0, (%rbx)
  movl $16, %edi
  call __myte_alloc
  movq %rax, %r12
  movl $0, (%r12)
  movl $2, %edi
  call __myte_alloc
  movb $0, (%rax)
  movb $0, 1(%rax)
  movq %rax, 8(%r12)
  movq %r12, 8(%rbx)
  movl $2, %edi
  call __myte_alloc
  movb $0, (%rax)
  movb $0, 1(%rax)
  movq %rbx, %rdi
  movq %rax, %rsi
  call test.nestedReassign
  movl $0, %eax
  pop %r12
  pop %rbx
  ret
test.nestedReassign:
  movq 8(%rdi), %rax
  movq 8(%rax), %rax
  movb $7, 1(%rax)
  movq 8(%rdi), %rax
  movq %rsi, 8(%rax)
  ret
test.simpleReassign:
  movl $1, 4(%rdi)
  movq $2, 8(%rdi)
  movb $3, (%rdi)
  ret