  .global _main

  .text
_main:
  movl $1, %edi
  call test.testMyteAllocLiteralCount
  movl $1, %edi
  call test.testMyteAllocVariableCount
  movl $0, %eax
  ret
test.testMyteAllocLiteralCount:
  movl $16, %edi
  call __myte_alloc
  movl $800, %edi
  call __myte_alloc
  ret
test.testMyteAllocVariableCount:
  push %rbx
  movl %edi, %ebx
  movl %ebx, %edi
  call __myte_alloc
  imull $4, %ebx, %edi
  call __myte_alloc
  imull $8, %ebx, %edi
  call __myte_alloc
  pop %rbx
  ret