test/parser/builtin/function.myte
{
  node: Module,
  loc: 1:0-7:32,
  name: {
    node: ModuleName,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-3:17,
      name: {
        node: Identifier,
        loc: 3:12-3:15,
        name: "foo",
      },
      params: [],
      body: None,
      return: None,
      type_params: [],
      is_public: false,
      is_builtin: true,
      is_static: false,
      is_override: false,
    },
    {
      node: Function,
      loc: 5:0-5:21,
      name: {
        node: Identifier,
        loc: 5:16-5:19,
        name: "foo",
      },
      params: [],
      body: None,
      return: None,
      type_params: [],
      is_public: true,
      is_builtin: true,
      is_static: false,
      is_override: false,
    },
    {
      node: Function,
      loc: 7:0-7:32,
      name: {
        node: Identifier,
        loc: 7:12-7:15,
        name: "foo",
      },
      params: [
        {
          node: Param,
          loc: 7:19-7:25,
          name: {
            node: Identifier,
            loc: 7:19-7:20,
            name: "x",
          },
          annot: {
            node: IdentifierType,
            loc: 7:22-7:25,
            name: {
              node: ScopedIdentifier,
              loc: 7:22-7:25,
              scopes: [],
              name: {
                node: Identifier,
                loc: 7:22-7:25,
                name: "Int",
              },
            },
            type_args: [],
          },
        },
      ],
      body: None,
      return: {
        node: IdentifierType,
        loc: 7:28-7:32,
        name: {
          node: ScopedIdentifier,
          loc: 7:28-7:32,
          scopes: [],
          name: {
            node: Identifier,
            loc: 7:28-7:32,
            name: "Unit",
          },
        },
        type_args: [],
      },
      type_params: [
        {
          node: TypeParameter,
          loc: 7:16-7:17,
          name: {
            node: Identifier,
            loc: 7:16-7:17,
            name: "T",
          },
          bounds: [],
        },
      ],
      is_public: false,
      is_builtin: true,
      is_static: false,
      is_override: false,
    },
  ],
}