test/parser/builtin/type.myte
{
  node: Module,
  loc: 1:0-7:21,
  name: {
    node: ModuleName,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: TypeDeclaration,
      loc: 3:0-3:18,
      name: {
        node: Identifier,
        loc: 3:13-3:18,
        name: "Array",
      },
      type_params: [],
      builtin: true,
      is_public: false,
    },
    {
      node: TypeDeclaration,
      loc: 5:0-5:22,
      name: {
        node: Identifier,
        loc: 5:17-5:22,
        name: "Array",
      },
      type_params: [],
      builtin: true,
      is_public: true,
    },
    {
      node: TypeDeclaration,
      loc: 7:0-7:21,
      name: {
        node: Identifier,
        loc: 7:13-7:18,
        name: "Array",
      },
      type_params: [
        {
          node: TypeParameter,
          loc: 7:19-7:20,
          name: {
            node: Identifier,
            loc: 7:19-7:20,
            name: "T",
          },
          bounds: [],
        },
      ],
      builtin: true,
      is_public: false,
    },
  ],
}