type test.Tup1 {int}

type test.Tup2 {std.string.String*, bool, unit}

type test.Tup3 {test.Tup1*, test.Tup2*, int}

type test.Rec1 {int}

type test.Rec2 {bool, unit, test.Tup2*}

type test.Rec3 {unit, bool, int}

type test.Tup4 {test.Tup5*}

type test.Tup5 {int}

func unit @test.useAll(test.Tup1* %0, test.Tup2* %1, test.Tup3* %2, test.Rec1* %3, test.Rec2* %4, test.Rec3* %5, test.Tup4* %6, test.Tup5* %7) {
  Ret
}

func int @test.main() {
  Ret 0
}