type test.Tup1 {int}

type test.Tup2 {bool, std.string.String*}

type test.Tup3 {int, test.Tup1*, test.Tup2*}

type test.Rec1 {int}

type test.Rec2 {bool, test.Tup2*}

type test.Rec3 {bool, int}

type test.Tup4 {test.Tup5*}

type test.Tup5 {int}

func void @test.useAll(test.Tup1* %0, test.Tup2* %1, test.Tup3* %2, test.Rec1* %3, test.Rec2* %4, test.Rec3* %5, test.Tup4* %6, test.Tup5* %7) {
  Ret
}

func void @test.use<Function>(fn %0) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.useAll)
  Ret 0
}