type test.Tup1 {int}

type test.Tup2 {long, long, int}

type test.Tup3 {byte, test.Tup2*, byte}

type test.Rec1 {int}

type test.Rec2 {long, long, int}

type test.Rec3 {byte, test.Tup2*, byte}

func void @test.arguments(int %0) {
  %1 := CallBuiltin test.Tup2* myte_alloc(1)
  %2 := GetPointer long, test.Tup2* %1.0
  Store long %2, 3
  %3 := GetPointer long, test.Tup2* %1.1
  Store long %3, 3
  %4 := GetPointer int, test.Tup2* %1.2
  Store int %4, %0
  %5 := CallBuiltin test.Tup3* myte_alloc(1)
  %6 := GetPointer byte, test.Tup3* %5.0
  Store byte %6, 6
  %7 := CallBuiltin test.Tup2* myte_alloc(1)
  %8 := GetPointer long, test.Tup2* %7.0
  Store long %8, 1
  %9 := GetPointer long, test.Tup2* %7.1
  Store long %9, 7
  %10 := GetPointer int, test.Tup2* %7.2
  Store int %10, 8
  %11 := GetPointer test.Tup2*, test.Tup3* %5.1
  Store test.Tup2* %11, %7
  %12 := GetPointer byte, test.Tup3* %5.2
  Store byte %12, 9
  %13 := CallBuiltin test.Rec3* myte_alloc(1)
  %14 := GetPointer byte, test.Rec3* %13.0
  Store byte %14, 6
  %15 := CallBuiltin test.Tup2* myte_alloc(1)
  %16 := GetPointer long, test.Tup2* %15.0
  Store long %16, 1
  %17 := GetPointer long, test.Tup2* %15.1
  Store long %17, 7
  %18 := GetPointer int, test.Tup2* %15.2
  Store int %18, 8
  %19 := GetPointer test.Tup2*, test.Rec3* %13.1
  Store test.Tup2* %19, %15
  %20 := GetPointer byte, test.Rec3* %13.2
  Store byte %20, 9
  Ret
}

func void @test.tupleConstructor() {
  %0 := CallBuiltin test.Tup1* myte_alloc(1)
  %1 := GetPointer int, test.Tup1* %0.0
  Store int %1, 3
  %2 := CallBuiltin test.Tup2* myte_alloc(1)
  %3 := GetPointer long, test.Tup2* %2.0
  Store long %3, 3
  %4 := GetPointer long, test.Tup2* %2.1
  Store long %4, 4
  %5 := GetPointer int, test.Tup2* %2.2
  Store int %5, 5
  Ret
}

func void @test.recordConstructor() {
  %0 := CallBuiltin test.Rec1* myte_alloc(1)
  %1 := GetPointer int, test.Rec1* %0.0
  Store int %1, 3
  %2 := CallBuiltin test.Rec2* myte_alloc(1)
  %3 := GetPointer long, test.Rec2* %2.0
  Store long %3, 3
  %4 := GetPointer long, test.Rec2* %2.1
  Store long %4, 4
  %5 := GetPointer int, test.Rec2* %2.2
  Store int %5, 5
  %6 := CallBuiltin test.Rec2* myte_alloc(1)
  %7 := GetPointer int, test.Rec2* %6.2
  Store int %7, 6
  %8 := GetPointer long, test.Rec2* %6.0
  Store long %8, 3
  %9 := GetPointer long, test.Rec2* %6.1
  Store long %9, 7
  Ret
}

func void @test.use<Function>(fn %0) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.arguments)
  Call void @test.use<Function>(@test.tupleConstructor)
  Call void @test.use<Function>(@test.recordConstructor)
  Ret 0
}