type test.V1<Bool> {byte, byte[1]}

type test.V1<Int> {byte, byte[7]}

type test.V1<Bool>::Tuple1 {byte, bool}

type test.V1<Int>::Tuple1 {byte, byte[3], int}

type test.V1<Bool>::Record1 {byte, bool}

type test.V1<Int>::Record1 {byte, byte[3], int}

func void @test.useV1Bool(test.V1<Bool>* %0) {
  Ret
}

func void @test.useV1Int(test.V1<Int>* %0) {
  Ret
}

func void @test.testEnumConstructors() {
  %0 := Call test.V1<Bool>* myte.builtin.alloc(1)
  %1 := Cast test.V1<Bool>* %0 to byte*
  Store byte %1, 0
  Call void @test.useV1Bool(%0)
  %2 := Call test.V1<Bool>* myte.builtin.alloc(1)
  %3 := Cast test.V1<Bool>* %2 to byte*
  Store byte %3, 1
  Call void @test.useV1Bool(%2)
  %4 := Call test.V1<Int>* myte.builtin.alloc(1)
  %5 := Cast test.V1<Int>* %4 to byte*
  Store byte %5, 0
  Call void @test.useV1Int(%4)
  %6 := Call test.V1<Int>* myte.builtin.alloc(1)
  %7 := Cast test.V1<Int>* %6 to byte*
  Store byte %7, 1
  Call void @test.useV1Int(%6)
  Ret
}

type test.V2 {byte, byte[7], byte*}

type test.V2::Tuple2 {byte, bool, byte[2], int, test.V1<Int>*}

type test.V2::Record2 {byte, bool, byte[2], int, test.V1<Int>*}

type test.V2::Record3 {byte, byte, byte[2], int, byte*}

func void @test.testTupleConstructors() {
  %0 := Call test.V1<Bool>::Tuple1* myte.builtin.alloc(1)
  %1 := Cast test.V1<Bool>::Tuple1* %0 to byte*
  Store byte %1, 2
  %2 := GetPointer bool, test.V1<Bool>::Tuple1* %0.1
  Store bool %2, true
  Call void @test.useV1Bool(%0)
  %3 := Call test.V1<Int>::Tuple1* myte.builtin.alloc(1)
  %4 := Cast test.V1<Int>::Tuple1* %3 to byte*
  Store byte %4, 2
  %5 := GetPointer int, test.V1<Int>::Tuple1* %3.2
  Store int %5, 7
  %6 := Call test.V2::Tuple2* myte.builtin.alloc(1)
  %7 := Cast test.V2::Tuple2* %6 to byte*
  Store byte %7, 0
  %8 := GetPointer int, test.V2::Tuple2* %6.3
  Store int %8, 3
  %9 := GetPointer bool, test.V2::Tuple2* %6.1
  Store bool %9, false
  %10 := GetPointer test.V1<Int>*, test.V2::Tuple2* %6.4
  Store test.V1<Int>* %10, %3
  Ret
}

func void @test.testRecordConstructors() {
  %0 := Call test.V1<Bool>::Record1* myte.builtin.alloc(1)
  %1 := Cast test.V1<Bool>::Record1* %0 to byte*
  Store byte %1, 3
  %2 := GetPointer bool, test.V1<Bool>::Record1* %0.1
  Store bool %2, true
  Call void @test.useV1Bool(%0)
  %3 := Call test.V1<Int>::Record1* myte.builtin.alloc(1)
  %4 := Cast test.V1<Int>::Record1* %3 to byte*
  Store byte %4, 3
  %5 := GetPointer int, test.V1<Int>::Record1* %3.2
  Store int %5, 7
  %6 := Call test.V2::Record2* myte.builtin.alloc(1)
  %7 := Cast test.V2::Record2* %6 to byte*
  Store byte %7, 1
  %8 := GetPointer int, test.V2::Record2* %6.3
  Store int %8, 3
  %9 := GetPointer bool, test.V2::Record2* %6.1
  Store bool %9, false
  %10 := GetPointer test.V1<Int>*, test.V2::Record2* %6.4
  Store test.V1<Int>* %10, %3
  %11 := Call test.V2::Record3* myte.builtin.alloc(1)
  %12 := Cast test.V2::Record3* %11 to byte*
  Store byte %12, 2
  %13 := GetPointer byte, test.V2::Record3* %11.1
  Store byte %13, 4
  %14 := GetPointer int, test.V2::Record3* %11.3
  Store int %14, 5
  Ret
}

func void @test.use<Function>(fn %0) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.testEnumConstructors)
  Call void @test.use<Function>(@test.testTupleConstructors)
  Call void @test.use<Function>(@test.testRecordConstructors)
  Ret 0
}