func void @test.testZeroSizeADT() {
  Call void @test.getUnit()
  Call void @test.id<Unit>()
  Call void @test.use<test.Tup1>()
  Call void @test.use<Unit>()
  Call void @test.use<Unit>()
  Call void @test.getUnit()
  Call void @test.id<Unit>()
  Call void @test.use<test.Rec1>()
  Call void @test.use<Unit>()
  Call void @test.use<Unit>()
  Ret
}

type test.Tup2 {byte, int}

type test.Rec2 {byte, int}

func void @test.testAggregateWithZeroSizeFields() {
  %0 := Call test.Tup2* myte.builtin.alloc(1)
  %1 := GetPointer int, test.Tup2* %0.1
  Store int %1, 6
  Call void @test.getUnit()
  Call void @test.id<Unit>()
  %2 := GetPointer byte, test.Tup2* %0.0
  Store byte %2, 5
  Call void @test.use<Unit>()
  %3 := GetPointer int, test.Tup2* %0.1
  %4 := Load int %3
  Call void @test.use<Int>(%4)
  Call void @test.use<Unit>()
  Call void @test.use<Unit>()
  %5 := GetPointer byte, test.Tup2* %0.0
  %6 := Load byte %5
  Call void @test.use<Byte>(%6)
  %7 := Call test.Rec2* myte.builtin.alloc(1)
  Call void @test.getUnit()
  %8 := GetPointer int, test.Rec2* %7.1
  Store int %8, 6
  Call void @test.id<Unit>()
  %9 := GetPointer byte, test.Rec2* %7.0
  Store byte %9, 5
  Call void @test.use<Unit>()
  %10 := GetPointer int, test.Rec2* %7.1
  %11 := Load int %10
  Call void @test.use<Int>(%11)
  Call void @test.use<Unit>()
  %12 := GetPointer byte, test.Rec2* %7.0
  %13 := Load byte %12
  Call void @test.use<Byte>(%13)
  Ret
}

type test.Variant1 {byte, byte[7]}

type test.Variant1::Tup3 {byte, byte, byte[2], int}

type test.Variant1::Rec3 {byte, byte, byte[2], int}

type test.Variant1::Tup4 {byte, byte[7]}

type test.Variant1::Rec4 {byte, byte[7]}

func void @test.testVariantWithZeroSizeFields() {
  %0 := Call test.Variant1::Tup3* myte.builtin.alloc(1)
  Store byte %0, 0
  %1 := GetPointer int, test.Variant1::Tup3* %0.3
  Store int %1, 1
  Call void @test.getUnit()
  %2 := GetPointer byte, test.Variant1::Tup3* %0.1
  Store byte %2, 2
  Call void @test.use<test.Variant1>(%0)
  %3 := Call test.Variant1::Rec3* myte.builtin.alloc(1)
  Store byte %3, 1
  %4 := GetPointer byte, test.Variant1::Rec3* %3.1
  Store byte %4, 3
  Call void @test.id<Unit>()
  %5 := GetPointer int, test.Variant1::Rec3* %3.3
  Store int %5, 4
  Call void @test.use<test.Variant1>(%3)
  %6 := Call test.Variant1::Tup4* myte.builtin.alloc(1)
  Store byte %6, 2
  Call void @test.id<Unit>()
  Call void @test.use<test.Variant1>(%6)
  %7 := Call test.Variant1::Rec4* myte.builtin.alloc(1)
  Store byte %7, 3
  Call void @test.getUnit()
  Call void @test.id<Unit>()
  Call void @test.use<test.Variant1>(%7)
  Ret
}

func void @test.getUnit() {
  Ret
}

func void @test.id<Unit>() {
  Ret
}

func void @test.use<Byte>(byte %0) {
  Ret
}

func void @test.use<Function>(fn %0) {
  Ret
}

func void @test.use<Int>(int %0) {
  Ret
}

func void @test.use<Unit>() {
  Ret
}

func void @test.use<test.Rec1>() {
  Ret
}

func void @test.use<test.Tup1>() {
  Ret
}

func void @test.use<test.Variant1>(test.Variant1* %0) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.testZeroSizeADT)
  Call void @test.use<Function>(@test.testAggregateWithZeroSizeFields)
  Call void @test.use<Function>(@test.testVariantWithZeroSizeFields)
  Ret 0
}