  .global _main

  .text
test.divByteImmReg:
  movw $60, %ax
  movsx %dil, %cx
  cwd 
  idivw %cx
  ret
test.divByteRegImm:
  movsx %dil, %ax
  movw $60, %cx
  cwd 
  idivw %cx
  ret
test.divByteRegs:
  movsx %dil, %ax
  movsx %sil, %cx
  cwd 
  idivw %cx
  ret
test.divIntImmReg:
  movl $257, %eax
  cdq 
  idivl %edi
  ret
test.divIntRegImm:
  movl %edi, %eax
  movl $257, %ecx
  cdq 
  idivl %ecx
  ret
test.divIntRegs:
  movl %edi, %eax
  cdq 
  idivl %esi
  ret
test.divLongImmReg:
  movq $2147483648, %rax
  cqo 
  idivq %rdi
  ret
test.divLongRegImm:
  movq $2147483648, %rcx
  movq %rdi, %rax
  cqo 
  idivq %rcx
  ret
test.divLongRegs:
  movq %rdi, %rax
  cqo 
  idivq %rsi
  ret
_main:
  leaq test.divByteRegs(%rip), %rdi
  call test.use$fn$
  leaq test.divByteImmReg(%rip), %rdi
  call test.use$fn$
  leaq test.divByteRegImm(%rip), %rdi
  call test.use$fn$
  leaq test.divIntRegs(%rip), %rdi
  call test.use$fn$
  leaq test.divIntRegImm(%rip), %rdi
  call test.use$fn$
  leaq test.divIntImmReg(%rip), %rdi
  call test.use$fn$
  leaq test.divLongRegs(%rip), %rdi
  call test.use$fn$
  leaq test.divLongRegImm(%rip), %rdi
  call test.use$fn$
  leaq test.divLongImmReg(%rip), %rdi
  call test.use$fn$
  leaq test.remByteRegs(%rip), %rdi
  call test.use$fn$
  leaq test.remByteImmReg(%rip), %rdi
  call test.use$fn$
  leaq test.remByteRegImm(%rip), %rdi
  call test.use$fn$
  leaq test.remIntRegs(%rip), %rdi
  call test.use$fn$
  leaq test.remIntRegImm(%rip), %rdi
  call test.use$fn$
  leaq test.remIntImmReg(%rip), %rdi
  call test.use$fn$
  leaq test.remLongRegs(%rip), %rdi
  call test.use$fn$
  leaq test.remLongRegImm(%rip), %rdi
  call test.use$fn$
  leaq test.remLongImmReg(%rip), %rdi
  call test.use$fn$
  movl $0, %eax
  ret
test.remByteImmReg:
  movw $60, %ax
  movsx %dil, %cx
  cwd 
  idivw %cx
  movl %edx, %eax
  ret
test.remByteRegImm:
  movsx %dil, %ax
  movw $60, %cx
  cwd 
  idivw %cx
  movl %edx, %eax
  ret
test.remByteRegs:
  movsx %dil, %ax
  movsx %sil, %cx
  cwd 
  idivw %cx
  movl %edx, %eax
  ret
test.remIntImmReg:
  movl $257, %eax
  cdq 
  idivl %edi
  movl %edx, %eax
  ret
test.remIntRegImm:
  movl %edi, %eax
  movl $257, %ecx
  cdq 
  idivl %ecx
  movl %edx, %eax
  ret
test.remIntRegs:
  movl %edi, %eax
  cdq 
  idivl %esi
  movl %edx, %eax
  ret
test.remLongImmReg:
  movq $2147483648, %rax
  cqo 
  idivq %rdi
  movq %rdx, %rax
  ret
test.remLongRegImm:
  movq $2147483648, %rcx
  movq %rdi, %rax
  cqo 
  idivq %rcx
  movq %rdx, %rax
  ret
test.remLongRegs:
  movq %rdi, %rax
  cqo 
  idivq %rsi
  movq %rdx, %rax
  ret
test.use$fn$:
  movq %rdi, %rax
  ret