  .global _main

  .text
_main:
  leaq test.mulByteRegs(%rip), %rdi
  call test.use$fn$
  leaq test.mulByteImmReg(%rip), %rdi
  call test.use$fn$
  leaq test.mulByteRegImm(%rip), %rdi
  call test.use$fn$
  leaq test.mulIntRegs(%rip), %rdi
  call test.use$fn$
  leaq test.mulIntRegImm(%rip), %rdi
  call test.use$fn$
  leaq test.mulIntImmReg(%rip), %rdi
  call test.use$fn$
  leaq test.mulLongRegs(%rip), %rdi
  call test.use$fn$
  leaq test.mulLongRegImm(%rip), %rdi
  call test.use$fn$
  leaq test.mulLongImmReg(%rip), %rdi
  call test.use$fn$
  movl $0, %eax
  ret
test.mulByteImmReg:
  imulw $60, %di, %ax
  ret
test.mulByteRegImm:
  imulw $60, %di, %ax
  ret
test.mulByteRegs:
  imulw %di, %si
  movl %esi, %eax
  ret
test.mulIntImmReg:
  imull $257, %edi, %eax
  ret
test.mulIntRegImm:
  imull $257, %edi, %eax
  ret
test.mulIntRegs:
  imull %edi, %esi
  movl %esi, %eax
  ret
test.mulLongImmReg:
  movq $2147483648, %rax
  imulq %rax, %rdi
  movq %rdi, %rax
  ret
test.mulLongRegImm:
  movq $2147483648, %rax
  imulq %rdi, %rax
  ret
test.mulLongRegs:
  imulq %rdi, %rsi
  movq %rsi, %rax
  ret
test.use$fn$:
  movq %rdi, %rax
  ret