  .global _start

  .text
_main:
  movl $0, %eax
  ret
test.mulByteImmReg:
  imulw $60, %di, %ax
  ret
test.mulByteRegImm:
  imulw $60, %di, %ax
  ret
test.mulByteRegs:
  imulw %di, %si
  movl %esi, %eax
  ret
test.mulIntImmReg:
  imull $257, %edi, %eax
  ret
test.mulIntRegImm:
  imull $257, %edi, %eax
  ret
test.mulIntRegs:
  imull %edi, %esi
  movl %esi, %eax
  ret
test.mulLongImmReg:
  movq $2147483648, %rax
  imulq %rax, %rdi
  movq %rdi, %rax
  ret
test.mulLongRegImm:
  movq $2147483648, %rax
  imulq %rdi, %rax
  ret
test.mulLongRegs:
  imulq %rdi, %rsi
  movq %rsi, %rax
  ret
_start:
  call __myte_init
  call _main
  ret