  .global _main

  .text
_main:
  leaq test.negByteReg(%rip), %rdi
  call test.use$fn$
  leaq test.negIntReg(%rip), %rdi
  call test.use$fn$
  leaq test.negLongReg(%rip), %rdi
  call test.use$fn$
  movl $0, %eax
  ret
test.negByteReg:
  negb %dil
  movl %edi, %eax
  ret
test.negIntReg:
  negl %edi
  movl %edi, %eax
  ret
test.negLongReg:
  negq %rdi
  movq %rdi, %rax
  ret
test.use$fn$:
  movq %rdi, %rax
  ret