  .global _main

  .text
_main:
  leaq test.notByteReg(%rip), %rdi
  call test.use$Function$
  leaq test.notIntReg(%rip), %rdi
  call test.use$Function$
  leaq test.notLongReg(%rip), %rdi
  call test.use$Function$
  movl $0, %eax
  ret
test.notByteReg:
  notb %dil
  movl %edi, %eax
  ret
test.notIntReg:
  notl %edi
  movl %edi, %eax
  ret
test.notLongReg:
  notq %rdi
  movq %rdi, %rax
  ret
test.use$Function$:
  movq %rdi, %rax
  ret