  .global _main

  .text
_main:
  movl $0, %eax
  ret
test.sarByteImmReg:
  movl %edi, %ecx
  movb $6, %al
  sarb %cl, %al
  ret
test.sarByteRegImm:
  sarb $6, %dil
  movl %edi, %eax
  ret
test.sarByteRegs:
  movl %esi, %ecx
  sarb %cl, %dil
  movl %edi, %eax
  ret
test.sarIntImmReg:
  movl %edi, %ecx
  movl $257, %eax
  sarl %cl, %eax
  ret
test.sarIntRegImm:
  sarl $6, %edi
  movl %edi, %eax
  ret
test.sarIntRegs:
  movl %esi, %ecx
  sarl %cl, %edi
  movl %edi, %eax
  ret
test.sarLongImmReg:
  movq $2147483648, %rax
  movl %edi, %ecx
  sarq %cl, %rax
  ret
test.sarLongRegImm:
  sarq $6, %rdi
  movq %rdi, %rax
  ret
test.sarLongRegs:
  movl %esi, %ecx
  sarq %cl, %rdi
  movq %rdi, %rax
  ret