  .global _start

  .text
_main:
  movl $0, %eax
  ret
test.shrByteImmReg:
  movl %edi, %ecx
  movb $6, %al
  shrb %cl, %al
  ret
test.shrByteRegImm:
  shrb $6, %dil
  movl %edi, %eax
  ret
test.shrByteRegs:
  movl %esi, %ecx
  shrb %cl, %dil
  movl %edi, %eax
  ret
test.shrIntImmReg:
  movl %edi, %ecx
  movl $257, %eax
  shrl %cl, %eax
  ret
test.shrIntRegImm:
  shrl $6, %edi
  movl %edi, %eax
  ret
test.shrIntRegs:
  movl %esi, %ecx
  shrl %cl, %edi
  movl %edi, %eax
  ret
test.shrLongImmReg:
  movq $2147483648, %rax
  movl %edi, %ecx
  shrq %cl, %rax
  ret
test.shrLongRegImm:
  shrq $6, %rdi
  movq %rdi, %rax
  ret
test.shrLongRegs:
  movl %esi, %ecx
  shrq %cl, %rdi
  movq %rdi, %rax
  ret