  .global _main

  .text
_main:
  leaq test.testRegister(%rip), %rdi
  call test.use$fn$
  leaq test.testMemory(%rip), %rdi
  call test.use$fn$
  movl $0, %eax
  ret
test.testMemory:
  movb 8(%rsp), %al
  testb %al, %al
  je .L0
  movl $1, %eax
  ret
.L0:
  movl $2, %eax
  ret
test.testRegister:
  testb %dil, %dil
  je .L1
  movl $1, %eax
  ret
.L1:
  movl $2, %eax
  ret
test.use$fn$:
  movq %rdi, %rax
  ret