  .global _main

  .text
_main:
  leaq test.testRegister(%rip), %rdi
  call test.use$Function$
  leaq test.testMemory(%rip), %rdi
  call test.use$Function$
  movl $0, %eax
  ret
test.testMemory:
  cmpq $3, 8(%rsp)
  jne .L0
  movl $1, %eax
  ret
.L0:
  movl $2, %eax
  ret
test.testRegister:
  cmpq $3, %rdi
  jne .L1
  movl $1, %eax
  ret
.L1:
  movl $2, %eax
  ret
test.use$Function$:
  movq %rdi, %rax
  ret