  .global _main

  .text
_main:
  leaq test.xorByteRegs(%rip), %rdi
  call test.use$fn$
  leaq test.xorByteImmReg(%rip), %rdi
  call test.use$fn$
  leaq test.xorByteRegImm(%rip), %rdi
  call test.use$fn$
  leaq test.xorIntRegs(%rip), %rdi
  call test.use$fn$
  leaq test.xorIntRegImm(%rip), %rdi
  call test.use$fn$
  leaq test.xorIntImmReg(%rip), %rdi
  call test.use$fn$
  leaq test.xorLongRegs(%rip), %rdi
  call test.use$fn$
  leaq test.xorLongRegImm(%rip), %rdi
  call test.use$fn$
  leaq test.xorLongImmReg(%rip), %rdi
  call test.use$fn$
  movl $0, %eax
  ret
test.use$fn$:
  movq %rdi, %rax
  ret
test.xorByteImmReg:
  xorb $60, %dil
  movl %edi, %eax
  ret
test.xorByteRegImm:
  xorb $60, %dil
  movl %edi, %eax
  ret
test.xorByteRegs:
  xorb %dil, %sil
  movl %esi, %eax
  ret
test.xorIntImmReg:
  xorl $257, %edi
  movl %edi, %eax
  ret
test.xorIntRegImm:
  xorl $257, %edi
  movl %edi, %eax
  ret
test.xorIntRegs:
  xorl %edi, %esi
  movl %esi, %eax
  ret
test.xorLongImmReg:
  movq $2147483648, %rax
  xorq %rax, %rdi
  movq %rdi, %rax
  ret
test.xorLongRegImm:
  movq $2147483648, %rax
  xorq %rdi, %rax
  ret
test.xorLongRegs:
  xorq %rdi, %rsi
  movq %rsi, %rax
  ret