  .global _main

  .bss
  .balign 8
test.s:
  .skip 8

  .data
.S0:
  .ascii "foobar"
.S1:
  .ascii "foo"

  .text
_init:
  movl $16, %edi
  call __myte_alloc
  leaq .S1(%rip), %rdx
  movq %rdx, 8(%rax)
  movl $3, (%rax)
  movl $3, 4(%rax)
  movq %rax, test.s(%rip)
  ret
_main:
  movq test.s(%rip), %rdi
  call test.use$String$
  leaq test.test(%rip), %rdi
  call test.use$Function$
  movl $0, %eax
  ret
test.test:
  movl $16, %edi
  call __myte_alloc
  leaq .S0(%rip), %rdx
  movq %rdx, 8(%rax)
  movl $6, (%rax)
  movl $6, 4(%rax)
  ret
test.use$Function$:
  movq %rdi, %rax
  ret
test.use$String$:
  movq %rdi, %rax
  ret