test/parser/char_literal/basic.myte
{
  node: Module,
  loc: 1:0-21:1,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-21:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-21:1,
        statements: [
          {
            node: ExpressionStatement,
            loc: 5:2-5:7,
            expression: {
              node: CharLiteral,
              loc: 5:2-5:6,
              value: "\'",
            },
          },
          {
            node: ExpressionStatement,
            loc: 6:2-6:7,
            expression: {
              node: CharLiteral,
              loc: 6:2-6:6,
              value: "\\",
            },
          },
          {
            node: ExpressionStatement,
            loc: 7:2-7:7,
            expression: {
              node: CharLiteral,
              loc: 7:2-7:6,
              value: "\n",
            },
          },
          {
            node: ExpressionStatement,
            loc: 8:2-8:7,
            expression: {
              node: CharLiteral,
              loc: 8:2-8:6,
              value: "\t",
            },
          },
          {
            node: ExpressionStatement,
            loc: 9:2-9:7,
            expression: {
              node: CharLiteral,
              loc: 9:2-9:6,
              value: "\r",
            },
          },
          {
            node: ExpressionStatement,
            loc: 12:2-12:6,
            expression: {
              node: CharLiteral,
              loc: 12:2-12:5,
              value: "0",
            },
          },
          {
            node: ExpressionStatement,
            loc: 13:2-13:6,
            expression: {
              node: CharLiteral,
              loc: 13:2-13:5,
              value: "9",
            },
          },
          {
            node: ExpressionStatement,
            loc: 14:2-14:6,
            expression: {
              node: CharLiteral,
              loc: 14:2-14:5,
              value: "a",
            },
          },
          {
            node: ExpressionStatement,
            loc: 15:2-15:6,
            expression: {
              node: CharLiteral,
              loc: 15:2-15:5,
              value: "A",
            },
          },
          {
            node: ExpressionStatement,
            loc: 16:2-16:6,
            expression: {
              node: CharLiteral,
              loc: 16:2-16:5,
              value: "z",
            },
          },
          {
            node: ExpressionStatement,
            loc: 17:2-17:6,
            expression: {
              node: CharLiteral,
              loc: 17:2-17:5,
              value: "Z",
            },
          },
          {
            node: ExpressionStatement,
            loc: 18:2-18:6,
            expression: {
              node: CharLiteral,
              loc: 18:2-18:5,
              value: """,
            },
          },
          {
            node: ExpressionStatement,
            loc: 19:2-19:6,
            expression: {
              node: CharLiteral,
              loc: 19:2-19:5,
              value: " ",
            },
          },
          {
            node: ExpressionStatement,
            loc: 20:2-20:6,
            expression: {
              node: CharLiteral,
              loc: 20:2-20:5,
              value: "~",
            },
          },
        ],
      },
      return: None,
      type_params: [],
      builtin: false,
      static: false,
      override: false,
    },
  ],
}