func unit @test.use<bool>(bool %0) {
  Ret
}

func unit @test.use<int>(int %1) {
  Ret
}

func unit @test.empty() {
  Ret
}

func unit @test.emptyParams(int %2, bool %3) {
  Ret
}

func int @test.shorthand(int %4) {
  Ret 1
}

func unit @test.withBody(int %5, bool %6, bool %7) {
  %8 := Call unit @test.use<int>(10)
  branch %6, @1, @0
label @0:
  continue @1
label @1:
  %9 := Phi bool @test.withBody:%7, @0:false
  Ret
}

func int @test.main() {
  %10 := Call unit @test.use<bool>(true)
  Ret 0
}