func unit @test.use<Bool>(bool %0) {
  Ret
}

func unit @test.use<Function>(fn %1) {
  Ret
}

func unit @test.use<Int>(int %2) {
  Ret
}

func unit @test.empty() {
  Ret
}

func unit @test.emptyParams(int %3, bool %4) {
  Ret
}

func int @test.shorthand(int %5) {
  Ret 1
}

func unit @test.withBody(int %6, bool %7, bool %8) {
  %9 := Call unit @test.use<Int>(10)
  branch %7, @1, @0
label @0:
  continue @1
label @1:
  %10 := Phi bool @test.withBody:%8, @0:false
  Ret
}

func int @test.main() {
  %11 := Call unit @test.use<Bool>(true)
  %12 := Call unit @test.use<Function>(@test.empty)
  %13 := Call unit @test.use<Function>(@test.emptyParams)
  %14 := Call unit @test.use<Function>(@test.shorthand)
  %15 := Call unit @test.use<Function>(@test.withBody)
  Ret 0
}