type test.ConcreteType {int}

func void @test.ConcreteType.recursive(test.ConcreteType* %0) {
  Call void @test.use<Bool>(true)
  Call void @test.ConcreteType.recursive(%0)
  Ret
}

type test.GenericType<Bool> {bool}

type test.GenericType<Int> {int}

func void @test.GenericType.recursive<Bool>(test.GenericType<Bool>* %0) {
  Call void @test.use<Bool>(true)
  Call void @test.GenericType.recursive<Bool>(%0)
  Ret
}

func void @test.GenericType.recursive<Int>(test.GenericType<Int>* %0) {
  Call void @test.use<Bool>(true)
  Call void @test.GenericType.recursive<Int>(%0)
  Ret
}

func void @test.concreteFunctionRecursive() {
  Call void @test.use<Bool>(true)
  Call void @test.concreteFunctionRecursive()
  Ret
}

func void @test.genericFunctionRecursive<Int>(int %0) {
  Call void @test.use<Bool>(true)
  Call void @test.genericFunctionRecursive<Int>(%0)
  Ret
}

func void @test.testGenericFunctionRecursive() {
  Call void @test.genericFunctionRecursive<Int>(1)
  Ret
}

func void @test.testConcreteMethodRecursive(test.ConcreteType* %0) {
  Call void @test.ConcreteType.recursive(%0)
  Ret
}

func void @test.testGenericMethodRecursive(test.GenericType<Int>* %0, test.GenericType<Bool>* %1) {
  Call void @test.GenericType.recursive<Int>(%0)
  Call void @test.GenericType.recursive<Bool>(%1)
  Ret
}

func void @test.use<Bool>(bool %0) {
  Ret
}

func int @test.main() {
  Ret 0
}