func int @test.testReturnValue() {
  %0 := Eq long 3, 3
  branch %0, @0, @1
label @0:
  %1 := Call int @test.id<Int>(1)
  %2 := Call int @test.id<Int>(2)
  %3 := Add int %1, %2
  Ret %3
label @1:
  Ret 1
}

func void @test.getUnit() {
  Ret
}

func void @test.testReturnZeroSizeType() {
  %0 := Eq long 3, 3
  branch %0, @0, @1
label @0:
  Call void @test.getUnit()
  Call void @test.id<test.ZeroSize>()
  Ret
label @1:
  Ret
}

func int @test.id<Int>(int %0) {
  Ret %0
}

func void @test.id<test.ZeroSize>() {
  Ret
}

func void @test.use<Function>(fn %0) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.testReturnValue)
  Call void @test.use<Function>(@test.testReturnZeroSizeType)
  Ret 0
}