func int @test.Trait1.foo(int %0) {
  %1 := Add int %0, 10
  Ret %1
}

func long @test.Trait2.foo(long %0) {
  %1 := Add long %0, 10
  Ret %1
}

func bool @test.Type1.foo(bool %0) {
  %1 := LogNot %0
  Ret %1
}

func void @test.test() {
  %0 := Call int @test.Trait1.foo(1)
  %1 := Call long @test.Trait2.foo(1)
  %2 := Call bool @test.Type1.foo(true)
  Ret
}

func void @test.use<Function>(fn %0) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.test)
  Ret 0
}