  .global _main

  .data
test.b:
  .byte 0
  .balign 4
test.i:
  .long 0
  .balign 8
_closure$test.getByte:
  .quad test.getByte
  .quad 0
test.f:
  .quad _closure$test.getByte
test.l:
  .quad 0

  .text
test.getByte:
  movb $1, %al
  ret
_main:
  movl $0, %edi
  call test.testReferencing
  movl $0, %eax
  ret
test.testReferencing:
  movb test.b(%rip), %al
  movl test.i(%rip), %eax
  movq test.l(%rip), %rax
  movq test.f(%rip), %rax
  movl test.i(%rip), %eax
  addl %eax, %edi
  movl test.i(%rip), %ecx
  movl test.i(%rip), %eax
  addl %ecx, %eax
  movq test.f(%rip), %rax
  movq (%rax), %rcx
  movq 8(%rax), %rdi
  callq *%rcx
  ret