  .global _main

  .text
_main:
  stp x20, x30, [sp, #-32]!
  str x19, [sp, #16]
  movz w0, #16
  bl mytec_alloc
  mov x20, x0
  str wzr, [x20, #4]
  str xzr, [x20, #8]
  strb wzr, [x20]
  movz w0, #16
  bl mytec_alloc
  mov x19, x0
  str wzr, [x19, #4]
  str xzr, [x19, #8]
  strb wzr, [x19]
  movz w0, #3
  bl mytec_alloc
  mov x2, x0
  strb wzr, [x2]
  strb wzr, [x2, #1]
  strb wzr, [x2, #2]
  mov x0, x20
  mov x1, x19
  bl test.simpleAccess
  movz w0, #16
  bl mytec_alloc
  mov x19, x0
  str xzr, [x19]
  movz w0, #16
  bl mytec_alloc
  mov x20, x0
  str wzr, [x20]
  movz w0, #2
  bl mytec_alloc
  strb wzr, [x0]
  strb wzr, [x0, #1]
  str x0, [x20, #8]
  str x20, [x19, #8]
  mov x0, x19
  bl test.nestedAccess
  mov w0, wzr
  ldr x19, [sp, #16]
  ldp x20, x30, [sp], #32
  ret
test.nestedAccess:
  ldr x1, [x0, #8]
  ldr x1, [x0, #8]
  ldr x1, [x1, #8]
  ldr x0, [x0, #8]
  ldr x0, [x0, #8]
  ldrsb w0, [x0, #1]
  ret
test.simpleAccess:
  ldr w3, [x0, #4]
  ldr x3, [x0, #8]
  ldrsb w0, [x0]
  ldr w0, [x1, #4]
  ldr x0, [x1, #8]
  ldrsb w0, [x1]
  ldrsb w0, [x2]
  ldrsb w0, [x2, #1]
  ldrsb w0, [x2, #2]
  ret