  .global _main

  .text
_main:
  stp x20, x30, [sp, #-32]!
  str x19, [sp, #16]
  movz w0, #16
  bl mytec_alloc
  str wzr, [x0, #4]
  str xzr, [x0, #8]
  strb wzr, [x0]
  bl test.simpleReassign
  movz w0, #16
  bl mytec_alloc
  mov x19, x0
  str xzr, [x19]
  movz w0, #16
  bl mytec_alloc
  mov x20, x0
  str wzr, [x20]
  movz w0, #2
  bl mytec_alloc
  strb wzr, [x0]
  strb wzr, [x0, #1]
  str x0, [x20, #8]
  str x20, [x19, #8]
  movz w0, #2
  bl mytec_alloc
  mov x1, x0
  strb wzr, [x1]
  strb wzr, [x1, #1]
  mov x0, x19
  bl test.nestedReassign
  mov w0, wzr
  ldr x19, [sp, #16]
  ldp x20, x30, [sp], #32
  ret
test.nestedReassign:
  ldr x2, [x0, #8]
  ldr x3, [x2, #8]
  movz w2, #7
  strb w2, [x3, #1]
  ldr x0, [x0, #8]
  str x1, [x0, #8]
  ret
test.simpleReassign:
  movz w1, #1
  str w1, [x0, #4]
  movz x1, #2
  str x1, [x0, #8]
  movz w1, #3
  strb w1, [x0]
  ret