test/parser/ast/variable_declaration/basic.myte
{
  node: Module,
  loc: 1:0-6:15,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: VariableDeclaration,
      loc: 3:0-3:10,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 3:4-3:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 3:8-3:9,
        value: 1,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 4:0-4:10,
      kind: Mutable,
      pattern: {
        node: Identifier,
        loc: 4:4-4:5,
        name: "y",
      },
      init: {
        node: IntLiteral,
        loc: 4:8-4:9,
        value: 2,
        raw: "2",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 6:0-6:15,
      kind: Immutable,
      pattern: {
        node: Identifier,
        loc: 6:4-6:5,
        name: "x",
      },
      init: {
        node: IntLiteral,
        loc: 6:13-6:14,
        value: 1,
        raw: "1",
      },
      annot: {
        node: PrimitiveType,
        loc: 6:7-6:10,
        kind: Int,
      },
    },
  ],
}