test/parser/ast/trait_declaration/traits.myte
{
  node: Module,
  loc: 1:0-24:1,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: TraitDeclaration,
      loc: 3:0-3:12,
      kind: Trait,
      name: {
        node: Identifier,
        loc: 3:6-3:9,
        name: "Foo",
      },
      type_params: [],
      implemented: [],
      methods: [],
    },
    {
      node: TraitDeclaration,
      loc: 5:0-8:1,
      kind: Trait,
      name: {
        node: Identifier,
        loc: 5:6-5:9,
        name: "Foo",
      },
      type_params: [],
      implemented: [
        {
          node: ImplementedTrait,
          loc: 6:2-6:16,
          name: {
            node: ScopedIdentifier,
            loc: 6:10-6:13,
            scopes: [],
            name: {
              node: Identifier,
              loc: 6:10-6:13,
              name: "Bar",
            },
          },
          type_args: [
            {
              node: IdentifierType,
              loc: 6:14-6:15,
              name: {
                node: ScopedIdentifier,
                loc: 6:14-6:15,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 6:14-6:15,
                  name: "T",
                },
              },
              type_params: [],
            },
          ],
        },
        {
          node: ImplementedTrait,
          loc: 7:2-7:24,
          name: {
            node: ScopedIdentifier,
            loc: 7:10-7:13,
            scopes: [],
            name: {
              node: Identifier,
              loc: 7:10-7:13,
              name: "Baz",
            },
          },
          type_args: [
            {
              node: IdentifierType,
              loc: 7:14-7:15,
              name: {
                node: ScopedIdentifier,
                loc: 7:14-7:15,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 7:14-7:15,
                  name: "T",
                },
              },
              type_params: [],
            },
            {
              node: TupleType,
              loc: 7:17-7:23,
              elements: [
                {
                  node: IdentifierType,
                  loc: 7:18-7:19,
                  name: {
                    node: ScopedIdentifier,
                    loc: 7:18-7:19,
                    scopes: [],
                    name: {
                      node: Identifier,
                      loc: 7:18-7:19,
                      name: "U",
                    },
                  },
                  type_params: [],
                },
                {
                  node: IdentifierType,
                  loc: 7:21-7:22,
                  name: {
                    node: ScopedIdentifier,
                    loc: 7:21-7:22,
                    scopes: [],
                    name: {
                      node: Identifier,
                      loc: 7:21-7:22,
                      name: "V",
                    },
                  },
                  type_params: [],
                },
              ],
            },
          ],
        },
      ],
      methods: [],
    },
    {
      node: TraitDeclaration,
      loc: 10:0-14:1,
      kind: Trait,
      name: {
        node: Identifier,
        loc: 10:6-10:9,
        name: "Foo",
      },
      type_params: [],
      implemented: [],
      methods: [
        {
          node: Function,
          loc: 11:2-11:17,
          name: {
            node: Identifier,
            loc: 11:6-11:9,
            name: "bar",
          },
          params: [
            {
              node: Param,
              loc: 11:10-11:16,
              name: {
                node: Identifier,
                loc: 11:10-11:11,
                name: "x",
              },
              annot: {
                node: IdentifierType,
                loc: 11:13-11:16,
                name: {
                  node: ScopedIdentifier,
                  loc: 11:13-11:16,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 11:13-11:16,
                    name: "Int",
                  },
                },
                type_params: [],
              },
            },
          ],
          body: None,
          return: None,
          type_params: [],
          builtin: false,
          static: false,
          override: false,
        },
        {
          node: Function,
          loc: 12:2-12:25,
          name: {
            node: Identifier,
            loc: 12:6-12:9,
            name: "foo",
          },
          params: [
            {
              node: Param,
              loc: 12:10-12:16,
              name: {
                node: Identifier,
                loc: 12:10-12:11,
                name: "x",
              },
              annot: {
                node: IdentifierType,
                loc: 12:13-12:16,
                name: {
                  node: ScopedIdentifier,
                  loc: 12:13-12:16,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 12:13-12:16,
                    name: "Int",
                  },
                },
                type_params: [],
              },
            },
          ],
          body: None,
          return: {
            node: IdentifierType,
            loc: 12:19-12:25,
            name: {
              node: ScopedIdentifier,
              loc: 12:19-12:25,
              scopes: [],
              name: {
                node: Identifier,
                loc: 12:19-12:25,
                name: "String",
              },
            },
            type_params: [],
          },
          type_params: [],
          builtin: false,
          static: false,
          override: false,
        },
        {
          node: Function,
          loc: 13:2-13:17,
          name: {
            node: Identifier,
            loc: 13:6-13:9,
            name: "baz",
          },
          params: [
            {
              node: Param,
              loc: 13:10-13:16,
              name: {
                node: Identifier,
                loc: 13:10-13:11,
                name: "x",
              },
              annot: {
                node: IdentifierType,
                loc: 13:13-13:16,
                name: {
                  node: ScopedIdentifier,
                  loc: 13:13-13:16,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 13:13-13:16,
                    name: "Int",
                  },
                },
                type_params: [],
              },
            },
          ],
          body: None,
          return: None,
          type_params: [],
          builtin: false,
          static: false,
          override: false,
        },
      ],
    },
    {
      node: TraitDeclaration,
      loc: 16:0-24:1,
      kind: Trait,
      name: {
        node: Identifier,
        loc: 16:6-16:9,
        name: "Foo",
      },
      type_params: [
        {
          node: TypeParameter,
          loc: 16:10-16:11,
          name: {
            node: Identifier,
            loc: 16:10-16:11,
            name: "T",
          },
          bounds: [],
        },
      ],
      implemented: [],
      methods: [
        {
          node: Function,
          loc: 17:2-19:3,
          name: {
            node: Identifier,
            loc: 17:6-17:9,
            name: "foo",
          },
          params: [
            {
              node: Param,
              loc: 17:13-17:17,
              name: {
                node: Identifier,
                loc: 17:13-17:14,
                name: "x",
              },
              annot: {
                node: IdentifierType,
                loc: 17:16-17:17,
                name: {
                  node: ScopedIdentifier,
                  loc: 17:16-17:17,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 17:16-17:17,
                    name: "T",
                  },
                },
                type_params: [],
              },
            },
          ],
          body: {
            node: Block,
            loc: 17:22-19:3,
            statements: [
              {
                node: Return,
                loc: 18:4-18:13,
                arg: {
                  node: IntLiteral,
                  loc: 18:11-18:12,
                  raw: "1",
                },
              },
            ],
          },
          return: {
            node: IdentifierType,
            loc: 17:20-17:21,
            name: {
              node: ScopedIdentifier,
              loc: 17:20-17:21,
              scopes: [],
              name: {
                node: Identifier,
                loc: 17:20-17:21,
                name: "U",
              },
            },
            type_params: [],
          },
          type_params: [
            {
              node: TypeParameter,
              loc: 17:10-17:11,
              name: {
                node: Identifier,
                loc: 17:10-17:11,
                name: "U",
              },
              bounds: [],
            },
          ],
          builtin: false,
          static: false,
          override: false,
        },
        {
          node: Function,
          loc: 21:2-21:26,
          name: {
            node: Identifier,
            loc: 21:14-21:24,
            name: "builtinFun",
          },
          params: [],
          body: None,
          return: None,
          type_params: [],
          builtin: true,
          static: false,
          override: false,
        },
        {
          node: Function,
          loc: 22:2-22:28,
          name: {
            node: Identifier,
            loc: 22:15-22:26,
            name: "overrideFun",
          },
          params: [],
          body: None,
          return: None,
          type_params: [],
          builtin: false,
          static: false,
          override: true,
        },
        {
          node: Function,
          loc: 23:2-23:24,
          name: {
            node: Identifier,
            loc: 23:13-23:22,
            name: "staticFun",
          },
          params: [],
          body: None,
          return: None,
          type_params: [],
          builtin: false,
          static: true,
          override: false,
        },
      ],
    },
  ],
}