type test.Tup1 {int}

type test.Tup2 {bool, long, int}

type test.Tup3 {byte, test.Tup2*, byte}

type test.Rec1 {int}

type test.Rec2 {bool, long, int}

type test.Rec3 {byte, test.Tup2*, byte}

func unit @test.arguments(int %0) {
  %1 := CallBuiltin test.Tup2* myte_alloc(1)
  %2 := GetPointer bool %1.0
  Store bool %2, true
  %3 := GetPointer long %1.1
  Store long %3, 3
  %4 := GetPointer int %1.2
  Store int %4, %0
  %5 := CallBuiltin test.Tup3* myte_alloc(1)
  %6 := GetPointer byte %5.0
  Store byte %6, 6
  %7 := CallBuiltin test.Tup2* myte_alloc(1)
  %8 := GetPointer bool %7.0
  Store bool %8, false
  %9 := GetPointer long %7.1
  Store long %9, 7
  %10 := GetPointer int %7.2
  Store int %10, 8
  %11 := GetPointer test.Tup2* %5.1
  Store test.Tup2* %11, %7
  %12 := GetPointer byte %5.2
  Store byte %12, 9
  %13 := CallBuiltin test.Rec3* myte_alloc(1)
  %14 := GetPointer byte %13.0
  Store byte %14, 6
  %15 := CallBuiltin test.Tup2* myte_alloc(1)
  %16 := GetPointer bool %15.0
  Store bool %16, false
  %17 := GetPointer long %15.1
  Store long %17, 7
  %18 := GetPointer int %15.2
  Store int %18, 8
  %19 := GetPointer test.Tup2* %13.1
  Store test.Tup2* %19, %15
  %20 := GetPointer byte %13.2
  Store byte %20, 9
  Ret
}

func unit @test.tupleConstructor() {
  %21 := CallBuiltin test.Tup1* myte_alloc(1)
  %22 := GetPointer int %21.0
  Store int %22, 3
  %23 := CallBuiltin test.Tup2* myte_alloc(1)
  %24 := GetPointer bool %23.0
  Store bool %24, true
  %25 := GetPointer long %23.1
  Store long %25, 4
  %26 := GetPointer int %23.2
  Store int %26, 5
  Ret
}

func unit @test.recordConstructor() {
  %27 := CallBuiltin test.Rec1* myte_alloc(1)
  %28 := GetPointer int %27.0
  Store int %28, 3
  %29 := CallBuiltin test.Rec2* myte_alloc(1)
  %30 := GetPointer bool %29.0
  Store bool %30, true
  %31 := GetPointer long %29.1
  Store long %31, 4
  %32 := GetPointer int %29.2
  Store int %32, 5
  %33 := CallBuiltin test.Rec2* myte_alloc(1)
  %34 := GetPointer int %33.2
  Store int %34, 6
  %35 := GetPointer bool %33.0
  Store bool %35, true
  %36 := GetPointer long %33.1
  Store long %36, 7
  Ret
}

func unit @test.main() {
  Ret
}