type Tup1 {int}

type Tup2 {bool, long, int}

type Tup3 {byte, Tup2*, byte}

type Rec1 {int}

type Rec2 {bool, long, int}

type Rec3 {byte, Tup2*, byte}

func unit @test.arguments(int %0) {
  %1 := CallBuiltin Tup2* myte.myte_alloc(1)
  %2 := GetOffset bool %1[0].0
  Store %2, true
  %3 := GetOffset long %1[0].1
  Store %3, 3
  %4 := GetOffset int %1[0].2
  Store %4, %0
  %5 := CallBuiltin Tup3* myte.myte_alloc(1)
  %6 := GetOffset byte %5[0].0
  Store %6, 6
  %7 := CallBuiltin Tup2* myte.myte_alloc(1)
  %8 := GetOffset bool %7[0].0
  Store %8, false
  %9 := GetOffset long %7[0].1
  Store %9, 7
  %10 := GetOffset int %7[0].2
  Store %10, 8
  %11 := GetOffset Tup2* %5[0].1
  Store %11, %7
  %12 := GetOffset byte %5[0].2
  Store %12, 9
  %13 := CallBuiltin Rec3* myte.myte_alloc(1)
  %14 := GetOffset byte %13[0].0
  Store %14, 6
  %15 := CallBuiltin Tup2* myte.myte_alloc(1)
  %16 := GetOffset bool %15[0].0
  Store %16, false
  %17 := GetOffset long %15[0].1
  Store %17, 7
  %18 := GetOffset int %15[0].2
  Store %18, 8
  %19 := GetOffset Tup2* %13[0].1
  Store %19, %15
  %20 := GetOffset byte %13[0].2
  Store %20, 9
  Ret
}

func unit @test.tupleConstructor() {
  %21 := CallBuiltin Tup1* myte.myte_alloc(1)
  %22 := GetOffset int %21[0].0
  Store %22, 3
  %23 := CallBuiltin Tup2* myte.myte_alloc(1)
  %24 := GetOffset bool %23[0].0
  Store %24, true
  %25 := GetOffset long %23[0].1
  Store %25, 4
  %26 := GetOffset int %23[0].2
  Store %26, 5
  Ret
}

func unit @test.recordConstructor() {
  %27 := CallBuiltin Rec1* myte.myte_alloc(1)
  %28 := GetOffset int %27[0].0
  Store %28, 3
  %29 := CallBuiltin Rec2* myte.myte_alloc(1)
  %30 := GetOffset bool %29[0].0
  Store %30, true
  %31 := GetOffset long %29[0].1
  Store %31, 4
  %32 := GetOffset int %29[0].2
  Store %32, 5
  %33 := CallBuiltin Rec2* myte.myte_alloc(1)
  %34 := GetOffset int %33[0].2
  Store %34, 6
  %35 := GetOffset bool %33[0].0
  Store %35, true
  %36 := GetOffset long %33[0].1
  Store %36, 7
  Ret
}

func unit @test.main() {
  Ret
}