func unit @test.testCopy1(int* %0, int* %1) {
  %2 := CallBuiltin unit myte_copy(%0, %1, 7)
  Ret
}

func unit @test.testCopy2(int* %3, int* %4, int %5) {
  %6 := GetPointer int, int* %3[int %5]
  %7 := CallBuiltin unit myte_copy(%6, %4, 7)
  Ret
}

func unit @test.testCopy3(int* %8, int* %9, int %10) {
  %11 := GetPointer int, int* %9[int %10]
  %12 := CallBuiltin unit myte_copy(%8, %11, 7)
  Ret
}

func unit @test.testCopy(int* %13, int* %14, int %15) {
  %16 := GetPointer int, int* %13[int %15]
  %17 := GetPointer int, int* %14[int %15]
  %18 := CallBuiltin unit myte_copy(%16, %17, 7)
  Ret
}

func int @test.main() {
  Ret 0
}