func void @test.use<std.memory.Array<Int>>(int* %0) {
  Ret
}

func void @test.use<std.memory.Array<Unit>>(std._ZeroSize* %0) {
  Ret
}

func void @test.use<std.memory.Array<test.ZeroSize>>(std._ZeroSize* %0) {
  Ret
}

func int @test.main() {
  %0 := Call int* myte.builtin.alloc(99)
  Call void @test.use<std.memory.Array<Int>>(%0)
  Call void @test.use<std.memory.Array<Int>>(null)
  %1 := Call std._ZeroSize* myte.builtin.alloc(3)
  Call void @test.use<std.memory.Array<Unit>>(%1)
  %2 := Call std._ZeroSize* myte.builtin.alloc(3)
  Call void @test.use<std.memory.Array<test.ZeroSize>>(%2)
  Ret 0
}