func int @test.testWithoutOffset(int %0, byte* %1, int %2) {
  %3 := CallBuiltin int myte_write(%0, %1, %2)
  Ret %3
}

func int @test.testWithOffset(int %4, byte* %5, int %6) {
  %7 := GetPointer byte, byte* %5[int 123]
  %8 := CallBuiltin int myte_write(%4, %7, %6)
  Ret %8
}

func void @test.use<Function>(fn %9) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.testWithoutOffset)
  Call void @test.use<Function>(@test.testWithOffset)
  Ret 0
}