func void @test.testCopy1(int* %0, int* %1) {
  Call void myte.builtin.copy(%0, %1, 7)
  Ret
}

func void @test.testCopy2(int* %0, int* %1, int %2) {
  %3 := GetPointer int, int* %0[int %2]
  Call void myte.builtin.copy(%3, %1, 7)
  Ret
}

func void @test.testCopy3(int* %0, int* %1, int %2) {
  %3 := GetPointer int, int* %1[int %2]
  Call void myte.builtin.copy(%0, %3, 7)
  Ret
}

func void @test.testCopy(int* %0, int* %1, int %2) {
  %3 := GetPointer int, int* %0[int %2]
  %4 := GetPointer int, int* %1[int %2]
  Call void myte.builtin.copy(%3, %4, 7)
  Ret
}

func int @test.main() {
  Ret 0
}