type _ZeroSize {}

func void @test.use<std.memory.Array<Int>>(int* %0) {
  Ret
}

func void @test.use<std.memory.Array<Unit>>(_ZeroSize* %0) {
  Ret
}

func void @test.use<std.memory.Array<test.ZeroSize>>(_ZeroSize* %0) {
  Ret
}

func int @test.main() {
  %0 := CallBuiltin int* myte_alloc(99)
  Call void @test.use<std.memory.Array<Int>>(%0)
  Call void @test.use<std.memory.Array<Int>>(0)
  %1 := CallBuiltin _ZeroSize* myte_alloc(3)
  Call void @test.use<std.memory.Array<Unit>>(%1)
  %2 := CallBuiltin _ZeroSize* myte_alloc(3)
  Call void @test.use<std.memory.Array<test.ZeroSize>>(%2)
  Ret 0
}