type std.vec.Vec<int> {int*, int, int}

type std.vec.Vec<bool> {bool*, int, int}

func int @std.vec.Vec.get<int>(std.vec.Vec<int>* %0, int %1) {
  %2 := Lt int %1, 0
  branch %2, @0, @1
label @0:
  %3 := Mov bool true
  continue @2
label @1:
  %4 := GetPointer int %0.1
  %5 := Load int %4
  %6 := GtEq int %1, %5
  %7 := Mov bool %6
  continue @2
label @2:
  %8 := Phi bool @1:%7, @0:%3
  branch %8, @3, @4
label @3:
  %9 := Call unit @std.sys.abort()
  continue @4
label @4:
  %10 := GetPointer int* %0.0
  %11 := Load int* %10
  %12 := GetPointer int %11[int %1]
  %13 := Load int %12
  Ret %13
}

func bool @std.vec.Vec.get<bool>(std.vec.Vec<bool>* %14, int %15) {
  %16 := Lt int %15, 0
  branch %16, @5, @6
label @5:
  %17 := Mov bool true
  continue @7
label @6:
  %18 := GetPointer int %14.1
  %19 := Load int %18
  %20 := GtEq int %15, %19
  %21 := Mov bool %20
  continue @7
label @7:
  %22 := Phi bool @6:%21, @5:%17
  branch %22, @8, @9
label @8:
  %23 := Call unit @std.sys.abort()
  continue @9
label @9:
  %24 := GetPointer bool* %14.0
  %25 := Load bool* %24
  %26 := GetPointer bool %25[int %15]
  %27 := Load bool %26
  Ret %27
}

func unit @std.vec.Vec.set<int>(std.vec.Vec<int>* %28, int %29, int %30) {
  %31 := Lt int %29, 0
  branch %31, @10, @11
label @10:
  %32 := Mov bool true
  continue @12
label @11:
  %33 := GetPointer int %28.1
  %34 := Load int %33
  %35 := GtEq int %29, %34
  %36 := Mov bool %35
  continue @12
label @12:
  %37 := Phi bool @11:%36, @10:%32
  branch %37, @13, @14
label @13:
  %38 := Call unit @std.sys.abort()
  continue @14
label @14:
  %39 := GetPointer int* %28.0
  %40 := Load int* %39
  %41 := GetPointer int %40[int %29]
  Store int %41, %30
  Ret
}

func unit @std.vec.Vec.set<bool>(std.vec.Vec<bool>* %42, int %43, bool %44) {
  %45 := Lt int %43, 0
  branch %45, @15, @16
label @15:
  %46 := Mov bool true
  continue @17
label @16:
  %47 := GetPointer int %42.1
  %48 := Load int %47
  %49 := GtEq int %43, %48
  %50 := Mov bool %49
  continue @17
label @17:
  %51 := Phi bool @16:%50, @15:%46
  branch %51, @18, @19
label @18:
  %52 := Call unit @std.sys.abort()
  continue @19
label @19:
  %53 := GetPointer bool* %42.0
  %54 := Load bool* %53
  %55 := GetPointer bool %54[int %43]
  Store bool %55, %44
  Ret
}

func unit @std.vec.Vec.push<int>(std.vec.Vec<int>* %56, int %57) {
  %58 := GetPointer int %56.1
  %59 := Load int %58
  %60 := GetPointer int %56.2
  %61 := Load int %60
  %62 := Eq int %59, %61
  branch %62, @20, @21
label @20:
  %63 := Call unit @std.vec.Vec.resize<int>(%56)
  continue @21
label @21:
  %64 := GetPointer int* %56.0
  %65 := Load int* %64
  %66 := GetPointer int %56.1
  %67 := Load int %66
  %68 := GetPointer int %65[int %67]
  Store int %68, %57
  %69 := GetPointer int %56.1
  %70 := GetPointer int %56.1
  %71 := Load int %70
  %72 := Add int %71, 1
  Store int %69, %72
  Ret
}

func unit @std.vec.Vec.push<bool>(std.vec.Vec<bool>* %73, bool %74) {
  %75 := GetPointer int %73.1
  %76 := Load int %75
  %77 := GetPointer int %73.2
  %78 := Load int %77
  %79 := Eq int %76, %78
  branch %79, @22, @23
label @22:
  %80 := Call unit @std.vec.Vec.resize<bool>(%73)
  continue @23
label @23:
  %81 := GetPointer bool* %73.0
  %82 := Load bool* %81
  %83 := GetPointer int %73.1
  %84 := Load int %83
  %85 := GetPointer bool %82[int %84]
  Store bool %85, %74
  %86 := GetPointer int %73.1
  %87 := GetPointer int %73.1
  %88 := Load int %87
  %89 := Add int %88, 1
  Store int %86, %89
  Ret
}

func unit @std.vec.Vec.resize<int>(std.vec.Vec<int>* %90) {
  %91 := GetPointer int %90.2
  %92 := Load int %91
  %93 := Mov int %92
  %94 := Mul int %93, 2
  %95 := Mov int %94
  %96 := Eq int %95, 0
  branch %96, @24, @25
label @24:
  %97 := Mov int 1
  continue @25
label @25:
  %98 := Phi int @std.vec.Vec.resize<int>:%95, @24:%97
  %99 := GetPointer int %90.2
  Store int %99, %98
  %100 := CallBuiltin int* myte_alloc(%98)
  %101 := Mov int* %100
  %102 := GetPointer int* %90.0
  %103 := Load int* %102
  %104 := CallBuiltin unit myte_copy(%101, %103, %93)
  %105 := GetPointer int* %90.0
  Store int* %105, %101
  Ret
}

func unit @std.vec.Vec.resize<bool>(std.vec.Vec<bool>* %106) {
  %107 := GetPointer int %106.2
  %108 := Load int %107
  %109 := Mov int %108
  %110 := Mul int %109, 2
  %111 := Mov int %110
  %112 := Eq int %111, 0
  branch %112, @26, @27
label @26:
  %113 := Mov int 1
  continue @27
label @27:
  %114 := Phi int @std.vec.Vec.resize<bool>:%111, @26:%113
  %115 := GetPointer int %106.2
  Store int %115, %114
  %116 := CallBuiltin bool* myte_alloc(%114)
  %117 := Mov bool* %116
  %118 := GetPointer bool* %106.0
  %119 := Load bool* %118
  %120 := CallBuiltin unit myte_copy(%117, %119, %109)
  %121 := GetPointer bool* %106.0
  Store bool* %121, %117
  Ret
}

func unit @test.testVecGet(std.vec.Vec<int>* %122, std.vec.Vec<bool>* %123) {
  %124 := Call int @std.vec.Vec.get<int>(%122, 7)
  %125 := Call bool @std.vec.Vec.get<bool>(%123, 7)
  Ret
}

func unit @test.testVecSet(std.vec.Vec<int>* %126, std.vec.Vec<bool>* %127) {
  %128 := Call unit @std.vec.Vec.set<int>(%126, 7, 8)
  %129 := Call unit @std.vec.Vec.set<bool>(%127, 7, true)
  Ret
}

func unit @test.testVecPush(std.vec.Vec<int>* %130, std.vec.Vec<bool>* %131) {
  %132 := Call unit @std.vec.Vec.push<int>(%130, 1)
  %133 := Call unit @std.vec.Vec.push<bool>(%131, true)
  Ret
}

func int @test.main() {
  Ret 0
}