test/parser/ast/access/basic.myte
{
  node: Module,
  loc: 1:0-6:1,
  name: {
    node: ScopedIdentifier,
    loc: 1:7-1:11,
    scopes: [],
    name: {
      node: Identifier,
      loc: 1:7-1:11,
      name: "Test",
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-6:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-6:1,
        statements: [
          {
            node: ExpressionStatement,
            loc: 4:2-4:6,
            expression: {
              node: Access,
              loc: 4:2-4:5,
              left: {
                node: Identifier,
                loc: 4:2-4:3,
                name: "a",
              },
              right: {
                node: Identifier,
                loc: 4:4-4:5,
                name: "b",
              },
            },
          },
          {
            node: ExpressionStatement,
            loc: 5:2-5:8,
            expression: {
              node: Access,
              loc: 5:2-5:7,
              left: {
                node: Access,
                loc: 5:2-5:5,
                left: {
                  node: Identifier,
                  loc: 5:2-5:3,
                  name: "a",
                },
                right: {
                  node: Identifier,
                  loc: 5:4-5:5,
                  name: "b",
                },
              },
              right: {
                node: Identifier,
                loc: 5:6-5:7,
                name: "c",
              },
            },
          },
        ],
      },
      return: None,
    },
  ],
}