test/parser/ast/access/indexed_access.myte
{
  node: Module,
  loc: 1:0-6:1,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-6:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-6:1,
        statements: [
          {
            node: VariableDeclaration,
            loc: 4:2-4:15,
            kind: Mutable,
            pattern: {
              node: ScopedIdentifier,
              loc: 4:6-4:7,
              scopes: [],
              name: {
                node: Identifier,
                loc: 4:6-4:7,
                name: "a",
              },
            },
            init: {
              node: IndexedAccess,
              loc: 4:10-4:14,
              target: {
                node: IntLiteral,
                loc: 4:10-4:11,
                raw: "1",
              },
              index: {
                node: IntLiteral,
                loc: 4:12-4:13,
                raw: "2",
              },
            },
            annot: None,
          },
          {
            node: VariableDeclaration,
            loc: 5:2-5:25,
            kind: Mutable,
            pattern: {
              node: ScopedIdentifier,
              loc: 5:6-5:7,
              scopes: [],
              name: {
                node: Identifier,
                loc: 5:6-5:7,
                name: "b",
              },
            },
            init: {
              node: IndexedAccess,
              loc: 5:10-5:24,
              target: {
                node: IndexedAccess,
                loc: 5:10-5:21,
                target: {
                  node: IndexedAccess,
                  loc: 5:10-5:18,
                  target: {
                    node: Identifier,
                    loc: 5:10-5:11,
                    name: "a",
                  },
                  index: {
                    node: BinaryOperation,
                    loc: 5:12-5:17,
                    op: Add,
                    left: {
                      node: IntLiteral,
                      loc: 5:12-5:13,
                      raw: "2",
                    },
                    right: {
                      node: IntLiteral,
                      loc: 5:16-5:17,
                      raw: "4",
                    },
                  },
                },
                index: {
                  node: IntLiteral,
                  loc: 5:19-5:20,
                  raw: "3",
                },
              },
              index: {
                node: IntLiteral,
                loc: 5:22-5:23,
                raw: "5",
              },
            },
            annot: None,
          },
        ],
      },
      return: None,
      type_params: [],
      builtin: false,
      static: false,
      override: false,
    },
  ],
}