test/parser/expression/unit.myte
{
  node: Module,
  loc: 1:0-6:1,
  name: {
    node: ModuleName,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-6:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-6:1,
        statements: [
          {
            node: ExpressionStatement,
            loc: 4:2-4:5,
            expression: {
              node: Unit,
              loc: 4:2-4:4,
            },
          },
          {
            node: ExpressionStatement,
            loc: 5:2-5:9,
            expression: {
              node: Unit,
              loc: 5:4-5:6,
            },
          },
        ],
      },
      return: None,
      type_params: [],
      builtin: false,
      static: false,
      override: false,
    },
  ],
}