test/parser/ast/type_declaration/alias.myte
{
  node: Module,
  loc: 1:0-11:28,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: TypeDeclaration,
      loc: 3:0-3:20,
      name: {
        node: Identifier,
        loc: 3:11-3:13,
        name: "t1",
      },
      type_params: [],
      builtin: false,
      alias: {
        node: IdentifierType,
        loc: 3:16-3:20,
        name: {
          node: ScopedIdentifier,
          loc: 3:16-3:20,
          scopes: [],
          name: {
            node: Identifier,
            loc: 3:16-3:20,
            name: "Unit",
          },
        },
        type_params: [],
      },
    },
    {
      node: TypeDeclaration,
      loc: 5:0-5:19,
      name: {
        node: Identifier,
        loc: 5:11-5:13,
        name: "t2",
      },
      type_params: [],
      builtin: false,
      alias: {
        node: IdentifierType,
        loc: 5:16-5:19,
        name: {
          node: ScopedIdentifier,
          loc: 5:16-5:19,
          scopes: [],
          name: {
            node: Identifier,
            loc: 5:16-5:19,
            name: "Int",
          },
        },
        type_params: [],
      },
    },
    {
      node: TypeDeclaration,
      loc: 7:0-7:38,
      name: {
        node: Identifier,
        loc: 7:11-7:13,
        name: "t3",
      },
      type_params: [],
      builtin: false,
      alias: {
        node: FunctionType,
        loc: 7:16-7:38,
        params: [
          {
            node: IdentifierType,
            loc: 7:17-7:23,
            name: {
              node: ScopedIdentifier,
              loc: 7:17-7:23,
              scopes: [],
              name: {
                node: Identifier,
                loc: 7:17-7:23,
                name: "String",
              },
            },
            type_params: [],
          },
          {
            node: IdentifierType,
            loc: 7:25-7:29,
            name: {
              node: ScopedIdentifier,
              loc: 7:25-7:29,
              scopes: [],
              name: {
                node: Identifier,
                loc: 7:25-7:29,
                name: "Bool",
              },
            },
            type_params: [],
          },
        ],
        return: {
          node: IdentifierType,
          loc: 7:34-7:38,
          name: {
            node: ScopedIdentifier,
            loc: 7:34-7:38,
            scopes: [],
            name: {
              node: Identifier,
              loc: 7:34-7:38,
              name: "Unit",
            },
          },
          type_params: [],
        },
      },
    },
    {
      node: TypeDeclaration,
      loc: 9:0-9:23,
      name: {
        node: Identifier,
        loc: 9:11-9:13,
        name: "t4",
      },
      type_params: [
        {
          node: TypeParameter,
          loc: 9:14-9:15,
          name: {
            node: Identifier,
            loc: 9:14-9:15,
            name: "T",
          },
          bounds: [],
        },
      ],
      builtin: false,
      alias: {
        node: IdentifierType,
        loc: 9:19-9:23,
        name: {
          node: ScopedIdentifier,
          loc: 9:19-9:23,
          scopes: [],
          name: {
            node: Identifier,
            loc: 9:19-9:23,
            name: "Unit",
          },
        },
        type_params: [],
      },
    },
    {
      node: TypeDeclaration,
      loc: 11:0-11:28,
      name: {
        node: Identifier,
        loc: 11:11-11:13,
        name: "t5",
      },
      type_params: [
        {
          node: TypeParameter,
          loc: 11:14-11:15,
          name: {
            node: Identifier,
            loc: 11:14-11:15,
            name: "T",
          },
          bounds: [],
        },
        {
          node: TypeParameter,
          loc: 11:17-11:18,
          name: {
            node: Identifier,
            loc: 11:17-11:18,
            name: "U",
          },
          bounds: [],
        },
        {
          node: TypeParameter,
          loc: 11:20-11:21,
          name: {
            node: Identifier,
            loc: 11:20-11:21,
            name: "V",
          },
          bounds: [],
        },
      ],
      builtin: false,
      alias: {
        node: IdentifierType,
        loc: 11:25-11:28,
        name: {
          node: ScopedIdentifier,
          loc: 11:25-11:28,
          scopes: [],
          name: {
            node: Identifier,
            loc: 11:25-11:28,
            name: "Int",
          },
        },
        type_params: [],
      },
    },
  ],
}