test/parser/ast/type_declaration/record.myte
{
  node: Module,
  loc: 1:0-15:35,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: TypeDeclaration,
      loc: 3:0-3:20,
      name: {
        node: Identifier,
        loc: 3:5-3:7,
        name: "r1",
      },
      type_params: [],
      builtin: false,
      record: {
        node: RecordVariant,
        loc: 3:5-3:20,
        name: {
          node: Identifier,
          loc: 3:5-3:7,
          name: "r1",
        },
        fields: [
          {
            node: RecordVariantField,
            loc: 3:5-3:18,
            name: {
              node: Identifier,
              loc: 3:10-3:13,
              name: "foo",
            },
            type: {
              node: PrimitiveType,
              loc: 3:15-3:18,
              kind: Int,
            },
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 5:0-5:21,
      name: {
        node: Identifier,
        loc: 5:5-5:7,
        name: "r2",
      },
      type_params: [],
      builtin: false,
      record: {
        node: RecordVariant,
        loc: 5:5-5:21,
        name: {
          node: Identifier,
          loc: 5:5-5:7,
          name: "r2",
        },
        fields: [
          {
            node: RecordVariantField,
            loc: 5:5-5:18,
            name: {
              node: Identifier,
              loc: 5:10-5:13,
              name: "foo",
            },
            type: {
              node: PrimitiveType,
              loc: 5:15-5:18,
              kind: Int,
            },
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 7:0-7:44,
      name: {
        node: Identifier,
        loc: 7:5-7:7,
        name: "r3",
      },
      type_params: [],
      builtin: false,
      record: {
        node: RecordVariant,
        loc: 7:5-7:44,
        name: {
          node: Identifier,
          loc: 7:5-7:7,
          name: "r3",
        },
        fields: [
          {
            node: RecordVariantField,
            loc: 7:5-7:18,
            name: {
              node: Identifier,
              loc: 7:10-7:13,
              name: "foo",
            },
            type: {
              node: PrimitiveType,
              loc: 7:15-7:18,
              kind: Int,
            },
          },
          {
            node: RecordVariantField,
            loc: 7:5-7:29,
            name: {
              node: Identifier,
              loc: 7:20-7:23,
              name: "bar",
            },
            type: {
              node: PrimitiveType,
              loc: 7:25-7:29,
              kind: Bool,
            },
          },
          {
            node: RecordVariantField,
            loc: 7:5-7:42,
            name: {
              node: Identifier,
              loc: 7:31-7:34,
              name: "baz",
            },
            type: {
              node: IdentifierType,
              loc: 7:36-7:42,
              name: {
                node: ScopedIdentifier,
                loc: 7:36-7:42,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 7:36-7:42,
                  name: "String",
                },
              },
              type_params: [],
            },
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 9:0-9:45,
      name: {
        node: Identifier,
        loc: 9:5-9:7,
        name: "r4",
      },
      type_params: [],
      builtin: false,
      record: {
        node: RecordVariant,
        loc: 9:5-9:45,
        name: {
          node: Identifier,
          loc: 9:5-9:7,
          name: "r4",
        },
        fields: [
          {
            node: RecordVariantField,
            loc: 9:5-9:18,
            name: {
              node: Identifier,
              loc: 9:10-9:13,
              name: "foo",
            },
            type: {
              node: PrimitiveType,
              loc: 9:15-9:18,
              kind: Int,
            },
          },
          {
            node: RecordVariantField,
            loc: 9:5-9:29,
            name: {
              node: Identifier,
              loc: 9:20-9:23,
              name: "bar",
            },
            type: {
              node: PrimitiveType,
              loc: 9:25-9:29,
              kind: Bool,
            },
          },
          {
            node: RecordVariantField,
            loc: 9:5-9:42,
            name: {
              node: Identifier,
              loc: 9:31-9:34,
              name: "baz",
            },
            type: {
              node: IdentifierType,
              loc: 9:36-9:42,
              name: {
                node: ScopedIdentifier,
                loc: 9:36-9:42,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 9:36-9:42,
                  name: "String",
                },
              },
              type_params: [],
            },
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 11:0-11:74,
      name: {
        node: Identifier,
        loc: 11:5-11:7,
        name: "r5",
      },
      type_params: [],
      builtin: false,
      record: {
        node: RecordVariant,
        loc: 11:5-11:74,
        name: {
          node: Identifier,
          loc: 11:5-11:7,
          name: "r5",
        },
        fields: [
          {
            node: RecordVariantField,
            loc: 11:5-11:22,
            name: {
              node: Identifier,
              loc: 11:10-11:13,
              name: "foo",
            },
            type: {
              node: PrimitiveType,
              loc: 11:17-11:20,
              kind: Int,
            },
          },
          {
            node: RecordVariantField,
            loc: 11:5-11:51,
            name: {
              node: Identifier,
              loc: 11:24-11:27,
              name: "bar",
            },
            type: {
              node: FunctionType,
              loc: 11:29-11:51,
              params: [
                {
                  node: PrimitiveType,
                  loc: 11:30-11:34,
                  kind: Bool,
                },
                {
                  node: IdentifierType,
                  loc: 11:36-11:42,
                  name: {
                    node: ScopedIdentifier,
                    loc: 11:36-11:42,
                    scopes: [],
                    name: {
                      node: Identifier,
                      loc: 11:36-11:42,
                      name: "String",
                    },
                  },
                  type_params: [],
                },
              ],
              return: {
                node: PrimitiveType,
                loc: 11:47-11:51,
                kind: Unit,
              },
            },
          },
          {
            node: RecordVariantField,
            loc: 11:5-11:72,
            name: {
              node: Identifier,
              loc: 11:53-11:56,
              name: "baz",
            },
            type: {
              node: TupleType,
              loc: 11:58-11:72,
              elements: [
                {
                  node: IdentifierType,
                  loc: 11:59-11:65,
                  name: {
                    node: ScopedIdentifier,
                    loc: 11:59-11:65,
                    scopes: [],
                    name: {
                      node: Identifier,
                      loc: 11:59-11:65,
                      name: "String",
                    },
                  },
                  type_params: [],
                },
                {
                  node: PrimitiveType,
                  loc: 11:67-11:71,
                  kind: Unit,
                },
              ],
            },
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 13:0-13:21,
      name: {
        node: Identifier,
        loc: 13:5-13:7,
        name: "t6",
      },
      type_params: [
        {
          node: TypeParameter,
          loc: 13:8-13:9,
          name: {
            node: Identifier,
            loc: 13:8-13:9,
            name: "T",
          },
        },
      ],
      builtin: false,
      record: {
        node: RecordVariant,
        loc: 13:5-13:21,
        name: {
          node: Identifier,
          loc: 13:5-13:7,
          name: "t6",
        },
        fields: [
          {
            node: RecordVariantField,
            loc: 13:5-13:19,
            name: {
              node: Identifier,
              loc: 13:13-13:16,
              name: "foo",
            },
            type: {
              node: IdentifierType,
              loc: 13:18-13:19,
              name: {
                node: ScopedIdentifier,
                loc: 13:18-13:19,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 13:18-13:19,
                  name: "T",
                },
              },
              type_params: [],
            },
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 15:0-15:35,
      name: {
        node: Identifier,
        loc: 15:5-15:7,
        name: "t7",
      },
      type_params: [
        {
          node: TypeParameter,
          loc: 15:8-15:9,
          name: {
            node: Identifier,
            loc: 15:8-15:9,
            name: "T",
          },
        },
        {
          node: TypeParameter,
          loc: 15:11-15:12,
          name: {
            node: Identifier,
            loc: 15:11-15:12,
            name: "U",
          },
        },
        {
          node: TypeParameter,
          loc: 15:14-15:15,
          name: {
            node: Identifier,
            loc: 15:14-15:15,
            name: "V",
          },
        },
      ],
      builtin: false,
      record: {
        node: RecordVariant,
        loc: 15:5-15:35,
        name: {
          node: Identifier,
          loc: 15:5-15:7,
          name: "t7",
        },
        fields: [
          {
            node: RecordVariantField,
            loc: 15:5-15:33,
            name: {
              node: Identifier,
              loc: 15:19-15:22,
              name: "foo",
            },
            type: {
              node: TupleType,
              loc: 15:24-15:33,
              elements: [
                {
                  node: IdentifierType,
                  loc: 15:25-15:26,
                  name: {
                    node: ScopedIdentifier,
                    loc: 15:25-15:26,
                    scopes: [],
                    name: {
                      node: Identifier,
                      loc: 15:25-15:26,
                      name: "V",
                    },
                  },
                  type_params: [],
                },
                {
                  node: IdentifierType,
                  loc: 15:28-15:29,
                  name: {
                    node: ScopedIdentifier,
                    loc: 15:28-15:29,
                    scopes: [],
                    name: {
                      node: Identifier,
                      loc: 15:28-15:29,
                      name: "U",
                    },
                  },
                  type_params: [],
                },
                {
                  node: IdentifierType,
                  loc: 15:31-15:32,
                  name: {
                    node: ScopedIdentifier,
                    loc: 15:31-15:32,
                    scopes: [],
                    name: {
                      node: Identifier,
                      loc: 15:31-15:32,
                      name: "T",
                    },
                  },
                  type_params: [],
                },
              ],
            },
          },
        ],
      },
    },
  ],
}