test/parser/ast/type_declaration/tuple.myte
{
  node: Module,
  loc: 1:0-15:21,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: TypeDeclaration,
      loc: 3:0-3:12,
      name: {
        node: Identifier,
        loc: 3:5-3:7,
        name: "t1",
      },
      type_params: [],
      builtin: false,
      tuple: {
        node: TupleVariant,
        loc: 3:5-3:12,
        name: {
          node: Identifier,
          loc: 3:5-3:7,
          name: "t1",
        },
        elements: [
          {
            node: PrimitiveType,
            loc: 3:8-3:11,
            kind: Int,
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 5:0-5:16,
      name: {
        node: Identifier,
        loc: 5:5-5:7,
        name: "t2",
      },
      type_params: [],
      builtin: false,
      tuple: {
        node: TupleVariant,
        loc: 5:5-5:16,
        name: {
          node: Identifier,
          loc: 5:5-5:7,
          name: "t2",
        },
        elements: [
          {
            node: PrimitiveType,
            loc: 5:10-5:13,
            kind: Int,
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 7:0-7:26,
      name: {
        node: Identifier,
        loc: 7:5-7:7,
        name: "t3",
      },
      type_params: [],
      builtin: false,
      tuple: {
        node: TupleVariant,
        loc: 7:5-7:26,
        name: {
          node: Identifier,
          loc: 7:5-7:7,
          name: "t3",
        },
        elements: [
          {
            node: PrimitiveType,
            loc: 7:8-7:11,
            kind: Int,
          },
          {
            node: PrimitiveType,
            loc: 7:13-7:17,
            kind: Bool,
          },
          {
            node: IdentifierType,
            loc: 7:19-7:25,
            name: {
              node: ScopedIdentifier,
              loc: 7:19-7:25,
              scopes: [],
              name: {
                node: Identifier,
                loc: 7:19-7:25,
                name: "String",
              },
            },
            type_params: [],
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 9:0-9:27,
      name: {
        node: Identifier,
        loc: 9:5-9:7,
        name: "t4",
      },
      type_params: [],
      builtin: false,
      tuple: {
        node: TupleVariant,
        loc: 9:5-9:27,
        name: {
          node: Identifier,
          loc: 9:5-9:7,
          name: "t4",
        },
        elements: [
          {
            node: PrimitiveType,
            loc: 9:8-9:11,
            kind: Int,
          },
          {
            node: PrimitiveType,
            loc: 9:13-9:17,
            kind: Bool,
          },
          {
            node: IdentifierType,
            loc: 9:19-9:25,
            name: {
              node: ScopedIdentifier,
              loc: 9:19-9:25,
              scopes: [],
              name: {
                node: Identifier,
                loc: 9:19-9:25,
                name: "String",
              },
            },
            type_params: [],
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 11:0-11:28,
      name: {
        node: Identifier,
        loc: 11:5-11:7,
        name: "t5",
      },
      type_params: [],
      builtin: false,
      tuple: {
        node: TupleVariant,
        loc: 11:5-11:28,
        name: {
          node: Identifier,
          loc: 11:5-11:7,
          name: "t5",
        },
        elements: [
          {
            node: TupleType,
            loc: 11:8-11:19,
            elements: [
              {
                node: PrimitiveType,
                loc: 11:9-11:12,
                kind: Int,
              },
              {
                node: PrimitiveType,
                loc: 11:14-11:18,
                kind: Bool,
              },
            ],
          },
          {
            node: IdentifierType,
            loc: 11:21-11:27,
            name: {
              node: ScopedIdentifier,
              loc: 11:21-11:27,
              scopes: [],
              name: {
                node: Identifier,
                loc: 11:21-11:27,
                name: "String",
              },
            },
            type_params: [],
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 13:0-13:16,
      name: {
        node: Identifier,
        loc: 13:5-13:7,
        name: "t6",
      },
      type_params: [
        {
          node: TypeParameter,
          loc: 13:8-13:9,
          name: {
            node: Identifier,
            loc: 13:8-13:9,
            name: "T",
          },
        },
      ],
      builtin: false,
      tuple: {
        node: TupleVariant,
        loc: 13:5-13:16,
        name: {
          node: Identifier,
          loc: 13:5-13:7,
          name: "t6",
        },
        elements: [
          {
            node: PrimitiveType,
            loc: 13:11-13:15,
            kind: Unit,
          },
        ],
      },
    },
    {
      node: TypeDeclaration,
      loc: 15:0-15:21,
      name: {
        node: Identifier,
        loc: 15:5-15:7,
        name: "t7",
      },
      type_params: [
        {
          node: TypeParameter,
          loc: 15:8-15:9,
          name: {
            node: Identifier,
            loc: 15:8-15:9,
            name: "T",
          },
        },
        {
          node: TypeParameter,
          loc: 15:11-15:12,
          name: {
            node: Identifier,
            loc: 15:11-15:12,
            name: "U",
          },
        },
        {
          node: TypeParameter,
          loc: 15:14-15:15,
          name: {
            node: Identifier,
            loc: 15:14-15:15,
            name: "V",
          },
        },
      ],
      builtin: false,
      tuple: {
        node: TupleVariant,
        loc: 15:5-15:21,
        name: {
          node: Identifier,
          loc: 15:5-15:7,
          name: "t7",
        },
        elements: [
          {
            node: PrimitiveType,
            loc: 15:17-15:20,
            kind: Int,
          },
        ],
      },
    },
  ],
}