  .global _main

  .text
test.callerSavedRegistersDoubleSavedAcrossFunctionCalls:
  subq $40, %rsp
  movq %xmm0, (%rsp)
  movq %xmm1, 8(%rsp)
  movq %xmm2, 16(%rsp)
  movq %xmm3, 24(%rsp)
  movq %xmm4, 32(%rsp)
  movl $3, %edi
  call test.use$Int$
  movq 8(%rsp), %xmm1
  addsd (%rsp), %xmm1
  movq 16(%rsp), %xmm0
  addsd %xmm1, %xmm0
  movq 24(%rsp), %xmm1
  addsd %xmm0, %xmm1
  movq 32(%rsp), %xmm0
  addsd %xmm1, %xmm0
  addq $40, %rsp
  ret
test.callerSavedRegistersIntSavedAcrossFunctionCalls:
  push %rbx
  push %r12
  push %r13
  push %r14
  push %r15
  movl %edi, %r15d
  movl %esi, %r14d
  movl %edx, %r13d
  movl %ecx, %r12d
  movl %r8d, %ebx
  movl $3, %edi
  call test.use$Int$
  addl %r15d, %r14d
  addl %r14d, %r13d
  addl %r13d, %r12d
  movl %ebx, %eax
  addl %r12d, %eax
  pop %r15
  pop %r14
  pop %r13
  pop %r12
  pop %rbx
  ret
test.callerSavedRegistersSavedAcrossFunctionCallsWithSpills:
  push %rbx
  push %r12
  push %r13
  push %r14
  push %r15
  subq $32, %rsp
  movl %edi, %r14d
  movl %esi, (%rsp)
  movl %edx, 8(%rsp)
  movl %ecx, 16(%rsp)
  movl %r8d, 24(%rsp)
  movl %r9d, %r15d
  cmpl $1, %r14d
  jne .L0
  movl $101, %r13d
  movl $102, %r12d
  movl $103, %ebx
  jmp .L1
.L0:
  movl $1, %r13d
  movl $2, %r12d
  movl $3, %ebx
.L1:
  movl $3, %edi
  call test.use$Int$
  addl %r13d, %r12d
  addl %r12d, %ebx
  addl %ebx, %r14d
  movl (%rsp), %eax
  addl %r14d, %eax
  movl 8(%rsp), %ebx
  addl %eax, %ebx
  movl 16(%rsp), %eax
  addl %ebx, %eax
  movl 24(%rsp), %ebx
  addl %eax, %ebx
  movl %r15d, %eax
  addl %ebx, %eax
  addq $32, %rsp
  pop %r15
  pop %r14
  pop %r13
  pop %r12
  pop %rbx
  ret
_main:
  movl $0, %eax
  ret
test.testDefaultToCalleeSaveRegistersIfAcrossFunctionCall:
  push %rbx
  push %r12
  testb %dil, %dil
  je .L2
  movl $101, %r12d
  movl $102, %ebx
  jmp .L3
.L2:
  movl $1, %r12d
  movl $2, %ebx
.L3:
  movl $3, %edi
  call test.use$Int$
  movl %r12d, %edi
  call test.use$Int$
  movl %ebx, %edi
  call test.use$Int$
  pop %r12
  pop %rbx
  ret
test.testDefaultToCallerSaveRegisters:
  testb %sil, %sil
  je .L4
  movl $101, %r11d
  movl $102, %r10d
  movl $103, %r9d
  movl $104, %r8d
  movl $105, %edi
  movl $106, %esi
  movl $107, %edx
  movl $108, %ecx
  movl $109, %eax
  jmp .L5
.L4:
  movl $1, %r11d
  movl $2, %r10d
  movl $3, %r9d
  movl $4, %r8d
  movl $5, %edi
  movl $6, %esi
  movl $7, %edx
  movl $8, %ecx
  movl $9, %eax
.L5:
  addl %r11d, %r10d
  addl %r10d, %r9d
  addl %r9d, %r8d
  addl %r8d, %edi
  addl %edi, %esi
  addl %esi, %edx
  addl %edx, %ecx
  addl %ecx, %eax
  ret
test.use$Int$:
  movl %edi, %eax
  ret