  .global _main

  .data
  .balign 8
_float$9.:
  .quad 4621256167635550208
_float$10.:
  .quad 4621819117588971520
_float$1.:
  .quad 4607182418800017408
_float$2.:
  .quad 4611686018427387904
_float$3.:
  .quad 4613937818241073152
_float$4.:
  .quad 4616189618054758400
_float$5.:
  .quad 4617315517961601024
_float$6.:
  .quad 4618441417868443648
_float$7.:
  .quad 4619567317775286272
_float$8.:
  .quad 4620693217682128896

  .text
test.longArgs:
  addq 8(%rsp), %rdi
  movq %rdi, %rax
  ret
_main:
  movl $0, %eax
  ret
test.passedInRegistersAndStackFloat:
  subq $16, %rsp
  movq _float$9.(%rip), %xmm0
  movq %xmm0, (%rsp)
  movq _float$10.(%rip), %xmm0
  movq %xmm0, 8(%rsp)
  movq _float$1.(%rip), %xmm0
  movq _float$2.(%rip), %xmm1
  movq _float$3.(%rip), %xmm2
  movq _float$4.(%rip), %xmm3
  movq _float$5.(%rip), %xmm4
  movq _float$6.(%rip), %xmm5
  movq _float$7.(%rip), %xmm6
  movq _float$8.(%rip), %xmm7
  call test.testTenArgFunctionFloat
  addq $16, %rsp
  ret
test.passedInRegistersAndStackInt:
  subq $24, %rsp
  movl $7, (%rsp)
  movl $8, 8(%rsp)
  movl $9, 16(%rsp)
  movl $1, %edi
  movl $2, %esi
  movl $3, %edx
  movl $4, %ecx
  movl $5, %r8d
  movl $6, %r9d
  call test.testNineArgFunction
  addq $24, %rsp
  ret
test.testEightArgFunction:
  addl %edi, %esi
  addl %esi, %edx
  addl %edx, %ecx
  addl %ecx, %r8d
  addl %r8d, %r9d
  addl 8(%rsp), %r9d
  addl 16(%rsp), %r9d
  movl %r9d, %eax
  ret
test.testEightArgFunctionFloat:
  addsd %xmm0, %xmm1
  addsd %xmm1, %xmm2
  addsd %xmm2, %xmm3
  addsd %xmm3, %xmm4
  addsd %xmm4, %xmm5
  addsd %xmm5, %xmm6
  addsd %xmm6, %xmm7
  movq %xmm7, %xmm0
  ret
test.testFiveArgFunction:
  addl %edi, %esi
  addl %esi, %edx
  addl %edx, %ecx
  addl %ecx, %r8d
  movl %r8d, %eax
  ret
test.testFiveArgFunctionFloat:
  addsd %xmm0, %xmm1
  addsd %xmm1, %xmm2
  addsd %xmm2, %xmm3
  addsd %xmm3, %xmm4
  movq %xmm4, %xmm0
  ret
test.testFourArgFunction:
  addl %edi, %esi
  addl %esi, %edx
  addl %edx, %ecx
  movl %ecx, %eax
  ret
test.testFourArgFunctionFloat:
  addsd %xmm0, %xmm1
  addsd %xmm1, %xmm2
  addsd %xmm2, %xmm3
  movq %xmm3, %xmm0
  ret
test.testFunctionStackParamsOffsetByPushedCalleeSavedRegisters:
  push %rbx
  movl %edi, %ebx
  addsd 24(%rsp), %xmm0
  call test.use$Double$
  addl 16(%rsp), %ebx
  movl %ebx, %eax
  pop %rbx
  ret
test.testFunctionStackParamsOffsetByStackFrameAndPushedCalleeSavedRegisters:
  push %rbx
  push %r12
  push %r13
  push %r14
  push %r15
  subq $8, %rsp
  movl %edi, (%rsp)
  movl %esi, %r15d
  movl %edx, %r14d
  movl %ecx, %r13d
  movl %r8d, %r12d
  movl %r9d, %ebx
  movl $3, %edi
  call test.use$Int$
  addl (%rsp), %r15d
  addl %r15d, %r14d
  addl %r14d, %r13d
  addl %r13d, %r12d
  movl %ebx, %eax
  addl %r12d, %eax
  addl 56(%rsp), %eax
  addl 64(%rsp), %eax
  addq $8, %rsp
  pop %r15
  pop %r14
  pop %r13
  pop %r12
  pop %rbx
  ret
test.testLongArgs:
  subq $8, %rsp
  movq $7, (%rsp)
  movq $1, %rdi
  movl $2, %esi
  movl $3, %edx
  movl $4, %ecx
  movl $5, %r8d
  movl $6, %r9d
  call test.longArgs
  movq $2147483648, %rax
  movq %rax, (%rsp)
  movq $2147483648, %rdi
  movl $2, %esi
  movl $3, %edx
  movl $4, %ecx
  movl $5, %r8d
  movl $6, %r9d
  call test.longArgs
  addq $8, %rsp
  ret
test.testMixedArgs:
  push %rbx
  addsd %xmm0, %xmm1
  addsd %xmm1, %xmm2
  addsd %xmm2, %xmm3
  addsd %xmm3, %xmm4
  addsd %xmm4, %xmm5
  addsd %xmm5, %xmm6
  addsd %xmm6, %xmm7
  addsd 24(%rsp), %xmm7
  addsd 32(%rsp), %xmm7
  addl %edi, %esi
  addl %esi, %edx
  addl %edx, %ecx
  addl %ecx, %r8d
  addl %r8d, %r9d
  addl 16(%rsp), %r9d
  movl %r9d, %ebx
  addl 40(%rsp), %ebx
  movq %xmm7, %xmm0
  call test.use$Double$
  movl %ebx, %edi
  call test.use$Int$
  pop %rbx
  ret
test.testNineArgFunction:
  addl %edi, %esi
  addl %esi, %edx
  addl %edx, %ecx
  addl %ecx, %r8d
  addl %r8d, %r9d
  addl 8(%rsp), %r9d
  addl 16(%rsp), %r9d
  addl 24(%rsp), %r9d
  movl %r9d, %eax
  ret
test.testNineArgFunctionFloat:
  addsd %xmm0, %xmm1
  addsd %xmm1, %xmm2
  addsd %xmm2, %xmm3
  addsd %xmm3, %xmm4
  addsd %xmm4, %xmm5
  addsd %xmm5, %xmm6
  addsd %xmm6, %xmm7
  addsd 8(%rsp), %xmm7
  movq %xmm7, %xmm0
  ret
test.testOneArgFunction:
  movl %edi, %eax
  ret
test.testOneArgFunctionFloat:
  ret
test.testSevenArgFunction:
  addl %edi, %esi
  addl %esi, %edx
  addl %edx, %ecx
  addl %ecx, %r8d
  addl %r8d, %r9d
  addl 8(%rsp), %r9d
  movl %r9d, %eax
  ret
test.testSevenArgFunctionFloat:
  addsd %xmm0, %xmm1
  addsd %xmm1, %xmm2
  addsd %xmm2, %xmm3
  addsd %xmm3, %xmm4
  addsd %xmm4, %xmm5
  addsd %xmm5, %xmm6
  movq %xmm6, %xmm0
  ret
test.testSixArgFunction:
  addl %edi, %esi
  addl %esi, %edx
  addl %edx, %ecx
  addl %ecx, %r8d
  addl %r8d, %r9d
  movl %r9d, %eax
  ret
test.testSixArgFunctionFloat:
  addsd %xmm0, %xmm1
  addsd %xmm1, %xmm2
  addsd %xmm2, %xmm3
  addsd %xmm3, %xmm4
  addsd %xmm4, %xmm5
  movq %xmm5, %xmm0
  ret
test.testTenArgFunctionFloat:
  addsd %xmm0, %xmm1
  addsd %xmm1, %xmm2
  addsd %xmm2, %xmm3
  addsd %xmm3, %xmm4
  addsd %xmm4, %xmm5
  addsd %xmm5, %xmm6
  addsd %xmm6, %xmm7
  addsd 8(%rsp), %xmm7
  addsd 16(%rsp), %xmm7
  movq %xmm7, %xmm0
  ret
test.testThreeArgFunction:
  addl %edi, %esi
  addl %esi, %edx
  movl %edx, %eax
  ret
test.testThreeArgFunctionFloat:
  addsd %xmm0, %xmm1
  addsd %xmm1, %xmm2
  movq %xmm2, %xmm0
  ret
test.testTwoArgFunction:
  addl %edi, %esi
  movl %esi, %eax
  ret
test.testTwoArgFunctionFloat:
  addsd %xmm0, %xmm1
  movq %xmm1, %xmm0
  ret
test.use$Double$:
  ret
test.use$Int$:
  movl %edi, %eax
  ret
test.zeroArgFunction:
  movl $1, %eax
  ret