  .global _main

  .data
  .balign 8
_float$1.:
  .quad 4607182418800017408

  .text
_main:
  movl $0, %eax
  ret
test.testNestedReturnNoReturnRegisterMove:
  call test.testReturnsInMain
  ret
test.testNestedReturnNoReturnRegisterMoveFloat:
  call test.testReturnsDouble
  ret
test.testReturnRegisterClobberAcrossCall:
  push %rbx
  call test.testReturnsInMain
  movl %eax, %ebx
  call test.testReturnsInMain
  addl %ebx, %eax
  pop %rbx
  ret
test.testReturnRegisterClobberAcrossCallFloat:
  subq $8, %rsp
  call test.testReturnsDouble
  movq %xmm0, (%rsp)
  call test.testReturnsDouble
  addsd (%rsp), %xmm0
  addq $8, %rsp
  ret
test.testReturnsDouble:
  movq _float$1.(%rip), %xmm0
  ret
test.testReturnsInMain:
  movl $1, %eax
  ret
test.testReturnsInMain2:
  movl %edi, %eax
  ret