test/parser/ast/interpolated_strings/basic.myte
{
  node: Module,
  loc: 1:0-25:1,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-25:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-25:1,
        statements: [
          {
            node: ExpressionStatement,
            loc: 5:2-5:8,
            expression: {
              node: InterpolatedString,
              loc: 5:2-5:7,
              parts: [
                {
                  node: StringLiteral,
                  loc: 5:2-5:7,
                  value: "foo",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 8:2-8:9,
            expression: {
              node: InterpolatedString,
              loc: 8:2-8:8,
              parts: [
                {
                  node: IntLiteral,
                  loc: 8:5-8:6,
                  raw: "1",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 9:2-9:12,
            expression: {
              node: InterpolatedString,
              loc: 9:2-9:11,
              parts: [
                {
                  node: StringLiteral,
                  loc: 9:2-9:8,
                  value: "foo",
                },
                {
                  node: IntLiteral,
                  loc: 9:8-9:9,
                  raw: "1",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 10:2-10:12,
            expression: {
              node: InterpolatedString,
              loc: 10:2-10:11,
              parts: [
                {
                  node: IntLiteral,
                  loc: 10:5-10:6,
                  raw: "1",
                },
                {
                  node: StringLiteral,
                  loc: 10:6-10:11,
                  value: "bar",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 11:2-11:15,
            expression: {
              node: InterpolatedString,
              loc: 11:2-11:14,
              parts: [
                {
                  node: StringLiteral,
                  loc: 11:2-11:8,
                  value: "foo",
                },
                {
                  node: IntLiteral,
                  loc: 11:8-11:9,
                  raw: "1",
                },
                {
                  node: StringLiteral,
                  loc: 11:9-11:14,
                  value: "bar",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 12:2-12:16,
            expression: {
              node: InterpolatedString,
              loc: 12:2-12:15,
              parts: [
                {
                  node: IntLiteral,
                  loc: 12:5-12:6,
                  raw: "1",
                },
                {
                  node: StringLiteral,
                  loc: 12:6-12:12,
                  value: "foo",
                },
                {
                  node: IntLiteral,
                  loc: 12:12-12:13,
                  raw: "2",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 15:2-15:23,
            expression: {
              node: InterpolatedString,
              loc: 15:2-15:22,
              parts: [
                {
                  node: StringLiteral,
                  loc: 15:2-15:8,
                  value: "foo",
                },
                {
                  node: IntLiteral,
                  loc: 15:8-15:9,
                  raw: "1",
                },
                {
                  node: IntLiteral,
                  loc: 15:12-15:13,
                  raw: "2",
                },
                {
                  node: IntLiteral,
                  loc: 15:16-15:17,
                  raw: "3",
                },
                {
                  node: StringLiteral,
                  loc: 15:17-15:22,
                  value: "bar",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 18:2-18:15,
            expression: {
              node: InterpolatedString,
              loc: 18:2-18:14,
              parts: [
                {
                  node: StringLiteral,
                  loc: 18:2-18:14,
                  value: "foo
   bar",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 21:3-21:34,
            expression: {
              node: InterpolatedString,
              loc: 21:3-21:33,
              parts: [
                {
                  node: StringLiteral,
                  loc: 21:3-21:9,
                  value: "foo",
                },
                {
                  node: BinaryOperation,
                  loc: 21:9-21:28,
                  op: Add,
                  left: {
                    node: IntLiteral,
                    loc: 21:9-21:10,
                    raw: "1",
                  },
                  right: {
                    node: BinaryOperation,
                    loc: 21:13-21:28,
                    op: Multiply,
                    left: {
                      node: IntLiteral,
                      loc: 21:13-21:14,
                      raw: "2",
                    },
                    right: {
                      node: Call,
                      loc: 21:17-21:28,
                      func: {
                        node: Identifier,
                        loc: 21:17-21:21,
                        name: "call",
                      },
                      args: [
                        {
                          node: BinaryOperation,
                          loc: 21:22-21:27,
                          op: Add,
                          left: {
                            node: Identifier,
                            loc: 21:22-21:23,
                            name: "x",
                          },
                          right: {
                            node: IntLiteral,
                            loc: 21:26-21:27,
                            raw: "1",
                          },
                        },
                      ],
                    },
                  },
                },
                {
                  node: StringLiteral,
                  loc: 21:28-21:33,
                  value: "bar",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 24:3-24:65,
            expression: {
              node: InterpolatedString,
              loc: 24:3-24:64,
              parts: [
                {
                  node: StringLiteral,
                  loc: 24:3-24:10,
                  value: "foo1",
                },
                {
                  node: InterpolatedString,
                  loc: 24:10-24:37,
                  parts: [
                    {
                      node: StringLiteral,
                      loc: 24:10-24:17,
                      value: "foo2",
                    },
                    {
                      node: InterpolatedString,
                      loc: 24:17-24:31,
                      parts: [
                        {
                          node: StringLiteral,
                          loc: 24:17-24:24,
                          value: "foo3",
                        },
                        {
                          node: IntLiteral,
                          loc: 24:24-24:25,
                          raw: "1",
                        },
                        {
                          node: StringLiteral,
                          loc: 24:25-24:31,
                          value: "bar3",
                        },
                      ],
                    },
                    {
                      node: StringLiteral,
                      loc: 24:31-24:37,
                      value: "bar2",
                    },
                  ],
                },
                {
                  node: StringLiteral,
                  loc: 24:37-24:44,
                  value: "bar1",
                },
                {
                  node: InterpolatedString,
                  loc: 24:44-24:58,
                  parts: [
                    {
                      node: StringLiteral,
                      loc: 24:44-24:51,
                      value: "foo4",
                    },
                    {
                      node: IntLiteral,
                      loc: 24:51-24:52,
                      raw: "1",
                    },
                    {
                      node: StringLiteral,
                      loc: 24:52-24:58,
                      value: "bar4",
                    },
                  ],
                },
                {
                  node: StringLiteral,
                  loc: 24:58-24:64,
                  value: "baz1",
                },
              ],
            },
          },
        ],
      },
      return: None,
      type_params: [],
      builtin: false,
      static: false,
      override: false,
    },
  ],
}