func void @test.use<Function>(fn %0) {
  Ret
}

func void @test.use<Int>(int %1) {
  Ret
}

global int @test.x = 1

func void @test.test1(int %2) {
  %3 := Load int @test.x
  %4 := Mul int 2, %2
  %5 := Add int %3, %4
  Ret
}

func void @test.test2() {
  %6 := Load int @test.x
  %7 := Mul int 4, 34
  Call void @test.use<Int>(%6)
  Call void @test.use<Int>(%7)
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.test1)
  Call void @test.use<Function>(@test.test2)
  Ret 0
}