test/parser/ast/unary_operation/basic.myte
{
  node: Program,
  loc: 1:0-7:1,
  toplevels: [
    {
      node: Function,
      loc: 1:0-7:1,
      name: {
        node: Identifier,
        loc: 1:4-1:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 1:11-7:1,
        statements: [
          {
            node: ExpressionStatement,
            loc: 2:2-2:5,
            expression: {
              node: UnaryOperation,
              loc: 2:2-2:4,
              op: Plus,
              operand: {
                node: IntLiteral,
                loc: 2:3-2:4,
                value: 1,
                raw: "1",
              },
            },
          },
          {
            node: ExpressionStatement,
            loc: 3:2-3:5,
            expression: {
              node: UnaryOperation,
              loc: 3:2-3:4,
              op: Minus,
              operand: {
                node: IntLiteral,
                loc: 3:3-3:4,
                value: 1,
                raw: "1",
              },
            },
          },
          {
            node: ExpressionStatement,
            loc: 4:2-4:8,
            expression: {
              node: UnaryOperation,
              loc: 4:2-4:7,
              op: LogicalNot,
              operand: {
                node: BoolLiteral,
                loc: 4:3-4:7,
                value: true,
              },
            },
          },
          {
            node: ExpressionStatement,
            loc: 6:2-6:6,
            expression: {
              node: UnaryOperation,
              loc: 6:2-6:5,
              op: Plus,
              operand: {
                node: UnaryOperation,
                loc: 6:3-6:5,
                op: Minus,
                operand: {
                  node: IntLiteral,
                  loc: 6:4-6:5,
                  value: 1,
                  raw: "1",
                },
              },
            },
          },
        ],
      },
      return: None,
    },
  ],
}