test/parser/ast/unary_operation/basic.myte
{
  node: Program,
  loc: 1:0-5:4,
  statements: [
    {
      node: ExpressionStatement,
      loc: 1:0-1:3,
      expression: {
        node: UnaryOperation,
        loc: 1:0-1:2,
        op: Plus,
        operand: {
          node: IntLiteral,
          loc: 1:1-1:2,
          value: 1,
          raw: "1",
        },
      },
    },
    {
      node: ExpressionStatement,
      loc: 2:0-2:3,
      expression: {
        node: UnaryOperation,
        loc: 2:0-2:2,
        op: Minus,
        operand: {
          node: IntLiteral,
          loc: 2:1-2:2,
          value: 1,
          raw: "1",
        },
      },
    },
    {
      node: ExpressionStatement,
      loc: 3:0-3:6,
      expression: {
        node: UnaryOperation,
        loc: 3:0-3:5,
        op: LogicalNot,
        operand: {
          node: BoolLiteral,
          loc: 3:1-3:5,
          value: true,
        },
      },
    },
    {
      node: ExpressionStatement,
      loc: 5:0-5:4,
      expression: {
        node: UnaryOperation,
        loc: 5:0-5:3,
        op: Plus,
        operand: {
          node: UnaryOperation,
          loc: 5:1-5:3,
          op: Minus,
          operand: {
            node: IntLiteral,
            loc: 5:2-5:3,
            value: 1,
            raw: "1",
          },
        },
      },
    },
  ],
}