test/parser/attributes/basic.myte
{
  node: Module,
  loc: 1:0-26:12,
  name: {
    node: ModuleName,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-4:12,
      name: {
        node: Identifier,
        loc: 4:4-4:7,
        name: "foo",
      },
      params: [],
      body: {
        node: Block,
        loc: 4:10-4:12,
        statements: [],
      },
      return: None,
      type_params: [],
      attributes: [
        {
          node: Attribute,
          loc: 3:0-3:7,
          items: [
            {
              node: Identifier,
              loc: 3:2-3:6,
              name: "Attr",
            },
          ],
        },
      ],
      is_public: false,
      is_static: false,
      is_override: false,
    },
    {
      node: Function,
      loc: 6:0-9:12,
      name: {
        node: Identifier,
        loc: 9:4-9:7,
        name: "foo",
      },
      params: [],
      body: {
        node: Block,
        loc: 9:10-9:12,
        statements: [],
      },
      return: None,
      type_params: [],
      attributes: [
        {
          node: Attribute,
          loc: 6:0-6:8,
          items: [
            {
              node: Identifier,
              loc: 6:2-6:7,
              name: "First",
            },
          ],
        },
        {
          node: Attribute,
          loc: 7:0-7:9,
          items: [
            {
              node: Identifier,
              loc: 7:2-7:8,
              name: "Second",
            },
          ],
        },
        {
          node: Attribute,
          loc: 8:0-8:8,
          items: [
            {
              node: Identifier,
              loc: 8:2-8:7,
              name: "Third",
            },
          ],
        },
      ],
      is_public: false,
      is_static: false,
      is_override: false,
    },
    {
      node: Function,
      loc: 11:0-12:12,
      name: {
        node: Identifier,
        loc: 12:4-12:7,
        name: "foo",
      },
      params: [],
      body: {
        node: Block,
        loc: 12:10-12:12,
        statements: [],
      },
      return: None,
      type_params: [],
      attributes: [
        {
          node: Attribute,
          loc: 11:0-11:22,
          items: [
            {
              node: Identifier,
              loc: 11:2-11:7,
              name: "Attr1",
            },
            {
              node: Identifier,
              loc: 11:9-11:14,
              name: "Attr2",
            },
            {
              node: Identifier,
              loc: 11:16-11:21,
              name: "Attr3",
            },
          ],
        },
      ],
      is_public: false,
      is_static: false,
      is_override: false,
    },
    {
      node: Function,
      loc: 14:0-15:12,
      name: {
        node: Identifier,
        loc: 15:4-15:7,
        name: "foo",
      },
      params: [],
      body: {
        node: Block,
        loc: 15:10-15:12,
        statements: [],
      },
      return: None,
      type_params: [],
      attributes: [
        {
          node: Attribute,
          loc: 14:0-14:23,
          items: [
            {
              node: Identifier,
              loc: 14:2-14:7,
              name: "Attr1",
            },
            {
              node: Identifier,
              loc: 14:9-14:14,
              name: "Attr2",
            },
            {
              node: Identifier,
              loc: 14:16-14:21,
              name: "Attr3",
            },
          ],
        },
      ],
      is_public: false,
      is_static: false,
      is_override: false,
    },
    {
      node: VariableDeclaration,
      loc: 17:0-18:16,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 18:4-18:7,
        scopes: [],
        name: {
          node: Identifier,
          loc: 18:4-18:7,
          name: "foo",
        },
      },
      init: {
        node: IntLiteral,
        loc: 18:15-18:16,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 18:9-18:12,
        name: {
          node: ScopedIdentifier,
          loc: 18:9-18:12,
          scopes: [],
          name: {
            node: Identifier,
            loc: 18:9-18:12,
            name: "Int",
          },
        },
        type_args: [],
      },
      attributes: [
        {
          node: Attribute,
          loc: 17:0-17:7,
          items: [
            {
              node: Identifier,
              loc: 17:2-17:6,
              name: "Attr",
            },
          ],
        },
      ],
      is_public: false,
    },
    {
      node: TypeDeclaration,
      loc: 20:0-23:6,
      name: {
        node: Identifier,
        loc: 21:5-21:8,
        name: "Foo",
      },
      type_params: [],
      variants: [
        {
          node: Identifier,
          loc: 22:4-22:6,
          name: "E1",
        },
        {
          node: Identifier,
          loc: 23:4-23:6,
          name: "E2",
        },
      ],
      attributes: [
        {
          node: Attribute,
          loc: 20:0-20:7,
          items: [
            {
              node: Identifier,
              loc: 20:2-20:6,
              name: "Attr",
            },
          ],
        },
      ],
      is_public: false,
    },
    {
      node: TraitDeclaration,
      loc: 25:0-26:12,
      kind: Trait,
      name: {
        node: Identifier,
        loc: 26:6-26:9,
        name: "Foo",
      },
      type_params: [],
      implemented: [],
      methods: [],
      attributes: [
        {
          node: Attribute,
          loc: 25:0-25:7,
          items: [
            {
              node: Identifier,
              loc: 25:2-25:6,
              name: "Attr",
            },
          ],
        },
      ],
      is_public: false,
    },
  ],
}