type test.RecordType {bool, int}

func bool @test.RecordType.getBar(test.RecordType* %0) {
  %1 := GetPointer bool, test.RecordType* %0.0
  %2 := Load bool %1
  Ret %2
}

func test.RecordType* @test.RecordType.setBar(test.RecordType* %0, bool %1) {
  %2 := GetPointer bool, test.RecordType* %0.0
  Store bool %2, %1
  Ret %0
}

func bool @test.RecordType.setThenGet(test.RecordType* %0, bool %1) {
  %2 := Call test.RecordType* @test.RecordType.setBar(%0, %1)
  %3 := Call bool @test.RecordType.getBar(%0)
  Ret %3
}

func void @test.testRecordType(test.RecordType* %0) {
  %1 := Call bool @test.RecordType.setThenGet(%0, true)
  Ret
}

func bool @test.Trait.getBar<test.InheritsType>(test.InheritsType* %0) {
  Ret true
}

func test.InheritsType* @test.Trait.setBar<test.InheritsType>(test.InheritsType* %0, bool %1) {
  Ret %0
}

func bool @test.Trait.setThenGet<test.InheritsType>(test.InheritsType* %0, bool %1) {
  %2 := Call test.InheritsType* @test.Trait.setBar<test.InheritsType>(%0, %1)
  %3 := Call bool @test.Trait.getBar<test.InheritsType>(%0)
  Ret %3
}

type test.InheritsType {int}

func void @test.testInheritsType(test.InheritsType* %0) {
  %1 := Call bool @test.Trait.setThenGet<test.InheritsType>(%0, true)
  Ret
}

func void @test.use<Function>(fn %0) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.testRecordType)
  Call void @test.use<Function>(@test.testInheritsType)
  Ret 0
}