func void @test.ZeroSize.useThis(std._ZeroSize* %0) {
  Call void @test.use<test.ZeroSize>()
  Call void @test.use<Unit>()
  Ret
}

func void @test.ZeroSize.method1(std._ZeroSize* %0) {
  Call void @test.use<Unit>()
  Call void @test.use<test.ZeroSize>()
  Ret
}

func void @test.ZeroSize.method2(std._ZeroSize* %0, int %1) {
  Call void @test.use<Unit>()
  Ret
}

func void @test.useAll() {
  Call void @test.ZeroSize.useThis(@std._ZeroSize)
  Call void @test.ZeroSize.method1(@std._ZeroSize)
  Call void @test.ZeroSize.method2(@std._ZeroSize, 1)
  Ret
}

func void @test.use<Unit>() {
  Ret
}

func void @test.use<test.ZeroSize>() {
  Ret
}

func int @test.main() {
  Ret 0
}