type _ZeroSize {}

global _ZeroSize @_ZeroSize = uninitialized

func void @test.ZeroSize.useThis(_ZeroSize* %0) {
  Call void @test.use<test.ZeroSize>()
  Call void @test.use<Unit>()
  Ret
}

func void @test.ZeroSize.method1(_ZeroSize* %1) {
  Call void @test.use<Unit>()
  Call void @test.use<test.ZeroSize>()
  Ret
}

func void @test.ZeroSize.method2(_ZeroSize* %2, int %3) {
  Call void @test.use<Unit>()
  Ret
}

func void @test.useAll() {
  Call void @test.ZeroSize.useThis(@_ZeroSize)
  Call void @test.ZeroSize.method1(@_ZeroSize)
  Call void @test.ZeroSize.method2(@_ZeroSize, 1)
  Ret
}

func void @test.use<Function>(fn %4) {
  Ret
}

func void @test.use<Unit>() {
  Ret
}

func void @test.use<test.ZeroSize>() {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.useAll)
  Ret 0
}