func void @test.testWithoutAltern() {
  Call void @test.use<Int>(1)
  branch true, @0, @1
label @0:
  Call void @test.use<Int>(2)
  continue @1
label @1:
  Call void @test.use<Int>(3)
  Ret
}

func void @test.testWithAltern() {
  Call void @test.use<Int>(1)
  branch true, @0, @1
label @0:
  Call void @test.use<Int>(2)
  continue @2
label @1:
  Call void @test.use<Int>(3)
  continue @2
label @2:
  Call void @test.use<Int>(4)
  Ret
}

func void @test.nested() {
  Call void @test.use<Int>(1)
  branch true, @0, @4
label @0:
  Call void @test.use<Int>(2)
  branch false, @1, @2
label @1:
  Call void @test.use<Int>(3)
  continue @3
label @2:
  Call void @test.use<Int>(4)
  continue @3
label @3:
  Call void @test.use<Int>(5)
  continue @8
label @4:
  Call void @test.use<Int>(6)
  branch false, @5, @6
label @5:
  Call void @test.use<Int>(7)
  continue @7
label @6:
  Call void @test.use<Int>(8)
  continue @7
label @7:
  Call void @test.use<Int>(9)
  continue @8
label @8:
  Ret
}

func void @test.use<Int>(int %0) {
  Ret
}

func int @test.main() {
  Ret 0
}