func unit @test.use(int %0) {
  Ret
}

func unit @test.testWithoutAltern() {
  %1 := Call unit @test.use(1)
  branch true, @0, @1
label @0:
  %2 := Call unit @test.use(2)
  continue @1
label @1:
  %3 := Call unit @test.use(3)
  Ret
}

func unit @test.testWithAltern() {
  %4 := Call unit @test.use(1)
  branch true, @2, @3
label @2:
  %5 := Call unit @test.use(2)
  continue @4
label @3:
  %6 := Call unit @test.use(3)
  continue @4
label @4:
  %7 := Call unit @test.use(4)
  Ret
}

func unit @test.nested() {
  %8 := Call unit @test.use(1)
  branch true, @5, @9
label @5:
  %9 := Call unit @test.use(2)
  branch false, @6, @7
label @6:
  %10 := Call unit @test.use(3)
  continue @8
label @7:
  %11 := Call unit @test.use(4)
  continue @8
label @8:
  %12 := Call unit @test.use(5)
  continue @13
label @9:
  %13 := Call unit @test.use(6)
  branch false, @10, @11
label @10:
  %14 := Call unit @test.use(7)
  continue @12
label @11:
  %15 := Call unit @test.use(8)
  continue @12
label @12:
  %16 := Call unit @test.use(9)
  continue @13
label @13:
  Ret
}

func int @test.main() {
  Ret 0
}