func unit @test.testWithoutAltern() {
  %0 := Call unit @test.use<int>(1)
  branch true, @0, @1
label @0:
  %1 := Call unit @test.use<int>(2)
  continue @1
label @1:
  %2 := Call unit @test.use<int>(3)
  Ret
}

func unit @test.testWithAltern() {
  %3 := Call unit @test.use<int>(1)
  branch true, @2, @3
label @2:
  %4 := Call unit @test.use<int>(2)
  continue @4
label @3:
  %5 := Call unit @test.use<int>(3)
  continue @4
label @4:
  %6 := Call unit @test.use<int>(4)
  Ret
}

func unit @test.nested() {
  %7 := Call unit @test.use<int>(1)
  branch true, @5, @9
label @5:
  %8 := Call unit @test.use<int>(2)
  branch false, @6, @7
label @6:
  %9 := Call unit @test.use<int>(3)
  continue @8
label @7:
  %10 := Call unit @test.use<int>(4)
  continue @8
label @8:
  %11 := Call unit @test.use<int>(5)
  continue @13
label @9:
  %12 := Call unit @test.use<int>(6)
  branch false, @10, @11
label @10:
  %13 := Call unit @test.use<int>(7)
  continue @12
label @11:
  %14 := Call unit @test.use<int>(8)
  continue @12
label @12:
  %15 := Call unit @test.use<int>(9)
  continue @13
label @13:
  Ret
}

func unit @test.use<fn>(fn %16) {
  Ret
}

func unit @test.use<int>(int %17) {
  Ret
}

func int @test.main() {
  %18 := Call unit @test.use<fn>(@test.testWithoutAltern)
  %19 := Call unit @test.use<fn>(@test.testWithAltern)
  %20 := Call unit @test.use<fn>(@test.nested)
  Ret 0
}