func void @test.test1() {
  Call void @test.use<Int>(1)
  Ret
}

func int @test.test2() {
  Ret 99
}

func void @test.returnPreventsContinue() {
  branch true, @0, @1
label @0:
  Ret
label @1:
  branch true, @2, @3
label @2:
  Ret
label @3:
  Ret
}

func void @test.use<Function>(fn %0) {
  Ret
}

func void @test.use<Int>(int %0) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.test1)
  Call void @test.use<Function>(@test.test2)
  Call void @test.use<Function>(@test.returnPreventsContinue)
  Ret 0
}