func unit @test.test1() {
  %0 := Call unit @test.use<int>(1)
  Ret
}

func int @test.test2() {
  Ret 99
}

func unit @test.returnPreventsContinue() {
  branch true, @0, @1
label @0:
  Ret
label @1:
  branch true, @2, @3
label @2:
  Ret
label @3:
  Ret
}

func unit @test.use<fn>(fn %1) {
  Ret
}

func unit @test.use<int>(int %2) {
  Ret
}

func int @test.main() {
  %3 := Call unit @test.use<fn>(@test.test1)
  %4 := Call unit @test.use<fn>(@test.test2)
  %5 := Call unit @test.use<fn>(@test.returnPreventsContinue)
  Ret 0
}