func int @test.main() {
  continue @0
label @0:
  branch true, @0, @1
label @1:
  branch true, @2, @3
label @2:
  %0 := Add int 1, 1
  continue @1
label @3:
  %1 := Not bool false
  branch %1, @4, @8
label @4:
  %2 := Add int 2, 2
  continue @5
label @5:
  %3 := Not bool true
  branch %3, @6, @7
label @6:
  %4 := Add int 3, 3
  continue @5
label @7:
  %5 := Add int 4, 4
  continue @3
label @8:
  Ret 0
}