func int @test.main() {
  %0 := Eq long 3, 3
  branch %0, @test.main, @0
label @0:
  %1 := Eq long 3, 3
  branch %1, @1, @2
label @1:
  %2 := Add int 1, 1
  continue @0
label @2:
  %3 := BitXor long, 1 2
  %4 := Eq long %3, 3
  branch %4, @3, @7
label @3:
  %5 := Add int 2, 2
  continue @4
label @4:
  %6 := BitXor long, 3 2
  %7 := Eq long %6, 3
  branch %7, @5, @6
label @5:
  %8 := Add int 3, 3
  continue @4
label @6:
  %9 := Add int 4, 4
  continue @2
label @7:
  Ret 0
}