type $tuple<test.Tuple1,Byte> {int, byte}

func int @test.testConstructor1(int %0) {
  Ret %0
}

func bool @test.testConstructor2() {
  Ret false
}

func int @test.testIndexing(int %0, int %1) {
  %2 := Add int %0, %1
  Ret %2
}

type test.Record {byte, $tuple<test.Tuple1,Byte>*}

func int @test.testNestedIndexing(test.Record* %0) {
  %1 := GetPointer $tuple<test.Tuple1,Byte>*, test.Record* %0.1
  %2 := Load $tuple<test.Tuple1,Byte>* %1
  %3 := GetPointer int, $tuple<test.Tuple1,Byte>* %2.0
  %4 := Load int %3
  %5 := Add int %4, 4
  Ret %5
}

func int @test.testGenerics(int %0, byte %1) {
  %2 := SExt byte %1 to int
  %3 := Add int %0, %2
  Ret %3
}

func int @test.main() {
  Ret 0
}