test/parser/ast/pattern/basic.myte
{
  node: Module,
  loc: 1:0-36:0,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: VariableDeclaration,
      loc: 4:0-4:9,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 4:4-4:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 4:4-4:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 4:8-4:9,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 7:0-7:9,
      kind: Immutable,
      pattern: {
        node: Wildcard,
        loc: 7:4-7:5,
      },
      init: {
        node: IntLiteral,
        loc: 7:8-7:9,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 8:0-8:14,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 8:4-8:10,
        name: None,
        elements: [
          {
            node: Wildcard,
            loc: 8:5-8:6,
          },
          {
            node: Wildcard,
            loc: 8:8-8:9,
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 8:13-8:14,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 11:0-11:14,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 11:4-11:10,
        name: None,
        elements: [
          {
            node: ScopedIdentifier,
            loc: 11:5-11:6,
            scopes: [],
            name: {
              node: Identifier,
              loc: 11:5-11:6,
              name: "x",
            },
          },
          {
            node: ScopedIdentifier,
            loc: 11:8-11:9,
            scopes: [],
            name: {
              node: Identifier,
              loc: 11:8-11:9,
              name: "y",
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 11:13-11:14,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 12:0-12:17,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 12:4-12:13,
        name: None,
        elements: [
          {
            node: ScopedIdentifier,
            loc: 12:5-12:6,
            scopes: [],
            name: {
              node: Identifier,
              loc: 12:5-12:6,
              name: "x",
            },
          },
          {
            node: ScopedIdentifier,
            loc: 12:8-12:9,
            scopes: [],
            name: {
              node: Identifier,
              loc: 12:8-12:9,
              name: "y",
            },
          },
          {
            node: ScopedIdentifier,
            loc: 12:11-12:12,
            scopes: [],
            name: {
              node: Identifier,
              loc: 12:11-12:12,
              name: "z",
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 12:16-12:17,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 13:0-13:18,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 13:4-13:14,
        name: None,
        elements: [
          {
            node: ScopedIdentifier,
            loc: 13:5-13:6,
            scopes: [],
            name: {
              node: Identifier,
              loc: 13:5-13:6,
              name: "x",
            },
          },
          {
            node: ScopedIdentifier,
            loc: 13:8-13:9,
            scopes: [],
            name: {
              node: Identifier,
              loc: 13:8-13:9,
              name: "y",
            },
          },
          {
            node: ScopedIdentifier,
            loc: 13:11-13:12,
            scopes: [],
            name: {
              node: Identifier,
              loc: 13:11-13:12,
              name: "z",
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 13:17-13:18,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 16:0-16:15,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 16:4-16:11,
        name: {
          node: ScopedIdentifier,
          loc: 16:4-16:7,
          scopes: [],
          name: {
            node: Identifier,
            loc: 16:4-16:7,
            name: "Tup",
          },
        },
        elements: [
          {
            node: ScopedIdentifier,
            loc: 16:9-16:10,
            scopes: [],
            name: {
              node: Identifier,
              loc: 16:9-16:10,
              name: "x",
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 16:14-16:15,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 17:0-17:18,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 17:4-17:14,
        name: {
          node: ScopedIdentifier,
          loc: 17:4-17:7,
          scopes: [],
          name: {
            node: Identifier,
            loc: 17:4-17:7,
            name: "Tup",
          },
        },
        elements: [
          {
            node: ScopedIdentifier,
            loc: 17:9-17:10,
            scopes: [],
            name: {
              node: Identifier,
              loc: 17:9-17:10,
              name: "x",
            },
          },
          {
            node: ScopedIdentifier,
            loc: 17:12-17:13,
            scopes: [],
            name: {
              node: Identifier,
              loc: 17:12-17:13,
              name: "y",
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 17:17-17:18,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 18:0-18:21,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 18:4-18:17,
        name: {
          node: ScopedIdentifier,
          loc: 18:4-18:7,
          scopes: [],
          name: {
            node: Identifier,
            loc: 18:4-18:7,
            name: "Tup",
          },
        },
        elements: [
          {
            node: ScopedIdentifier,
            loc: 18:9-18:10,
            scopes: [],
            name: {
              node: Identifier,
              loc: 18:9-18:10,
              name: "x",
            },
          },
          {
            node: ScopedIdentifier,
            loc: 18:12-18:13,
            scopes: [],
            name: {
              node: Identifier,
              loc: 18:12-18:13,
              name: "y",
            },
          },
          {
            node: ScopedIdentifier,
            loc: 18:15-18:16,
            scopes: [],
            name: {
              node: Identifier,
              loc: 18:15-18:16,
              name: "z",
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 18:20-18:21,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 19:0-19:22,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 19:4-19:18,
        name: {
          node: ScopedIdentifier,
          loc: 19:4-19:7,
          scopes: [],
          name: {
            node: Identifier,
            loc: 19:4-19:7,
            name: "Tup",
          },
        },
        elements: [
          {
            node: ScopedIdentifier,
            loc: 19:9-19:10,
            scopes: [],
            name: {
              node: Identifier,
              loc: 19:9-19:10,
              name: "x",
            },
          },
          {
            node: ScopedIdentifier,
            loc: 19:12-19:13,
            scopes: [],
            name: {
              node: Identifier,
              loc: 19:12-19:13,
              name: "y",
            },
          },
          {
            node: ScopedIdentifier,
            loc: 19:15-19:16,
            scopes: [],
            name: {
              node: Identifier,
              loc: 19:15-19:16,
              name: "z",
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 19:21-19:22,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 22:0-22:24,
      kind: Immutable,
      pattern: {
        node: RecordPattern,
        loc: 22:4-22:20,
        name: {
          node: ScopedIdentifier,
          loc: 22:4-22:7,
          scopes: [],
          name: {
            node: Identifier,
            loc: 22:4-22:7,
            name: "Rec",
          },
        },
        fields: [
          {
            node: RecordPatternField,
            loc: 22:10-22:18,
            name: {
              node: Identifier,
              loc: 22:10-22:15,
              name: "field",
            },
            value: {
              node: ScopedIdentifier,
              loc: 22:17-22:18,
              scopes: [],
              name: {
                node: Identifier,
                loc: 22:17-22:18,
                name: "x",
              },
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 22:23-22:24,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 23:0-23:21,
      kind: Immutable,
      pattern: {
        node: RecordPattern,
        loc: 23:4-23:17,
        name: {
          node: ScopedIdentifier,
          loc: 23:4-23:7,
          scopes: [],
          name: {
            node: Identifier,
            loc: 23:4-23:7,
            name: "Rec",
          },
        },
        fields: [
          {
            node: RecordPatternField,
            loc: 23:10-23:15,
            name: None,
            value: {
              node: ScopedIdentifier,
              loc: 23:10-23:15,
              scopes: [],
              name: {
                node: Identifier,
                loc: 23:10-23:15,
                name: "field",
              },
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 23:20-23:21,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 24:0-24:33,
      kind: Immutable,
      pattern: {
        node: RecordPattern,
        loc: 24:4-24:29,
        name: {
          node: ScopedIdentifier,
          loc: 24:4-24:7,
          scopes: [],
          name: {
            node: Identifier,
            loc: 24:4-24:7,
            name: "Rec",
          },
        },
        fields: [
          {
            node: RecordPatternField,
            loc: 24:10-24:19,
            name: {
              node: Identifier,
              loc: 24:10-24:16,
              name: "field1",
            },
            value: {
              node: ScopedIdentifier,
              loc: 24:18-24:19,
              scopes: [],
              name: {
                node: Identifier,
                loc: 24:18-24:19,
                name: "x",
              },
            },
          },
          {
            node: RecordPatternField,
            loc: 24:21-24:27,
            name: None,
            value: {
              node: ScopedIdentifier,
              loc: 24:21-24:27,
              scopes: [],
              name: {
                node: Identifier,
                loc: 24:21-24:27,
                name: "field2",
              },
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 24:32-24:33,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 25:0-25:45,
      kind: Immutable,
      pattern: {
        node: RecordPattern,
        loc: 25:4-25:41,
        name: {
          node: ScopedIdentifier,
          loc: 25:4-25:7,
          scopes: [],
          name: {
            node: Identifier,
            loc: 25:4-25:7,
            name: "Rec",
          },
        },
        fields: [
          {
            node: RecordPatternField,
            loc: 25:10-25:16,
            name: None,
            value: {
              node: ScopedIdentifier,
              loc: 25:10-25:16,
              scopes: [],
              name: {
                node: Identifier,
                loc: 25:10-25:16,
                name: "field1",
              },
            },
          },
          {
            node: RecordPatternField,
            loc: 25:18-25:27,
            name: {
              node: Identifier,
              loc: 25:18-25:24,
              name: "field2",
            },
            value: {
              node: ScopedIdentifier,
              loc: 25:26-25:27,
              scopes: [],
              name: {
                node: Identifier,
                loc: 25:26-25:27,
                name: "x",
              },
            },
          },
          {
            node: RecordPatternField,
            loc: 25:29-25:38,
            name: {
              node: Identifier,
              loc: 25:29-25:35,
              name: "field3",
            },
            value: {
              node: ScopedIdentifier,
              loc: 25:37-25:38,
              scopes: [],
              name: {
                node: Identifier,
                loc: 25:37-25:38,
                name: "y",
              },
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 25:44-25:45,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 28:0-28:13,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 28:4-28:9,
        scopes: [
          {
            node: Identifier,
            loc: 28:4-28:5,
            name: "A",
          },
          {
            node: Identifier,
            loc: 28:6-28:7,
            name: "B",
          },
        ],
        name: {
          node: Identifier,
          loc: 28:8-28:9,
          name: "C",
        },
      },
      init: {
        node: IntLiteral,
        loc: 28:12-28:13,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 29:0-29:21,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 29:4-29:17,
        name: {
          node: ScopedIdentifier,
          loc: 29:4-29:13,
          scopes: [
            {
              node: Identifier,
              loc: 29:4-29:5,
              name: "A",
            },
            {
              node: Identifier,
              loc: 29:6-29:7,
              name: "B",
            },
            {
              node: Identifier,
              loc: 29:8-29:9,
              name: "C",
            },
          ],
          name: {
            node: Identifier,
            loc: 29:10-29:13,
            name: "Tup",
          },
        },
        elements: [
          {
            node: ScopedIdentifier,
            loc: 29:15-29:16,
            scopes: [],
            name: {
              node: Identifier,
              loc: 29:15-29:16,
              name: "x",
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 29:20-29:21,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 30:0-30:27,
      kind: Immutable,
      pattern: {
        node: RecordPattern,
        loc: 30:4-30:23,
        name: {
          node: ScopedIdentifier,
          loc: 30:4-30:13,
          scopes: [
            {
              node: Identifier,
              loc: 30:4-30:5,
              name: "A",
            },
            {
              node: Identifier,
              loc: 30:6-30:7,
              name: "B",
            },
            {
              node: Identifier,
              loc: 30:8-30:9,
              name: "C",
            },
          ],
          name: {
            node: Identifier,
            loc: 30:10-30:13,
            name: "Rec",
          },
        },
        fields: [
          {
            node: RecordPatternField,
            loc: 30:16-30:21,
            name: None,
            value: {
              node: ScopedIdentifier,
              loc: 30:16-30:21,
              scopes: [],
              name: {
                node: Identifier,
                loc: 30:16-30:21,
                name: "field",
              },
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 30:26-30:27,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 33:0-33:19,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 33:4-33:15,
        name: None,
        elements: [
          {
            node: TuplePattern,
            loc: 33:5-33:11,
            name: None,
            elements: [
              {
                node: ScopedIdentifier,
                loc: 33:6-33:7,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 33:6-33:7,
                  name: "x",
                },
              },
              {
                node: ScopedIdentifier,
                loc: 33:9-33:10,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 33:9-33:10,
                  name: "y",
                },
              },
            ],
          },
          {
            node: ScopedIdentifier,
            loc: 33:13-33:14,
            scopes: [],
            name: {
              node: Identifier,
              loc: 33:13-33:14,
              name: "z",
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 33:18-33:19,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 34:0-34:34,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 34:4-34:30,
        name: None,
        elements: [
          {
            node: TuplePattern,
            loc: 34:5-34:14,
            name: {
              node: ScopedIdentifier,
              loc: 34:5-34:8,
              scopes: [],
              name: {
                node: Identifier,
                loc: 34:5-34:8,
                name: "Tup",
              },
            },
            elements: [
              {
                node: ScopedIdentifier,
                loc: 34:9-34:10,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 34:9-34:10,
                  name: "x",
                },
              },
              {
                node: ScopedIdentifier,
                loc: 34:12-34:13,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 34:12-34:13,
                  name: "y",
                },
              },
            ],
          },
          {
            node: RecordPattern,
            loc: 34:16-34:29,
            name: {
              node: ScopedIdentifier,
              loc: 34:16-34:19,
              scopes: [],
              name: {
                node: Identifier,
                loc: 34:16-34:19,
                name: "Rec",
              },
            },
            fields: [
              {
                node: RecordPatternField,
                loc: 34:22-34:27,
                name: None,
                value: {
                  node: ScopedIdentifier,
                  loc: 34:22-34:27,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 34:22-34:27,
                    name: "field",
                  },
                },
              },
            ],
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 34:33-34:34,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 35:0-35:33,
      kind: Immutable,
      pattern: {
        node: RecordPattern,
        loc: 35:4-35:29,
        name: {
          node: ScopedIdentifier,
          loc: 35:4-35:7,
          scopes: [],
          name: {
            node: Identifier,
            loc: 35:4-35:7,
            name: "Rec",
          },
        },
        fields: [
          {
            node: RecordPatternField,
            loc: 35:10-35:27,
            name: {
              node: Identifier,
              loc: 35:10-35:15,
              name: "field",
            },
            value: {
              node: TuplePattern,
              loc: 35:17-35:27,
              name: {
                node: ScopedIdentifier,
                loc: 35:17-35:20,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 35:17-35:20,
                  name: "Tup",
                },
              },
              elements: [
                {
                  node: ScopedIdentifier,
                  loc: 35:22-35:23,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 35:22-35:23,
                    name: "x",
                  },
                },
                {
                  node: ScopedIdentifier,
                  loc: 35:25-35:26,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 35:25-35:26,
                    name: "y",
                  },
                },
              ],
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 35:32-35:33,
        raw: "1",
      },
      annot: None,
    },
  ],
}