type _ZeroSize {}

type _object$std.bool.Bool$std.string.ToString {bool, byte[7], fn*}

global fn[1] @_vtable$std.bool.Bool$std.string.ToString = [@std.bool.Bool.toString]

type _object$std.byte.Byte$std.string.ToString {byte, byte[7], fn*}

global fn[1] @_vtable$std.byte.Byte$std.string.ToString = [@std.byte.Byte.toString]

type _object$std.int.Int$std.string.ToString {int, byte[4], fn*}

global fn[1] @_vtable$std.int.Int$std.string.ToString = [@std.int.Int.toString]

type _object$std.long.Long$std.string.ToString {long, fn*}

global fn[1] @_vtable$std.long.Long$std.string.ToString = [@std.long.Long.toString]

type _object$std.string.ToString {byte*, fn*}

type _object$std.unit.Unit$std.string.ToString {_ZeroSize*, fn*}

global fn[1] @_vtable$std.unit.Unit$std.string.ToString = [@std.unit.Unit.toString]

func std.string.String* @test.useToString(_object$std.string.ToString* %0) {
  %1 := GetPointer byte*, _object$std.string.ToString* %0.0
  %2 := Load byte* %1
  %3 := GetPointer fn*, _object$std.string.ToString* %0.1
  %4 := Load fn* %3
  %5 := GetPointer fn, fn* %4[int 0]
  %6 := Load fn %5
  %7 := Call std.string.String* %6(%2)
  Ret %7
}

func void @test.testUnitPromotion() {
  %0 := Call _object$std.unit.Unit$std.string.ToString* myte.builtin.alloc(1)
  %1 := GetPointer fn*, _object$std.unit.Unit$std.string.ToString* %0.1
  Store fn* %1, @_vtable$std.unit.Unit$std.string.ToString
  %2 := Cast _object$std.unit.Unit$std.string.ToString* %0 to _object$std.string.ToString*
  %3 := Call std.string.String* @test.useToString(%2)
  %4 := Call _object$std.unit.Unit$std.string.ToString* myte.builtin.alloc(1)
  %5 := GetPointer fn*, _object$std.unit.Unit$std.string.ToString* %4.1
  Store fn* %5, @_vtable$std.unit.Unit$std.string.ToString
  %6 := Cast _object$std.unit.Unit$std.string.ToString* %4 to _object$std.string.ToString*
  %7 := Call std.string.String* @test.useToString(%6)
  Ret
}

func void @test.testBoolPromotion(bool %0) {
  %1 := Call _object$std.bool.Bool$std.string.ToString* myte.builtin.alloc(1)
  %2 := GetPointer bool, _object$std.bool.Bool$std.string.ToString* %1.0
  Store bool %2, %0
  %3 := GetPointer fn*, _object$std.bool.Bool$std.string.ToString* %1.2
  Store fn* %3, @_vtable$std.bool.Bool$std.string.ToString
  %4 := Cast _object$std.bool.Bool$std.string.ToString* %1 to _object$std.string.ToString*
  %5 := Call std.string.String* @test.useToString(%4)
  %6 := Call _object$std.bool.Bool$std.string.ToString* myte.builtin.alloc(1)
  %7 := GetPointer bool, _object$std.bool.Bool$std.string.ToString* %6.0
  Store bool %7, true
  %8 := GetPointer fn*, _object$std.bool.Bool$std.string.ToString* %6.2
  Store fn* %8, @_vtable$std.bool.Bool$std.string.ToString
  %9 := Cast _object$std.bool.Bool$std.string.ToString* %6 to _object$std.string.ToString*
  %10 := Call std.string.String* @test.useToString(%9)
  Ret
}

func void @test.testBytePromotion(byte %0) {
  %1 := Call _object$std.byte.Byte$std.string.ToString* myte.builtin.alloc(1)
  %2 := GetPointer byte, _object$std.byte.Byte$std.string.ToString* %1.0
  Store byte %2, %0
  %3 := GetPointer fn*, _object$std.byte.Byte$std.string.ToString* %1.2
  Store fn* %3, @_vtable$std.byte.Byte$std.string.ToString
  %4 := Cast _object$std.byte.Byte$std.string.ToString* %1 to _object$std.string.ToString*
  %5 := Call std.string.String* @test.useToString(%4)
  %6 := Call _object$std.byte.Byte$std.string.ToString* myte.builtin.alloc(1)
  %7 := GetPointer byte, _object$std.byte.Byte$std.string.ToString* %6.0
  Store byte %7, 1
  %8 := GetPointer fn*, _object$std.byte.Byte$std.string.ToString* %6.2
  Store fn* %8, @_vtable$std.byte.Byte$std.string.ToString
  %9 := Cast _object$std.byte.Byte$std.string.ToString* %6 to _object$std.string.ToString*
  %10 := Call std.string.String* @test.useToString(%9)
  Ret
}

func void @test.testIntPromotion(int %0) {
  %1 := Call _object$std.int.Int$std.string.ToString* myte.builtin.alloc(1)
  %2 := GetPointer int, _object$std.int.Int$std.string.ToString* %1.0
  Store int %2, %0
  %3 := GetPointer fn*, _object$std.int.Int$std.string.ToString* %1.2
  Store fn* %3, @_vtable$std.int.Int$std.string.ToString
  %4 := Cast _object$std.int.Int$std.string.ToString* %1 to _object$std.string.ToString*
  %5 := Call std.string.String* @test.useToString(%4)
  %6 := Call _object$std.int.Int$std.string.ToString* myte.builtin.alloc(1)
  %7 := GetPointer int, _object$std.int.Int$std.string.ToString* %6.0
  Store int %7, 1
  %8 := GetPointer fn*, _object$std.int.Int$std.string.ToString* %6.2
  Store fn* %8, @_vtable$std.int.Int$std.string.ToString
  %9 := Cast _object$std.int.Int$std.string.ToString* %6 to _object$std.string.ToString*
  %10 := Call std.string.String* @test.useToString(%9)
  Ret
}

func void @test.testLongPromotion(long %0) {
  %1 := Call _object$std.long.Long$std.string.ToString* myte.builtin.alloc(1)
  %2 := GetPointer long, _object$std.long.Long$std.string.ToString* %1.0
  Store long %2, %0
  %3 := GetPointer fn*, _object$std.long.Long$std.string.ToString* %1.1
  Store fn* %3, @_vtable$std.long.Long$std.string.ToString
  %4 := Cast _object$std.long.Long$std.string.ToString* %1 to _object$std.string.ToString*
  %5 := Call std.string.String* @test.useToString(%4)
  %6 := Call _object$std.long.Long$std.string.ToString* myte.builtin.alloc(1)
  %7 := GetPointer long, _object$std.long.Long$std.string.ToString* %6.0
  Store long %7, 1
  %8 := GetPointer fn*, _object$std.long.Long$std.string.ToString* %6.1
  Store fn* %8, @_vtable$std.long.Long$std.string.ToString
  %9 := Cast _object$std.long.Long$std.string.ToString* %6 to _object$std.string.ToString*
  %10 := Call std.string.String* @test.useToString(%9)
  Ret
}

type _object$test.ZeroSize$std.string.ToString {_ZeroSize*, fn*}

global fn[1] @_vtable$test.ZeroSize$std.string.ToString = [@test.ZeroSize.toString]

func std.string.String* @test.ZeroSize.toString(_ZeroSize* %0) {
  %1 := Call std.string.String* myte.builtin.alloc(1)
  %2 := GetPointer byte*, std.string.String* %1.2
  Store byte* %2, 0
  %3 := GetPointer int, std.string.String* %1.0
  Store int %3, 0
  %4 := GetPointer int, std.string.String* %1.1
  Store int %4, 0
  Ret %1
}

func void @test.testZeroSizePromotion() {
  %0 := Call _object$test.ZeroSize$std.string.ToString* myte.builtin.alloc(1)
  %1 := GetPointer fn*, _object$test.ZeroSize$std.string.ToString* %0.1
  Store fn* %1, @_vtable$test.ZeroSize$std.string.ToString
  %2 := Cast _object$test.ZeroSize$std.string.ToString* %0 to _object$std.string.ToString*
  %3 := Call std.string.String* @test.useToString(%2)
  Call void @test.use<Unit>()
  %4 := Call _object$test.ZeroSize$std.string.ToString* myte.builtin.alloc(1)
  %5 := GetPointer fn*, _object$test.ZeroSize$std.string.ToString* %4.1
  Store fn* %5, @_vtable$test.ZeroSize$std.string.ToString
  %6 := Cast _object$test.ZeroSize$std.string.ToString* %4 to _object$std.string.ToString*
  %7 := Call std.string.String* @test.useToString(%6)
  Ret
}

func void @test.use<Function>(fn %0) {
  Ret
}

func void @test.use<Unit>() {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.testUnitPromotion)
  Call void @test.use<Function>(@test.testBoolPromotion)
  Call void @test.use<Function>(@test.testBytePromotion)
  Call void @test.use<Function>(@test.testIntPromotion)
  Call void @test.use<Function>(@test.testLongPromotion)
  Call void @test.use<Function>(@test.testZeroSizePromotion)
  Ret 0
}