type _ZeroSize {}

type _object$std.bool.Bool$std.string.ToString {bool, byte[7], fn[1]*}

global fn[1] @_vtable$std.bool.Bool$std.string.ToString = [@std.bool.Bool.toString]

type _object$std.byte.Byte$std.string.ToString {byte, byte[7], fn[1]*}

global fn[1] @_vtable$std.byte.Byte$std.string.ToString = [@std.byte.Byte.toString]

type _object$std.int.Int$std.string.ToString {int, byte[4], fn[1]*}

global fn[1] @_vtable$std.int.Int$std.string.ToString = [@std.int.Int.toString]

type _object$std.long.Long$std.string.ToString {long, fn[1]*}

global fn[1] @_vtable$std.long.Long$std.string.ToString = [@std.long.Long.toString]

type _object$std.string.ToString {byte*, fn[1]*}

type _object$std.unit.Unit$std.string.ToString {_ZeroSize*, fn[1]*}

global fn[1] @_vtable$std.unit.Unit$std.string.ToString = [@std.unit.Unit.toString]

func std.string.String* @test.useToString(_object$std.string.ToString* %0) {
  %1 := GetPointer byte*, _object$std.string.ToString* %0.0
  %2 := Load byte* %1
  %3 := GetPointer fn[1]*, _object$std.string.ToString* %0.1
  %4 := Load fn[1]* %3
  %5 := GetPointer fn, fn* %4[int 0]
  %6 := Load fn %5
  %7 := Call std.string.String* %6(%2)
  Ret %7
}

func void @test.testUnitPromotion() {
  %8 := CallBuiltin _object$std.unit.Unit$std.string.ToString* myte_alloc(1)
  %9 := GetPointer fn[1]*, _object$std.unit.Unit$std.string.ToString* %8.1
  Store fn[1]* %9, @_vtable$std.unit.Unit$std.string.ToString
  %10 := Call std.string.String* @test.useToString(%8)
  %11 := CallBuiltin _object$std.unit.Unit$std.string.ToString* myte_alloc(1)
  %12 := GetPointer fn[1]*, _object$std.unit.Unit$std.string.ToString* %11.1
  Store fn[1]* %12, @_vtable$std.unit.Unit$std.string.ToString
  %13 := Call std.string.String* @test.useToString(%11)
  Ret
}

func void @test.testBoolPromotion(bool %14) {
  %15 := CallBuiltin _object$std.bool.Bool$std.string.ToString* myte_alloc(1)
  %16 := GetPointer bool, _object$std.bool.Bool$std.string.ToString* %15.0
  Store bool %16, %14
  %17 := GetPointer fn[1]*, _object$std.bool.Bool$std.string.ToString* %15.2
  Store fn[1]* %17, @_vtable$std.bool.Bool$std.string.ToString
  %18 := Call std.string.String* @test.useToString(%15)
  %19 := CallBuiltin _object$std.bool.Bool$std.string.ToString* myte_alloc(1)
  %20 := GetPointer bool, _object$std.bool.Bool$std.string.ToString* %19.0
  Store bool %20, true
  %21 := GetPointer fn[1]*, _object$std.bool.Bool$std.string.ToString* %19.2
  Store fn[1]* %21, @_vtable$std.bool.Bool$std.string.ToString
  %22 := Call std.string.String* @test.useToString(%19)
  Ret
}

func void @test.testBytePromotion(byte %23) {
  %24 := CallBuiltin _object$std.byte.Byte$std.string.ToString* myte_alloc(1)
  %25 := GetPointer byte, _object$std.byte.Byte$std.string.ToString* %24.0
  Store byte %25, %23
  %26 := GetPointer fn[1]*, _object$std.byte.Byte$std.string.ToString* %24.2
  Store fn[1]* %26, @_vtable$std.byte.Byte$std.string.ToString
  %27 := Call std.string.String* @test.useToString(%24)
  %28 := CallBuiltin _object$std.byte.Byte$std.string.ToString* myte_alloc(1)
  %29 := GetPointer byte, _object$std.byte.Byte$std.string.ToString* %28.0
  Store byte %29, 1
  %30 := GetPointer fn[1]*, _object$std.byte.Byte$std.string.ToString* %28.2
  Store fn[1]* %30, @_vtable$std.byte.Byte$std.string.ToString
  %31 := Call std.string.String* @test.useToString(%28)
  Ret
}

func void @test.testIntPromotion(int %32) {
  %33 := CallBuiltin _object$std.int.Int$std.string.ToString* myte_alloc(1)
  %34 := GetPointer int, _object$std.int.Int$std.string.ToString* %33.0
  Store int %34, %32
  %35 := GetPointer fn[1]*, _object$std.int.Int$std.string.ToString* %33.2
  Store fn[1]* %35, @_vtable$std.int.Int$std.string.ToString
  %36 := Call std.string.String* @test.useToString(%33)
  %37 := CallBuiltin _object$std.int.Int$std.string.ToString* myte_alloc(1)
  %38 := GetPointer int, _object$std.int.Int$std.string.ToString* %37.0
  Store int %38, 1
  %39 := GetPointer fn[1]*, _object$std.int.Int$std.string.ToString* %37.2
  Store fn[1]* %39, @_vtable$std.int.Int$std.string.ToString
  %40 := Call std.string.String* @test.useToString(%37)
  Ret
}

func void @test.testLongPromotion(long %41) {
  %42 := CallBuiltin _object$std.long.Long$std.string.ToString* myte_alloc(1)
  %43 := GetPointer long, _object$std.long.Long$std.string.ToString* %42.0
  Store long %43, %41
  %44 := GetPointer fn[1]*, _object$std.long.Long$std.string.ToString* %42.1
  Store fn[1]* %44, @_vtable$std.long.Long$std.string.ToString
  %45 := Call std.string.String* @test.useToString(%42)
  %46 := CallBuiltin _object$std.long.Long$std.string.ToString* myte_alloc(1)
  %47 := GetPointer long, _object$std.long.Long$std.string.ToString* %46.0
  Store long %47, 1
  %48 := GetPointer fn[1]*, _object$std.long.Long$std.string.ToString* %46.1
  Store fn[1]* %48, @_vtable$std.long.Long$std.string.ToString
  %49 := Call std.string.String* @test.useToString(%46)
  Ret
}

func void @test.use<Function>(fn %50) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.testUnitPromotion)
  Call void @test.use<Function>(@test.testBoolPromotion)
  Call void @test.use<Function>(@test.testBytePromotion)
  Call void @test.use<Function>(@test.testIntPromotion)
  Call void @test.use<Function>(@test.testLongPromotion)
  Ret 0
}