func void @t.func(int %0) {
  Ret
}

func bool @t.rand() {
  Ret true
}

func void @t.ifStatement() {
  Call void @t.func(3)
  Call void @t.func(4)
  Call void @t.func(5)
  Ret
}

func int @t.nestedIfStatements() {
  Ret 2
}

func void @t.whileTrue() {
  continue @0
label @0:
  Call void @t.func(1)
  continue @0
}

func void @t.whileFalse() {
  Call void @t.func(3)
  Ret
}

func void @t.whileTrueWithReturn() {
  Call void @t.func(1)
  Ret
}

func void @t.whileTrueWithBreak() {
  Call void @t.func(1)
  Call void @t.func(2)
  Ret
}

func void @t.whileTrueWithContinue() {
  continue @0
label @0:
  Call void @t.func(1)
  continue @0
}

func int @t.main() {
  Ret 0
}