  .global _main

  .data
  .balign 8
_float$1.:
  .quad 4607182418800017408

  .text
test.addByteImm:
  addb $60, %dil
  movl %edi, %eax
  ret
test.addByteImm2:
  addb $60, %dil
  movl %edi, %eax
  ret
test.addByteRegs:
  addb %dil, %sil
  movl %esi, %eax
  ret
test.addDoubleImm:
  addsd _float$1.(%rip), %xmm0
  ret
test.addDoubleRegs:
  addsd %xmm0, %xmm1
  movq %xmm1, %xmm0
  ret
test.addImmDouble:
  addsd _float$1.(%rip), %xmm0
  ret
test.addIntByteImm:
  addl $60, %edi
  movl %edi, %eax
  ret
test.addIntIntImm:
  addl $257, %edi
  movl %edi, %eax
  ret
test.addIntRegs:
  addl %edi, %esi
  movl %esi, %eax
  ret
test.addLongByteImm:
  addq $60, %rdi
  movq %rdi, %rax
  ret
test.addLongIntImm:
  addq $257, %rdi
  movq %rdi, %rax
  ret
test.addLongLongImm:
  movq $2147483648, %rax
  addq %rdi, %rax
  ret
test.addLongLongImm2:
  movq $2147483648, %rax
  addq %rax, %rdi
  movq %rdi, %rax
  ret
test.addLongRegs:
  addq %rdi, %rsi
  movq %rsi, %rax
  ret
_main:
  movl $0, %eax
  ret