  .global _main

  .text
test.andByteImmReg:
  andb $60, %dil
  movl %edi, %eax
  ret
test.andByteRegImm:
  andb $60, %dil
  movl %edi, %eax
  ret
test.andByteRegs:
  andb %dil, %sil
  movl %esi, %eax
  ret
test.andIntImmReg:
  andl $257, %edi
  movl %edi, %eax
  ret
test.andIntRegImm:
  andl $257, %edi
  movl %edi, %eax
  ret
test.andIntRegs:
  andl %edi, %esi
  movl %esi, %eax
  ret
test.andLongImmReg:
  movq $2147483648, %rax
  andq %rax, %rdi
  movq %rdi, %rax
  ret
test.andLongRegImm:
  movq $2147483648, %rax
  andq %rdi, %rax
  ret
test.andLongRegs:
  andq %rdi, %rsi
  movq %rsi, %rax
  ret
_main:
  leaq test.andByteRegs(%rip), %rdi
  call test.use$Function$
  leaq test.andByteImmReg(%rip), %rdi
  call test.use$Function$
  leaq test.andByteRegImm(%rip), %rdi
  call test.use$Function$
  leaq test.andIntRegs(%rip), %rdi
  call test.use$Function$
  leaq test.andIntRegImm(%rip), %rdi
  call test.use$Function$
  leaq test.andIntImmReg(%rip), %rdi
  call test.use$Function$
  leaq test.andLongRegs(%rip), %rdi
  call test.use$Function$
  leaq test.andLongRegImm(%rip), %rdi
  call test.use$Function$
  leaq test.andLongImmReg(%rip), %rdi
  call test.use$Function$
  movl $0, %eax
  ret
test.use$Function$:
  movq %rdi, %rax
  ret