  .global _main

  .data
  .balign 8
_float$60.:
  .quad 4633641066610819072

  .text
test.divByteImmReg:
  movw $60, %ax
  movsbw %dil, %cx
  cwd 
  idivw %cx
  ret
test.divByteRegImm:
  movsbw %dil, %ax
  movw $60, %cx
  cwd 
  idivw %cx
  ret
test.divByteRegs:
  movsbw %dil, %ax
  movsbw %sil, %cx
  cwd 
  idivw %cx
  ret
test.divIntImmReg:
  movl $257, %eax
  cdq 
  idivl %edi
  ret
test.divIntRegImm:
  movl %edi, %eax
  movl $257, %ecx
  cdq 
  idivl %ecx
  ret
test.divIntRegs:
  movl %edi, %eax
  cdq 
  idivl %esi
  ret
test.divLongImmReg:
  movq $2147483648, %rax
  cqo 
  idivq %rdi
  ret
test.divLongRegImm:
  movq $2147483648, %rcx
  movq %rdi, %rax
  cqo 
  idivq %rcx
  ret
test.divLongRegs:
  movq %rdi, %rax
  cqo 
  idivq %rsi
  ret
_main:
  movl $0, %eax
  ret
test.remByteImmReg:
  movw $60, %ax
  movsbw %dil, %cx
  cwd 
  idivw %cx
  movl %edx, %eax
  ret
test.remByteRegImm:
  movsbw %dil, %ax
  movw $60, %cx
  cwd 
  idivw %cx
  movl %edx, %eax
  ret
test.remByteRegs:
  movsbw %dil, %ax
  movsbw %sil, %cx
  cwd 
  idivw %cx
  movl %edx, %eax
  ret
test.remDoublImmReg:
  movq _float$60.(%rip), %xmm1
  divsd %xmm0, %xmm1
  movq %xmm1, %xmm0
  ret
test.remDoubleRegImm:
  divsd _float$60.(%rip), %xmm0
  ret
test.remDoubleRegs:
  divsd %xmm1, %xmm0
  ret
test.remIntImmReg:
  movl $257, %eax
  cdq 
  idivl %edi
  movl %edx, %eax
  ret
test.remIntRegImm:
  movl %edi, %eax
  movl $257, %ecx
  cdq 
  idivl %ecx
  movl %edx, %eax
  ret
test.remIntRegs:
  movl %edi, %eax
  cdq 
  idivl %esi
  movl %edx, %eax
  ret
test.remLongImmReg:
  movq $2147483648, %rax
  cqo 
  idivq %rdi
  movq %rdx, %rax
  ret
test.remLongRegImm:
  movq $2147483648, %rcx
  movq %rdi, %rax
  cqo 
  idivq %rcx
  movq %rdx, %rax
  ret
test.remLongRegs:
  movq %rdi, %rax
  cqo 
  idivq %rsi
  movq %rdx, %rax
  ret