  .global _main

  .text
test.divByteImmReg:
  movw $60, %ax
  movsx %dil, %cx
  cwd 
  idivw %cx
  ret
test.divByteRegImm:
  movsx %dil, %ax
  movw $60, %cx
  cwd 
  idivw %cx
  ret
test.divByteRegs:
  movsx %dil, %ax
  movsx %sil, %cx
  cwd 
  idivw %cx
  ret
test.divIntImmReg:
  movl $257, %eax
  cdq 
  idivl %edi
  ret
test.divIntRegImm:
  movl %edi, %eax
  movl $257, %ecx
  cdq 
  idivl %ecx
  ret
test.divIntRegs:
  movl %edi, %eax
  cdq 
  idivl %esi
  ret
test.divLongImmReg:
  movq $2147483648, %rax
  cqo 
  idivq %rdi
  ret
test.divLongRegImm:
  movq $2147483648, %rcx
  movq %rdi, %rax
  cqo 
  idivq %rcx
  ret
test.divLongRegs:
  movq %rdi, %rax
  cqo 
  idivq %rsi
  ret
_main:
  movl $0, %eax
  ret
test.remByteImmReg:
  movw $60, %ax
  movsx %dil, %cx
  cwd 
  idivw %cx
  movl %edx, %eax
  ret
test.remByteRegImm:
  movsx %dil, %ax
  movw $60, %cx
  cwd 
  idivw %cx
  movl %edx, %eax
  ret
test.remByteRegs:
  movsx %dil, %ax
  movsx %sil, %cx
  cwd 
  idivw %cx
  movl %edx, %eax
  ret
test.remIntImmReg:
  movl $257, %eax
  cdq 
  idivl %edi
  movl %edx, %eax
  ret
test.remIntRegImm:
  movl %edi, %eax
  movl $257, %ecx
  cdq 
  idivl %ecx
  movl %edx, %eax
  ret
test.remIntRegs:
  movl %edi, %eax
  cdq 
  idivl %esi
  movl %edx, %eax
  ret
test.remLongImmReg:
  movq $2147483648, %rax
  cqo 
  idivq %rdi
  movq %rdx, %rax
  ret
test.remLongRegImm:
  movq $2147483648, %rcx
  movq %rdi, %rax
  cqo 
  idivq %rcx
  movq %rdx, %rax
  ret
test.remLongRegs:
  movq %rdi, %rax
  cqo 
  idivq %rsi
  movq %rdx, %rax
  ret