  .global _main

  .data
  .balign 8
_float$5.:
  .quad 4617315517961601024

  .text
_main:
  movl $0, %eax
  ret
test.mulByteImmReg:
  imulw $60, %di, %ax
  ret
test.mulByteRegImm:
  imulw $60, %di, %ax
  ret
test.mulByteRegs:
  imulw %di, %si
  movl %esi, %eax
  ret
test.mulDoubleImm:
  mulsd _float$5.(%rip), %xmm0
  ret
test.mulDoubleRegs:
  mulsd %xmm0, %xmm1
  movq %xmm1, %xmm0
  ret
test.mulImmDouble:
  mulsd _float$5.(%rip), %xmm0
  ret
test.mulIntImmReg:
  imull $257, %edi, %eax
  ret
test.mulIntRegImm:
  imull $257, %edi, %eax
  ret
test.mulIntRegs:
  imull %edi, %esi
  movl %esi, %eax
  ret
test.mulLongImmReg:
  movq $2147483648, %rax
  imulq %rax, %rdi
  movq %rdi, %rax
  ret
test.mulLongRegImm:
  movq $2147483648, %rax
  imulq %rdi, %rax
  ret
test.mulLongRegs:
  imulq %rdi, %rsi
  movq %rsi, %rax
  ret