  .global _main

  .text
_main:
  leaq test.shrByteRegs(%rip), %rdi
  call test.use$Function$
  leaq test.shrByteImmReg(%rip), %rdi
  call test.use$Function$
  leaq test.shrByteRegImm(%rip), %rdi
  call test.use$Function$
  leaq test.shrIntRegs(%rip), %rdi
  call test.use$Function$
  leaq test.shrIntRegImm(%rip), %rdi
  call test.use$Function$
  leaq test.shrIntImmReg(%rip), %rdi
  call test.use$Function$
  leaq test.shrLongRegs(%rip), %rdi
  call test.use$Function$
  leaq test.shrLongRegImm(%rip), %rdi
  call test.use$Function$
  leaq test.shrLongImmReg(%rip), %rdi
  call test.use$Function$
  movl $0, %eax
  ret
test.shrByteImmReg:
  movl %edi, %ecx
  movb $6, %al
  shrb %cl, %al
  ret
test.shrByteRegImm:
  shrb $6, %dil
  movl %edi, %eax
  ret
test.shrByteRegs:
  movl %esi, %ecx
  shrb %cl, %dil
  movl %edi, %eax
  ret
test.shrIntImmReg:
  movl %edi, %ecx
  movl $257, %eax
  shrl %cl, %eax
  ret
test.shrIntRegImm:
  shrl $6, %edi
  movl %edi, %eax
  ret
test.shrIntRegs:
  movl %esi, %ecx
  shrl %cl, %edi
  movl %edi, %eax
  ret
test.shrLongImmReg:
  movq $2147483648, %rax
  movl %edi, %ecx
  shrq %cl, %rax
  ret
test.shrLongRegImm:
  shrq $6, %rdi
  movq %rdi, %rax
  ret
test.shrLongRegs:
  movl %esi, %ecx
  shrq %cl, %rdi
  movq %rdi, %rax
  ret
test.use$Function$:
  movq %rdi, %rax
  ret