  .global _main

  .text
_main:
  mov w0, wzr
  ret
test.testEightArgFunction:
  add w0, w0, w1
  add w0, w0, w2
  add w0, w0, w3
  add w0, w0, w4
  add w0, w0, w5
  add w0, w0, w6
  add w0, w0, w7
  ret
test.testEightArgFunctionFloat:
  fadd d0, d0, d1
  fadd d0, d0, d2
  fadd d0, d0, d3
  fadd d0, d0, d4
  fadd d0, d0, d5
  fadd d0, d0, d6
  fadd d0, d0, d7
  ret
test.testFiveArgFunction:
  add w0, w0, w1
  add w0, w0, w2
  add w0, w0, w3
  add w0, w0, w4
  ret
test.testFiveArgFunctionFloat:
  fadd d0, d0, d1
  fadd d0, d0, d2
  fadd d0, d0, d3
  fadd d0, d0, d4
  ret
test.testFourArgFunction:
  add w0, w0, w1
  add w0, w0, w2
  add w0, w0, w3
  ret
test.testFourArgFunctionFloat:
  fadd d0, d0, d1
  fadd d0, d0, d2
  fadd d0, d0, d3
  ret
test.testOneArgFunction:
  ret
test.testOneArgFunctionFloat:
  ret
test.testSevenArgFunction:
  add w0, w0, w1
  add w0, w0, w2
  add w0, w0, w3
  add w0, w0, w4
  add w0, w0, w5
  add w0, w0, w6
  ret
test.testSevenArgFunctionFloat:
  fadd d0, d0, d1
  fadd d0, d0, d2
  fadd d0, d0, d3
  fadd d0, d0, d4
  fadd d0, d0, d5
  fadd d0, d0, d6
  ret
test.testSixArgFunction:
  add w0, w0, w1
  add w0, w0, w2
  add w0, w0, w3
  add w0, w0, w4
  add w0, w0, w5
  ret
test.testSixArgFunctionFloat:
  fadd d0, d0, d1
  fadd d0, d0, d2
  fadd d0, d0, d3
  fadd d0, d0, d4
  fadd d0, d0, d5
  ret
test.testThreeArgFunction:
  add w0, w0, w1
  add w0, w0, w2
  ret
test.testThreeArgFunctionFloat:
  fadd d0, d0, d1
  fadd d0, d0, d2
  ret
test.testTwoArgFunction:
  add w0, w0, w1
  ret
test.testTwoArgFunctionFloat:
  fadd d0, d0, d1
  ret
test.testZeroArgFunctionFloat:
  fmov d0, #1.
  ret
test.zeroArgFunction:
  movz w0, #1
  ret