func void @test.indexing(int* %0, bool*** %1) {
  %2 := GetPointer int, int* %0[int 0]
  %3 := Load int %2
  %4 := GetPointer bool**, bool*** %1[int 0]
  %5 := Load bool** %4
  %6 := GetPointer bool**, bool*** %1[int 1]
  %7 := Load bool** %6
  %8 := GetPointer bool*, bool** %7[int 2]
  %9 := Load bool* %8
  %10 := GetPointer bool, bool* %9[int 3]
  %11 := Load bool %10
  Ret
}

func void @test.indexingAllIntegerTypes(byte* %12, int %13, byte %14, long %15) {
  %16 := GetPointer byte, byte* %12[int %13]
  %17 := Load byte %16
  %18 := GetPointer byte, byte* %12[byte %14]
  %19 := Load byte %18
  %20 := GetPointer byte, byte* %12[long %15]
  %21 := Load byte %20
  %22 := GetPointer byte, byte* %12[int 3]
  %23 := Load byte %22
  %24 := GetPointer byte, byte* %12[byte 3]
  %25 := Load byte %24
  %26 := GetPointer byte, byte* %12[long 3]
  %27 := Load byte %26
  Ret
}

type test.Tup0 {long, byte}

type test.Tup1 {std.string.String*, bool*}

func void @test.indexingWithTuple(test.Tup0** %28, test.Tup1* %29) {
  %30 := GetPointer test.Tup0*, test.Tup0** %28[int 77]
  %31 := Load test.Tup0* %30
  %32 := GetPointer byte, test.Tup0* %31.1
  %33 := Load byte %32
  %34 := GetPointer bool*, test.Tup1* %29.1
  %35 := Load bool* %34
  %36 := GetPointer bool, bool* %35[int 1]
  %37 := Load bool %36
  Ret
}

type test.Rec0 {std.string.String*, bool*}

func void @test.indexingWithRecord(test.Rec0** %38, test.Rec1* %39, int %40) {
  %41 := GetPointer test.Rec0*, test.Rec0** %38[int 77]
  %42 := Load test.Rec0* %41
  %43 := GetPointer bool*, test.Rec0* %42.1
  %44 := Load bool* %43
  %45 := GetPointer bool, bool* %44[int %40]
  %46 := Load bool %45
  Ret
}

type test.Rec1 {std.string.String*, test.Tup2**}

type test.Tup2 {byte, long}

func void @test.indexingWithRecordAndTuple(test.Rec1* %47) {
  %48 := GetPointer test.Tup2**, test.Rec1* %47.1
  %49 := Load test.Tup2** %48
  %50 := GetPointer test.Tup2*, test.Tup2** %49[int 99]
  %51 := Load test.Tup2* %50
  %52 := GetPointer long, test.Tup2* %51.1
  %53 := Load long %52
  Ret
}

func void @test.use<Function>(fn %54) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.indexing)
  Call void @test.use<Function>(@test.indexingAllIntegerTypes)
  Call void @test.use<Function>(@test.indexingWithTuple)
  Call void @test.use<Function>(@test.indexingWithRecord)
  Call void @test.use<Function>(@test.indexingWithRecordAndTuple)
  Ret 0
}