func unit @test.simpleAccesses(int* %0) {
  %1 := GetPointer int, int* %0[int 90]
  Store int %1, 1
  Ret
}

func unit @test.nestedAccesses(std.string.String**** %2, std.string.String** %3) {
  %4 := CallBuiltin std.string.String* myte_alloc(1)
  %5 := GetPointer byte*, std.string.String* %4.0
  Store byte* %5, @.S0
  %6 := GetPointer int, std.string.String* %4.1
  Store int %6, 4
  %7 := GetPointer int, std.string.String* %4.2
  Store int %7, 4
  %8 := GetPointer std.string.String***, std.string.String**** %2[int 5]
  %9 := Load std.string.String*** %8
  %10 := GetPointer std.string.String**, std.string.String*** %9[int 6]
  %11 := Load std.string.String** %10
  %12 := GetPointer std.string.String*, std.string.String** %11[int 7]
  Store std.string.String* %12, %4
  %13 := GetPointer std.string.String***, std.string.String**** %2[int 55]
  %14 := Load std.string.String*** %13
  %15 := GetPointer std.string.String**, std.string.String*** %14[int 66]
  Store std.string.String** %15, %3
  Ret
}

global byte[4] @.S0 = "test"

type test.Tup1 {byte, test.Rec1**, bool}

type test.Rec1 {bool, byte, std.string.String*}

type test.Rec2 {long*, byte}

func unit @test.indexAndAccesses(test.Tup1* %16, test.Rec2** %17) {
  %18 := CallBuiltin std.string.String* myte_alloc(1)
  %19 := GetPointer byte*, std.string.String* %18.0
  Store byte* %19, @.S1
  %20 := GetPointer int, std.string.String* %18.1
  Store int %20, 4
  %21 := GetPointer int, std.string.String* %18.2
  Store int %21, 4
  %22 := GetPointer test.Rec1**, test.Tup1* %16.1
  %23 := Load test.Rec1** %22
  %24 := GetPointer test.Rec1*, test.Rec1** %23[int 500]
  %25 := Load test.Rec1* %24
  %26 := GetPointer std.string.String*, test.Rec1* %25.2
  Store std.string.String* %26, %18
  %27 := GetPointer test.Rec2*, test.Rec2** %17[int 999]
  %28 := Load test.Rec2* %27
  %29 := GetPointer long*, test.Rec2* %28.0
  %30 := Load long* %29
  %31 := GetPointer long, long* %30[int 888]
  Store long %31, 7
  Ret
}

global byte[4] @.S1 = "test"

func int @test.main() {
  Ret 0
}