func void @test.indexing(int* %0, bool*** %1) {
  %2 := GetPointer int, int* %0[int 0]
  %3 := Load int %2
  %4 := GetPointer bool**, bool*** %1[int 0]
  %5 := Load bool** %4
  %6 := GetPointer bool**, bool*** %1[int 1]
  %7 := Load bool** %6
  %8 := GetPointer bool*, bool** %7[int 2]
  %9 := Load bool* %8
  %10 := GetPointer bool, bool* %9[int 3]
  %11 := Load bool %10
  Ret
}

func void @test.indexingAllIntegerTypes(byte* %0, int %1, byte %2, long %3) {
  %4 := GetPointer byte, byte* %0[int %1]
  %5 := Load byte %4
  %6 := GetPointer byte, byte* %0[byte %2]
  %7 := Load byte %6
  %8 := GetPointer byte, byte* %0[long %3]
  %9 := Load byte %8
  %10 := GetPointer byte, byte* %0[int 3]
  %11 := Load byte %10
  %12 := GetPointer byte, byte* %0[byte 3]
  %13 := Load byte %12
  %14 := GetPointer byte, byte* %0[long 3]
  %15 := Load byte %14
  Ret
}

type test.Tup0 {byte, long}

type test.Tup1 {std.string.String*, bool*}

func void @test.indexingWithTuple(test.Tup0** %0, test.Tup1* %1) {
  %2 := GetPointer test.Tup0*, test.Tup0** %0[int 77]
  %3 := Load test.Tup0* %2
  %4 := GetPointer byte, test.Tup0* %3.0
  %5 := Load byte %4
  %6 := GetPointer bool*, test.Tup1* %1.1
  %7 := Load bool* %6
  %8 := GetPointer bool, bool* %7[int 1]
  %9 := Load bool %8
  Ret
}

type test.Rec0 {std.string.String*, bool*}

func void @test.indexingWithRecord(test.Rec0** %0, test.Rec1* %1, int %2) {
  %3 := GetPointer test.Rec0*, test.Rec0** %0[int 77]
  %4 := Load test.Rec0* %3
  %5 := GetPointer bool*, test.Rec0* %4.1
  %6 := Load bool* %5
  %7 := GetPointer bool, bool* %6[int %2]
  %8 := Load bool %7
  Ret
}

type test.Rec1 {std.string.String*, test.Tup2**}

type test.Tup2 {byte, long}

func void @test.indexingWithRecordAndTuple(test.Rec1* %0) {
  %1 := GetPointer test.Tup2**, test.Rec1* %0.1
  %2 := Load test.Tup2** %1
  %3 := GetPointer test.Tup2*, test.Tup2** %2[int 99]
  %4 := Load test.Tup2* %3
  %5 := GetPointer long, test.Tup2* %4.1
  %6 := Load long %5
  Ret
}

func void @test.use<Function>(fn %0) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.indexing)
  Call void @test.use<Function>(@test.indexingAllIntegerTypes)
  Call void @test.use<Function>(@test.indexingWithTuple)
  Call void @test.use<Function>(@test.indexingWithRecord)
  Call void @test.use<Function>(@test.indexingWithRecordAndTuple)
  Ret 0
}