  .global _main

  .text
test.andByteImmReg:
  and w0, w0, #60
  ret
test.andByteRegImm:
  and w0, w0, #60
  ret
test.andByteRegs:
  and w0, w0, w1
  ret
test.andIntImmReg:
  and w0, w0, #60
  ret
test.andIntRegImm:
  and w0, w0, #60
  ret
test.andIntRegs:
  and w0, w0, w1
  ret
test.andLongImmReg:
  and x0, x0, #60
  ret
test.andLongRegImm:
  and x0, x0, #60
  ret
test.andLongRegs:
  and x0, x0, x1
  ret
_main:
  mov w0, wzr
  ret