  .global _main

  .text
_main:
  mov w0, wzr
  ret
test.orByteImmReg:
  orr w0, w0, #60
  ret
test.orByteRegImm:
  orr w0, w0, #60
  ret
test.orByteRegs:
  orr w0, w0, w1
  ret
test.orIntImmReg:
  orr w0, w0, #60
  ret
test.orIntRegImm:
  orr w0, w0, #60
  ret
test.orIntRegs:
  orr w0, w0, w1
  ret
test.orLongImmReg:
  orr x0, x0, #60
  ret
test.orLongRegImm:
  orr x0, x0, #60
  ret
test.orLongRegs:
  orr x0, x0, x1
  ret