  .global _main
  .lcomm test.intArray, 8

  .text
_init:
  movl $40, %edi
  call _myte_alloc
  movq %rax, test.intArray(%rip)
  ret
test.constantIndexing:
  movb (%rdi), %al
  movb 1(%rdi), %al
  movb 2(%rdi), %al
  movl (%rsi), %eax
  movl 4(%rsi), %eax
  movl 8(%rsi), %eax
  movq (%rdx), %rax
  movq 8(%rdx), %rax
  movq 16(%rdx), %rax
  movq (%rcx), %rax
  movq 8(%rcx), %rax
  movq 16(%rcx), %rax
  movb $4, 3(%rdi)
  movq $6, 40(%rdx)
  ret
test.indexIntoGlobal:
  movq test.intArray(%rip), %rax
  movl 20(%rax), %eax
  movq test.intArray(%rip), %rcx
  movl %edi, %eax
  movl (%rcx, %rax, 4), %eax
  movq test.intArray(%rip), %rax
  movl $6, 20(%rax)
  movq test.intArray(%rip), %rcx
  movl %edi, %eax
  movl $7, (%rcx, %rax, 4)
  ret
test.longConstantIndexing:
  movq $17179869184, %rax
  movl (%rdi, %rax), %eax
  ret
_main:
  leaq test.constantIndexing(%rip), %rdi
  call test.use$Function$
  leaq test.longConstantIndexing(%rip), %rdi
  call test.use$Function$
  leaq test.variableIndexing(%rip), %rdi
  call test.use$Function$
  leaq test.nestedIndexing(%rip), %rdi
  call test.use$Function$
  leaq test.indexIntoGlobal(%rip), %rdi
  call test.use$Function$
  movl $0, %eax
  ret
test.nestedIndexing:
  movq 40(%rdi), %rax
  movb 4(%rax), %al
  movq 8(%rsi), %rax
  movl 20(%rax), %eax
  movl %edx, %eax
  movq (%rdi, %rax, 8), %rax
  movb 4(%rax), %al
  movq 8(%rsi), %rcx
  movl %edx, %eax
  movl (%rcx, %rax, 4), %eax
  ret
test.use$Function$:
  movq %rdi, %rax
  ret
test.variableIndexing:
  movl %r8d, %eax
  movb (%rdi, %rax), %al
  movl %r8d, %eax
  movl (%rsi, %rax, 4), %eax
  movl %r8d, %eax
  movq (%rdx, %rax, 8), %rax
  movl %r8d, %eax
  movq (%rcx, %rax, 8), %rax
  movzx %r9b, %rax
  movb (%rdi, %rax), %al
  movzx %r9b, %rax
  movl (%rsi, %rax, 4), %eax
  movzx %r9b, %rax
  movq (%rdx, %rax, 8), %rax
  movzx %r9b, %rax
  movq (%rcx, %rax, 8), %rax
  ret