  .global _start
  .lcomm test.intArray, 8

  .text
_init:
  movl $40, %edi
  call __myte_alloc
  movq %rax, test.intArray(%rip)
  ret
test.constantIndexing:
  movb (%rdi), %al
  movb 1(%rdi), %al
  movb 2(%rdi), %al
  movl (%rsi), %eax
  movl 4(%rsi), %eax
  movl 8(%rsi), %eax
  movq (%rdx), %rax
  movq 8(%rdx), %rax
  movq 16(%rdx), %rax
  movq (%rcx), %rax
  movq 8(%rcx), %rax
  movq 16(%rcx), %rax
  movb $4, 3(%rdi)
  movq $6, 40(%rdx)
  ret
test.indexIntoGlobal:
  movq test.intArray(%rip), %rax
  movl 20(%rax), %eax
  movq test.intArray(%rip), %rax
  movl (%rax, %rdi, 4), %eax
  movq test.intArray(%rip), %rax
  movl $6, 20(%rax)
  movq test.intArray(%rip), %rax
  movl $7, (%rax, %rdi, 4)
  ret
test.longConstantIndexing:
  movq $17179869184, %rax
  movl (%rdi, %rax), %eax
  ret
_main:
  movl $0, %eax
  ret
test.nestedIndexing:
  movq 40(%rdi), %rax
  movb 4(%rax), %al
  movq 8(%rsi), %rax
  movl 20(%rax), %eax
  movq (%rdi, %rdx, 8), %rax
  movb 4(%rax), %al
  movq 8(%rsi), %rax
  movl (%rax, %rdx, 4), %eax
  ret
test.variableIndexing:
  movb (%rdi, %r8), %al
  movl (%rsi, %r8, 4), %eax
  movq (%rdx, %r8, 8), %rax
  movq (%rcx, %r8, 8), %rax
  ret