func unit @test.empty() {
  Ret
}

func unit @test.emptyParams(int %0, bool %1) {
  Ret
}

func int @test.shorthand(int %2) {
  Ret 1
}

func unit @test.withBody(int %3, bool %4) {
  %5 := Mov int 10
  branch true, @0, @1
label @0:
  %6 := Mov bool false
  continue @2
label @1:
  %7 := Mov bool false
  continue @2
label @2:
  %8 := Phi @0:%6, @1:%7
  %9 := Mov bool %8
  Ret
}

func unit @test.main() {
  %10 := Mov bool true
  Ret
}