func std.string.String* @test.testSingleStringPart() {
  %0 := CallBuiltin std.string.String* myte_alloc(1)
  %1 := GetPointer byte*, std.string.String* %0.0
  Store byte* %1, @.S4
  %2 := GetPointer int, std.string.String* %0.1
  Store int %2, 3
  %3 := GetPointer int, std.string.String* %0.2
  Store int %3, 3
  Ret %0
}

global byte[3] @.S4 = "foo"

func std.string.String* @test.testSingleExpressionPart() {
  %0 := CallBuiltin std.string.String* myte_alloc(1)
  %1 := GetPointer byte*, std.string.String* %0.0
  Store byte* %1, 0
  %2 := GetPointer int, std.string.String* %0.1
  Store int %2, 0
  %3 := GetPointer int, std.string.String* %0.2
  Store int %3, 0
  %4 := Call std.string.String* @std.int.Int.toString(1)
  Call void @std.string.String.append(%0, %4)
  Ret %0
}

func std.string.String* @test.testMultipleParts1() {
  %0 := CallBuiltin std.string.String* myte_alloc(1)
  %1 := GetPointer byte*, std.string.String* %0.0
  Store byte* %1, 0
  %2 := GetPointer int, std.string.String* %0.1
  Store int %2, 0
  %3 := GetPointer int, std.string.String* %0.2
  Store int %3, 0
  %4 := Call std.string.String* @std.int.Int.toString(1)
  Call void @std.string.String.append(%0, %4)
  %5 := CallBuiltin std.string.String* myte_alloc(1)
  %6 := GetPointer byte*, std.string.String* %5.0
  Store byte* %6, @.S0
  %7 := GetPointer int, std.string.String* %5.1
  Store int %7, 3
  %8 := GetPointer int, std.string.String* %5.2
  Store int %8, 3
  Call void @std.string.String.append(%0, %5)
  %9 := Call std.string.String* @std.int.Int.toString(2)
  Call void @std.string.String.append(%0, %9)
  Ret %0
}

global byte[3] @.S0 = "foo"

func std.string.String* @test.testMultipleParts2() {
  %0 := CallBuiltin std.string.String* myte_alloc(1)
  %1 := GetPointer byte*, std.string.String* %0.0
  Store byte* %1, @.S2
  %2 := GetPointer int, std.string.String* %0.1
  Store int %2, 3
  %3 := GetPointer int, std.string.String* %0.2
  Store int %3, 3
  %4 := Call std.string.String* @std.int.Int.toString(1)
  Call void @std.string.String.append(%0, %4)
  %5 := Call std.string.String* @std.int.Int.toString(2)
  Call void @std.string.String.append(%0, %5)
  %6 := CallBuiltin std.string.String* myte_alloc(1)
  %7 := GetPointer byte*, std.string.String* %6.0
  Store byte* %7, @.S3
  %8 := GetPointer int, std.string.String* %6.1
  Store int %8, 3
  %9 := GetPointer int, std.string.String* %6.2
  Store int %9, 3
  Call void @std.string.String.append(%0, %6)
  Ret %0
}

global byte[3] @.S2 = "foo"

global byte[3] @.S3 = "bar"

func void @test.use<Function>(fn %0) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.testSingleStringPart)
  Call void @test.use<Function>(@test.testSingleExpressionPart)
  Call void @test.use<Function>(@test.testMultipleParts1)
  Call void @test.use<Function>(@test.testMultipleParts2)
  Ret 0
}