global byte[3] @.IS0 = "foo"

global int @.IS0Size = 3

global byte[3] @.IS1 = "bar"

global int @.IS1Size = 3

func std.string.String* @test.testSingleStringPart() {
  %0 := CallBuiltin std.string.String* myte_alloc(1)
  %1 := GetPointer byte*, std.string.String* %0.0
  Store byte* %1, @.S3
  %2 := GetPointer int, std.string.String* %0.1
  Store int %2, 3
  %3 := GetPointer int, std.string.String* %0.2
  Store int %3, 3
  Ret %0
}

global byte[3] @.S3 = "foo"

func std.string.String* @test.testSingleExpressionPart() {
  %0 := CallBuiltin std.string.String* myte_alloc(1)
  %1 := GetPointer byte*, std.string.String* %0.0
  Store byte* %1, 0
  %2 := GetPointer int, std.string.String* %0.1
  Store int %2, 0
  %3 := GetPointer int, std.string.String* %0.2
  Store int %3, 0
  %4 := Call std.string.String* @std.int.Int.toString(1)
  Call void @std.string.String.append(%0, %4)
  Ret %0
}

func std.string.String* @test.testMultipleParts1() {
  %0 := CallBuiltin std.string.String* myte_alloc(1)
  %1 := GetPointer byte*, std.string.String* %0.0
  Store byte* %1, 0
  %2 := GetPointer int, std.string.String* %0.1
  Store int %2, 0
  %3 := GetPointer int, std.string.String* %0.2
  Store int %3, 0
  %4 := Call std.string.String* @std.int.Int.toString(1)
  Call void @std.string.String.append(%0, %4)
  %5 := Load int @.IS0Size
  Call void @std.string.String.appendImmutable(%0, @.IS0, %5)
  %6 := Call std.string.String* @std.int.Int.toString(2)
  Call void @std.string.String.append(%0, %6)
  Ret %0
}

func std.string.String* @test.testMultipleParts2() {
  %0 := CallBuiltin std.string.String* myte_alloc(1)
  %1 := GetPointer byte*, std.string.String* %0.0
  Store byte* %1, @.S1
  %2 := GetPointer int, std.string.String* %0.1
  Store int %2, 3
  %3 := GetPointer int, std.string.String* %0.2
  Store int %3, 3
  %4 := Call std.string.String* @std.int.Int.toString(1)
  Call void @std.string.String.append(%0, %4)
  %5 := Call std.string.String* @std.int.Int.toString(2)
  Call void @std.string.String.append(%0, %5)
  %6 := Load int @.IS1Size
  Call void @std.string.String.appendImmutable(%0, @.IS1, %6)
  Ret %0
}

global byte[3] @.S1 = "foo"

func std.string.String* @test.testRepeatedParts() {
  %0 := CallBuiltin std.string.String* myte_alloc(1)
  %1 := GetPointer byte*, std.string.String* %0.0
  Store byte* %1, @.S2
  %2 := GetPointer int, std.string.String* %0.1
  Store int %2, 3
  %3 := GetPointer int, std.string.String* %0.2
  Store int %3, 3
  %4 := Call std.string.String* @std.int.Int.toString(1)
  Call void @std.string.String.append(%0, %4)
  %5 := Load int @.IS1Size
  Call void @std.string.String.appendImmutable(%0, @.IS1, %5)
  %6 := Call std.string.String* @std.int.Int.toString(2)
  Call void @std.string.String.append(%0, %6)
  %7 := Load int @.IS0Size
  Call void @std.string.String.appendImmutable(%0, @.IS0, %7)
  %8 := Call std.string.String* @std.int.Int.toString(3)
  Call void @std.string.String.append(%0, %8)
  %9 := Load int @.IS1Size
  Call void @std.string.String.appendImmutable(%0, @.IS1, %9)
  Ret %0
}

global byte[3] @.S2 = "foo"

func void @test.use<Function>(fn %0) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.testSingleStringPart)
  Call void @test.use<Function>(@test.testSingleExpressionPart)
  Call void @test.use<Function>(@test.testMultipleParts1)
  Call void @test.use<Function>(@test.testMultipleParts2)
  Call void @test.use<Function>(@test.testRepeatedParts)
  Ret 0
}