  .global _main

  .text
_main:
  xorl %eax, %eax
  ret
test.testCompareMemoryMemory:
  movq 8(%rsp), %xmm0
  ucomisd 16(%rsp), %xmm0
  jne .L0
  jp .L0
  xorl %eax, %eax
  movq 8(%rsp), %xmm0
  ucomisd 16(%rsp), %xmm0
  sete %al
  setnp %cl
  andb %cl, %al
  jmp .L7
.L0:
  movq 8(%rsp), %xmm0
  ucomisd 16(%rsp), %xmm0
  jne .L1
  jnp .L2
.L1:
  xorl %eax, %eax
  movq 8(%rsp), %xmm0
  ucomisd 16(%rsp), %xmm0
  setne %al
  setp %cl
  orb %cl, %al
  jmp .L7
.L2:
  movq 8(%rsp), %xmm0
  ucomisd 16(%rsp), %xmm0
  jae .L3
  xorl %eax, %eax
  movq 8(%rsp), %xmm0
  ucomisd 16(%rsp), %xmm0
  setb %al
  jmp .L7
.L3:
  movq 8(%rsp), %xmm0
  ucomisd 16(%rsp), %xmm0
  ja .L4
  xorl %eax, %eax
  movq 8(%rsp), %xmm0
  ucomisd 16(%rsp), %xmm0
  setbe %al
  jmp .L7
.L4:
  movq 8(%rsp), %xmm0
  ucomisd 16(%rsp), %xmm0
  jbe .L5
  xorl %eax, %eax
  movq 8(%rsp), %xmm0
  ucomisd 16(%rsp), %xmm0
  seta %al
  jmp .L7
.L5:
  movq 8(%rsp), %xmm0
  ucomisd 16(%rsp), %xmm0
  jb .L6
  xorl %eax, %eax
  movq 8(%rsp), %xmm0
  ucomisd 16(%rsp), %xmm0
  setae %al
  jmp .L7
.L6:
  movb $1, %al
.L7:
  ret
test.testCompareMemoryRegister:
  ucomisd 8(%rsp), %xmm0
  jne .L8
  jp .L8
  xorl %eax, %eax
  ucomisd 8(%rsp), %xmm0
  sete %al
  setnp %cl
  andb %cl, %al
  jmp .L15
.L8:
  ucomisd 8(%rsp), %xmm0
  jne .L9
  jnp .L10
.L9:
  xorl %eax, %eax
  ucomisd 8(%rsp), %xmm0
  setne %al
  setp %cl
  orb %cl, %al
  jmp .L15
.L10:
  ucomisd 8(%rsp), %xmm0
  jbe .L11
  xorl %eax, %eax
  ucomisd 8(%rsp), %xmm0
  seta %al
  jmp .L15
.L11:
  ucomisd 8(%rsp), %xmm0
  jb .L12
  xorl %eax, %eax
  ucomisd 8(%rsp), %xmm0
  setae %al
  jmp .L15
.L12:
  ucomisd 8(%rsp), %xmm0
  jae .L13
  xorl %eax, %eax
  ucomisd 8(%rsp), %xmm0
  setb %al
  jmp .L15
.L13:
  ucomisd 8(%rsp), %xmm0
  ja .L14
  xorl %eax, %eax
  ucomisd 8(%rsp), %xmm0
  setbe %al
  jmp .L15
.L14:
  movb $1, %al
.L15:
  ret
test.testCompareRegisterMemory:
  ucomisd 8(%rsp), %xmm0
  jne .L16
  jp .L16
  xorl %eax, %eax
  ucomisd 8(%rsp), %xmm0
  sete %al
  setnp %cl
  andb %cl, %al
  jmp .L23
.L16:
  ucomisd 8(%rsp), %xmm0
  jne .L17
  jnp .L18
.L17:
  xorl %eax, %eax
  ucomisd 8(%rsp), %xmm0
  setne %al
  setp %cl
  orb %cl, %al
  jmp .L23
.L18:
  ucomisd 8(%rsp), %xmm0
  jae .L19
  xorl %eax, %eax
  ucomisd 8(%rsp), %xmm0
  setb %al
  jmp .L23
.L19:
  ucomisd 8(%rsp), %xmm0
  ja .L20
  xorl %eax, %eax
  ucomisd 8(%rsp), %xmm0
  setbe %al
  jmp .L23
.L20:
  ucomisd 8(%rsp), %xmm0
  jbe .L21
  xorl %eax, %eax
  ucomisd 8(%rsp), %xmm0
  seta %al
  jmp .L23
.L21:
  ucomisd 8(%rsp), %xmm0
  jb .L22
  xorl %eax, %eax
  ucomisd 8(%rsp), %xmm0
  setae %al
  jmp .L23
.L22:
  movb $1, %al
.L23:
  ret
test.testCompareRegisterRegister:
  ucomisd %xmm1, %xmm0
  jne .L24
  jp .L24
  xorl %eax, %eax
  ucomisd %xmm1, %xmm0
  sete %al
  setnp %cl
  andb %cl, %al
  jmp .L31
.L24:
  ucomisd %xmm1, %xmm0
  jne .L25
  jnp .L26
.L25:
  xorl %eax, %eax
  ucomisd %xmm1, %xmm0
  setne %al
  setp %cl
  orb %cl, %al
  jmp .L31
.L26:
  ucomisd %xmm1, %xmm0
  jae .L27
  xorl %eax, %eax
  ucomisd %xmm1, %xmm0
  setb %al
  jmp .L31
.L27:
  ucomisd %xmm1, %xmm0
  ja .L28
  xorl %eax, %eax
  ucomisd %xmm1, %xmm0
  setbe %al
  jmp .L31
.L28:
  ucomisd %xmm1, %xmm0
  jbe .L29
  xorl %eax, %eax
  ucomisd %xmm1, %xmm0
  seta %al
  jmp .L31
.L29:
  ucomisd %xmm1, %xmm0
  jb .L30
  xorl %eax, %eax
  ucomisd %xmm1, %xmm0
  setae %al
  jmp .L31
.L30:
  movb $1, %al
.L31:
  ret