  .global _start
  .lcomm test.b, 1
  .lcomm test.f, 8
  .lcomm test.i, 4
  .lcomm test.l, 8

  .data
test.constantB:
  .byte 123
test.constantF:
  .quad test.getByte
test.constantI:
  .long 123
test.constantL:
  .quad 123

  .text
_init:
  call test.getByte
  movb %al, test.b(%rip)
  call test.getInt
  movl %eax, test.i(%rip)
  call test.getLong
  movq %rax, test.l(%rip)
  call test.getFunction
  movq %rax, test.f(%rip)
  ret
test.getByte:
  movb $22, %al
  ret
test.getFunction:
  leaq test.getByte(%rip), %rax
  ret
test.getInt:
  movl $23, %eax
  ret
test.getLong:
  movq $24, %rax
  ret
_main:
  movl $0, %eax
  ret