  .global _main
  .lcomm test.t, 8

  .data
test.b:
  .byte 0
test.i:
  .long 0
test.l:
  .quad 0

  .text
_init:
  movl $4, %edi
  call _myte_alloc
  movl $1, (%rax)
  movq %rax, test.t(%rip)
  ret
_main:
  movl $4, %edi
  call _myte_alloc
  movl $0, (%rax)
  movl $0, %edi
  movq $0, %rsi
  movq %rax, %rdx
  call test.testReassignGlobals
  movl $0, %eax
  ret
test.testReassignGlobals:
  movb $4, test.b(%rip)
  movl %edi, test.i(%rip)
  imulq $13, %rsi, %rax
  movq %rax, test.l(%rip)
  movq %rdx, test.t(%rip)
  movl $4, %edi
  call _myte_alloc
  movl $2, (%rax)
  movq %rax, test.t(%rip)
  ret