  .global _main

  .data
test.b:
  .byte 0
test.f:
  .quad test.getByte
test.i:
  .long 0
test.l:
  .quad 0

  .text
test.getByte:
  movb $1, %al
  ret
_main:
  movl $0, %eax
  ret
test.testReferencing:
  movb test.b(%rip), %al
  movl test.i(%rip), %eax
  movq test.l(%rip), %rax
  movq test.f(%rip), %rax
  movl test.i(%rip), %eax
  addl %eax, %edi
  movl test.i(%rip), %ecx
  movl test.i(%rip), %eax
  addl %ecx, %eax
  movq test.f(%rip), %rax
  callq *%rax
  ret