  .global _start

  .text
_main:
  movl $0, %eax
  ret
test.testNestedReturnNoReturnRegisterMove:
  call test.testReturnsInMain
  ret
test.testReturnRegisterClobberAcrossCall:
  push %rbx
  call test.testReturnsInMain
  movl %eax, %ebx
  call test.testReturnsInMain
  addl %ebx, %eax
  pop %rbx
  ret
test.testReturnsInMain:
  movl $1, %eax
  ret
test.testReturnsInMain2:
  movl %edi, %eax
  ret
_start:
  call __myte_init
  call _main
  ret