test/parser/ast/tuple/expression.myte
{
  node: Module,
  loc: 1:0-11:1,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-11:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-11:1,
        statements: [
          {
            node: ExpressionStatement,
            loc: 4:2-4:12,
            expression: {
              node: TupleExpression,
              loc: 4:2-4:11,
              elements: [
                {
                  node: IntLiteral,
                  loc: 4:3-4:4,
                  raw: "1",
                },
                {
                  node: IntLiteral,
                  loc: 4:6-4:7,
                  raw: "3",
                },
                {
                  node: IntLiteral,
                  loc: 4:9-4:10,
                  raw: "2",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 7:2-7:25,
            expression: {
              node: TupleExpression,
              loc: 7:2-7:24,
              elements: [
                {
                  node: TupleExpression,
                  loc: 7:3-7:9,
                  elements: [
                    {
                      node: Identifier,
                      loc: 7:4-7:5,
                      name: "a",
                    },
                    {
                      node: IntLiteral,
                      loc: 7:7-7:8,
                      raw: "1",
                    },
                  ],
                },
                {
                  node: TupleExpression,
                  loc: 7:11-7:20,
                  elements: [
                    {
                      node: Identifier,
                      loc: 7:12-7:13,
                      name: "b",
                    },
                    {
                      node: Identifier,
                      loc: 7:15-7:16,
                      name: "c",
                    },
                    {
                      node: Identifier,
                      loc: 7:18-7:19,
                      name: "d",
                    },
                  ],
                },
                {
                  node: Identifier,
                  loc: 7:22-7:23,
                  name: "e",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 10:2-10:10,
            expression: {
              node: TupleExpression,
              loc: 10:2-10:9,
              elements: [
                {
                  node: IntLiteral,
                  loc: 10:3-10:4,
                  raw: "1",
                },
                {
                  node: IntLiteral,
                  loc: 10:6-10:7,
                  raw: "2",
                },
              ],
            },
          },
        ],
      },
      return: None,
      type_params: [],
      builtin: false,
      static: false,
      override: false,
    },
  ],
}