type test.Tup1<test.Tup1<byte>*> {int, test.Tup1<byte>*}

type test.Tup1<int> {int, int}

type test.Tup1<byte> {int, byte}

type test.Tup1<bool> {int, bool}

func unit @test.id<unit>(unit %0) {
  Ret %0
}

func test.Tup1<byte>* @test.id<test.Tup1<byte>*>(test.Tup1<byte>* %1) {
  Ret %1
}

func int @test.id<int>(int %2) {
  Ret %2
}

func bool @test.id<bool>(bool %3) {
  Ret %3
}

func test.Tup1<test.Tup1<byte>*>* @test.singleParameter<test.Tup1<byte>*>(test.Tup1<byte>* %4) {
  %5 := Call test.Tup1<byte>* @test.id<test.Tup1<byte>*>(%4)
  %6 := Mov test.Tup1<byte>* %5
  %7 := CallBuiltin test.Tup1<test.Tup1<byte>*>* myte_alloc(1)
  %8 := GetPointer int %7.0
  Store int %8, 1
  %9 := GetPointer test.Tup1<byte>* %7.1
  Store test.Tup1<byte>* %9, %6
  Ret %7
}

func test.Tup1<int>* @test.singleParameter<int>(int %10) {
  %11 := Call int @test.id<int>(%10)
  %12 := Mov int %11
  %13 := CallBuiltin test.Tup1<int>* myte_alloc(1)
  %14 := GetPointer int %13.0
  Store int %14, 1
  %15 := GetPointer int %13.1
  Store int %15, %12
  Ret %13
}

func test.Tup1<bool>* @test.singleParameter<bool>(bool %16) {
  %17 := Call bool @test.id<bool>(%16)
  %18 := Mov bool %17
  %19 := CallBuiltin test.Tup1<bool>* myte_alloc(1)
  %20 := GetPointer int %19.0
  Store int %20, 1
  %21 := GetPointer bool %19.1
  Store bool %21, %18
  Ret %19
}

func unit @test.testSingleParameter() {
  %22 := Call test.Tup1<int>* @test.singleParameter<int>(1)
  %23 := Call test.Tup1<bool>* @test.singleParameter<bool>(true)
  %24 := CallBuiltin test.Tup1<byte>* myte_alloc(1)
  %25 := GetPointer int %24.0
  Store int %25, 1
  %26 := GetPointer byte %24.1
  Store byte %26, 1
  %27 := Call test.Tup1<test.Tup1<byte>*>* @test.singleParameter<test.Tup1<byte>*>(%24)
  Ret
}

func fn @test.testInstantiationFromNonCallUse() {
  Ret @test.id<unit>
}

func unit @test.main() {
  Ret
}