type test.Tup1<Int> {int, int}

type test.Tup1<Bool> {int, bool}

func unit @test.testConstructor() {
  %0 := CallBuiltin test.Tup1<Int>* myte.myte_alloc(1)
  %1 := GetPointer int %0.0
  Store int %1, 1
  %2 := GetPointer int %0.1
  Store int %2, 2
  %3 := Mov test.Tup1<Int>* %0
  %4 := CallBuiltin test.Tup1<Bool>* myte.myte_alloc(1)
  %5 := GetPointer int %4.0
  Store int %5, 1
  %6 := GetPointer bool %4.1
  Store bool %6, true
  %7 := Mov test.Tup1<Bool>* %4
  Ret
}

func unit @test.testIndexing(test.Tup1<Int>* %8, test.Tup1<Bool>* %9) {
  %10 := GetPointer int %8.1
  %11 := Load int %10
  %12 := GetPointer bool %9.1
  %13 := Load bool %12
  Ret
}

func unit @test.main() {
  Ret
}