test/parser/call/basic.myte
{
  node: Module,
  loc: 1:0-13:1,
  name: {
    node: ModuleName,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-13:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-13:1,
        statements: [
          {
            node: ExpressionStatement,
            loc: 4:2-4:8,
            expression: {
              node: Call,
              loc: 4:2-4:7,
              func: {
                node: Identifier,
                loc: 4:2-4:5,
                name: "foo",
              },
              args: [],
            },
          },
          {
            node: ExpressionStatement,
            loc: 5:2-5:9,
            expression: {
              node: Call,
              loc: 5:2-5:8,
              func: {
                node: Identifier,
                loc: 5:2-5:5,
                name: "foo",
              },
              args: [
                {
                  node: IntLiteral,
                  loc: 5:6-5:7,
                  raw: "1",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 6:2-6:15,
            expression: {
              node: Call,
              loc: 6:2-6:14,
              func: {
                node: Identifier,
                loc: 6:2-6:5,
                name: "foo",
              },
              args: [
                {
                  node: IntLiteral,
                  loc: 6:6-6:7,
                  raw: "1",
                },
                {
                  node: IntLiteral,
                  loc: 6:9-6:10,
                  raw: "2",
                },
                {
                  node: IntLiteral,
                  loc: 6:12-6:13,
                  raw: "3",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 7:2-7:16,
            expression: {
              node: Call,
              loc: 7:2-7:15,
              func: {
                node: Identifier,
                loc: 7:2-7:5,
                name: "foo",
              },
              args: [
                {
                  node: IntLiteral,
                  loc: 7:6-7:7,
                  raw: "1",
                },
                {
                  node: IntLiteral,
                  loc: 7:9-7:10,
                  raw: "2",
                },
                {
                  node: IntLiteral,
                  loc: 7:12-7:13,
                  raw: "3",
                },
              ],
            },
          },
          {
            node: ExpressionStatement,
            loc: 9:2-9:10,
            expression: {
              node: Call,
              loc: 9:2-9:9,
              func: {
                node: Identifier,
                loc: 9:3-9:6,
                name: "foo",
              },
              args: [],
            },
          },
          {
            node: ExpressionStatement,
            loc: 10:2-10:19,
            expression: {
              node: Call,
              loc: 10:2-10:18,
              func: {
                node: LogicalOr,
                loc: 10:3-10:15,
                left: {
                  node: Identifier,
                  loc: 10:3-10:6,
                  name: "foo",
                },
                right: {
                  node: Identifier,
                  loc: 10:11-10:14,
                  name: "bar",
                },
              },
              args: [],
            },
          },
          {
            node: ExpressionStatement,
            loc: 12:2-12:12,
            expression: {
              node: Call,
              loc: 12:2-12:11,
              func: {
                node: Call,
                loc: 12:2-12:9,
                func: {
                  node: Call,
                  loc: 12:2-12:7,
                  func: {
                    node: Identifier,
                    loc: 12:2-12:5,
                    name: "foo",
                  },
                  args: [],
                },
                args: [],
              },
              args: [],
            },
          },
        ],
      },
      return: None,
      type_params: [],
      is_public: false,
      is_builtin: false,
      is_static: false,
      is_override: false,
    },
  ],
}