#!/bin/bash

set -e

CURRENT_DIR=$(cd "$(dirname "$0")" && pwd)
ROOT_DIR=$(dirname "$CURRENT_DIR")

# Set up and build library
BUILD_DIR="$ROOT_DIR/build"
LIB_DIR="$BUILD_DIR/lib"
LIB_RUNTIME_DIR="$LIB_DIR/runtime"
LIB_STDLIB_DIR="$LIB_DIR/stdlib"
LIB_GC_DIR="$LIB_DIR/gc"
rm -rf "$LIB_RUNTIME_DIR" "$LIB_STDLIB_DIR"
mkdir -p "$BUILD_DIR"

# Build boehm gc if it has not already been built
if [[ ! -f "$LIB_GC_DIR/libgc.a" ]]; then
  "$ROOT_DIR/scripts/build_boehm_gc"
fi

# Copy library files into build directory
cp -r "$ROOT_DIR/lib" "$BUILD_DIR"
cd "$LIB_RUNTIME_DIR"

# Detect current OS
ALL_OS_NAMES=(linux macos)
case "$(uname -s)" in
  Linux)
    CURRENT_OS=linux
    ;;
  Darwin)
    CURRENT_OS=macos
    ;;
  *)
    echo "Unsupported operating system $(uname -s)"
    exit 1
    ;;
esac

# Filter files to only those for this OS
FILES=()
for FILE in *.c *.S; do
  for OS_NAME in "${ALL_OS_NAMES[@]}"; do
    if [ "$OS_NAME" != "$CURRENT_OS" ] && [[ "$FILE" = *"$OS_NAME"* ]]; then
      continue 2
    fi
  done

  FILES+=("$FILE")
done

# Build runtime library
clang -O2 --include-directory="$LIB_GC_DIR/include" -c "${FILES[@]}"
ar rcs libmyte.a ./*.o