#!/bin/bash

set -e

CURRENT_DIR=$(cd "$(dirname "$0")" && pwd)
ROOT_DIR=$(dirname "$CURRENT_DIR")

TAR="$ROOT_DIR/deps/gc-8.0.6.tar.gz"
BOEHM_DIR="$ROOT_DIR/boehm"
LIB_GC_DIR="$ROOT_DIR/build/lib/gc"

# Clear workspace before building
rm -rf "$BOEHM_DIR"
mkdir "$BOEHM_DIR"

# Unpack source code to directory
echo "Unpacking Boehm GC"
tar -xf "$TAR" -C "$BOEHM_DIR" --strip-components=1

# Build source code
echo "Building Boehm GC"
(cd "$BOEHM_DIR" && ./configure --prefix="$BOEHM_DIR/out" --disable-threads --enable-static)
(cd "$BOEHM_DIR" && make install)

# Copy source code to built lib
rm -rf "$LIB_GC_DIR"
mkdir -p "$LIB_GC_DIR"
cp "$BOEHM_DIR/out/lib/libgc.a" "$LIB_GC_DIR/libgc.a"
cp -r "$BOEHM_DIR/out/include" "$LIB_GC_DIR/include"

# Clean up
rm -rf "$BOEHM_DIR"