#!/bin/bash

set -e

CURRENT_DIR=$(cd "$(dirname "$0")" && pwd)
ROOT_DIR=$(dirname "$CURRENT_DIR")

# Build myte bytecode
cd "$ROOT_DIR/src"
opam exec -- dune build myte.bc --no-print-directory

. "$CURRENT_DIR/setup_myte_env"

ocamldebug "$ROOT_DIR/_build/default/src/myte.bc" "$@"