#!/bin/sh

set -e

CURRENT_DIR=$(cd "$(dirname "$0")" && pwd)
ROOT_DIR=$(dirname "$CURRENT_DIR")

cd "$ROOT_DIR"
ML_FILES=$(find src test -type f -name "*.ml")
MLI_FILES=$(find src test -type f -name "*.mli")

# Intentional word splitting
opam exec -- ocamlformat -i $ML_FILES $MLI_FILES
