#!/bin/bash

set -e

CURRENT_DIR=$(cd "$(dirname "$0")" && pwd)
ROOT_DIR=$(dirname "$CURRENT_DIR")

cd "$ROOT_DIR"
ML_FILES=$(find src test -type f -name "*.ml")
MLI_FILES=$(find src test -type f -name "*.mli")

# Intentional word splitting
opam exec -- ocamlformat -i $ML_FILES $MLI_FILES

# Format C files
H_FILES=$(find lib -type f -name "*.h")
C_FILES=$(find lib -type f -name "*.c")
clang-format -i $H_FILES $C_FILES
