#!/bin/sh

set -e

CURRENT_DIR=$(cd "$(dirname "$0")" && pwd)
ROOT_DIR=$(dirname "$CURRENT_DIR")

cd "$ROOT_DIR"

# Clear build directory in preparation for build
rm -rf "$ROOT_DIR/_build"

# Build myte binary statically linked with musl c
docker run --rm -i -w /myte -v "$(pwd):/myte" ocaml/opam:alpine-ocaml-4.09 bash <<EOF
  opam install . --deps-only --yes &&
  ./scripts/build --profile static
  exit
EOF