#!/bin/bash

set -e

CURRENT_DIR=$(cd "$(dirname "$0")" && pwd)
ROOT_DIR=$(dirname "$CURRENT_DIR")

xcrun xctrace record \
  --env MYTEPATH="$ROOT_DIR/build" \
  --template 'Time Profiler' \
  --launch -- "$ROOT_DIR/_build/default/src/myte.exe" $@