test/parser/ast/if/basic.myte
{
  node: Program,
  loc: 1:0-14:1,
  toplevels: [
    {
      node: Function,
      loc: 1:0-14:1,
      name: {
        node: Identifier,
        loc: 1:4-1:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 1:11-14:1,
        statements: [
          {
            node: If,
            loc: 2:2-2:14,
            test: {
              node: Identifier,
              loc: 2:6-2:10,
              name: "test",
            },
            conseq: {
              node: ExpressionStatement,
              loc: 2:12-2:14,
              expression: {
                node: IntLiteral,
                loc: 2:12-2:13,
                value: 1,
                raw: "1",
              },
            },
            altern: None,
          },
          {
            node: If,
            loc: 4:2-4:14,
            test: {
              node: Identifier,
              loc: 4:6-4:10,
              name: "test",
            },
            conseq: {
              node: Block,
              loc: 4:12-4:14,
              statements: [],
            },
            altern: None,
          },
          {
            node: If,
            loc: 6:2-8:3,
            test: {
              node: Identifier,
              loc: 6:6-6:10,
              name: "test",
            },
            conseq: {
              node: Block,
              loc: 6:12-7:3,
              statements: [],
            },
            altern: {
              node: Block,
              loc: 7:9-8:3,
              statements: [],
            },
          },
          {
            node: If,
            loc: 10:2-13:3,
            test: {
              node: Identifier,
              loc: 10:6-10:10,
              name: "test",
            },
            conseq: {
              node: Block,
              loc: 10:12-11:3,
              statements: [],
            },
            altern: {
              node: If,
              loc: 11:9-13:3,
              test: {
                node: Identifier,
                loc: 11:13-11:18,
                name: "test2",
              },
              conseq: {
                node: Block,
                loc: 11:20-12:3,
                statements: [],
              },
              altern: {
                node: Block,
                loc: 12:9-13:3,
                statements: [],
              },
            },
          },
        ],
      },
      return: None,
    },
  ],
}