func unit @test.test() {
  %0 := CallBuiltin std.string.String* myte_alloc(1)
  %1 := GetPointer byte* %0.0
  Store byte* %1, @.S0
  %2 := GetPointer int %0.1
  Store int %2, 3
  %3 := GetPointer int %0.2
  Store int %3, 3
  %4 := CallBuiltin std.string.String* myte_alloc(1)
  %5 := GetPointer byte* %4.0
  Store byte* %5, @.S1
  %6 := GetPointer int %4.1
  Store int %6, 6
  %7 := GetPointer int %4.2
  Store int %7, 6
  Ret
}

global byte[3] @.S0 = "foo"

global byte[6] @.S1 = "barbaz"

func unit @test.main() {
  Ret
}