test/parser/comment/block.myte
{
  node: Program,
  loc: 1:0-12:1,
  toplevels: [
    {
      node: Function,
      loc: 1:0-12:1,
      name: {
        node: Identifier,
        loc: 1:4-1:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 1:11-12:1,
        statements: [
          {
            node: ExpressionStatement,
            loc: 2:2-2:18,
            expression: {
              node: StringLiteral,
              loc: 2:2-2:17,
              value: "empty comment",
            },
          },
          {
            node: ExpressionStatement,
            loc: 4:2-4:16,
            expression: {
              node: StringLiteral,
              loc: 4:2-4:15,
              value: "single line",
            },
          },
          {
            node: ExpressionStatement,
            loc: 6:2-6:14,
            expression: {
              node: StringLiteral,
              loc: 6:2-6:13,
              value: "multiline",
            },
          },
          {
            node: ExpressionStatement,
            loc: 11:2-11:19,
            expression: {
              node: StringLiteral,
              loc: 11:2-11:18,
              value: "after comments",
            },
          },
        ],
      },
      return: None,
    },
  ],
}