test/parser/comment/block.myte
{
  node: Module,
  loc: 1:0-14:1,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-14:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-14:1,
        statements: [
          {
            node: ExpressionStatement,
            loc: 4:2-4:18,
            expression: {
              node: StringLiteral,
              loc: 4:2-4:17,
              value: "empty comment",
            },
          },
          {
            node: ExpressionStatement,
            loc: 6:2-6:16,
            expression: {
              node: StringLiteral,
              loc: 6:2-6:15,
              value: "single line",
            },
          },
          {
            node: ExpressionStatement,
            loc: 8:2-8:14,
            expression: {
              node: StringLiteral,
              loc: 8:2-8:13,
              value: "multiline",
            },
          },
          {
            node: ExpressionStatement,
            loc: 13:2-13:19,
            expression: {
              node: StringLiteral,
              loc: 13:2-13:18,
              value: "after comments",
            },
          },
        ],
      },
      return: None,
      type_params: [],
      builtin: false,
    },
  ],
}