test/parser/comment/line.myte
{
  node: Program,
  loc: 1:0-9:1,
  toplevels: [
    {
      node: Function,
      loc: 1:0-9:1,
      name: {
        node: Identifier,
        loc: 1:4-1:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 1:11-9:1,
        statements: [
          {
            node: ExpressionStatement,
            loc: 2:2-2:18,
            expression: {
              node: StringLiteral,
              loc: 2:2-2:17,
              value: "empty comment",
            },
          },
          {
            node: ExpressionStatement,
            loc: 4:2-4:14,
            expression: {
              node: StringLiteral,
              loc: 4:2-4:13,
              value: "with text",
            },
          },
          {
            node: ExpressionStatement,
            loc: 7:2-7:22,
            expression: {
              node: StringLiteral,
              loc: 7:2-7:21,
              value: "terminated by eof",
            },
          },
        ],
      },
      return: None,
    },
  ],
}