test/parser/comment/line.myte
{
  node: Program,
  loc: 1:0-11:1,
  module: {
    node: ScopedIdentifier,
    loc: 1:7-1:11,
    scopes: [],
    name: {
      node: Identifier,
      loc: 1:7-1:11,
      name: "Test",
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-11:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-11:1,
        statements: [
          {
            node: ExpressionStatement,
            loc: 4:2-4:18,
            expression: {
              node: StringLiteral,
              loc: 4:2-4:17,
              value: "empty comment",
            },
          },
          {
            node: ExpressionStatement,
            loc: 6:2-6:14,
            expression: {
              node: StringLiteral,
              loc: 6:2-6:13,
              value: "with text",
            },
          },
          {
            node: ExpressionStatement,
            loc: 9:2-9:22,
            expression: {
              node: StringLiteral,
              loc: 9:2-9:21,
              value: "terminated by eof",
            },
          },
        ],
      },
      return: None,
    },
  ],
}