test/parser/comment/line.myte
{
  node: Program,
  loc: 1:0-8:0,
  statements: [
    {
      node: ExpressionStatement,
      loc: 1:0-1:16,
      expression: {
        node: StringLiteral,
        loc: 1:0-1:15,
        value: "empty comment",
      },
    },
    {
      node: ExpressionStatement,
      loc: 3:0-3:12,
      expression: {
        node: StringLiteral,
        loc: 3:0-3:11,
        value: "with text",
      },
    },
    {
      node: ExpressionStatement,
      loc: 6:0-6:20,
      expression: {
        node: StringLiteral,
        loc: 6:0-6:19,
        value: "terminated by eof",
      },
    },
  ],
}