type _ZeroSize {}

global _ZeroSize @_ZeroSize = uninitialized

func bool @test.use<Bool>(bool %0) {
  Ret %0
}

func fn @test.use<Function>(fn %1) {
  Ret %1
}

func int @test.use<Int>(int %2) {
  Ret %2
}

func void @test.unit() {
  Ret
}

func void @test.testInt() {
  %3 := Call int @test.use<Int>(-56)
  %4 := Call int @test.use<Int>(3)
  %5 := Call int @test.use<Int>(-1)
  %6 := Call int @test.use<Int>(14)
  %7 := Call int @test.use<Int>(8)
  %8 := Call int @test.use<Int>(1)
  %9 := Call int @test.use<Int>(8)
  %10 := Call int @test.use<Int>(14)
  %11 := Call int @test.use<Int>(6)
  %12 := Call int @test.use<Int>(16)
  %13 := Call int @test.use<Int>(-1)
  %14 := Call int @test.use<Int>(1073741823)
  %15 := Call bool @test.use<Bool>(false)
  Ret
}

func void @test.testByte() {
  %16 := Call int @test.use<Int>(-56)
  %17 := Call int @test.use<Int>(3)
  %18 := Call int @test.use<Int>(-1)
  %19 := Call int @test.use<Int>(14)
  %20 := Call int @test.use<Int>(8)
  %21 := Call int @test.use<Int>(1)
  %22 := Call int @test.use<Int>(8)
  %23 := Call int @test.use<Int>(14)
  %24 := Call int @test.use<Int>(6)
  %25 := Call int @test.use<Int>(16)
  %26 := Call int @test.use<Int>(-1)
  %27 := Call int @test.use<Int>(1073741823)
  %28 := Call bool @test.use<Bool>(false)
  Ret
}

func void @test.testLong() {
  %29 := Call int @test.use<Int>(-56)
  %30 := Call int @test.use<Int>(3)
  %31 := Call int @test.use<Int>(-1)
  %32 := Call int @test.use<Int>(14)
  %33 := Call int @test.use<Int>(8)
  %34 := Call int @test.use<Int>(1)
  %35 := Call int @test.use<Int>(8)
  %36 := Call int @test.use<Int>(14)
  %37 := Call int @test.use<Int>(6)
  %38 := Call int @test.use<Int>(16)
  %39 := Call int @test.use<Int>(-1)
  %40 := Call int @test.use<Int>(1073741823)
  %41 := Call bool @test.use<Bool>(false)
  Ret
}

func void @test.testBool() {
  %42 := Call bool @test.use<Bool>(false)
  %43 := Call bool @test.use<Bool>(false)
  %44 := Call bool @test.use<Bool>(true)
  %45 := Call bool @test.use<Bool>(false)
  %46 := Call bool @test.use<Bool>(true)
  Ret
}

func void @test.testUnit() {
  %47 := Call bool @std.unit.Unit.equals(@_ZeroSize)
  %48 := Call bool @test.use<Bool>(%47)
  %49 := Call bool @std.unit.Unit.equals(@_ZeroSize)
  %50 := LogNot %49
  %51 := Call bool @test.use<Bool>(%50)
  Call void @test.unit()
  Call void @test.unit()
  %52 := Call bool @std.unit.Unit.equals(@_ZeroSize)
  %53 := Call bool @test.use<Bool>(%52)
  Call void @test.unit()
  Call void @test.unit()
  %54 := Call bool @std.unit.Unit.equals(@_ZeroSize)
  %55 := LogNot %54
  %56 := Call bool @test.use<Bool>(%55)
  Ret
}

func void @test.testShift() {
  %57 := Call int @test.use<Int>(4)
  %58 := Call int @test.use<Int>(4)
  Ret
}

func int @test.main() {
  %59 := Call fn @test.use<Function>(@test.testInt)
  %60 := Call fn @test.use<Function>(@test.testByte)
  %61 := Call fn @test.use<Function>(@test.testLong)
  %62 := Call fn @test.use<Function>(@test.testBool)
  %63 := Call fn @test.use<Function>(@test.testUnit)
  %64 := Call fn @test.use<Function>(@test.testShift)
  Ret 0
}