func int @test.test1(bool %0) {
  branch %0, @1, @0
label @0:
  continue @1
label @1:
  %1 := Phi int @test.test1:2, @0:3
  Ret %1
}

func int @test.test2(bool %2, int %3) {
  branch %2, @3, @2
label @2:
  continue @3
label @3:
  %4 := Phi int @test.test2:3, @2:%3
  %5 := Add int %4, 2
  Ret %5
}

func void @test.test3() {
  continue @4
label @4:
  %7 := Phi int @test.test3:1, @5:%6
  %8 := Eq int %7, 2
  branch %8, @5, @6
label @5:
  %6 := Add int %7, 1
  continue @4
label @6:
  %9 := Neg int %7
  Ret
}

func void @test.use<Function>(fn %10) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.test1)
  Call void @test.use<Function>(@test.test2)
  Call void @test.use<Function>(@test.test3)
  Ret 0
}