func int @test.test1(long %0) {
  %1 := Eq long %0, 3
  branch %1, @1, @0
label @0:
  continue @1
label @1:
  %2 := Phi int @test.test1:2, @0:3
  Ret %2
}

func int @test.test2(long %0, int %1) {
  %2 := Eq long %0, 3
  branch %2, @1, @0
label @0:
  continue @1
label @1:
  %3 := Phi int @test.test2:3, @0:%1
  %4 := Add int %3, 2
  Ret %4
}

func void @test.test3() {
  continue @0
label @0:
  %1 := Phi int @test.test3:1, @1:%0
  %2 := Eq int %1, 2
  branch %2, @1, @2
label @1:
  %0 := Add int %1, 1
  continue @0
label @2:
  %3 := Neg int %1
  Ret
}

func void @test.use<Function>(fn %0) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.test1)
  Call void @test.use<Function>(@test.test2)
  Call void @test.use<Function>(@test.test3)
  Ret 0
}