func int @test.test1(bool %0) {
  branch %0, @1, @0
label @0:
  continue @1
label @1:
  %1 := Phi int @test.test1:2, @0:3
  Ret %1
}

func int @test.test2(bool %0, int %1) {
  branch %0, @1, @0
label @0:
  continue @1
label @1:
  %2 := Phi int @test.test2:3, @0:%1
  %3 := Add int %2, 2
  Ret %3
}

func void @test.test3() {
  continue @0
label @0:
  %1 := Phi int @test.test3:1, @1:%0
  %2 := Eq int %1, 2
  branch %2, @1, @2
label @1:
  %0 := Add int %1, 1
  continue @0
label @2:
  %3 := Neg int %1
  Ret
}

func void @test.use<Function>(fn %0) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.test1)
  Call void @test.use<Function>(@test.test2)
  Call void @test.use<Function>(@test.test3)
  Ret 0
}