func void @test.byteSignExtension() {
  %0 := Call int @test.use<Int>(1)
  %1 := Call int @test.use<Int>(-1)
  %2 := Call long @test.use<Long>(1)
  %3 := Call long @test.use<Long>(-1)
  Ret
}

func void @test.intSignExtension() {
  %0 := Call long @test.use<Long>(1)
  %1 := Call long @test.use<Long>(-1)
  Ret
}

func void @test.boolZeroExtension() {
  %0 := Call byte @test.use<Option<Bool>>(0)
  %1 := Call byte @test.use<Option<Bool>>(1)
  Ret
}

func void @test.byteZeroExtension() {
  %0 := Call int @test.use<Option<Byte>>(1)
  %1 := Call int @test.use<Option<Byte>>(255)
  Ret
}

func void @test.intZeroExtension() {
  %0 := Call long @test.use<Option<Int>>(1)
  %1 := Call long @test.use<Option<Int>>(4294967295)
  Ret
}

func void @test.intTruncation() {
  %0 := Call byte @test.use<Byte>(1)
  %1 := Call byte @test.use<Byte>(127)
  %2 := Call byte @test.use<Byte>(-128)
  %3 := Call byte @test.use<Byte>(-1)
  %4 := Call byte @test.use<Byte>(-128)
  %5 := Call byte @test.use<Byte>(127)
  Ret
}

func void @test.longTruncation() {
  %0 := Call byte @test.use<Byte>(1)
  %1 := Call byte @test.use<Byte>(127)
  %2 := Call byte @test.use<Byte>(-128)
  %3 := Call byte @test.use<Byte>(-1)
  %4 := Call byte @test.use<Byte>(-128)
  %5 := Call byte @test.use<Byte>(127)
  %6 := Call int @test.use<Int>(1)
  %7 := Call int @test.use<Int>(2147483647)
  %8 := Call int @test.use<Int>(-2147483648)
  %9 := Call int @test.use<Int>(-1)
  %10 := Call int @test.use<Int>(-2147483648)
  %11 := Call int @test.use<Int>(2147483647)
  Ret
}

func byte @test.use<Byte>(byte %0) {
  Ret %0
}

func int @test.use<Int>(int %0) {
  Ret %0
}

func long @test.use<Long>(long %0) {
  Ret %0
}

func byte @test.use<Option<Bool>>(byte %0) {
  Ret %0
}

func int @test.use<Option<Byte>>(int %0) {
  Ret %0
}

func long @test.use<Option<Int>>(long %0) {
  Ret %0
}

func int @test.main() {
  Ret 0
}