global int @t.int1 = 3

global bool @t.bool1 = false

global int @t.int2 = -286

global bool @t.bool2 = true

global bool @t.mixed = true

func void @t.useBool(bool %0) {
  Ret
}

func void @t.useInt(int %1) {
  Ret
}

func bool @t.rand() {
  Ret true
}

func int @t.main() {
  Call void @t.useInt(6)
  Call void @t.useBool(false)
  %2 := Call bool @t.rand()
  Call void @t.useBool(true)
  Call void @t.useAllGlobals()
  Ret 0
}

func void @t.useAllGlobals() {
  %3 := Load int @t.int1
  Call void @t.useInt(%3)
  %4 := Load bool @t.bool1
  Call void @t.useBool(%4)
  %5 := Load int @t.int2
  Call void @t.useInt(%5)
  %6 := Load bool @t.bool2
  Call void @t.useBool(%6)
  %7 := Load bool @t.mixed
  Call void @t.useBool(%7)
  Ret
}