global int @test.int3 = 2

global int @test.int4 = 9

func void @test.testFolded() {
  Call void @test.use<Int>(10)
  Call void @test.use<Int>(68)
  Call void @test.use<Int>(-132)
  Ret
}

func void @test.testNotFolded() {
  %0 := Load int @test.int3
  %1 := Mul int %0, 2
  Call void @test.use<Int>(%1)
  %2 := Load int @test.int4
  %3 := Mul int %2, 3
  Call void @test.use<Int>(%3)
  Ret
}

func void @test.use<Function>(fn %4) {
  Ret
}

func void @test.use<Int>(int %5) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.testFolded)
  Call void @test.use<Function>(@test.testNotFolded)
  Ret 0
}