global int @test.int3 = 2

global int @test.int4 = 9

func unit @test.testFolded() {
  %0 := Call unit @test.use<int>(10)
  %1 := Call unit @test.use<int>(68)
  %2 := Call unit @test.use<int>(-132)
  Ret
}

func unit @test.testNotFolded() {
  %3 := Load int @test.int3
  %4 := Mul int %3, 2
  %5 := Call unit @test.use<int>(%4)
  %6 := Load int @test.int4
  %7 := Mul int %6, 3
  %8 := Call unit @test.use<int>(%7)
  Ret
}

func unit @test.use<fn>(fn %9) {
  Ret
}

func unit @test.use<int>(int %10) {
  Ret
}

func int @test.main() {
  %11 := Call unit @test.use<fn>(@test.testFolded)
  %12 := Call unit @test.use<fn>(@test.testNotFolded)
  Ret 0
}