func int @move_in_previous_block.main() {
  branch true, @0, @1
label @0:
  %0 := Mov int 2
  continue @2
label @1:
  %0 := Mov int 3
  continue @2
label @2:
  %1 := Neg int %0
  Call void @move_in_previous_block.multiple()
  Ret 0
}

func void @move_in_previous_block.multiple() {
  branch true, @0, @1
label @0:
  %0 := Mov int 3
  %1 := Mov int 4
  continue @2
label @1:
  %0 := Mov int 5
  %1 := Mov int 6
  continue @2
label @2:
  %2 := Add int %0, %1
  Ret
}