func unit @_init() {
  Ret
}

func int @move_in_previous_block.main() {
  branch true, @0, @1
label @0:
  %0 := Mov int 2
  continue @2
label @1:
  %0 := Mov int 3
  continue @2
label @2:
  %1 := Neg int %0
  %2 := Call unit @move_in_previous_block.multiple()
  Ret 0
}

func unit @move_in_previous_block.multiple() {
  branch true, @3, @4
label @3:
  %3 := Mov int 3
  %4 := Mov int 4
  continue @5
label @4:
  %3 := Mov int 5
  %4 := Mov int 6
  continue @5
label @5:
  %5 := Add int %3, %4
  Ret
}