func void @_init() {
  Ret
}

func void @test.swap() {
  %0 := Mov int 1
  %1 := Mov int 2
  continue @0
label @0:
  branch true, @1, @2
label @1:
  %2 := Mov int %1
  %1 := Mov int %0
  %0 := Mov int %2
  continue @0
label @2:
  Ret
}

func void @test.doubleSwap() {
  %3 := Mov int 1
  %4 := Mov int 2
  %5 := Mov int 3
  %6 := Mov int 4
  continue @3
label @3:
  branch true, @4, @5
label @4:
  %7 := Mov int %4
  %4 := Mov int %3
  %3 := Mov int %7
  %8 := Mov int %6
  %6 := Mov int %5
  %5 := Mov int %8
  continue @3
label @5:
  Ret
}

func void @test.longSwap() {
  %9 := Mov int 1
  %10 := Mov int 2
  %11 := Mov int 3
  %12 := Mov int 4
  continue @6
label @6:
  branch true, @7, @8
label @7:
  %13 := Mov int %10
  %10 := Mov int %11
  %11 := Mov int %12
  %12 := Mov int %9
  %9 := Mov int %13
  continue @6
label @8:
  Ret
}

func void @test.use<Function>(fn %14) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.swap)
  Call void @test.use<Function>(@test.doubleSwap)
  Call void @test.use<Function>(@test.longSwap)
  Ret 0
}