func void @test.swap() {
  %0 := Mov int 1
  %1 := Mov int 2
  continue @0
label @0:
  branch true, @1, @2
label @1:
  %2 := Mov int %1
  %1 := Mov int %0
  %0 := Mov int %2
  continue @0
label @2:
  Ret
}

func void @test.doubleSwap() {
  %0 := Mov int 1
  %1 := Mov int 2
  %2 := Mov int 3
  %3 := Mov int 4
  continue @0
label @0:
  branch true, @1, @2
label @1:
  %4 := Mov int %1
  %1 := Mov int %0
  %0 := Mov int %4
  %5 := Mov int %3
  %3 := Mov int %2
  %2 := Mov int %5
  continue @0
label @2:
  Ret
}

func void @test.longSwap() {
  %0 := Mov int 1
  %1 := Mov int 2
  %2 := Mov int 3
  %3 := Mov int 4
  continue @0
label @0:
  branch true, @1, @2
label @1:
  %4 := Mov int %1
  %1 := Mov int %2
  %2 := Mov int %3
  %3 := Mov int %0
  %0 := Mov int %4
  continue @0
label @2:
  Ret
}

func void @test.use<Function>(fn %0) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.swap)
  Call void @test.use<Function>(@test.doubleSwap)
  Call void @test.use<Function>(@test.longSwap)
  Ret 0
}