func void @_init() {
  Ret
}

func void @split_incoming_edge.inexhaustiveIf() {
  %0 := Eq long 3, 3
  branch %0, @0, @1
label @0:
  %1 := Mov int 2
  continue @2
label @1:
  %1 := Mov int 1
  continue @2
label @2:
  %2 := Neg int %1
  Ret
}

func void @split_incoming_edge.loop() {
  %0 := Mov int 1
  continue @0
label @0:
  %1 := Eq long 3, 3
  branch %1, @1, @4
label @1:
  %2 := Neg int %0
  %3 := Eq long 1, 3
  branch %3, @2, @3
label @2:
  %0 := Mov int 2
  continue @0
label @3:
  %4 := Mov int 3
  continue @5
label @4:
  %4 := Mov int %0
  continue @5
label @5:
  %5 := Neg int %4
  Ret
}

func void @split_incoming_edge.multiple() {
  %0 := Eq long 3, 3
  branch %0, @0, @1
label @0:
  %1 := Mov int 3
  %2 := Mov int 4
  continue @2
label @1:
  %1 := Mov int 1
  %2 := Mov int 2
  continue @2
label @2:
  %3 := Add int %1, %2
  Ret
}

func void @split_incoming_edge.use<Function>(fn %0) {
  Ret
}

func int @split_incoming_edge.main() {
  Call void @split_incoming_edge.use<Function>(@split_incoming_edge.inexhaustiveIf)
  Call void @split_incoming_edge.use<Function>(@split_incoming_edge.loop)
  Call void @split_incoming_edge.use<Function>(@split_incoming_edge.multiple)
  Ret 0
}