test/parser/ast/literals/bool.myte
{
  node: Program,
  loc: 1:0-2:6,
  statements: [
    {
      node: ExpressionStatement,
      loc: 1:0-1:5,
      expression: {
        node: BoolLiteral,
        loc: 1:0-1:4,
        value: true,
      },
    },
    {
      node: ExpressionStatement,
      loc: 2:0-2:6,
      expression: {
        node: BoolLiteral,
        loc: 2:0-2:5,
        value: false,
      },
    },
  ],
}