test/parser/ast/literals/int.myte
{
  node: Program,
  loc: 1:0-3:1,
  toplevels: [
    {
      node: Function,
      loc: 1:0-3:1,
      name: {
        node: Identifier,
        loc: 1:4-1:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 1:11-3:1,
        statements: [
          {
            node: ExpressionStatement,
            loc: 2:2-2:4,
            expression: {
              node: IntLiteral,
              loc: 2:2-2:3,
              value: 1,
              raw: "1",
            },
          },
        ],
      },
      return: None,
    },
  ],
}