test/parser/ast/literals/unit.myte
{
  node: Module,
  loc: 1:0-5:1,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-5:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-5:1,
        statements: [
          {
            node: VariableDeclaration,
            loc: 4:2-4:13,
            kind: Immutable,
            pattern: {
              node: ScopedIdentifier,
              loc: 4:6-4:7,
              scopes: [],
              name: {
                node: Identifier,
                loc: 4:6-4:7,
                name: "u",
              },
            },
            init: {
              node: Unit,
              loc: 4:10-4:12,
            },
            annot: None,
          },
        ],
      },
      return: None,
      type_params: [],
      builtin: false,
      static: false,
      override: false,
    },
  ],
}