global int @test.global = 0

func void @test.eliminatedInstructions(int %0, int %1, int %2) {
  %3 := Add int %0, 3
  %4 := Add int %3, %1
  %5 := Add int %4, 4
  %6 := Add int %5, %2
  Call void @test.use<Int>(%6)
  Ret
}

func void @test.loadsEliminated() {
  %0 := Load int @test.global
  %1 := Add int %0, 2
  Call void @test.use<Int>(%1)
  Ret
}

func int @test.ignoredInstructions() {
  Call void @test.use<Int>(2)
  Store int @test.global, 2
  Ret 3
}

func void @test.use<Int>(int %0) {
  Ret
}

func int @test.main() {
  Ret 0
}