  .global _main

  .text
test.bool:
  movb $1, %al
  ret
_main:
  movl $0, %eax
  ret
test.testIfWithExpressions:
  push %rbx
  push %r12
  movl %edi, %r12d
  movl %esi, %ebx
  call test.bool
  testb %al, %al
  je .L0
  addl %r12d, %ebx
  jmp .L1
.L0:
  imull %r12d, %ebx
  addl %ebx, %r12d
  movl %r12d, %ebx
.L1:
  movl %ebx, %eax
  pop %r12
  pop %rbx
  ret
test.testNestedIfStatementInExpressionPosition:
  call test.bool
  testb %al, %al
  je .L3
  call test.bool
  testb %al, %al
  je .L2
  movl $1, %eax
  jmp .L5
.L2:
  movl $2, %eax
  jmp .L5
.L3:
  call test.bool
  testb %al, %al
  je .L4
  movl $3, %eax
  jmp .L5
.L4:
  movl $4, %eax
.L5:
  ret
test.testSimpleIf:
  call test.bool
  testb %al, %al
  je .L6
  movl $1, %eax
  jmp .L7
.L6:
  movl $2, %eax
.L7:
  ret