  .global _main

  .data
  .balign 8
_vtable$std.bool.Bool$std.string.ToString:
  .quad _trampoline$std.bool.Bool.toString
_vtable$std.byte.Byte$std.string.ToString:
  .quad _trampoline$std.byte.Byte.toString
_vtable$std.int.Int$std.string.ToString:
  .quad _trampoline$std.int.Int.toString
_vtable$std.long.Long$std.string.ToString:
  .quad _trampoline$std.long.Long.toString
_vtable$std.unit.Unit$std.string.ToString:
  .quad std.unit.Unit.toString

  .text
_trampoline$std.bool.Bool.toString:
  movb (%rdi), %dil
  call std.bool.Bool.toString
  ret
_trampoline$std.byte.Byte.toString:
  movb (%rdi), %dil
  call std.byte.Byte.toString
  ret
_trampoline$std.int.Int.toString:
  movl (%rdi), %edi
  call std.int.Int.toString
  ret
_trampoline$std.long.Long.toString:
  movq (%rdi), %rdi
  call std.long.Long.toString
  ret
_main:
  leaq test.testUnitPromotion(%rip), %rdi
  call test.use$Function$
  leaq test.testBoolPromotion(%rip), %rdi
  call test.use$Function$
  leaq test.testBytePromotion(%rip), %rdi
  call test.use$Function$
  leaq test.testIntPromotion(%rip), %rdi
  call test.use$Function$
  leaq test.testLongPromotion(%rip), %rdi
  call test.use$Function$
  movl $0, %eax
  ret
test.testBoolPromotion:
  push %rbx
  push %r12
  movl %edi, %r12d
  movl $16, %edi
  call __myte_alloc
  movq %rax, %rbx
  movl $1, %edi
  call __myte_alloc
  movb %r12b, (%rax)
  movq %rax, (%rbx)
  leaq 8(%rbx), %rax
  leaq _vtable$std.bool.Bool$std.string.ToString(%rip), %rcx
  movq %rcx, (%rax)
  movq %rbx, %rdi
  call test.useToString
  pop %r12
  pop %rbx
  ret
test.testBytePromotion:
  push %rbx
  push %r12
  movl %edi, %r12d
  movl $16, %edi
  call __myte_alloc
  movq %rax, %rbx
  movl $1, %edi
  call __myte_alloc
  movb %r12b, (%rax)
  movq %rax, (%rbx)
  leaq 8(%rbx), %rax
  leaq _vtable$std.byte.Byte$std.string.ToString(%rip), %rcx
  movq %rcx, (%rax)
  movq %rbx, %rdi
  call test.useToString
  pop %r12
  pop %rbx
  ret
test.testIntPromotion:
  push %rbx
  push %r12
  movl %edi, %r12d
  movl $16, %edi
  call __myte_alloc
  movq %rax, %rbx
  movl $4, %edi
  call __myte_alloc
  movl %r12d, (%rax)
  movq %rax, (%rbx)
  leaq 8(%rbx), %rax
  leaq _vtable$std.int.Int$std.string.ToString(%rip), %rcx
  movq %rcx, (%rax)
  movq %rbx, %rdi
  call test.useToString
  pop %r12
  pop %rbx
  ret
test.testLongPromotion:
  push %rbx
  push %r12
  movq %rdi, %r12
  movl $16, %edi
  call __myte_alloc
  movq %rax, %rbx
  movl $8, %edi
  call __myte_alloc
  movq %r12, (%rax)
  movq %rax, (%rbx)
  leaq 8(%rbx), %rax
  leaq _vtable$std.long.Long$std.string.ToString(%rip), %rcx
  movq %rcx, (%rax)
  movq %rbx, %rdi
  call test.useToString
  pop %r12
  pop %rbx
  ret
test.testUnitPromotion:
  movl $16, %edi
  call __myte_alloc
  leaq 8(%rax), %rcx
  leaq _vtable$std.unit.Unit$std.string.ToString(%rip), %rdx
  movq %rdx, (%rcx)
  movq %rax, %rdi
  call test.useToString
  ret
test.use$Function$:
  ret
test.useToString:
  movq (%rdi), %rax
  movq 8(%rdi), %rcx
  movq (%rcx), %rcx
  movq %rax, %rdi
  callq *%rcx
  ret