func unit @testNeitherUpdated() {
  %0 := Mov int 1
  branch true, @0, @1
label @0:
  %1 := Mov int 0
  continue @2
label @1:
  %2 := Mov int 1
  continue @2
label @2:
  %3 := Neg int %0
}

func unit @testOnlyFirstUpdated() {
  %4 := Mov int 1
  branch true, @3, @4
label @3:
  %5 := Mov int 2
  continue @5
label @4:
  %6 := Mov int 0
  continue @5
label @5:
  %7 := Phi %4, %5
  %8 := Neg int %7
}

func unit @testOnlySecondUpdated() {
  %9 := Mov int 1
  branch true, @6, @7
label @6:
  %10 := Mov int 0
  continue @8
label @7:
  %11 := Mov int 2
  continue @8
label @8:
  %12 := Phi %9, %11
  %13 := Neg int %12
}

func unit @testBothUpdated() {
  %14 := Mov int 1
  branch true, @9, @10
label @9:
  %15 := Mov int 2
  continue @11
label @10:
  %16 := Mov int 3
  continue @11
label @11:
  %17 := Phi %15, %16
  %18 := Neg int %17
}

func unit @testMultiple() {
  %19 := Mov int 0
  %20 := Mov int 1
  %21 := Mov int 2
  branch true, @12, @13
label @12:
  %22 := Mov int 3
  continue @14
label @13:
  %23 := Mov int 4
  continue @14
label @14:
  %24 := Phi %19, %22
  %25 := Phi %20, %23
  %26 := Neg int %24
  %27 := Neg int %25
  %28 := Neg int %21
}

global int %glob {
  StoreGlobal %glob, 1
}

func unit @testGlobal() {
  branch true, @15, @16
label @15:
  StoreGlobal %glob, 2
  continue @17
label @16:
  %29 := Mov int 0
  continue @17
label @17:
  %30 := LoadGlobal %glob
  %31 := Neg int %30
  branch true, @18, @19
label @18:
  %32 := Mov int 0
  continue @20
label @19:
  StoreGlobal %glob, 3
  continue @20
label @20:
  %33 := LoadGlobal %glob
  %34 := Neg int %33
  branch true, @21, @22
label @21:
  StoreGlobal %glob, 4
  continue @23
label @22:
  StoreGlobal %glob, 5
  continue @23
label @23:
  %35 := LoadGlobal %glob
  %36 := Neg int %35
}

func unit @main() {

}