func unit @test() {
  %0 := Mov int 1
  %1 := Mov int 2
  branch true, @0, @3
label @0:
  branch false, @1, @2
label @1:
  %2 := Mov int 3
  %3 := Mov int 4
  continue @2
label @2:
  %4 := Phi %0, %2
  %5 := Phi %1, %3
  continue @6
label @3:
  branch false, @4, @5
label @4:
  %6 := Mov int 5
  continue @5
label @5:
  %7 := Phi %1, %6
  continue @6
label @6:
  %8 := Phi %0, %4
  %9 := Phi %5, %7
  %10 := Neg int %8
  %11 := Neg int %9
}

func unit @main() {

}