global int @test.x {
  Store int @test.x, 0
}

func unit @test.testReassignGlobals() {
  Store int @test.x, 1
  %0 := Add int 2, 3
  Store int @test.x, %0
  %1 := Load int @test.x
  %2 := Load int @test.x
  %3 := Mul int %1, %2
  Store int @test.x, %3
  Ret
}

func unit @test.testReassignLocals() {
  %4 := Mov int 0
  %5 := Neg int %4
  %6 := Mov int 1
  %7 := Neg int %6
  %8 := Add int 2, 3
  %9 := Mov int %8
  %10 := Neg int %9
  %11 := Mul int %9, %9
  %12 := Mov int %11
  Ret
}

func unit @test.main() {
  Ret
}