global int %x {
  StoreGlobal %x, 0
}

func unit @testReassignGlobals() {
  StoreGlobal %x, 1
  %0 := Add int 2, 3
  StoreGlobal %x, %0
  %1 := LoadGlobal %x
  %2 := LoadGlobal %x
  %3 := Mul int %1, %2
  StoreGlobal %x, %3
}

func unit @testReassignLocals() {
  %4 := Mov int 0
  %5 := Neg int %4
  %6 := Mov int 1
  %7 := Neg int %6
  %8 := Add int 2, 3
  %9 := Neg int %8
  %10 := Mul int %8, %8
}

func unit @main() {

}