test/parser/pattern/basic.myte
{
  node: Module,
  loc: 1:0-51:0,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: VariableDeclaration,
      loc: 4:0-4:9,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 4:4-4:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 4:4-4:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 4:8-4:9,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 7:0-7:9,
      kind: Immutable,
      pattern: {
        node: Wildcard,
        loc: 7:4-7:5,
      },
      init: {
        node: IntLiteral,
        loc: 7:8-7:9,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 8:0-8:14,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 8:4-8:10,
        name: None,
        elements: [
          {
            node: Wildcard,
            loc: 8:5-8:6,
          },
          {
            node: Wildcard,
            loc: 8:8-8:9,
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 8:13-8:14,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 11:0-11:14,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 11:4-11:10,
        name: None,
        elements: [
          {
            node: ScopedIdentifier,
            loc: 11:5-11:6,
            scopes: [],
            name: {
              node: Identifier,
              loc: 11:5-11:6,
              name: "x",
            },
          },
          {
            node: ScopedIdentifier,
            loc: 11:8-11:9,
            scopes: [],
            name: {
              node: Identifier,
              loc: 11:8-11:9,
              name: "y",
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 11:13-11:14,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 12:0-12:17,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 12:4-12:13,
        name: None,
        elements: [
          {
            node: ScopedIdentifier,
            loc: 12:5-12:6,
            scopes: [],
            name: {
              node: Identifier,
              loc: 12:5-12:6,
              name: "x",
            },
          },
          {
            node: ScopedIdentifier,
            loc: 12:8-12:9,
            scopes: [],
            name: {
              node: Identifier,
              loc: 12:8-12:9,
              name: "y",
            },
          },
          {
            node: ScopedIdentifier,
            loc: 12:11-12:12,
            scopes: [],
            name: {
              node: Identifier,
              loc: 12:11-12:12,
              name: "z",
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 12:16-12:17,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 13:0-13:18,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 13:4-13:14,
        name: None,
        elements: [
          {
            node: ScopedIdentifier,
            loc: 13:5-13:6,
            scopes: [],
            name: {
              node: Identifier,
              loc: 13:5-13:6,
              name: "x",
            },
          },
          {
            node: ScopedIdentifier,
            loc: 13:8-13:9,
            scopes: [],
            name: {
              node: Identifier,
              loc: 13:8-13:9,
              name: "y",
            },
          },
          {
            node: ScopedIdentifier,
            loc: 13:11-13:12,
            scopes: [],
            name: {
              node: Identifier,
              loc: 13:11-13:12,
              name: "z",
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 13:17-13:18,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 16:0-16:15,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 16:4-16:11,
        name: {
          node: ScopedIdentifier,
          loc: 16:4-16:7,
          scopes: [],
          name: {
            node: Identifier,
            loc: 16:4-16:7,
            name: "Tup",
          },
        },
        elements: [
          {
            node: ScopedIdentifier,
            loc: 16:9-16:10,
            scopes: [],
            name: {
              node: Identifier,
              loc: 16:9-16:10,
              name: "x",
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 16:14-16:15,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 17:0-17:18,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 17:4-17:14,
        name: {
          node: ScopedIdentifier,
          loc: 17:4-17:7,
          scopes: [],
          name: {
            node: Identifier,
            loc: 17:4-17:7,
            name: "Tup",
          },
        },
        elements: [
          {
            node: ScopedIdentifier,
            loc: 17:9-17:10,
            scopes: [],
            name: {
              node: Identifier,
              loc: 17:9-17:10,
              name: "x",
            },
          },
          {
            node: ScopedIdentifier,
            loc: 17:12-17:13,
            scopes: [],
            name: {
              node: Identifier,
              loc: 17:12-17:13,
              name: "y",
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 17:17-17:18,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 18:0-18:21,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 18:4-18:17,
        name: {
          node: ScopedIdentifier,
          loc: 18:4-18:7,
          scopes: [],
          name: {
            node: Identifier,
            loc: 18:4-18:7,
            name: "Tup",
          },
        },
        elements: [
          {
            node: ScopedIdentifier,
            loc: 18:9-18:10,
            scopes: [],
            name: {
              node: Identifier,
              loc: 18:9-18:10,
              name: "x",
            },
          },
          {
            node: ScopedIdentifier,
            loc: 18:12-18:13,
            scopes: [],
            name: {
              node: Identifier,
              loc: 18:12-18:13,
              name: "y",
            },
          },
          {
            node: ScopedIdentifier,
            loc: 18:15-18:16,
            scopes: [],
            name: {
              node: Identifier,
              loc: 18:15-18:16,
              name: "z",
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 18:20-18:21,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 19:0-19:22,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 19:4-19:18,
        name: {
          node: ScopedIdentifier,
          loc: 19:4-19:7,
          scopes: [],
          name: {
            node: Identifier,
            loc: 19:4-19:7,
            name: "Tup",
          },
        },
        elements: [
          {
            node: ScopedIdentifier,
            loc: 19:9-19:10,
            scopes: [],
            name: {
              node: Identifier,
              loc: 19:9-19:10,
              name: "x",
            },
          },
          {
            node: ScopedIdentifier,
            loc: 19:12-19:13,
            scopes: [],
            name: {
              node: Identifier,
              loc: 19:12-19:13,
              name: "y",
            },
          },
          {
            node: ScopedIdentifier,
            loc: 19:15-19:16,
            scopes: [],
            name: {
              node: Identifier,
              loc: 19:15-19:16,
              name: "z",
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 19:21-19:22,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 22:0-22:24,
      kind: Immutable,
      pattern: {
        node: RecordPattern,
        loc: 22:4-22:20,
        name: {
          node: ScopedIdentifier,
          loc: 22:4-22:7,
          scopes: [],
          name: {
            node: Identifier,
            loc: 22:4-22:7,
            name: "Rec",
          },
        },
        fields: [
          {
            node: RecordPatternField,
            loc: 22:10-22:18,
            name: {
              node: Identifier,
              loc: 22:10-22:15,
              name: "field",
            },
            value: {
              node: ScopedIdentifier,
              loc: 22:17-22:18,
              scopes: [],
              name: {
                node: Identifier,
                loc: 22:17-22:18,
                name: "x",
              },
            },
          },
        ],
        rest: false,
      },
      init: {
        node: IntLiteral,
        loc: 22:23-22:24,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 23:0-23:21,
      kind: Immutable,
      pattern: {
        node: RecordPattern,
        loc: 23:4-23:17,
        name: {
          node: ScopedIdentifier,
          loc: 23:4-23:7,
          scopes: [],
          name: {
            node: Identifier,
            loc: 23:4-23:7,
            name: "Rec",
          },
        },
        fields: [
          {
            node: RecordPatternField,
            loc: 23:10-23:15,
            name: None,
            value: {
              node: ScopedIdentifier,
              loc: 23:10-23:15,
              scopes: [],
              name: {
                node: Identifier,
                loc: 23:10-23:15,
                name: "field",
              },
            },
          },
        ],
        rest: false,
      },
      init: {
        node: IntLiteral,
        loc: 23:20-23:21,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 24:0-24:33,
      kind: Immutable,
      pattern: {
        node: RecordPattern,
        loc: 24:4-24:29,
        name: {
          node: ScopedIdentifier,
          loc: 24:4-24:7,
          scopes: [],
          name: {
            node: Identifier,
            loc: 24:4-24:7,
            name: "Rec",
          },
        },
        fields: [
          {
            node: RecordPatternField,
            loc: 24:10-24:19,
            name: {
              node: Identifier,
              loc: 24:10-24:16,
              name: "field1",
            },
            value: {
              node: ScopedIdentifier,
              loc: 24:18-24:19,
              scopes: [],
              name: {
                node: Identifier,
                loc: 24:18-24:19,
                name: "x",
              },
            },
          },
          {
            node: RecordPatternField,
            loc: 24:21-24:27,
            name: None,
            value: {
              node: ScopedIdentifier,
              loc: 24:21-24:27,
              scopes: [],
              name: {
                node: Identifier,
                loc: 24:21-24:27,
                name: "field2",
              },
            },
          },
        ],
        rest: false,
      },
      init: {
        node: IntLiteral,
        loc: 24:32-24:33,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 25:0-25:45,
      kind: Immutable,
      pattern: {
        node: RecordPattern,
        loc: 25:4-25:41,
        name: {
          node: ScopedIdentifier,
          loc: 25:4-25:7,
          scopes: [],
          name: {
            node: Identifier,
            loc: 25:4-25:7,
            name: "Rec",
          },
        },
        fields: [
          {
            node: RecordPatternField,
            loc: 25:10-25:16,
            name: None,
            value: {
              node: ScopedIdentifier,
              loc: 25:10-25:16,
              scopes: [],
              name: {
                node: Identifier,
                loc: 25:10-25:16,
                name: "field1",
              },
            },
          },
          {
            node: RecordPatternField,
            loc: 25:18-25:27,
            name: {
              node: Identifier,
              loc: 25:18-25:24,
              name: "field2",
            },
            value: {
              node: ScopedIdentifier,
              loc: 25:26-25:27,
              scopes: [],
              name: {
                node: Identifier,
                loc: 25:26-25:27,
                name: "x",
              },
            },
          },
          {
            node: RecordPatternField,
            loc: 25:29-25:38,
            name: {
              node: Identifier,
              loc: 25:29-25:35,
              name: "field3",
            },
            value: {
              node: ScopedIdentifier,
              loc: 25:37-25:38,
              scopes: [],
              name: {
                node: Identifier,
                loc: 25:37-25:38,
                name: "y",
              },
            },
          },
        ],
        rest: false,
      },
      init: {
        node: IntLiteral,
        loc: 25:44-25:45,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 26:0-26:27,
      kind: Immutable,
      pattern: {
        node: RecordPattern,
        loc: 26:4-26:23,
        name: {
          node: ScopedIdentifier,
          loc: 26:4-26:7,
          scopes: [],
          name: {
            node: Identifier,
            loc: 26:4-26:7,
            name: "Rec",
          },
        },
        fields: [
          {
            node: RecordPatternField,
            loc: 26:10-26:16,
            name: None,
            value: {
              node: ScopedIdentifier,
              loc: 26:10-26:16,
              scopes: [],
              name: {
                node: Identifier,
                loc: 26:10-26:16,
                name: "field1",
              },
            },
          },
        ],
        rest: true,
      },
      init: {
        node: IntLiteral,
        loc: 26:26-26:27,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 27:0-27:28,
      kind: Immutable,
      pattern: {
        node: RecordPattern,
        loc: 27:4-27:24,
        name: {
          node: ScopedIdentifier,
          loc: 27:4-27:7,
          scopes: [],
          name: {
            node: Identifier,
            loc: 27:4-27:7,
            name: "Rec",
          },
        },
        fields: [
          {
            node: RecordPatternField,
            loc: 27:10-27:16,
            name: None,
            value: {
              node: ScopedIdentifier,
              loc: 27:10-27:16,
              scopes: [],
              name: {
                node: Identifier,
                loc: 27:10-27:16,
                name: "field1",
              },
            },
          },
        ],
        rest: true,
      },
      init: {
        node: IntLiteral,
        loc: 27:27-27:28,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 30:0-30:13,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 30:4-30:9,
        scopes: [
          {
            node: Identifier,
            loc: 30:4-30:5,
            name: "A",
          },
          {
            node: Identifier,
            loc: 30:6-30:7,
            name: "B",
          },
        ],
        name: {
          node: Identifier,
          loc: 30:8-30:9,
          name: "C",
        },
      },
      init: {
        node: IntLiteral,
        loc: 30:12-30:13,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 31:0-31:21,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 31:4-31:17,
        name: {
          node: ScopedIdentifier,
          loc: 31:4-31:13,
          scopes: [
            {
              node: Identifier,
              loc: 31:4-31:5,
              name: "A",
            },
            {
              node: Identifier,
              loc: 31:6-31:7,
              name: "B",
            },
            {
              node: Identifier,
              loc: 31:8-31:9,
              name: "C",
            },
          ],
          name: {
            node: Identifier,
            loc: 31:10-31:13,
            name: "Tup",
          },
        },
        elements: [
          {
            node: ScopedIdentifier,
            loc: 31:15-31:16,
            scopes: [],
            name: {
              node: Identifier,
              loc: 31:15-31:16,
              name: "x",
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 31:20-31:21,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 32:0-32:27,
      kind: Immutable,
      pattern: {
        node: RecordPattern,
        loc: 32:4-32:23,
        name: {
          node: ScopedIdentifier,
          loc: 32:4-32:13,
          scopes: [
            {
              node: Identifier,
              loc: 32:4-32:5,
              name: "A",
            },
            {
              node: Identifier,
              loc: 32:6-32:7,
              name: "B",
            },
            {
              node: Identifier,
              loc: 32:8-32:9,
              name: "C",
            },
          ],
          name: {
            node: Identifier,
            loc: 32:10-32:13,
            name: "Rec",
          },
        },
        fields: [
          {
            node: RecordPatternField,
            loc: 32:16-32:21,
            name: None,
            value: {
              node: ScopedIdentifier,
              loc: 32:16-32:21,
              scopes: [],
              name: {
                node: Identifier,
                loc: 32:16-32:21,
                name: "field",
              },
            },
          },
        ],
        rest: false,
      },
      init: {
        node: IntLiteral,
        loc: 32:26-32:27,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 35:0-35:19,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 35:4-35:15,
        name: None,
        elements: [
          {
            node: TuplePattern,
            loc: 35:5-35:11,
            name: None,
            elements: [
              {
                node: ScopedIdentifier,
                loc: 35:6-35:7,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 35:6-35:7,
                  name: "x",
                },
              },
              {
                node: ScopedIdentifier,
                loc: 35:9-35:10,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 35:9-35:10,
                  name: "y",
                },
              },
            ],
          },
          {
            node: ScopedIdentifier,
            loc: 35:13-35:14,
            scopes: [],
            name: {
              node: Identifier,
              loc: 35:13-35:14,
              name: "z",
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 35:18-35:19,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 36:0-36:34,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 36:4-36:30,
        name: None,
        elements: [
          {
            node: TuplePattern,
            loc: 36:5-36:14,
            name: {
              node: ScopedIdentifier,
              loc: 36:5-36:8,
              scopes: [],
              name: {
                node: Identifier,
                loc: 36:5-36:8,
                name: "Tup",
              },
            },
            elements: [
              {
                node: ScopedIdentifier,
                loc: 36:9-36:10,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 36:9-36:10,
                  name: "x",
                },
              },
              {
                node: ScopedIdentifier,
                loc: 36:12-36:13,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 36:12-36:13,
                  name: "y",
                },
              },
            ],
          },
          {
            node: RecordPattern,
            loc: 36:16-36:29,
            name: {
              node: ScopedIdentifier,
              loc: 36:16-36:19,
              scopes: [],
              name: {
                node: Identifier,
                loc: 36:16-36:19,
                name: "Rec",
              },
            },
            fields: [
              {
                node: RecordPatternField,
                loc: 36:22-36:27,
                name: None,
                value: {
                  node: ScopedIdentifier,
                  loc: 36:22-36:27,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 36:22-36:27,
                    name: "field",
                  },
                },
              },
            ],
            rest: false,
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 36:33-36:34,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 37:0-37:33,
      kind: Immutable,
      pattern: {
        node: RecordPattern,
        loc: 37:4-37:29,
        name: {
          node: ScopedIdentifier,
          loc: 37:4-37:7,
          scopes: [],
          name: {
            node: Identifier,
            loc: 37:4-37:7,
            name: "Rec",
          },
        },
        fields: [
          {
            node: RecordPatternField,
            loc: 37:10-37:27,
            name: {
              node: Identifier,
              loc: 37:10-37:15,
              name: "field",
            },
            value: {
              node: TuplePattern,
              loc: 37:17-37:27,
              name: {
                node: ScopedIdentifier,
                loc: 37:17-37:20,
                scopes: [],
                name: {
                  node: Identifier,
                  loc: 37:17-37:20,
                  name: "Tup",
                },
              },
              elements: [
                {
                  node: ScopedIdentifier,
                  loc: 37:22-37:23,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 37:22-37:23,
                    name: "x",
                  },
                },
                {
                  node: ScopedIdentifier,
                  loc: 37:25-37:26,
                  scopes: [],
                  name: {
                    node: Identifier,
                    loc: 37:25-37:26,
                    name: "y",
                  },
                },
              ],
            },
          },
        ],
        rest: false,
      },
      init: {
        node: IntLiteral,
        loc: 37:32-37:33,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 40:0-40:13,
      kind: Immutable,
      pattern: {
        node: NamedWildcard,
        loc: 40:4-40:9,
        name: {
          node: ScopedIdentifier,
          loc: 40:4-40:7,
          scopes: [],
          name: {
            node: Identifier,
            loc: 40:4-40:7,
            name: "Tup",
          },
        },
      },
      init: {
        node: IntLiteral,
        loc: 40:12-40:13,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 41:0-41:15,
      kind: Immutable,
      pattern: {
        node: NamedWildcard,
        loc: 41:4-41:11,
        name: {
          node: ScopedIdentifier,
          loc: 41:4-41:9,
          scopes: [
            {
              node: Identifier,
              loc: 41:4-41:5,
              name: "A",
            },
            {
              node: Identifier,
              loc: 41:6-41:7,
              name: "B",
            },
          ],
          name: {
            node: Identifier,
            loc: 41:8-41:9,
            name: "C",
          },
        },
      },
      init: {
        node: IntLiteral,
        loc: 41:14-41:15,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 42:0-42:24,
      kind: Immutable,
      pattern: {
        node: TuplePattern,
        loc: 42:4-42:20,
        name: None,
        elements: [
          {
            node: NamedWildcard,
            loc: 42:5-42:10,
            name: {
              node: ScopedIdentifier,
              loc: 42:5-42:8,
              scopes: [],
              name: {
                node: Identifier,
                loc: 42:5-42:8,
                name: "Rec",
              },
            },
          },
          {
            node: NamedWildcard,
            loc: 42:12-42:19,
            name: {
              node: ScopedIdentifier,
              loc: 42:12-42:17,
              scopes: [
                {
                  node: Identifier,
                  loc: 42:12-42:13,
                  name: "A",
                },
                {
                  node: Identifier,
                  loc: 42:14-42:15,
                  name: "B",
                },
              ],
              name: {
                node: Identifier,
                loc: 42:16-42:17,
                name: "C",
              },
            },
          },
        ],
      },
      init: {
        node: IntLiteral,
        loc: 42:23-42:24,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 45:0-45:15,
      kind: Immutable,
      pattern: {
        node: NamedWildcard,
        loc: 45:5-45:10,
        name: {
          node: ScopedIdentifier,
          loc: 45:5-45:8,
          scopes: [],
          name: {
            node: Identifier,
            loc: 45:5-45:8,
            name: "Tup",
          },
        },
      },
      init: {
        node: IntLiteral,
        loc: 45:14-45:15,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 46:0-46:15,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 46:7-46:8,
        scopes: [],
        name: {
          node: Identifier,
          loc: 46:7-46:8,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 46:14-46:15,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 49:0-49:14,
      kind: Immutable,
      pattern: {
        node: Binding,
        loc: 49:4-49:10,
        pattern: {
          node: ScopedIdentifier,
          loc: 49:4-49:5,
          scopes: [],
          name: {
            node: Identifier,
            loc: 49:4-49:5,
            name: "x",
          },
        },
        name: {
          node: Identifier,
          loc: 49:9-49:10,
          name: "y",
        },
      },
      init: {
        node: IntLiteral,
        loc: 49:13-49:14,
        raw: "1",
      },
      annot: None,
    },
    {
      node: VariableDeclaration,
      loc: 50:0-50:24,
      kind: Immutable,
      pattern: {
        node: Binding,
        loc: 50:4-50:20,
        pattern: {
          node: TuplePattern,
          loc: 50:4-50:15,
          name: None,
          elements: [
            {
              node: Wildcard,
              loc: 50:5-50:6,
            },
            {
              node: Binding,
              loc: 50:8-50:14,
              pattern: {
                node: Wildcard,
                loc: 50:8-50:9,
              },
              name: {
                node: Identifier,
                loc: 50:13-50:14,
                name: "x",
              },
            },
          ],
        },
        name: {
          node: Identifier,
          loc: 50:19-50:20,
          name: "y",
        },
      },
      init: {
        node: IntLiteral,
        loc: 50:23-50:24,
        raw: "1",
      },
      annot: None,
    },
  ],
}