test/parser/pattern/literals.myte
{
  node: Module,
  loc: 1:0-9:1,
  name: {
    node: ModuleName,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-9:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-9:1,
        statements: [
          {
            node: MatchStatement,
            loc: 4:2-8:3,
            args: [
              {
                node: Identifier,
                loc: 4:9-4:10,
                name: "x",
              },
            ],
            cases: [
              {
                node: MatchCase,
                loc: 5:6-5:33,
                pattern: {
                  node: TuplePattern,
                  loc: 5:6-5:28,
                  name: None,
                  elements: [
                    {
                      node: Unit,
                      loc: 5:7-5:9,
                    },
                    {
                      node: BoolLiteral,
                      loc: 5:11-5:15,
                      value: true,
                    },
                    {
                      node: IntLiteral,
                      loc: 5:17-5:18,
                      raw: "1",
                    },
                    {
                      node: StringLiteral,
                      loc: 5:20-5:22,
                      value: "",
                    },
                    {
                      node: CharLiteral,
                      loc: 5:24-5:27,
                      value: "a",
                    },
                  ],
                },
                guard: None,
                right: {
                  node: IntLiteral,
                  loc: 5:32-5:33,
                  raw: "1",
                },
              },
              {
                node: MatchCase,
                loc: 6:6-6:13,
                pattern: {
                  node: IntLiteral,
                  loc: 6:6-6:8,
                  raw: "-1",
                },
                guard: None,
                right: {
                  node: IntLiteral,
                  loc: 6:12-6:13,
                  raw: "2",
                },
              },
              {
                node: MatchCase,
                loc: 7:6-7:25,
                pattern: {
                  node: TuplePattern,
                  loc: 7:6-7:20,
                  name: {
                    node: ScopedIdentifier,
                    loc: 7:6-7:9,
                    scopes: [],
                    name: {
                      node: Identifier,
                      loc: 7:6-7:9,
                      name: "Tup",
                    },
                  },
                  elements: [
                    {
                      node: IntLiteral,
                      loc: 7:11-7:13,
                      raw: "-1",
                    },
                    {
                      node: BoolLiteral,
                      loc: 7:15-7:19,
                      value: true,
                    },
                  ],
                },
                guard: None,
                right: {
                  node: IntLiteral,
                  loc: 7:24-7:25,
                  raw: "3",
                },
              },
            ],
          },
        ],
      },
      return: None,
      type_params: [],
      builtin: false,
      static: false,
      override: false,
    },
  ],
}