test/parser/ast/unary_operation/basic.myte
{
  node: Module,
  loc: 1:0-12:1,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-12:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-12:1,
        statements: [
          {
            node: ExpressionStatement,
            loc: 4:2-4:5,
            expression: {
              node: UnaryOperation,
              loc: 4:2-4:4,
              op: Plus,
              operand: {
                node: IntLiteral,
                loc: 4:3-4:4,
                raw: "1",
              },
            },
          },
          {
            node: ExpressionStatement,
            loc: 5:2-5:7,
            expression: {
              node: UnaryOperation,
              loc: 5:2-5:6,
              op: Minus,
              operand: {
                node: IntLiteral,
                loc: 5:4-5:5,
                raw: "1",
              },
            },
          },
          {
            node: ExpressionStatement,
            loc: 6:2-6:5,
            expression: {
              node: UnaryOperation,
              loc: 6:2-6:4,
              op: Not,
              operand: {
                node: IntLiteral,
                loc: 6:3-6:4,
                raw: "1",
              },
            },
          },
          {
            node: ExpressionStatement,
            loc: 7:2-7:8,
            expression: {
              node: UnaryOperation,
              loc: 7:2-7:7,
              op: Not,
              operand: {
                node: BoolLiteral,
                loc: 7:3-7:7,
                value: true,
              },
            },
          },
          {
            node: ExpressionStatement,
            loc: 9:2-9:8,
            expression: {
              node: UnaryOperation,
              loc: 9:2-9:7,
              op: Plus,
              operand: {
                node: UnaryOperation,
                loc: 9:3-9:7,
                op: Minus,
                operand: {
                  node: IntLiteral,
                  loc: 9:5-9:6,
                  raw: "1",
                },
              },
            },
          },
          {
            node: ExpressionStatement,
            loc: 10:2-10:6,
            expression: {
              node: UnaryOperation,
              loc: 10:2-10:5,
              op: Minus,
              operand: {
                node: UnaryOperation,
                loc: 10:3-10:5,
                op: Plus,
                operand: {
                  node: IntLiteral,
                  loc: 10:4-10:5,
                  raw: "1",
                },
              },
            },
          },
          {
            node: ExpressionStatement,
            loc: 11:2-11:6,
            expression: {
              node: UnaryOperation,
              loc: 11:2-11:5,
              op: Minus,
              operand: {
                node: UnaryOperation,
                loc: 11:3-11:5,
                op: Not,
                operand: {
                  node: IntLiteral,
                  loc: 11:4-11:5,
                  raw: "1",
                },
              },
            },
          },
        ],
      },
      return: None,
      type_params: [],
      builtin: false,
      static: false,
      override: false,
    },
  ],
}