test/parser/ast/break/basic.myte
{
  node: Module,
  loc: 1:0-7:1,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-7:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-7:1,
        statements: [
          {
            node: While,
            loc: 4:2-6:3,
            test: {
              node: BoolLiteral,
              loc: 4:9-4:13,
              value: true,
            },
            body: {
              node: Block,
              loc: 4:15-6:3,
              statements: [
                {
                  node: Break,
                  loc: 5:4-5:10,
                },
              ],
            },
          },
        ],
      },
      return: None,
      type_params: [],
    },
  ],
}