type $tuple<int,$tuple<int,bool>*> {int, $tuple<int,bool>*}

type $tuple<int,bool,$tuple<int,$tuple<int,bool>*>*> {int, bool, $tuple<int,$tuple<int,bool>*>*}

type $tuple<int,bool> {int, bool}

func int @test.test1(int %0) {
  Ret %0
}

func int @test.test2(int %1, bool %2) {
  %3 := Eq bool %2, true
  branch %3, @3, @0
label @0:
  branch %2, @2, @1
label @1:
  continue @2
label @2:
  %4 := Phi int @0:1, @1:2
  continue @3
label @3:
  %5 := Phi int @test.test2:%1, @2:%4
  Ret %5
}

func int @test.test3(int %6) {
  %7 := Eq int %6, 1
  branch %7, @6, @4
label @4:
  %8 := Eq int %6, 2
  branch %8, @6, @5
label @5:
  %9 := Add int %6, %6
  %10 := Add int %9, %6
  continue @6
label @6:
  %11 := Phi int @test.test3:1, @4:%6, @5:%10
  Ret %11
}

func int @test.test4(int %12, int %13, int %14) {
  %15 := Eq int %12, 1
  branch %15, @7, @10
label @7:
  %16 := Lt int %13, 4
  branch %16, @13, @8
label @8:
  %17 := Eq int %13, 1
  branch %17, @9, @12
label @9:
  %18 := Add int %12, %14
  %19 := Lt int %18, 5
  branch %19, @13, @12
label @10:
  %20 := Eq int %13, 1
  branch %20, @11, @12
label @11:
  %21 := Add int %12, %14
  %22 := Lt int %21, 5
  branch %22, @13, @12
label @12:
  continue @13
label @13:
  %23 := Phi int @7:1, @9:2, @12:3
  Ret %23
}

func int @test.test5(int %24, int %25) {
  %26 := Eq int %25, 1
  branch %26, @15, @14
label @14:
  %27 := Eq int %24, 1
  branch %27, @15, @16
label @15:
  %28 := Phi int @test.test5:%24, @14:%25
  %29 := Add int %28, 2
  continue @16
label @16:
  %30 := Phi int @14:3, @15:%29
  Ret %30
}

func int @test.test6(int %31, int %32) {
  %33 := Eq int %31, 1
  branch %33, @18, @17
label @17:
  %34 := Eq int %32, 1
  continue @18
label @18:
  %35 := Phi int @test.test6:1, @17:2
  Ret %35
}

func int @test.test7($tuple<int,bool,$tuple<int,$tuple<int,bool>*>*>* %36) {
  %37 := GetPointer int, $tuple<int,bool,$tuple<int,$tuple<int,bool>*>*>* %36.0
  %38 := Load int %37
  %39 := Eq int %38, 1
  branch %39, @19, @20
label @19:
  %40 := GetPointer $tuple<int,$tuple<int,bool>*>*, $tuple<int,bool,$tuple<int,$tuple<int,bool>*>*>* %36.2
  %41 := Load $tuple<int,$tuple<int,bool>*>* %40
  %42 := GetPointer int, $tuple<int,$tuple<int,bool>*>* %41.0
  %43 := Load int %42
  continue @23
label @20:
  %44 := Eq int %38, 2
  branch %44, @21, @22
label @21:
  %45 := GetPointer $tuple<int,$tuple<int,bool>*>*, $tuple<int,bool,$tuple<int,$tuple<int,bool>*>*>* %36.2
  %46 := Load $tuple<int,$tuple<int,bool>*>* %45
  %47 := GetPointer int, $tuple<int,$tuple<int,bool>*>* %46.0
  %48 := Load int %47
  %49 := Add int %48, %48
  %50 := Add int %49, %48
  continue @23
label @22:
  %51 := GetPointer $tuple<int,$tuple<int,bool>*>*, $tuple<int,bool,$tuple<int,$tuple<int,bool>*>*>* %36.2
  %52 := Load $tuple<int,$tuple<int,bool>*>* %51
  %53 := GetPointer int, $tuple<int,$tuple<int,bool>*>* %52.0
  %54 := Load int %53
  %55 := GetPointer $tuple<int,bool>*, $tuple<int,$tuple<int,bool>*>* %52.1
  %56 := Load $tuple<int,bool>* %55
  %57 := GetPointer int, $tuple<int,bool>* %56.0
  %58 := Load int %57
  %59 := Add int %54, %58
  continue @23
label @23:
  %60 := Phi int @19:%43, @21:%50, @22:%59
  Ret %60
}

func int @test.test8(int %61) {
  %62 := Eq int %61, 1
  branch %62, @25, @24
label @24:
  %63 := Eq int %61, 2
  branch %63, @25, @26
label @25:
  continue @30
label @26:
  %64 := Eq int %61, 4
  branch %64, @29, @27
label @27:
  %65 := Eq int %61, 5
  branch %65, @29, @28
label @28:
  %66 := Eq int %61, 6
  branch %66, @29, @30
label @29:
  %67 := Add int %61, %61
  continue @30
label @30:
  %68 := Phi int @25:%61, @29:%67, @28:3
  Ret %68
}

func int @test.test9($tuple<int,$tuple<int,bool>*>* %69) {
  %70 := GetPointer $tuple<int,bool>*, $tuple<int,$tuple<int,bool>*>* %69.1
  %71 := Load $tuple<int,bool>* %70
  %72 := GetPointer int, $tuple<int,bool>* %71.0
  %73 := Load int %72
  %74 := Eq int %73, 1
  branch %74, @32, @31
label @31:
  %75 := Eq int %73, 2
  branch %75, @32, @33
label @32:
  continue @36
label @33:
  %76 := Eq int %73, 3
  branch %76, @35, @34
label @34:
  %77 := Eq int %73, 4
  branch %77, @35, @36
label @35:
  %78 := Add int %73, %73
  continue @36
label @36:
  %79 := Phi int @32:%73, @34:7, @35:%78
  Ret %79
}

func int @test.test10($tuple<int,$tuple<int,bool>*>* %80) {
  %81 := GetPointer $tuple<int,bool>*, $tuple<int,$tuple<int,bool>*>* %80.1
  %82 := Load $tuple<int,bool>* %81
  %83 := GetPointer int, $tuple<int,bool>* %82.0
  %84 := Load int %83
  %85 := Eq int %84, 1
  branch %85, @38, @37
label @37:
  %86 := Eq int %84, 2
  branch %86, @38, @39
label @38:
  continue @39
label @39:
  %87 := Phi int @37:7, @38:%84
  Ret %87
}

func int @test.test11(int %88) {
  %89 := Eq int %88, 1
  branch %89, @41, @40
label @40:
  %90 := Eq int %88, 2
  branch %90, @41, @42
label @41:
  continue @42
label @42:
  %91 := Phi int @40:7, @41:%88
  Ret %91
}

func int @test.main() {
  Ret 0
}