func int @test.test1(bool %0) {
  %1 := Eq bool %0, false
  branch %1, @0, @1
label @0:
  %2 := Mov int 2
  continue @2
label @1:
  %3 := Mov int 1
  continue @2
label @2:
  %4 := Phi int @0:%2, @1:%3
  Ret %4
}

func int @test.test2(bool %5, bool %6) {
  %7 := Eq bool %5, false
  branch %7, @3, @6
label @3:
  %8 := Eq bool %6, false
  branch %8, @4, @5
label @4:
  %9 := Mov int 4
  continue @9
label @5:
  %10 := Mov int 2
  continue @9
label @6:
  %11 := Eq bool %6, false
  branch %11, @7, @8
label @7:
  %12 := Mov int 1
  continue @9
label @8:
  %13 := Mov int 3
  continue @9
label @9:
  %14 := Phi int @4:%9, @5:%10, @7:%12, @8:%13
  Ret %14
}

func int @test.main() {
  Ret 0
}