type test.Tup {int, long}

type test.Rec {int, long}

func int @test.testNamedTuple(test.Tup* %0) {
  %1 := GetPointer int, test.Tup* %0.0
  %2 := Load int %1
  %3 := Eq int %2, 1
  branch %3, @0, @2
label @0:
  %4 := GetPointer long, test.Tup* %0.1
  %5 := Load long %4
  %6 := Eq long %5, 3
  branch %6, @2, @1
label @1:
  continue @2
label @2:
  %7 := Phi int @test.testNamedTuple:%2, @0:1, @1:2
  Ret %7
}

func int @test.testNamedRecord(test.Rec* %0) {
  %1 := GetPointer int, test.Rec* %0.0
  %2 := Load int %1
  %3 := Eq int %2, 1
  branch %3, @0, @2
label @0:
  %4 := GetPointer long, test.Rec* %0.1
  %5 := Load long %4
  %6 := Eq long %5, 1
  branch %6, @4, @1
label @1:
  continue @4
label @2:
  %7 := GetPointer long, test.Rec* %0.1
  %8 := Load long %7
  %9 := Eq long %8, 1
  branch %9, @3, @4
label @3:
  %10 := Add int %2, 3
  continue @4
label @4:
  %11 := Phi int @0:2, @2:%2, @1:1, @3:%10
  Ret %11
}

func void @test.use<Function>(fn %0) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.testNamedTuple)
  Call void @test.use<Function>(@test.testNamedRecord)
  Ret 0
}