type $tuple<int,bool,$tuple<int,bool>*> {int, bool, $tuple<int,bool>*}

type $tuple<int,bool,std.string.String*> {int, bool, std.string.String*}

type $tuple<int,bool> {int, bool}

func int @test.test1($tuple<int,bool,std.string.String*>* %0) {
  Ret 1
}

func int @test.test2($tuple<int,bool,std.string.String*>* %1) {
  %2 := GetPointer int, $tuple<int,bool,std.string.String*>* %1.0
  %3 := Load int %2
  %4 := Eq int %3, 1
  branch %4, @0, @2
label @0:
  %5 := GetPointer bool, $tuple<int,bool,std.string.String*>* %1.1
  %6 := Load bool %5
  %7 := Eq bool %6, false
  branch %7, @11, @1
label @1:
  continue @13
label @2:
  %8 := Eq int %3, 2
  branch %8, @3, @4
label @3:
  continue @13
label @4:
  %9 := Eq int %3, 3
  branch %9, @5, @7
label @5:
  %10 := GetPointer bool, $tuple<int,bool,std.string.String*>* %1.1
  %11 := Load bool %10
  %12 := Eq bool %11, false
  branch %12, @6, @12
label @6:
  continue @13
label @7:
  %13 := Eq int %3, 4
  branch %13, @8, @10
label @8:
  %14 := GetPointer bool, $tuple<int,bool,std.string.String*>* %1.1
  %15 := Load bool %14
  %16 := Eq bool %15, false
  branch %16, @9, @12
label @9:
  continue @13
label @10:
  %17 := GetPointer bool, $tuple<int,bool,std.string.String*>* %1.1
  %18 := Load bool %17
  %19 := Eq bool %18, false
  branch %19, @11, @12
label @11:
  continue @13
label @12:
  continue @13
label @13:
  %20 := Phi int @11:6, @1:1, @3:2, @6:4, @12:3, @9:5
  Ret %20
}

func int @test.test3($tuple<int,bool,$tuple<int,bool>*>* %21) {
  %22 := GetPointer int, $tuple<int,bool,$tuple<int,bool>*>* %21.0
  %23 := Load int %22
  %24 := Eq int %23, 1
  branch %24, @14, @15
label @14:
  continue @22
label @15:
  %25 := GetPointer bool, $tuple<int,bool,$tuple<int,bool>*>* %21.1
  %26 := Load bool %25
  %27 := Eq bool %26, true
  branch %27, @16, @17
label @16:
  continue @22
label @17:
  %28 := GetPointer $tuple<int,bool>*, $tuple<int,bool,$tuple<int,bool>*>* %21.2
  %29 := Load $tuple<int,bool>* %28
  %30 := GetPointer int, $tuple<int,bool>* %29.0
  %31 := Load int %30
  %32 := Eq int %31, 2
  branch %32, @18, @19
label @18:
  continue @22
label @19:
  %33 := GetPointer bool, $tuple<int,bool>* %29.1
  %34 := Load bool %33
  %35 := Eq bool %34, false
  branch %35, @20, @21
label @20:
  continue @22
label @21:
  continue @22
label @22:
  %36 := Phi int @14:1, @16:2, @18:3, @20:4, @21:5
  Ret %36
}

func int @test.test4($tuple<int,bool,$tuple<int,bool>*>* %37) {
  %38 := GetPointer int, $tuple<int,bool,$tuple<int,bool>*>* %37.0
  %39 := Load int %38
  %40 := Eq int %39, 1
  branch %40, @23, @27
label @23:
  %41 := GetPointer bool, $tuple<int,bool,$tuple<int,bool>*>* %37.1
  %42 := Load bool %41
  branch %42, @24, @25
label @24:
  continue @26
label @25:
  continue @26
label @26:
  %43 := Phi int @24:1, @25:2
  continue @35
label @27:
  %44 := GetPointer bool, $tuple<int,bool,$tuple<int,bool>*>* %37.1
  %45 := Load bool %44
  %46 := Eq bool %45, true
  branch %46, @28, @31
label @28:
  %47 := GetPointer $tuple<int,bool>*, $tuple<int,bool,$tuple<int,bool>*>* %37.2
  %48 := Load $tuple<int,bool>* %47
  %49 := GetPointer bool, $tuple<int,bool>* %48.1
  %50 := Load bool %49
  %51 := Eq bool %50, false
  branch %51, @29, @30
label @29:
  %52 := GetPointer int, $tuple<int,bool>* %48.0
  %53 := Load int %52
  %54 := Add int %53, 3
  continue @35
label @30:
  %55 := GetPointer int, $tuple<int,bool>* %48.0
  %56 := Load int %55
  %57 := Add int %39, %56
  %58 := Add int %57, 4
  continue @35
label @31:
  %59 := GetPointer $tuple<int,bool>*, $tuple<int,bool,$tuple<int,bool>*>* %37.2
  %60 := Load $tuple<int,bool>* %59
  %61 := GetPointer int, $tuple<int,bool>* %60.0
  %62 := Load int %61
  %63 := GetPointer bool, $tuple<int,bool>* %60.1
  %64 := Load bool %63
  branch %64, @32, @33
label @32:
  continue @34
label @33:
  %65 := Add int %62, 5
  continue @34
label @34:
  %66 := Phi int @32:%62, @33:%65
  continue @35
label @35:
  %67 := Phi int @26:%43, @29:%54, @30:%58, @34:%66
  Ret %67
}

func $tuple<int,bool>* @test.test5($tuple<int,bool,$tuple<int,bool>*>* %68) {
  %69 := GetPointer bool, $tuple<int,bool,$tuple<int,bool>*>* %68.1
  %70 := Load bool %69
  %71 := Eq bool %70, false
  branch %71, @36, @39
label @36:
  %72 := GetPointer $tuple<int,bool>*, $tuple<int,bool,$tuple<int,bool>*>* %68.2
  %73 := Load $tuple<int,bool>* %72
  %74 := GetPointer int, $tuple<int,bool>* %73.0
  %75 := Load int %74
  %76 := Eq int %75, 1
  branch %76, @37, @38
label @37:
  continue @42
label @38:
  %77 := CallBuiltin $tuple<int,bool>* myte_alloc(1)
  %78 := GetPointer int, $tuple<int,bool>* %73.0
  %79 := Load int %78
  %80 := GetPointer int, $tuple<int,bool>* %77.0
  Store int %80, %79
  %81 := GetPointer bool, $tuple<int,bool>* %73.1
  %82 := Load bool %81
  %83 := GetPointer bool, $tuple<int,bool>* %77.1
  Store bool %83, %82
  continue @42
label @39:
  %84 := GetPointer int, $tuple<int,bool,$tuple<int,bool>*>* %68.0
  %85 := Load int %84
  %86 := Eq int %85, 1
  branch %86, @40, @41
label @40:
  %87 := GetPointer $tuple<int,bool>*, $tuple<int,bool,$tuple<int,bool>*>* %68.2
  %88 := Load $tuple<int,bool>* %87
  continue @42
label @41:
  %89 := GetPointer $tuple<int,bool>*, $tuple<int,bool,$tuple<int,bool>*>* %68.2
  %90 := Load $tuple<int,bool>* %89
  continue @42
label @42:
  %91 := Phi $tuple<int,bool>* @37:%73, @38:%77, @40:%88, @41:%90
  Ret %91
}

func int @test.main() {
  Ret 0
}