func int @test.test1(bool %0) {
  %1 := Eq bool %0, false
  branch %1, @0, @1
label @0:
  continue @2
label @1:
  continue @2
label @2:
  %2 := Phi int @0:2, @1:1
  Ret %2
}

func int @test.test2(bool %3, bool %4) {
  %5 := Eq bool %3, false
  branch %5, @3, @6
label @3:
  %6 := Eq bool %4, false
  branch %6, @4, @5
label @4:
  continue @9
label @5:
  continue @9
label @6:
  %7 := Eq bool %4, false
  branch %7, @7, @8
label @7:
  continue @9
label @8:
  continue @9
label @9:
  %8 := Phi int @4:4, @5:2, @7:1, @8:3
  Ret %8
}

func int @test.main() {
  Ret 0
}