func void @test.marker(int %0) {
  Ret
}

func void @test.test1(bool %1, int %2) {
  %3 := Eq int %2, 1
  branch %3, @0, @1
label @0:
  Call void @test.marker(1)
  continue @6
label @1:
  %4 := Eq int %2, 2
  branch %4, @2, @5
label @2:
  %5 := Eq bool %1, false
  branch %5, @3, @4
label @3:
  Call void @test.marker(3)
  continue @6
label @4:
  Call void @test.marker(2)
  continue @6
label @5:
  Call void @test.marker(4)
  continue @6
label @6:
  Ret
}

func void @test.test2(bool %6, int %7) {
  %8 := Eq int %7, 1
  branch %8, @7, @10
label @7:
  %9 := Eq int %7, 2
  branch %9, @8, @9
label @8:
  Call void @test.marker(1)
  continue @17
label @9:
  Call void @test.marker(2)
  continue @17
label @10:
  %10 := Eq int %7, 2
  branch %10, @11, @16
label @11:
  %11 := Eq bool %6, true
  branch %11, @12, @16
label @12:
  branch %6, @13, @14
label @13:
  Call void @test.marker(3)
  continue @17
label @14:
  %12 := LogNot %6
  branch %12, @15, @16
label @15:
  Call void @test.marker(4)
  continue @17
label @16:
  Call void @test.marker(5)
  continue @17
label @17:
  Ret
}

func void @test.use<Function>(fn %13) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.test1)
  Call void @test.use<Function>(@test.test2)
  Ret 0
}