func int @test.testBytes(byte %0) {
  %1 := Eq byte %0, -1
  branch %1, @0, @1
label @0:
  continue @6
label @1:
  %2 := Eq byte %0, 0
  branch %2, @2, @3
label @2:
  continue @6
label @3:
  %3 := Eq byte %0, 5
  branch %3, @4, @5
label @4:
  continue @6
label @5:
  continue @6
label @6:
  %4 := Phi int @0:2, @2:1, @4:3, @5:4
  Ret %4
}

func int @test.testInts(int %5) {
  %6 := Eq int %5, -1
  branch %6, @7, @8
label @7:
  continue @13
label @8:
  %7 := Eq int %5, 0
  branch %7, @9, @10
label @9:
  continue @13
label @10:
  %8 := Eq int %5, 5
  branch %8, @11, @12
label @11:
  continue @13
label @12:
  continue @13
label @13:
  %9 := Phi int @7:2, @9:1, @11:3, @12:4
  Ret %9
}

func int @test.testLongs(long %10) {
  %11 := Eq long %10, -1
  branch %11, @14, @15
label @14:
  continue @20
label @15:
  %12 := Eq long %10, 0
  branch %12, @16, @17
label @16:
  continue @20
label @17:
  %13 := Eq long %10, 5
  branch %13, @18, @19
label @18:
  continue @20
label @19:
  continue @20
label @20:
  %14 := Phi int @14:2, @16:1, @18:3, @19:4
  Ret %14
}

func int @test.main() {
  Ret 0
}