func int @test.test1(long %0) {
  %1 := Eq long %0, 1
  branch %1, @1, @0
label @0:
  continue @1
label @1:
  %2 := Phi int @test.test1:2, @0:1
  Ret %2
}

func int @test.test2(long %0, long %1) {
  %2 := Eq long %0, 1
  branch %2, @0, @2
label @0:
  %3 := Eq long %1, 1
  branch %3, @4, @1
label @1:
  continue @4
label @2:
  %4 := Eq long %1, 1
  branch %4, @4, @3
label @3:
  continue @4
label @4:
  %5 := Phi int @0:4, @2:1, @1:2, @3:3
  Ret %5
}

func void @test.use<Function>(fn %0) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.test1)
  Call void @test.use<Function>(@test.test2)
  Ret 0
}