func void @test.marker(int %0) {
  Ret
}

func void @test.test1(bool %0, int %1) {
  %2 := Eq int %1, 1
  branch %2, @0, @1
label @0:
  Call void @test.marker(1)
  continue @6
label @1:
  %3 := Eq int %1, 2
  branch %3, @2, @5
label @2:
  %4 := Eq bool %0, false
  branch %4, @3, @4
label @3:
  Call void @test.marker(3)
  continue @6
label @4:
  Call void @test.marker(2)
  continue @6
label @5:
  Call void @test.marker(4)
  continue @6
label @6:
  Ret
}

func void @test.test2(bool %0, int %1) {
  %2 := Eq int %1, 1
  branch %2, @0, @3
label @0:
  %3 := Eq int %1, 2
  branch %3, @1, @2
label @1:
  Call void @test.marker(1)
  continue @10
label @2:
  Call void @test.marker(2)
  continue @10
label @3:
  %4 := Eq int %1, 2
  branch %4, @4, @9
label @4:
  %5 := Eq bool %0, true
  branch %5, @5, @9
label @5:
  branch %0, @6, @7
label @6:
  Call void @test.marker(3)
  continue @10
label @7:
  %6 := Not bool %0
  branch %6, @8, @9
label @8:
  Call void @test.marker(4)
  continue @10
label @9:
  Call void @test.marker(5)
  continue @10
label @10:
  Ret
}

func int @test.main() {
  Ret 0
}