func int @test.test1(bool %0, int %1) {
  %2 := Eq int %1, 0
  branch %2, @8, @0
label @0:
  %3 := Eq int %1, 1
  branch %3, @1, @3
label @1:
  branch %0, @8, @2
label @2:
  continue @8
label @3:
  %4 := Eq int %1, 2
  branch %4, @4, @8
label @4:
  branch %0, @8, @5
label @5:
  %5 := Not bool %0
  branch %5, @8, @6
label @6:
  %6 := Not bool %0
  %7 := Not bool %6
  branch %7, @8, @7
label @7:
  continue @8
label @8:
  %8 := Phi int @test.test1:0, @1:1, @3:7, @2:2, @4:3, @5:4, @6:5, @7:6
  Ret %8
}

func int @test.test2(bool %0, int %1) {
  %2 := Eq int %1, 1
  branch %2, @0, @2
label @0:
  branch %0, @7, @1
label @1:
  continue @7
label @2:
  %3 := Eq int %1, 3
  branch %3, @3, @6
label @3:
  %4 := Eq int %1, 2
  branch %4, @4, @6
label @4:
  branch %0, @7, @5
label @5:
  %5 := Not bool %0
  branch %5, @7, @6
label @6:
  continue @7
label @7:
  %6 := Phi int @0:1, @1:2, @4:3, @5:4, @6:5
  Ret %6
}

func int @test.main() {
  Ret 0
}