type $tuple<int,bool,$tuple<int,bool>*> {int, bool, $tuple<int,bool>*}

type $tuple<int,bool,std.string.String*> {int, bool, std.string.String*}

type $tuple<int,bool> {int, bool}

func int @test.test1($tuple<int,bool,std.string.String*>* %0) {
  %1 := Mov int 1
  continue @0
label @0:
  %2 := Phi int @test.test1:%1
  Ret %2
}

func int @test.test2($tuple<int,bool,std.string.String*>* %3) {
  %4 := GetPointer int %3.0
  %5 := Load int %4
  %6 := Eq int %5, 1
  branch %6, @1, @3
label @1:
  %7 := GetPointer bool %3.1
  %8 := Load bool %7
  %9 := Eq bool %8, false
  branch %9, @12, @2
label @2:
  %10 := Mov int 1
  continue @14
label @3:
  %11 := Eq int %5, 2
  branch %11, @4, @5
label @4:
  %12 := Mov int 2
  continue @14
label @5:
  %13 := Eq int %5, 3
  branch %13, @6, @8
label @6:
  %14 := GetPointer bool %3.1
  %15 := Load bool %14
  %16 := Eq bool %15, false
  branch %16, @7, @13
label @7:
  %17 := Mov int 4
  continue @14
label @8:
  %18 := Eq int %5, 4
  branch %18, @9, @11
label @9:
  %19 := GetPointer bool %3.1
  %20 := Load bool %19
  %21 := Eq bool %20, false
  branch %21, @10, @13
label @10:
  %22 := Mov int 5
  continue @14
label @11:
  %23 := GetPointer bool %3.1
  %24 := Load bool %23
  %25 := Eq bool %24, false
  branch %25, @12, @13
label @12:
  %26 := Mov int 6
  continue @14
label @13:
  %27 := Mov int 3
  continue @14
label @14:
  %28 := Phi int @12:%26, @2:%10, @4:%12, @7:%17, @13:%27, @10:%22
  Ret %28
}

func int @test.test3($tuple<int,bool,$tuple<int,bool>*>* %29) {
  %30 := GetPointer int %29.0
  %31 := Load int %30
  %32 := Eq int %31, 1
  branch %32, @15, @16
label @15:
  %33 := Mov int 1
  continue @23
label @16:
  %34 := GetPointer bool %29.1
  %35 := Load bool %34
  %36 := Eq bool %35, true
  branch %36, @17, @18
label @17:
  %37 := Mov int 2
  continue @23
label @18:
  %38 := GetPointer $tuple<int,bool>* %29.2
  %39 := Load $tuple<int,bool>* %38
  %40 := GetPointer int %39.0
  %41 := Load int %40
  %42 := Eq int %41, 2
  branch %42, @19, @20
label @19:
  %43 := Mov int 3
  continue @23
label @20:
  %44 := GetPointer $tuple<int,bool>* %29.2
  %45 := Load $tuple<int,bool>* %44
  %46 := GetPointer bool %45.1
  %47 := Load bool %46
  %48 := Eq bool %47, false
  branch %48, @21, @22
label @21:
  %49 := Mov int 4
  continue @23
label @22:
  %50 := Mov int 5
  continue @23
label @23:
  %51 := Phi int @15:%33, @17:%37, @19:%43, @21:%49, @22:%50
  Ret %51
}

func int @test.main() {
  Ret 0
}