type test.Tup {int, bool}

type test.Rec {int, bool}

func int @test.testNamedTuple(test.Tup* %0) {
  %1 := GetPointer int, test.Tup* %0.0
  %2 := Load int %1
  %3 := Eq int %2, 1
  branch %3, @0, @2
label @0:
  %4 := GetPointer bool, test.Tup* %0.1
  %5 := Load bool %4
  %6 := Eq bool %5, true
  branch %6, @2, @1
label @1:
  continue @2
label @2:
  %7 := Phi int @test.testNamedTuple:%2, @0:1, @1:2
  Ret %7
}

func int @test.testNamedRecord(test.Rec* %8) {
  %9 := GetPointer int, test.Rec* %8.0
  %10 := Load int %9
  %11 := Eq int %10, 1
  branch %11, @3, @5
label @3:
  %12 := GetPointer bool, test.Rec* %8.1
  %13 := Load bool %12
  %14 := Eq bool %13, false
  branch %14, @7, @4
label @4:
  continue @7
label @5:
  %15 := GetPointer bool, test.Rec* %8.1
  %16 := Load bool %15
  %17 := Eq bool %16, false
  branch %17, @6, @7
label @6:
  %18 := Add int %10, 3
  continue @7
label @7:
  %19 := Phi int @3:2, @5:%10, @4:1, @6:%18
  Ret %19
}

func unit @test.use<Function>(fn %20) {
  Ret
}

func int @test.main() {
  %21 := Call unit @test.use<Function>(@test.testNamedTuple)
  %22 := Call unit @test.use<Function>(@test.testNamedRecord)
  Ret 0
}