type $tuple<int,$tuple<int,bool>*> {int, $tuple<int,bool>*}

type $tuple<int,bool,$tuple<int,$tuple<int,bool>*>*> {int, bool, $tuple<int,$tuple<int,bool>*>*}

type $tuple<int,bool> {int, bool}

func int @test.test1(int %0) {
  Ret %0
}

func int @test.test2(int %1, bool %2) {
  %3 := Eq bool %2, true
  branch %3, @0, @1
label @0:
  continue @5
label @1:
  branch %2, @2, @3
label @2:
  continue @4
label @3:
  continue @4
label @4:
  %4 := Phi int @2:1, @3:2
  continue @5
label @5:
  %5 := Phi int @0:%1, @4:%4
  Ret %5
}

func int @test.test3(int %6) {
  %7 := Eq int %6, 1
  branch %7, @6, @7
label @6:
  continue @10
label @7:
  %8 := Eq int %6, 2
  branch %8, @8, @9
label @8:
  continue @10
label @9:
  %9 := Add int %6, %6
  %10 := Add int %9, %6
  continue @10
label @10:
  %11 := Phi int @6:1, @8:%6, @9:%10
  Ret %11
}

func int @test.test4(int %12, int %13, int %14) {
  %15 := Eq int %12, 1
  branch %15, @11, @15
label @11:
  %16 := Lt int %13, 4
  branch %16, @12, @13
label @12:
  continue @19
label @13:
  %17 := Eq int %13, 1
  branch %17, @14, @18
label @14:
  %18 := Add int %12, %14
  %19 := Lt int %18, 5
  branch %19, @17, @18
label @15:
  %20 := Eq int %13, 1
  branch %20, @16, @18
label @16:
  %21 := Add int %12, %14
  %22 := Lt int %21, 5
  branch %22, @17, @18
label @17:
  continue @19
label @18:
  continue @19
label @19:
  %23 := Phi int @12:1, @17:2, @18:3
  Ret %23
}

func int @test.test5(int %24, int %25) {
  %26 := Eq int %25, 1
  branch %26, @20, @21
label @20:
  continue @23
label @21:
  %27 := Eq int %24, 1
  branch %27, @22, @24
label @22:
  continue @23
label @23:
  %28 := Phi int @20:%24, @22:%25
  %29 := Add int %28, 2
  continue @25
label @24:
  continue @25
label @25:
  %30 := Phi int @23:%29, @24:3
  Ret %30
}

func int @test.test6(int %31, int %32) {
  %33 := Eq int %31, 1
  branch %33, @27, @26
label @26:
  %34 := Eq int %32, 1
  branch %34, @27, @28
label @27:
  continue @29
label @28:
  continue @29
label @29:
  %35 := Phi int @27:1, @28:2
  Ret %35
}

func int @test.test7($tuple<int,bool,$tuple<int,$tuple<int,bool>*>*>* %36) {
  %37 := GetPointer int, $tuple<int,bool,$tuple<int,$tuple<int,bool>*>*>* %36.0
  %38 := Load int %37
  %39 := Eq int %38, 1
  branch %39, @30, @31
label @30:
  %40 := GetPointer $tuple<int,$tuple<int,bool>*>*, $tuple<int,bool,$tuple<int,$tuple<int,bool>*>*>* %36.2
  %41 := Load $tuple<int,$tuple<int,bool>*>* %40
  %42 := GetPointer int, $tuple<int,$tuple<int,bool>*>* %41.0
  %43 := Load int %42
  continue @34
label @31:
  %44 := Eq int %38, 2
  branch %44, @32, @33
label @32:
  %45 := GetPointer $tuple<int,$tuple<int,bool>*>*, $tuple<int,bool,$tuple<int,$tuple<int,bool>*>*>* %36.2
  %46 := Load $tuple<int,$tuple<int,bool>*>* %45
  %47 := GetPointer int, $tuple<int,$tuple<int,bool>*>* %46.0
  %48 := Load int %47
  %49 := Add int %48, %48
  %50 := Add int %49, %48
  continue @34
label @33:
  %51 := GetPointer $tuple<int,$tuple<int,bool>*>*, $tuple<int,bool,$tuple<int,$tuple<int,bool>*>*>* %36.2
  %52 := Load $tuple<int,$tuple<int,bool>*>* %51
  %53 := GetPointer int, $tuple<int,$tuple<int,bool>*>* %52.0
  %54 := Load int %53
  %55 := GetPointer $tuple<int,bool>*, $tuple<int,$tuple<int,bool>*>* %52.1
  %56 := Load $tuple<int,bool>* %55
  %57 := GetPointer int, $tuple<int,bool>* %56.0
  %58 := Load int %57
  %59 := Add int %54, %58
  continue @34
label @34:
  %60 := Phi int @30:%43, @32:%50, @33:%59
  Ret %60
}

func int @test.test8(int %61) {
  %62 := Eq int %61, 1
  branch %62, @35, @36
label @35:
  continue @38
label @36:
  %63 := Eq int %61, 2
  branch %63, @37, @39
label @37:
  continue @38
label @38:
  %64 := Phi int @35:%61, @37:%61
  continue @47
label @39:
  %65 := Eq int %61, 4
  branch %65, @40, @41
label @40:
  continue @45
label @41:
  %66 := Eq int %61, 5
  branch %66, @42, @43
label @42:
  continue @45
label @43:
  %67 := Eq int %61, 6
  branch %67, @44, @46
label @44:
  continue @45
label @45:
  %68 := Phi int @40:%61, @42:%61, @44:%61
  %69 := Phi int @40:%61, @42:%61, @44:%61
  %70 := Add int %68, %69
  continue @47
label @46:
  continue @47
label @47:
  %71 := Phi int @38:%64, @45:%70, @46:3
  Ret %71
}

func int @test.test9($tuple<int,$tuple<int,bool>*>* %72) {
  %73 := GetPointer $tuple<int,bool>*, $tuple<int,$tuple<int,bool>*>* %72.1
  %74 := Load $tuple<int,bool>* %73
  %75 := GetPointer int, $tuple<int,bool>* %74.0
  %76 := Load int %75
  %77 := Eq int %76, 1
  branch %77, @48, @49
label @48:
  continue @51
label @49:
  %78 := Eq int %76, 2
  branch %78, @50, @52
label @50:
  continue @51
label @51:
  %79 := Phi int @48:%76, @50:%76
  continue @58
label @52:
  %80 := Eq int %76, 3
  branch %80, @53, @54
label @53:
  continue @56
label @54:
  %81 := Eq int %76, 4
  branch %81, @55, @57
label @55:
  continue @56
label @56:
  %82 := Phi int @53:%76, @55:%76
  %83 := Phi int @53:%76, @55:%76
  %84 := Add int %82, %83
  continue @58
label @57:
  continue @58
label @58:
  %85 := Phi int @51:%79, @56:%84, @57:7
  Ret %85
}

func int @test.test10($tuple<int,$tuple<int,bool>*>* %86) {
  %87 := GetPointer $tuple<int,bool>*, $tuple<int,$tuple<int,bool>*>* %86.1
  %88 := Load $tuple<int,bool>* %87
  %89 := GetPointer int, $tuple<int,bool>* %88.0
  %90 := Load int %89
  %91 := Eq int %90, 1
  branch %91, @59, @60
label @59:
  continue @62
label @60:
  %92 := Eq int %90, 2
  branch %92, @61, @63
label @61:
  continue @62
label @62:
  %93 := Phi int @59:%90, @61:%90
  continue @64
label @63:
  continue @64
label @64:
  %94 := Phi int @62:%93, @63:7
  Ret %94
}

func int @test.test11(int %95) {
  %96 := Eq int %95, 1
  branch %96, @65, @66
label @65:
  continue @68
label @66:
  %97 := Eq int %95, 2
  branch %97, @67, @69
label @67:
  continue @68
label @68:
  %98 := Phi int @65:%95, @67:%95
  continue @70
label @69:
  continue @70
label @70:
  %99 := Phi int @68:%98, @69:7
  Ret %99
}

func int @test.main() {
  Ret 0
}