type test.V1 {byte, byte[11]}

type test.V1::Tuple1 {byte, bool, byte[2], int, byte[4]}

type test.V1::Record1 {byte, byte[3], int, byte, byte[3]}

type test.V2 {byte, byte[23]}

type test.V2::Tuple2 {byte, bool, byte[6], test.V1*, byte[8]}

type test.V2::Record2 {byte, byte[7], test.V2*, bool, byte[7]}

func int @test.test1(test.V1* %0) {
  %1 := Load byte %0
  %2 := Eq byte %1, 0
  branch %2, @0, @1
label @0:
  %3 := Mov int 2
  continue @4
label @1:
  %4 := Eq byte %1, 2
  branch %4, @2, @3
label @2:
  %5 := Mov int 3
  continue @4
label @3:
  %6 := Mov int 1
  continue @4
label @4:
  %7 := Phi int @0:%3, @2:%5, @3:%6
  Ret %7
}

func int @test.test2(test.V1* %8) {
  %9 := Load byte %8
  %10 := Eq byte %9, 2
  branch %10, @5, @9
label @5:
  %11 := GetPointer int, test.V1::Record1* %8.2
  %12 := Load int %11
  %13 := Eq int %12, 2
  branch %13, @6, @7
label @6:
  %14 := Mov int 1
  continue @15
label @7:
  %15 := GetPointer byte, test.V1::Record1* %8.3
  %16 := Load byte %15
  %17 := Eq byte %16, 2
  branch %17, @8, @14
label @8:
  %18 := Mov int 3
  continue @15
label @9:
  %19 := Eq byte %9, 1
  branch %19, @10, @14
label @10:
  %20 := GetPointer int, test.V1::Tuple1* %8.3
  %21 := Load int %20
  %22 := Eq int %21, 4
  branch %22, @11, @12
label @11:
  %23 := Mov int 2
  continue @15
label @12:
  %24 := GetPointer bool, test.V1::Tuple1* %8.1
  %25 := Load bool %24
  %26 := Eq bool %25, true
  branch %26, @13, @14
label @13:
  %27 := Mov int 4
  continue @15
label @14:
  %28 := Mov int 5
  continue @15
label @15:
  %29 := Phi int @6:%14, @8:%18, @14:%28, @11:%23, @13:%27
  Ret %29
}

func int @test.test3(test.V2* %30) {
  %31 := Load byte %30
  %32 := Eq byte %31, 2
  branch %32, @16, @19
label @16:
  %33 := GetPointer test.V2*, test.V2::Record2* %30.2
  %34 := Load test.V2* %33
  %35 := Load byte %34
  %36 := Eq byte %35, 2
  branch %36, @17, @23
label @17:
  %37 := GetPointer test.V2*, test.V2::Record2* %30.2
  %38 := Load test.V2* %37
  %39 := GetPointer test.V2*, test.V2::Record2* %38.2
  %40 := Load test.V2* %39
  %41 := Load byte %40
  %42 := Eq byte %41, 1
  branch %42, @18, @23
label @18:
  %43 := Mov int 2
  continue @24
label @19:
  %44 := Eq byte %31, 0
  branch %44, @20, @23
label @20:
  %45 := GetPointer test.V1*, test.V2::Tuple2* %30.3
  %46 := Load test.V1* %45
  %47 := Load byte %46
  %48 := Eq byte %47, 1
  branch %48, @21, @23
label @21:
  %49 := GetPointer test.V1*, test.V2::Tuple2* %30.3
  %50 := Load test.V1* %49
  %51 := GetPointer bool, test.V1::Tuple1* %50.1
  %52 := Load bool %51
  %53 := Eq bool %52, true
  branch %53, @22, @23
label @22:
  %54 := Mov int 1
  continue @24
label @23:
  %55 := Mov int 3
  continue @24
label @24:
  %56 := Phi int @23:%55, @18:%43, @22:%54
  Ret %56
}

func int @test.main() {
  Ret 0
}