test/parser/ast/binary_operation/bitwise_or_in_match.myte
{
  node: Module,
  loc: 1:0-14:1,
  module: {
    node: Module,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-14:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "main",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-14:1,
        statements: [
          {
            node: Match,
            loc: 4:2-13:3,
            args: [
              {
                node: IntLiteral,
                loc: 4:9-4:10,
                raw: "1",
              },
            ],
            cases: [
              {
                node: MatchCase,
                loc: 5:6-5:18,
                pattern: {
                  node: Identifier,
                  loc: 5:6-5:7,
                  name: "_",
                },
                guard: None,
                right: {
                  node: BinaryOperation,
                  loc: 5:12-5:17,
                  op: BitwiseOr,
                  left: {
                    node: IntLiteral,
                    loc: 5:12-5:13,
                    raw: "2",
                  },
                  right: {
                    node: IntLiteral,
                    loc: 5:16-5:17,
                    raw: "3",
                  },
                },
              },
              {
                node: MatchCase,
                loc: 6:6-6:24,
                pattern: {
                  node: Identifier,
                  loc: 6:6-6:7,
                  name: "_",
                },
                guard: None,
                right: {
                  node: TupleExpression,
                  loc: 6:11-6:24,
                  elements: [
                    {
                      node: BinaryOperation,
                      loc: 6:12-6:17,
                      op: BitwiseOr,
                      left: {
                        node: IntLiteral,
                        loc: 6:12-6:13,
                        raw: "2",
                      },
                      right: {
                        node: IntLiteral,
                        loc: 6:16-6:17,
                        raw: "3",
                      },
                    },
                    {
                      node: IntLiteral,
                      loc: 6:19-6:20,
                      raw: "4",
                    },
                    {
                      node: IntLiteral,
                      loc: 6:22-6:23,
                      raw: "5",
                    },
                  ],
                },
              },
              {
                node: MatchCase,
                loc: 7:6-7:19,
                pattern: {
                  node: Identifier,
                  loc: 7:6-7:7,
                  name: "_",
                },
                guard: None,
                right: {
                  node: IndexedAccess,
                  loc: 7:11-7:19,
                  target: {
                    node: Identifier,
                    loc: 7:11-7:12,
                    name: "a",
                  },
                  index: {
                    node: BinaryOperation,
                    loc: 7:13-7:18,
                    op: BitwiseOr,
                    left: {
                      node: IntLiteral,
                      loc: 7:13-7:14,
                      raw: "2",
                    },
                    right: {
                      node: IntLiteral,
                      loc: 7:17-7:18,
                      raw: "3",
                    },
                  },
                },
              },
              {
                node: MatchCase,
                loc: 8:6-8:22,
                pattern: {
                  node: Identifier,
                  loc: 8:6-8:7,
                  name: "_",
                },
                guard: None,
                right: {
                  node: Call,
                  loc: 8:11-8:22,
                  func: {
                    node: Identifier,
                    loc: 8:11-8:14,
                    name: "Tup",
                  },
                  args: [
                    {
                      node: BinaryOperation,
                      loc: 8:16-8:21,
                      op: BitwiseOr,
                      left: {
                        node: IntLiteral,
                        loc: 8:16-8:17,
                        raw: "2",
                      },
                      right: {
                        node: IntLiteral,
                        loc: 8:20-8:21,
                        raw: "3",
                      },
                    },
                  ],
                },
              },
              {
                node: MatchCase,
                loc: 9:6-9:31,
                pattern: {
                  node: Identifier,
                  loc: 9:6-9:7,
                  name: "_",
                },
                guard: None,
                right: {
                  node: RecordExpression,
                  loc: 9:11-9:31,
                  name: {
                    node: Identifier,
                    loc: 9:11-9:14,
                    name: "Rec",
                  },
                  fields: [
                    {
                      node: RecordExpressionField,
                      loc: 9:17-9:29,
                      name: {
                        node: Identifier,
                        loc: 9:17-9:22,
                        name: "field",
                      },
                      value: {
                        node: BinaryOperation,
                        loc: 9:24-9:29,
                        op: BitwiseOr,
                        left: {
                          node: IntLiteral,
                          loc: 9:24-9:25,
                          raw: "2",
                        },
                        right: {
                          node: IntLiteral,
                          loc: 9:28-9:29,
                          raw: "3",
                        },
                      },
                    },
                  ],
                },
              },
              {
                node: MatchCase,
                loc: 10:6-12:6,
                pattern: {
                  node: Identifier,
                  loc: 10:6-10:7,
                  name: "_",
                },
                guard: None,
                right: {
                  node: Match,
                  loc: 10:12-12:5,
                  args: [
                    {
                      node: IntLiteral,
                      loc: 10:19-10:20,
                      raw: "1",
                    },
                  ],
                  cases: [
                    {
                      node: MatchCase,
                      loc: 11:9-11:21,
                      pattern: {
                        node: Identifier,
                        loc: 11:9-11:10,
                        name: "_",
                      },
                      guard: None,
                      right: {
                        node: BinaryOperation,
                        loc: 11:15-11:20,
                        op: BitwiseOr,
                        left: {
                          node: IntLiteral,
                          loc: 11:15-11:16,
                          raw: "2",
                        },
                        right: {
                          node: IntLiteral,
                          loc: 11:19-11:20,
                          raw: "3",
                        },
                      },
                    },
                  ],
                },
              },
            ],
          },
        ],
      },
      return: None,
      type_params: [],
    },
  ],
}