func unit @test.noArgsFunc() {
  Ret
}

func int @test.singleArgFunc(int %0) {
  Ret %0
}

func int @test.singleArgFunc2(int %1) {
  %2 := Add int %1, 1
  Ret %2
}

func unit @test.multiArgsFunc(int %3, int %4, std.string.String* %5) {
  Ret
}

func unit @test.directCalls() {
  %6 := CallBuiltin std.string.String* myte_alloc(1)
  %7 := GetPointer byte*, std.string.String* %6.0
  Store byte* %7, @.S0
  %8 := GetPointer int, std.string.String* %6.1
  Store int %8, 3
  %9 := GetPointer int, std.string.String* %6.2
  Store int %9, 3
  %10 := Call unit @test.noArgsFunc()
  %11 := Call int @test.singleArgFunc(33)
  %12 := CallBuiltin std.string.String* myte_alloc(1)
  %13 := GetPointer byte*, std.string.String* %12.0
  Store byte* %13, @.S1
  %14 := GetPointer int, std.string.String* %12.1
  Store int %14, 4
  %15 := GetPointer int, std.string.String* %12.2
  Store int %15, 4
  %16 := Call unit @test.multiArgsFunc(29, 98, %12)
  %17 := Call int @test.singleArgFunc(%11)
  %18 := Call int @test.singleArgFunc(45)
  %19 := Mul int 5, 6
  %20 := Add int 2, %19
  %21 := Call unit @test.multiArgsFunc(%18, %20, %6)
  Ret
}

global byte[3] @.S0 = "str"

global byte[4] @.S1 = "test"

func unit @test.indirectCalls() {
  branch true, @0, @1
label @0:
  continue @1
label @1:
  %22 := Phi fn @test.indirectCalls:@test.singleArgFunc, @0:@test.singleArgFunc2
  %23 := Call int %22(10)
  %24 := Add int 1, 2
  %25 := Call int %22(%24)
  %26 := Add int 3, %25
  Ret
}

func int @test.main() {
  Ret 0
}