func bool @test.bool() {
  Ret true
}

func int @test.testSimpleIf() {
  %0 := Call bool @test.bool()
  branch %0, @1, @0
label @0:
  continue @1
label @1:
  %1 := Phi int @test.testSimpleIf:1, @0:2
  Ret %1
}

func int @test.testIfWithExpressions(int %2, int %3) {
  %4 := Call bool @test.bool()
  branch %4, @2, @3
label @2:
  %5 := Add int %2, %3
  continue @4
label @3:
  %6 := Mul int %2, %3
  %7 := Add int %6, %2
  continue @4
label @4:
  %8 := Phi int @2:%5, @3:%7
  Ret %8
}

func int @test.testNestedIfStatementInExpressionPosition() {
  %9 := Call bool @test.bool()
  branch %9, @5, @8
label @5:
  %10 := Call bool @test.bool()
  branch %10, @7, @6
label @6:
  continue @7
label @7:
  %11 := Phi int @5:1, @6:2
  continue @11
label @8:
  %12 := Call bool @test.bool()
  branch %12, @10, @9
label @9:
  continue @10
label @10:
  %13 := Phi int @8:3, @9:4
  continue @11
label @11:
  %14 := Phi int @7:%11, @10:%13
  Ret %14
}

func void @test.use<Function>(fn %15) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.testSimpleIf)
  Call void @test.use<Function>(@test.testIfWithExpressions)
  Call void @test.use<Function>(@test.testNestedIfStatementInExpressionPosition)
  Ret 0
}