type test.Tup1 {int}

type test.Tup2 {bool, byte[3], int, std.string.String*}

type test.Tup3 {byte, byte[7], test.Tup2*, long}

type test.Tup4 {int, int, test.Tup3*}

type test.Rec1 {test.Tup4*}

func test.Tup1* @test.makeTup(int %0) {
  %1 := Call test.Tup1* myte.builtin.alloc(1)
  %2 := GetPointer int, test.Tup1* %1.0
  Store int %2, %0
  Ret %1
}

func void @test.testIndexing(test.Tup1* %0, test.Tup2* %1, test.Tup3* %2, test.Tup4* %3, test.Rec1* %4) {
  %5 := GetPointer int, test.Tup1* %0.0
  %6 := Load int %5
  %7 := GetPointer std.string.String*, test.Tup2* %1.3
  %8 := Load std.string.String* %7
  %9 := GetPointer bool, test.Tup2* %1.0
  %10 := Load bool %9
  %11 := GetPointer byte, test.Tup3* %2.0
  %12 := Load byte %11
  %13 := GetPointer test.Tup2*, test.Tup3* %2.2
  %14 := Load test.Tup2* %13
  %15 := GetPointer int, test.Tup2* %14.2
  %16 := Load int %15
  %17 := GetPointer test.Tup3*, test.Tup4* %3.2
  %18 := Load test.Tup3* %17
  %19 := GetPointer test.Tup2*, test.Tup3* %18.2
  %20 := Load test.Tup2* %19
  %21 := GetPointer std.string.String*, test.Tup2* %20.3
  %22 := Load std.string.String* %21
  %23 := Mul int 2, 3
  %24 := Call test.Tup1* @test.makeTup(%23)
  %25 := GetPointer int, test.Tup1* %24.0
  %26 := Load int %25
  %27 := GetPointer test.Tup4*, test.Rec1* %4.0
  %28 := Load test.Tup4* %27
  %29 := GetPointer test.Tup3*, test.Tup4* %28.2
  %30 := Load test.Tup3* %29
  %31 := GetPointer test.Tup2*, test.Tup3* %30.2
  %32 := Load test.Tup2* %31
  Ret
}

func int @test.main() {
  Ret 0
}