func bool @test.testConstants1() {
  Ret true
}

func bool @test.testConstants2() {
  branch true, @0, @1
label @0:
  continue @1
label @1:
  %0 := Phi bool @test.testConstants2:false, @0:true
  Ret %0
}

func bool @test.testConstants3() {
  Ret true
}

func bool @test.testConstants4() {
  branch false, @2, @3
label @2:
  continue @3
label @3:
  %1 := Phi bool @test.testConstants4:false, @2:true
  Ret %1
}

func bool @test.testConstant1(bool %2) {
  Ret true
}

func bool @test.testConstant2(bool %3) {
  branch %3, @4, @5
label @4:
  continue @5
label @5:
  %4 := Phi bool @test.testConstant2:false, @4:true
  Ret %4
}

func bool @test.testConstant3(bool %5) {
  branch true, @6, @7
label @6:
  continue @7
label @7:
  %6 := Phi bool @test.testConstant3:%5, @6:true
  Ret %6
}

func bool @test.testConstant4(bool %7) {
  branch false, @8, @9
label @8:
  continue @9
label @9:
  %8 := Phi bool @test.testConstant4:%7, @8:true
  Ret %8
}

func bool @test.testVariables(bool %9, bool %10) {
  branch %9, @10, @11
label @10:
  continue @11
label @11:
  %11 := Phi bool @test.testVariables:%10, @10:true
  Ret %11
}

func int @test.main() {
  Ret 0
}