func bool @test.testConstants1() {
  branch true, @1, @0
label @0:
  continue @1
label @1:
  %0 := Phi bool @test.testConstants1:true, @0:false
  Ret %0
}

func bool @test.testConstants2() {
  Ret false
}

func bool @test.testConstants3() {
  branch false, @1, @0
label @0:
  continue @1
label @1:
  %0 := Phi bool @test.testConstants3:true, @0:false
  Ret %0
}

func bool @test.testConstants4() {
  Ret false
}

func bool @test.testConstant1(bool %0) {
  branch %0, @1, @0
label @0:
  continue @1
label @1:
  %1 := Phi bool @test.testConstant1:true, @0:false
  Ret %1
}

func bool @test.testConstant2(bool %0) {
  Ret false
}

func bool @test.testConstant3(bool %0) {
  branch true, @1, @0
label @0:
  continue @1
label @1:
  %1 := Phi bool @test.testConstant3:%0, @0:false
  Ret %1
}

func bool @test.testConstant4(bool %0) {
  branch false, @1, @0
label @0:
  continue @1
label @1:
  %1 := Phi bool @test.testConstant4:%0, @0:false
  Ret %1
}

func bool @test.testVariables(bool %0, bool %1) {
  branch %0, @1, @0
label @0:
  continue @1
label @1:
  %2 := Phi bool @test.testVariables:%1, @0:false
  Ret %2
}

func int @test.main() {
  Ret 0
}