func bool @test.testConstants1() {
  Ret true
}

func bool @test.testConstants2() {
  branch true, @0, @1
label @0:
  continue @1
label @1:
  %0 := Phi bool @test.testConstants2:false, @0:true
  Ret %0
}

func bool @test.testConstants3() {
  Ret true
}

func bool @test.testConstants4() {
  branch false, @0, @1
label @0:
  continue @1
label @1:
  %0 := Phi bool @test.testConstants4:false, @0:true
  Ret %0
}

func bool @test.testConstant1(bool %0) {
  Ret true
}

func bool @test.testConstant2(bool %0) {
  branch %0, @0, @1
label @0:
  continue @1
label @1:
  %1 := Phi bool @test.testConstant2:false, @0:true
  Ret %1
}

func bool @test.testConstant3(bool %0) {
  branch true, @0, @1
label @0:
  continue @1
label @1:
  %1 := Phi bool @test.testConstant3:%0, @0:true
  Ret %1
}

func bool @test.testConstant4(bool %0) {
  branch false, @0, @1
label @0:
  continue @1
label @1:
  %1 := Phi bool @test.testConstant4:%0, @0:true
  Ret %1
}

func bool @test.testVariables(bool %0, bool %1) {
  branch %0, @0, @1
label @0:
  continue @1
label @1:
  %2 := Phi bool @test.testVariables:%1, @0:true
  Ret %2
}

func void @test.use<Function>(fn %0) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.testConstants1)
  Call void @test.use<Function>(@test.testConstants2)
  Call void @test.use<Function>(@test.testConstants3)
  Call void @test.use<Function>(@test.testConstants4)
  Call void @test.use<Function>(@test.testConstant1)
  Call void @test.use<Function>(@test.testConstant2)
  Call void @test.use<Function>(@test.testConstant3)
  Call void @test.use<Function>(@test.testConstant4)
  Call void @test.use<Function>(@test.testVariables)
  Ret 0
}