type test.Rec1 {int}

type test.Rec2 {bool, int, std.string.String*}

type test.Rec3 {byte, test.Rec2*, long}

type test.Rec4 {int, int, test.Rec3*}

type test.Tup1 {test.Rec4*}

func test.Rec1* @test.makeRec(int %0) {
  %1 := CallBuiltin test.Rec1* myte_alloc(1)
  %2 := GetPointer int, test.Rec1* %1.0
  Store int %2, %0
  Ret %1
}

func void @test.testIndexing(test.Rec1* %0, test.Rec2* %1, test.Rec3* %2, test.Rec4* %3, test.Tup1* %4) {
  %5 := GetPointer int, test.Rec1* %0.0
  %6 := Load int %5
  %7 := GetPointer std.string.String*, test.Rec2* %1.2
  %8 := Load std.string.String* %7
  %9 := GetPointer bool, test.Rec2* %1.0
  %10 := Load bool %9
  %11 := GetPointer byte, test.Rec3* %2.0
  %12 := Load byte %11
  %13 := GetPointer test.Rec2*, test.Rec3* %2.1
  %14 := Load test.Rec2* %13
  %15 := GetPointer int, test.Rec2* %14.1
  %16 := Load int %15
  %17 := GetPointer test.Rec3*, test.Rec4* %3.2
  %18 := Load test.Rec3* %17
  %19 := GetPointer test.Rec2*, test.Rec3* %18.1
  %20 := Load test.Rec2* %19
  %21 := GetPointer std.string.String*, test.Rec2* %20.2
  %22 := Load std.string.String* %21
  %23 := Mul int 2, 3
  %24 := Call test.Rec1* @test.makeRec(%23)
  %25 := GetPointer int, test.Rec1* %24.0
  %26 := Load int %25
  %27 := GetPointer test.Rec4*, test.Tup1* %4.0
  %28 := Load test.Rec4* %27
  %29 := GetPointer test.Rec3*, test.Rec4* %28.2
  %30 := Load test.Rec3* %29
  %31 := GetPointer test.Rec2*, test.Rec3* %30.1
  %32 := Load test.Rec2* %31
  Ret
}

func void @test.use<Function>(fn %0) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.testIndexing)
  Ret 0
}