type test.Rec1 {int}

type test.Rec2 {std.string.String*, bool, int}

type test.Rec3 {byte, test.Rec2*, long}

type test.Rec4 {int, int, test.Rec3*}

type test.Tup1 {test.Rec4*}

func test.Rec1* @test.makeRec(int %0) {
  %1 := CallBuiltin test.Rec1* myte_alloc(1)
  %2 := GetPointer int, test.Rec1* %1.0
  Store int %2, %0
  Ret %1
}

func unit @test.testIndexing(test.Rec1* %3, test.Rec2* %4, test.Rec3* %5, test.Rec4* %6, test.Tup1* %7) {
  %8 := GetPointer int, test.Rec1* %3.0
  %9 := Load int %8
  %10 := GetPointer std.string.String*, test.Rec2* %4.0
  %11 := Load std.string.String* %10
  %12 := GetPointer bool, test.Rec2* %4.1
  %13 := Load bool %12
  %14 := GetPointer byte, test.Rec3* %5.0
  %15 := Load byte %14
  %16 := GetPointer test.Rec2*, test.Rec3* %5.1
  %17 := Load test.Rec2* %16
  %18 := GetPointer int, test.Rec2* %17.2
  %19 := Load int %18
  %20 := GetPointer test.Rec3*, test.Rec4* %6.2
  %21 := Load test.Rec3* %20
  %22 := GetPointer test.Rec2*, test.Rec3* %21.1
  %23 := Load test.Rec2* %22
  %24 := GetPointer std.string.String*, test.Rec2* %23.0
  %25 := Load std.string.String* %24
  %26 := Mul int 2, 3
  %27 := Call test.Rec1* @test.makeRec(%26)
  %28 := GetPointer int, test.Rec1* %27.0
  %29 := Load int %28
  %30 := GetPointer test.Rec4*, test.Tup1* %7.0
  %31 := Load test.Rec4* %30
  %32 := GetPointer test.Rec3*, test.Rec4* %31.2
  %33 := Load test.Rec3* %32
  %34 := GetPointer test.Rec2*, test.Rec3* %33.1
  %35 := Load test.Rec2* %34
  Ret
}

func unit @test.use<fn>(fn %36) {
  Ret
}

func int @test.main() {
  %37 := Call unit @test.use<fn>(@test.testIndexing)
  Ret 0
}