func bool @test.bool() {
  Ret true
}

func int @test.testSimpleTernary() {
  %0 := Call bool @test.bool()
  branch %0, @0, @1
label @0:
  %1 := Mov int 1
  continue @2
label @1:
  %2 := Mov int 2
  continue @2
label @2:
  %3 := Phi int @0:%1, @1:%2
  Ret %3
}

func int @test.testTernaryWithExpressions(int %4, int %5) {
  %6 := Call bool @test.bool()
  branch %6, @3, @4
label @3:
  %7 := Add int %4, %5
  %8 := Mov int %7
  continue @5
label @4:
  %9 := Mul int %4, %5
  %10 := Add int %9, %4
  %11 := Mov int %10
  continue @5
label @5:
  %12 := Phi int @3:%8, @4:%11
  Ret %12
}

func int @test.testNestedTernary() {
  %13 := Call bool @test.bool()
  branch %13, @6, @10
label @6:
  %14 := Call bool @test.bool()
  branch %14, @7, @8
label @7:
  %15 := Mov int 1
  continue @9
label @8:
  %16 := Mov int 2
  continue @9
label @9:
  %17 := Phi int @7:%15, @8:%16
  %18 := Mov int %17
  continue @14
label @10:
  %19 := Call bool @test.bool()
  branch %19, @11, @12
label @11:
  %20 := Mov int 3
  continue @13
label @12:
  %21 := Mov int 4
  continue @13
label @13:
  %22 := Phi int @11:%20, @12:%21
  %23 := Mov int %22
  continue @14
label @14:
  %24 := Phi int @9:%18, @13:%23
  Ret %24
}

func int @test.main() {
  Ret 0
}