func unit @test.bools(bool %0) {
  %1 := LogNot %0
  Ret
}

func unit @test.ints(int %2) {
  %3 := Neg int %2
  %4 := BitNot int %2
  Ret
}

func unit @test.bytes(byte %5) {
  %6 := Neg byte %5
  %7 := BitNot byte %5
  Ret
}

func unit @test.longs(long %8) {
  %9 := Neg long %8
  %10 := BitNot long %8
  Ret
}

func unit @test.use<fn>(fn %11) {
  Ret
}

func int @test.main() {
  %12 := Call unit @test.use<fn>(@test.bools)
  %13 := Call unit @test.use<fn>(@test.ints)
  %14 := Call unit @test.use<fn>(@test.bytes)
  %15 := Call unit @test.use<fn>(@test.longs)
  Ret 0
}