func void @test.bools(bool %0) {
  %1 := Not bool %0
  Ret
}

func void @test.ints(int %0) {
  %1 := Neg int %0
  %2 := Not int %0
  Ret
}

func void @test.bytes(byte %0) {
  %1 := Neg byte %0
  %2 := Not byte %0
  Ret
}

func void @test.longs(long %0) {
  %1 := Neg long %0
  %2 := Not long %0
  Ret
}

func void @test.doubles(double %0) {
  %1 := Neg double %0
  Ret
}

func int @test.main() {
  Ret 0
}