func void @test.bools(bool %0) {
  %1 := LogNot %0
  Ret
}

func void @test.ints(int %2) {
  %3 := Neg int %2
  %4 := BitNot int %2
  Ret
}

func void @test.bytes(byte %5) {
  %6 := Neg byte %5
  %7 := BitNot byte %5
  Ret
}

func void @test.longs(long %8) {
  %9 := Neg long %8
  %10 := BitNot long %8
  Ret
}

func void @test.use<Function>(fn %11) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.bools)
  Call void @test.use<Function>(@test.ints)
  Call void @test.use<Function>(@test.bytes)
  Call void @test.use<Function>(@test.longs)
  Ret 0
}