func void @test.negateComparisons(int %0) {
  %1 := Neq int %0, 1
  Call void @test.use<Bool>(%1)
  %2 := Neq int %0, 1
  Call void @test.use<Bool>(%2)
  %3 := Eq int %0, 1
  Call void @test.use<Bool>(%3)
  %4 := GtEq int %0, 1
  Call void @test.use<Bool>(%4)
  %5 := Gt int %0, 1
  Call void @test.use<Bool>(%5)
  %6 := LtEq int %0, 1
  Call void @test.use<Bool>(%6)
  %7 := Lt int %0, 1
  Call void @test.use<Bool>(%7)
  Ret
}

func void @test.negateMultiple(int %0) {
  %1 := Neq int %0, 1
  Call void @test.use<Bool>(%1)
  %2 := Eq int %0, 1
  Call void @test.use<Bool>(%2)
  %3 := Neq int %0, 1
  Call void @test.use<Bool>(%3)
  %4 := Eq int %0, 1
  Call void @test.use<Bool>(%4)
  Ret
}

func void @test.use<Bool>(bool %0) {
  Ret
}

func int @test.main() {
  Ret 0
}