  .global _main

  .text
test.cond:
  movb $1, %al
  ret
_main:
  subq $8, %rsp
  movl $16, (%rsp)
  movl $1, %edi
  movl $2, %esi
  movl $3, %edx
  movl $4, %ecx
  movl $5, %r8d
  movl $6, %r9d
  call test.testSingleSpillUsingAllRegisters
  movl %eax, %edi
  call std.int.Int.toString
  movq %rax, %rdi
  call std.io.println
  leaq test.testSingleSpillUsingAllRegisters(%rip), %rdi
  call test.use$Function$
  leaq test.testCallerSavedRegistersSpilledAcrossFunctionCalls(%rip), %rdi
  call test.use$Function$
  leaq test.testSingleSpillUsingAllRegistersFromLocals(%rip), %rdi
  call test.use$Function$
  movl $0, %eax
  addq $8, %rsp
  ret
test.testCallerSavedRegistersSpilledAcrossFunctionCalls:
  push %rbx
  push %r12
  push %r13
  push %r14
  push %r15
  subq $8, %rsp
  movl %edi, (%rsp)
  movl %esi, %r15d
  movl %edx, %r14d
  movl %ecx, %r13d
  movl %r8d, %r12d
  movl %r9d, %ebx
  movl $3, %edi
  call test.use$Int$
  addl (%rsp), %r15d
  addl %r15d, %r14d
  addl %r14d, %r13d
  addl %r13d, %r12d
  movl %ebx, %eax
  addl %r12d, %eax
  addq $8, %rsp
  pop %r15
  pop %r14
  pop %r13
  pop %r12
  pop %rbx
  ret
test.testSingleSpillUsingAllRegisters:
  push %rbx
  push %r12
  push %r13
  push %r14
  push %r15
  subq $8, %rsp
  movl %edx, (%rsp)
  movl %ecx, %r15d
  movl %esi, %r14d
  addl %edi, %r14d
  movl (%rsp), %r13d
  addl %edi, %r13d
  movl %r15d, %r12d
  addl %edi, %r12d
  movl %r8d, %ebx
  addl %edi, %ebx
  movl %r9d, %r11d
  addl %edi, %r11d
  movl (%rsp), %r10d
  addl %esi, %r10d
  movl %r15d, %edx
  addl %esi, %edx
  movl %r8d, %ecx
  addl %esi, %ecx
  movl %r9d, %eax
  addl %esi, %eax
  addl %edi, %esi
  movl (%rsp), %edi
  addl %esi, %edi
  addl %edi, %r15d
  addl %r15d, %r8d
  addl %r8d, %r9d
  addl %r9d, %r14d
  addl %r14d, %r13d
  addl %r13d, %r12d
  addl %r12d, %ebx
  addl %ebx, %r11d
  addl %r11d, %r10d
  addl %r10d, %edx
  addl %edx, %ecx
  addl %ecx, %eax
  addl 56(%rsp), %eax
  addq $8, %rsp
  pop %r15
  pop %r14
  pop %r13
  pop %r12
  pop %rbx
  ret
test.testSingleSpillUsingAllRegistersFromLocals:
  push %rbx
  push %r12
  push %r13
  push %r14
  push %r15
  subq $8, %rsp
  call test.cond
  testb %al, %al
  je .L0
  movl $101, %r15d
  movl $102, %r14d
  movl $103, %r13d
  movl $104, (%rsp)
  movl $105, %r12d
  movl $106, %ebx
  movl $107, %r11d
  movl $108, %r10d
  movl $109, %r9d
  movl $110, %r8d
  movl $111, %edi
  movl $112, %esi
  movl $113, %edx
  movl $114, %ecx
  movl $115, %eax
  jmp .L1
.L0:
  movl $1, %r15d
  movl $2, %r14d
  movl $3, %r13d
  movl $4, (%rsp)
  movl $5, %r12d
  movl $6, %ebx
  movl $7, %r11d
  movl $8, %r10d
  movl $9, %r9d
  movl $10, %r8d
  movl $11, %edi
  movl $12, %esi
  movl $13, %edx
  movl $14, %ecx
  movl $15, %eax
.L1:
  addl %r15d, %r14d
  addl %r14d, %r13d
  movl (%rsp), %r14d
  addl %r13d, %r14d
  addl %r14d, %r12d
  addl %r12d, %ebx
  addl %ebx, %r11d
  addl %r11d, %r10d
  addl %r10d, %r9d
  addl %r9d, %r8d
  addl %r8d, %edi
  addl %edi, %esi
  addl %esi, %edx
  addl %edx, %ecx
  addl %ecx, %eax
  addq $8, %rsp
  pop %r15
  pop %r14
  pop %r13
  pop %r12
  pop %rbx
  ret
test.use$Function$:
  movq %rdi, %rax
  ret
test.use$Int$:
  movl %edi, %eax
  ret
88