type _ZeroSize {}

func void @test.emptyVec() {
  %0 := Call std.vec.Vec<Int>* myte.builtin.alloc(1)
  %1 := GetPointer int*, std.vec.Vec<Int>* %0.2
  Store int* %1, null
  %2 := GetPointer int, std.vec.Vec<Int>* %0.0
  Store int %2, 0
  %3 := GetPointer int, std.vec.Vec<Int>* %0.1
  Store int %3, 0
  %4 := Call std.vec.Vec<Bool>* myte.builtin.alloc(1)
  %5 := GetPointer bool*, std.vec.Vec<Bool>* %4.2
  Store bool* %5, null
  %6 := GetPointer int, std.vec.Vec<Bool>* %4.0
  Store int %6, 0
  %7 := GetPointer int, std.vec.Vec<Bool>* %4.1
  Store int %7, 0
  Ret
}

func void @test.oneElementVec() {
  %0 := Call int* myte.builtin.alloc(1)
  %1 := GetPointer int, int* %0[int 0]
  Store int %1, 1
  %2 := Call std.vec.Vec<Int>* myte.builtin.alloc(1)
  %3 := GetPointer int*, std.vec.Vec<Int>* %2.2
  Store int* %3, %0
  %4 := GetPointer int, std.vec.Vec<Int>* %2.0
  Store int %4, 1
  %5 := GetPointer int, std.vec.Vec<Int>* %2.1
  Store int %5, 1
  %6 := Call byte* myte.builtin.alloc(1)
  %7 := GetPointer byte, byte* %6[int 0]
  Store byte %7, 2
  %8 := Call std.vec.Vec<Byte>* myte.builtin.alloc(1)
  %9 := GetPointer byte*, std.vec.Vec<Byte>* %8.2
  Store byte* %9, %6
  %10 := GetPointer int, std.vec.Vec<Byte>* %8.0
  Store int %10, 1
  %11 := GetPointer int, std.vec.Vec<Byte>* %8.1
  Store int %11, 1
  Ret
}

func void @test.multiElementVec() {
  %0 := Call int* myte.builtin.alloc(3)
  %1 := GetPointer int, int* %0[int 0]
  Store int %1, 5
  %2 := GetPointer int, int* %0[int 1]
  Store int %2, 6
  %3 := GetPointer int, int* %0[int 2]
  Store int %3, 7
  %4 := Call std.vec.Vec<Int>* myte.builtin.alloc(1)
  %5 := GetPointer int*, std.vec.Vec<Int>* %4.2
  Store int* %5, %0
  %6 := GetPointer int, std.vec.Vec<Int>* %4.0
  Store int %6, 3
  %7 := GetPointer int, std.vec.Vec<Int>* %4.1
  Store int %7, 3
  %8 := Call bool* myte.builtin.alloc(4)
  %9 := GetPointer bool, bool* %8[int 0]
  Store bool %9, false
  %10 := GetPointer bool, bool* %8[int 1]
  Store bool %10, true
  %11 := GetPointer bool, bool* %8[int 2]
  Store bool %11, false
  %12 := GetPointer bool, bool* %8[int 3]
  Store bool %12, true
  %13 := Call std.vec.Vec<Bool>* myte.builtin.alloc(1)
  %14 := GetPointer bool*, std.vec.Vec<Bool>* %13.2
  Store bool* %14, %8
  %15 := GetPointer int, std.vec.Vec<Bool>* %13.0
  Store int %15, 4
  %16 := GetPointer int, std.vec.Vec<Bool>* %13.1
  Store int %16, 4
  Ret
}

func void @test.zeroSizeElementsVec() {
  %0 := Call _ZeroSize* myte.builtin.alloc(3)
  Call void @test.id<Unit>()
  %1 := Call std.vec.Vec<Unit>* myte.builtin.alloc(1)
  %2 := GetPointer _ZeroSize*, std.vec.Vec<Unit>* %1.2
  Store _ZeroSize* %2, %0
  %3 := GetPointer int, std.vec.Vec<Unit>* %1.0
  Store int %3, 3
  %4 := GetPointer int, std.vec.Vec<Unit>* %1.1
  Store int %4, 3
  %5 := Call _ZeroSize* myte.builtin.alloc(3)
  Call void @test.id<test.ZeroSize>()
  %6 := Call std.vec.Vec<test.ZeroSize>* myte.builtin.alloc(1)
  %7 := GetPointer _ZeroSize*, std.vec.Vec<test.ZeroSize>* %6.2
  Store _ZeroSize* %7, %5
  %8 := GetPointer int, std.vec.Vec<test.ZeroSize>* %6.0
  Store int %8, 3
  %9 := GetPointer int, std.vec.Vec<test.ZeroSize>* %6.1
  Store int %9, 3
  Ret
}

func void @test.id<Unit>() {
  Ret
}

func void @test.id<test.ZeroSize>() {
  Ret
}

func void @test.use<Function>(fn %0) {
  Ret
}

func int @test.main() {
  Call void @test.use<Function>(@test.emptyVec)
  Call void @test.use<Function>(@test.oneElementVec)
  Call void @test.use<Function>(@test.multiElementVec)
  Call void @test.use<Function>(@test.zeroSizeElementsVec)
  Ret 0
}