  .global _main

  .bss
  .balign 8
test.t:
  .skip 8

  .data
test.b:
  .byte 0
  .balign 4
test.i:
  .long 0
  .balign 8
test.d:
  .quad 0
test.l:
  .quad 0

  .text
_myte_init:
  str x30, [sp, #-16]!
  movz w0, #4
  bl mytec_alloc
  movz w1, #1
  str w1, [x0]
  adrp x1, test.t
  str x0, [x1, :lo12:test.t]
  ldr x30, [sp], #16
  ret
_main:
  str x30, [sp, #-16]!
  movz w0, #4
  bl mytec_alloc
  mov x2, x0
  str wzr, [x2]
  mov w0, wzr
  mov x1, xzr
  fmov d0, xzr
  bl test.testReassignGlobals
  mov w0, wzr
  ldr x30, [sp], #16
  ret
test.testReassignGlobals:
  str x30, [sp, #-16]!
  movz w4, #4
  adrp x3, test.b
  strb w4, [x3, :lo12:test.b]
  adrp x3, test.i
  str w0, [x3, :lo12:test.i]
  movz x0, #13
  mul x1, x1, x0
  adrp x0, test.l
  str x1, [x0, :lo12:test.l]
  adrp x0, test.d
  str d0, [x0, :lo12:test.d]
  adrp x0, test.t
  str x2, [x0, :lo12:test.t]
  movz w0, #4
  bl mytec_alloc
  movz w1, #2
  str w1, [x0]
  adrp x1, test.t
  str x0, [x1, :lo12:test.t]
  ldr x30, [sp], #16
  ret