test/parser/variable_declaration/basic.myte
{
  node: Module,
  loc: 1:0-7:14,
  name: {
    node: ModuleName,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "Test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: VariableDeclaration,
      loc: 3:0-3:9,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 3:4-3:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 3:4-3:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 3:8-3:9,
        raw: "1",
      },
      annot: None,
      is_public: false,
    },
    {
      node: VariableDeclaration,
      loc: 5:0-5:13,
      kind: Mutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 5:8-5:9,
        scopes: [],
        name: {
          node: Identifier,
          loc: 5:8-5:9,
          name: "y",
        },
      },
      init: {
        node: IntLiteral,
        loc: 5:12-5:13,
        raw: "2",
      },
      annot: None,
      is_public: true,
    },
    {
      node: VariableDeclaration,
      loc: 7:0-7:14,
      kind: Immutable,
      pattern: {
        node: ScopedIdentifier,
        loc: 7:4-7:5,
        scopes: [],
        name: {
          node: Identifier,
          loc: 7:4-7:5,
          name: "x",
        },
      },
      init: {
        node: IntLiteral,
        loc: 7:13-7:14,
        raw: "1",
      },
      annot: {
        node: IdentifierType,
        loc: 7:7-7:10,
        name: {
          node: ScopedIdentifier,
          loc: 7:7-7:10,
          scopes: [],
          name: {
            node: Identifier,
            loc: 7:7-7:10,
            name: "Int",
          },
        },
        type_args: [],
      },
      is_public: false,
    },
  ],
}