name: Build and test

on: [push]

jobs:
  build-mac:
    runs-on: macos-10.15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.0
      - name: Install Myte dependencies
        run: opam install . --deps-only
      - name: Build Myte
        run: opam exec -- ./scripts/build
      - name: Bundle files
        run: tar -czf build.tgz build
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: myte-build-macos
          path: build.tgz

  test-mac:
    needs: build-mac
    runs-on: macos-10.15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: myte-build-macos
      - name: Unzip files
        run: |
          tar -xzf build.tgz
          rm build.tgz
      - name: Run Myte tests
        run: ./scripts/run_tests

  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.0
      - name: Install Myte dependencies
        run: opam install . --deps-only
      - name: Build Myte
        run: opam exec -- ./scripts/build
      - name: Bundle files
        run: tar -czf build.tgz build
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: myte-build-linux
          path: build.tgz

  test-linux:
    needs: build-linux
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: myte-build-linux
      - name: Unzip files
        run: |
          tar -xzf build.tgz
          rm build.tgz
      - name: Run Myte tests
        run: ./scripts/run_tests
