name: Build and test
on: [push]
jobs:
  build:
    runs-on: macos-10.15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.09.x
      - name: Install Myte dependencies
        run: opam install . --deps-only
      - name: Build Myte
        run: opam exec -- ./scripts/build
      - name: Bundle files
        run: tar -czf build.tgz _build
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: myte-build-macos
          path: build.tgz
  test:
    needs: build
    runs-on: macos-10.15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: myte-build-macos
      - name: Unzip files
        run: tar -xzf myte-build-macos/build.tgz
      - name: Run Myte tests
        run: ./scripts/run_tests
