name: Build and test

on: [push]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.0
      - name: Install Myte dependencies
        run: opam install . --deps-only
      - name: Build Myte
        run: ./scripts/build
      - name: Run Myte tests
        run: ./scripts/run_tests
      - name: Bundle files
        run: tar -czf build.tgz build
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: myte-build-${{ matrix.os }}
          path: build.tgz
