test/parser/block/block_value.myte
{
  node: Module,
  loc: 1:0-11:1,
  name: {
    node: ModuleName,
    loc: 1:0-1:11,
    name: {
      node: ScopedIdentifier,
      loc: 1:7-1:11,
      scopes: [],
      name: {
        node: Identifier,
        loc: 1:7-1:11,
        name: "test",
      },
    },
  },
  imports: [],
  toplevels: [
    {
      node: Function,
      loc: 3:0-11:1,
      name: {
        node: Identifier,
        loc: 3:4-3:8,
        name: "test",
      },
      params: [],
      body: {
        node: Block,
        loc: 3:11-11:1,
        statements: [
          {
            node: Block,
            loc: 4:2-7:3,
            statements: [
              {
                node: ExpressionStatement,
                loc: 5:4-5:6,
                expression: {
                  node: IntLiteral,
                  loc: 5:4-5:5,
                  raw: "1",
                },
              },
              {
                node: ExpressionStatement,
                loc: 6:4-6:5,
                expression: {
                  node: IntLiteral,
                  loc: 6:4-6:5,
                  raw: "2",
                },
                is_value: true,
              },
            ],
          },
          {
            node: ExpressionStatement,
            loc: 9:2-9:4,
            expression: {
              node: IntLiteral,
              loc: 9:2-9:3,
              raw: "1",
            },
          },
          {
            node: ExpressionStatement,
            loc: 10:2-10:3,
            expression: {
              node: IntLiteral,
              loc: 10:2-10:3,
              raw: "2",
            },
            is_value: true,
          },
        ],
      },
      return: None,
      type_params: [],
      is_public: false,
      is_static: false,
      is_override: false,
    },
  ],
}