func void @test.use(int %0) {
  Ret
}

func int @test.main() {
  Call void @test.use(1)
  continue @0
label @0:
  %0 := Eq long 1, 3
  branch %0, @1, @23
label @1:
  %1 := Eq long 3, 3
  branch %1, @2, @6
label @2:
  Call void @test.use(2)
  %2 := Eq long 1, 3
  branch %2, @3, @4
label @3:
  Call void @test.use(3)
  continue @5
label @4:
  Call void @test.use(4)
  continue @5
label @5:
  Call void @test.use(5)
  continue @10
label @6:
  Call void @test.use(6)
  %3 := Eq long 1, 3
  branch %3, @7, @8
label @7:
  Call void @test.use(7)
  continue @9
label @8:
  Call void @test.use(8)
  continue @9
label @9:
  Call void @test.use(9)
  continue @10
label @10:
  Call void @test.use(10)
  continue @11
label @11:
  %4 := Eq long 1, 3
  branch %4, @12, @22
label @12:
  %5 := Eq long 3, 3
  branch %5, @13, @17
label @13:
  Call void @test.use(11)
  %6 := Eq long 1, 3
  branch %6, @14, @15
label @14:
  Call void @test.use(12)
  continue @16
label @15:
  Call void @test.use(13)
  continue @16
label @16:
  Call void @test.use(14)
  continue @21
label @17:
  Call void @test.use(15)
  %7 := Eq long 1, 3
  branch %7, @18, @19
label @18:
  Call void @test.use(16)
  continue @20
label @19:
  Call void @test.use(17)
  continue @20
label @20:
  Call void @test.use(18)
  continue @21
label @21:
  Call void @test.use(19)
  continue @11
label @22:
  Call void @test.use(20)
  continue @0
label @23:
  Call void @test.use(21)
  Ret 0
}